### ISSUE TITLE
Still not fix.... Spellbook for pet

### ISSUE THREAD

**Issue by fytro** [elysium-project/bug-tracker#10]
Hello. I need some help with my pet problem. When i hitted lvl 10 i tamed a boar, the pet had spellbook and abilities. I then went and got a place in the stable and turned the boar in, i tamed a new pet a cat and the problem started there! The cat did not have any abilities or spellbook. So i went back to the stable master and traded the cat for the boar, the boar had spellbook. so i abonded the boar took out the cat and is still the same problem. I then abonded all the pets, went out to the WDB folder deleted it and logged in again. I tamed a raptor but it was still the same problem. Can u guys help me ? i am the only one with this bug!!!

Edit: You wrote that this issue was fixed but it was not fixed. When i have my cat i only get the abilitie Cower, but i should have Cower Growl and Claw. AND when i stable my pet and go tame another one IT IS the same problem no spellbook no abilities. Can u fix my char as in make a new one same lvl and items if possible and i will send everything i need to an alt and then send it to the new charachter cause i know that will fix the problem!

**Comment by Terranzin** [comment]
Could you please supply me with the following information:
- Level when you tamed the cat
- The zone your tamed it (also exact name of the "cat" - before you renamed it)
- Your race
