### ISSUE TITLE
Drain Soul affected by Grim Reach

### ISSUE THREAD

**Issue by liskamic** [elysium-project/bug-tracker#102]
Drain Soul spell is not affected by the Grim Reach tallent. The spell's range remain 30 yards instead of 33/36 even though it's an Affliction spell.

**Comment by Navashed** [comment]
Reproduced.

Spell 1120 - Drain Soul(Rank 1)
Spell 18218 - Grim Reach (1/2)

Grim Reach is not affecting Drain Soul. Confirmed for both ranks of Grim Reach and all ranks of Drain Soul.
