### ISSUE TITLE
Slow effect doesn't effect fleeing mobs

### ISSUE THREAD

**Issue by eriks112** [elysium-project/bug-tracker#103]
Whenever a mob flee at low health all the applied slow movement effects are ignored.

https://youtu.be/yMeBA0D1LJY?t=699

Here is a old video showing murlocs fleeing slowly at start and then faster as the blizzard effect goes away.

**Comment by Navashed** [comment]
Reproduced.

Tested on many different NPCs. All ignore movement speed effects (both slows and sprints) for the entire duration they are fleeing.

Correct behavior: any buffs or debuffs which modify movement speed should affect speed while fleeing.

**Comment by Terranzin** [comment]
I´ve now tried to reproduce the issue after it´s been fixed. I attacked some murlocs using spell Blizzard at Misty Reed Strand, even when attempting to flee they are still slowed.
