### ISSUE TITLE
Orc racial talent Blood Fury #3268

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#105]
From the old bug tracker:
> I propose to check whether the Blood Fury counts the agi, str, AP comes from the gears and enchants, including crusader.

**Comment by Navashed** [comment]
Reproduced.

Spell 20572 - Blood Fury is scaling with Strength from gear (and maybe Agility for Rogues too). It is **not** scaling with +attack power from gear.

It adds 101 attack power naked:
![naked active](https://user-images.githubusercontent.com/2709545/33399713-9e94ab14-d521-11e7-9938-9fc9a9cee119.jpg)

With gear and buffs that give +attack power, it still gives 101 attack power:
![ap inactive](https://user-images.githubusercontent.com/2709545/33399747-b6472cdc-d521-11e7-848a-da057db360b7.jpg)
![ap active](https://user-images.githubusercontent.com/2709545/33399755-ba144264-d521-11e7-91e4-9a9af9438fe2.jpg)

But with gear and buffs that give Strength, it gives extra attack power (here 253):
![str inactive](https://user-images.githubusercontent.com/2709545/33399788-d7dca4e4-d521-11e7-94e5-60d5220b98c7.jpg)
![str active](https://user-images.githubusercontent.com/2709545/33399791-dbb7c1c0-d521-11e7-8b2e-ad131ed04816.jpg)

The correct behavior: Blood Fury should not scale at all. As the tooltip states, it should grant +25% of "base" melee attack power, i.e. before any gear. It should not scale with Strength (or Agility) from gear.

**Comment by shenna-elysium** [comment]
Please test again on PTR once it's up, fixed but requires testing.

**Comment by Terranzin** [comment]
Reviewed the new fix from the dev team. The blood fury is still generating to much attack melee power then it´s supposed to. The blood fury should generate 25% of the BASE attack power, but with gear on it generates more then it should´ve.

- Created new orc warrior, made it level 60
- Used blood fury (naked)  went from 406 attack power to 507, which is 101 extra attack power.
- Put on full Wrath gear. Blood fury racial went from  752 melee attack power to 940 which means the warrior gained 101 extra attack power + 87.
