### ISSUE TITLE
Priest Talent "Improved Power Word: Fortitude" is not working

### ISSUE THREAD

**Issue by nsknightmare** [elysium-project/bug-tracker#106]
The Talent is not working right. It should improve the Stamina spell but instead the stamina amount stays the same but the spell costs more mana.

**Comment by Navashed** [comment]
Unable to reproduce.

Spell 10938 - Power Word: Fortitude(Rank 6)
Spell 14767 - Improved Power Word: Fortitude (2/2)

For both ranks of Imp Fort and all ranks of Fort, the player was observed receiving the correct amount of Stamina and the spell was observed costing the correct amount of Mana.

In Vanilla, buff tooltips do not display talent improvements (i.e. Imp Fort, Imp Battle Shout, etc), even though the stat improvements are correctly applied.
