### ISSUE TITLE
Issue with PVP flagging while using the taxi service #3275

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#109]
From the old bug tracker:

> Whenever you use a flight master, PVP flag should be turned off for the whole duration of the flight and then the PVP flag should be applied again upon arrival depending if it's a contested zone or not.
> Right now, if you fly from a contested zone to a major city you remain flagged for pvp upon arrival.
>
>Source: https://www.youtube.com/watch?v=mA1vYEAbdgI&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&index=12
>This is a recording from Joana's speedrun from retail WoW, and judging by the lack of linked flight paths this was recorded pre patch 1.10. At the 10 minute mark, Joana takes a FP from Stonetalon to Thunder Bluff and you can see the behavior I just described. There are many other examples in his speed run that corroborates that.

**Comment by Navashed** [comment]
Reproduced.

Currently, taking a flight path does not remove the PvP flag, nor does it affect the PvP flag timer.

According to that video, PvP flags should be removed upon taking a flight path, at least before 1.10.

**Comment by Terranzin** [comment]
I´ve now reviewed the fix, the pvp flag turns off once you´re mounting up on the taxi and turns on when landing in Sun rock retreat.
