### ISSUE TITLE
Mage arcane concentration BUGGED!! BIG TIME

### ISSUE THREAD

**Issue by rshi00** [elysium-project/bug-tracker#11]
Hi! I had been playin mage for a long time.. since last vanilla Nostorius.
When my mage does arcane explosion for 10 times and I can barely get any free cast, I know something is wrong.. it's been like that since new server Nighthaven, it was ok on the previous Elysium server.
Please look into this... mages arcane explosion for 20 times not getting any free cast is very frustrating at times.. something must be wrong

**Comment by rshi00** [comment]
Just to note, cast 10-20 times with at least 5 mobs around, not getting the 10% per attack promised.. It's still counted as 10%.. but there should be more than that, cuz u have 5 mobs around for greater possibilities, but obviously that's not the case..

**Comment by WardenElysium** [comment]
Tested on PTR, Clearcasting proccs as it should from successful spellcasts/Arcane Explosion against an enemy. 

Report denied.
