### ISSUE TITLE
In dreams

### ISSUE THREAD

**Issue by tenlolz** [elysium-project/bug-tracker#113]
Fordring is not respawned in the tower pls fix it !
A lot of people are waiting for a quest !

**Comment by Terranzin** [comment]
Hello,

I´ve reviewed your issue on the live server. I went to the tower for "In Dreams" and he wasn´t at place, but do remember he can at times walk around in Hearthglen which you can see in my picture.

![image](https://user-images.githubusercontent.com/25831382/33529415-f9138c70-d870-11e7-8bf6-9e22e2386814.png)

Edit: After awhile he went back to his spot at the tower.

**Comment by Terranzin** [comment]
As a note: If players are doing the escort it may take awhile before he reached his spot and also respawns, here you can see a player doing the quest.
![image](https://user-images.githubusercontent.com/25831382/33529537-760d0084-d872-11e7-9997-df3c0e78a9d7.png)

**Comment by Terranzin** [comment]
https://github.com/elysium-project/bug-tracker/issues/244

**Comment by Terranzin** [comment]
https://github.com/elysium-project/bug-tracker/issues/244
