### ISSUE TITLE
[47] Freedom for All Creatures - Feralas

### ISSUE THREAD

**Issue by Sluddgermic** [elysium-project/bug-tracker#114]
Hey so I've come across this bug with this quest. I completed the quest originally, but failed to turn in the quest due to dieing and not making it back to turn-in npc on time. Now everytime I abandon and get the quest again, it says that the quest is still completed and does not allow for turn-in, I've done this 4 times now and have reported it to GMs in-game as well.

**Comment by Navashed** [comment]
Reproduced.

Quest 2969 - Freedom for All Creatures

After the quest's objective is completed, the timer is supposed to stop / go away. The player should not be able to fail the quest by running out of time after the objective is completed.

**Comment by shenna-elysium** [comment]
Now if you're testing on PTR you can see that timer isn't going anywhere once you're compled the quest but this time it won't fail the quest if you're running out of time after completing the objectives. IDK how it should be tbh.
