### ISSUE TITLE
Zamek's Distraction is missing script

### ISSUE THREAD

**Issue by liskamic** [elysium-project/bug-tracker#115]
Zamek's Distraction subquest within Keeping Pace quest is missing part of a script.
How it should work: Talk to Zamek at 79,77 next to the goblin hut. He will run toward the gnome camp and create a small explosion. Rizzle Brassbolts will run out from the gnome hut. Enter it and the plans are right there at 77,77.
How it works: Zamek walks to the gnome hut and back. Plans spawn. No explosion nor Rizzle running and schematics being active only while he's outside.

**Comment by Navashed** [comment]
Confirmed.

Quest 1191 - Zamek's Distraction
NPC 4709 - Zamek
NPC 4720 - Rizzle Brassbolts

RP scripting incomplete. No explosion from Zamek and no reaction from Rizzle Brassbolts. Quest functionality not impacted.

**Comment by Giperionn** [comment]
Hello @liskamic . Thank you for report.
Zamek's Distraction fix will be available on next server update (maybe a little later).
Here's a video report: https://www.youtube.com/watch?v=mVAasx84TYk
Have a good day ^_^ .
