### ISSUE TITLE
Dev updates 1/12 bugs.

### ISSUE THREAD

**Issue by Snowie493** [elysium-project/bug-tracker#116]
Well you did a excellent job with the updates, however some are not changed ingame.

Skills

The cost of riding is now how it should be (90G).

Tested on Darnassus mount npc's.

This meaning the mount would cost 9gold istead of riding. Mount is still 90gold.
Riding is still 9gold as of today 1/12. so i asked Stoley on discord what time the updates apply and he said they were already live so you missed this one.

**Comment by Navashed** [comment]
Unable to reproduce.

Apprentice Riding correctly costs (before discounts) 9g and Journeyman Riding correctly costs 90g. Level 40 mount correctly costs (before discounts) 100g and epic mount 1000g.

In early Vanilla, mounts were expensive and riding was cheap. In Patch 1.12.1, this system was reversed, making mounts cheap and riding expensive.
