### ISSUE TITLE
Debuffs from despawning boss

### ISSUE THREAD

**Issue by Aqw0rd** [elysium-project/bug-tracker#12]
Last boss in WC has the ability to charm players, so that they appear to be enemy, and cannot control their character. My bug is as follows:
Get charmed by boss > whole team wipe > boss kills escorts and despawns > Debuff despawns but effects still apply. Couldnt use stuck/hs, could leave party and force HS to orgrimmar. In orgrimmar i was still registered as charmed and got killed by guards(or potentially other hordes). When i tried to relog, i couldnt even move anymore, while i was dead. Couldnt talk to ressing spirit either.

**Comment by Aqw0rd** [comment]
Also, when I exit, i get teleported to corpse, but still immobilized

**Comment by WardenElysium** [comment]
Confirmed on Mutanus the Devourer. Charm effects on player character should disappear after a wipe even in charmed state if killed by an friendly player.

**Comment by cemak** [comment]
Write the name bosses or spells
