### ISSUE TITLE
Hunter Traps not working

### ISSUE THREAD

**Issue by Myrodor** [elysium-project/bug-tracker#120]
Good day,

this is my first time reporting a bug so hopefully i provided all thats needed.

Ok, so hunter traps are not working on my lvl 34 hunter. i did the restore character and i am currently playing on Stratholme server. Every time i put down my traps, whether its explosive, freeze, or immolation, mobs would walk right on top of it or run right through it and the trap wouldn't activate. the trap would sit there on the the ground without activating and then going away once it reaches 1 min ( the duration a trap can be placed) please fix this.

thank you,
Myroo

**Comment by Arteliese** [comment]
not working for my lvl 41 hunter on stratholme as well

**Comment by Terranzin** [comment]
This is being confirmed by the devs being a issue on Stratholme. I´ll set this as confirmed and we´ll wait for a hotfix. Thanks for reporting!
