### ISSUE TITLE
Azshara quest: Delivery to Archmage Xylem - Bug?

### ISSUE THREAD

**Issue by yaboydill** [elysium-project/bug-tracker#121]
I experienced and issue where i was unable to speak to "Sanath" the NPC who is supposed to teleport you up to where you can hand in this quest.  (It's located up on a mountain that you simply cannot walk to.)

Thankfully a GM was able to teleport me up the mountain so that i could progress in the quest, but maybe something worth looking into?

Cheers.

**Comment by Terranzin** [comment]
I´ve reviewed your issue, sadly I can´t manage to reproduce the error you´re speaking of.

1: Down with the blood elf and asks him to teleport me
![image](https://user-images.githubusercontent.com/25831382/33529717-0cc02e0a-d875-11e7-9d83-55435d1bf5b6.png)

2: Gets teleported and I can talk to the next npc and he teleports me back (I attempted same thing 3-4 times and not getting the same issue)

![image](https://user-images.githubusercontent.com/25831382/33529727-2fd36ed4-d875-11e7-9414-2210954e7a0d.png)
