### ISSUE TITLE
Cannibalize & Blade flurry not working

### ISSUE THREAD

**Issue by Socialjihad** [elysium-project/bug-tracker#122]
Playing on the Stratholme server I've noticed that Cannibalize and Blade flurry are not working at all.
I've tried using cannibalize on both player and npc corpses, human and undead, but neither are working.

Blade flurry is just plain not working at all.

Hopefully you'll find a quick fix for this.
Thanks!

**Comment by Navashed** [comment]
Unable to reproduce.

Both abilities appear to be working correctly.

**Comment by Terranzin** [comment]
PTR and Stratholme is not the same in the background, but since Stratholme is shutting down in a couple of days this will be invalid.
