### ISSUE TITLE
Fury warriors bloodthirst talent doesnt work? buff instantly removes itself on first strike 

### ISSUE THREAD

**Issue by Everfaithful** [elysium-project/bug-tracker#123]
Currently a 42 fury warrior using a 2h in Fury spec but bloodthirst will do the damage its suppose to inflict, but instantly the heal on the next 5 attacks buff is removed on the first swing also healing for 0 every time concurrently, other warriors in my guild seem to have the same issue not sure whats going on but otherwise it seems bloodthirst is not worth putting a point into

**Comment by Terranzin** [comment]
I´ve reviewed your issue and I cant manage to reproduce the error you´re speaking of. While having blood thirst on I can see on every successfull hit it ticks down from 5,4,3. Also I do get healed for each successful melee attack.

![image](https://user-images.githubusercontent.com/25831382/33529806-f9bde72e-d875-11e7-8d51-7d00f6d6127e.png)

You´ll need to send more proof of the issue you might have.

**Comment by Everfaithful** [comment]
okay ill try to take screenshots when i can, does your buff remove itself from your buff bar? mine does instantly before any of the [5] stacks are removed
