### ISSUE TITLE
Neutral AH

### ISSUE THREAD

**Issue by Grimrippah** [elysium-project/bug-tracker#124]
having problem auctioneering mats and gold over to the other faction from Booty Bay AH, items wont even come up when searching on them as me and my friend was rolling other faction.
This havent been an issue on other realm so is it a bug or na?

**Comment by Terranzin** [comment]
Hello,

I´ve reviewed your issue and I can´t reproduce your error. However, one thing to take in account, you can´t put up a item on auction on neutral AH and then make a second character on other faction to buy the item while using the same account.

Please give more proof with pictures, errors that is generated and such if you still believe there´s a bug.
