### ISSUE TITLE
Escort Quest: Freedom to Ruul #6482

### ISSUE THREAD

**Issue by Egregious** [elysium-project/bug-tracker#125]
This escort quest is currently only partially functional and, as such, unable to be completed.

The pathing of the friendly NPC, Ruul Snowhoof, works correctly while within Thistlefur Hold. He progresses out of his cage, up the hallway, spawns the appropriate mobs, and attempts to exit the cave. However, upon reaching the point of egress from the cave, he becomes stuck when he fails to find a viable path to step down from the cave rock to the grass hill.

![ruul quest](https://user-images.githubusercontent.com/1243093/33535611-92ec0bb4-d87c-11e7-96ec-f80673e4ffd5.png)

The 3 mobs he is supposed to spawn are correctly generated and engage him in combat, but none move toward Ruul and remain stationary at their spawn. 

Further testing of the quest is impossible as Ruul refuses to behave correctly from this point onward.

**Comment by Navashed** [comment]
The pathing from the cave object onto the ground is broken. The mobs cannot find a way in and Ruul cannot find a way out (actually he does manage to find a way out eventually, but ends up getting stuck in the sky).

**Comment by cemak** [comment]
work for me http://clip2net.com/s/3Q9Z2AM

**Comment by Namisma** [comment]
Ruul never appears in the cage, therefore it can not be performed
