### ISSUE TITLE
"Ooze Covered Mithril Deposit" mine dont work

### ISSUE THREAD

**Issue by shyrkatawi** [elysium-project/bug-tracker#126]
Nighthaven PvP
Alliance, Liferuiner hunter 31lvl 
Hello, in zone "The shimmering flats" in coords 68 86 is a few(~9-10) "Ooze Covered Mithril Deposit" mines.
For him possible to knock, increases skill, but no lot and does not disappear.
I grow my minig skill from 195 to 202... all mines remained standing on the spot.
Same with me tried to gather ore, a random player, but without success.

Sorry for my bad english, I from Russia(PUTIN,VODKA,BALALAIKA).
If there is a possibility I can russian admin to tell in russian language.

**Comment by shyrkatawi** [comment]
Near them is "Ooze Covered Silver Vein", it mine works well.

**Comment by Terranzin** [comment]
https://github.com/elysium-project/bug-tracker/issues/22 - It´s been fixed in newer patch that will be released now.

**Comment by shyrkatawi** [comment]
Join in game to check, the player Nordrek in my eyes was able to gather all mines, but anyway i cant.
What day of the patch with the fix?

**Comment by Levris** [comment]
ill heave that bug too !!!!!!

**Comment by Levris** [comment]
![giphy](https://user-images.githubusercontent.com/30007964/34319200-625e6f3e-e7ed-11e7-81ee-8a370b574f15.gif)
