### ISSUE TITLE
Item: Tome of Conjured Food VII (Patch 1.09) drops & behaves weirdly

### ISSUE THREAD

**Issue by Daumen** [elysium-project/bug-tracker#130]
The Stratholme Archivist Galford (NPC 10811) currently drops the Tome of Conjure Food VII (22897) on Nighthaven (1.2) (Tome was Added in Patch 1.09/1.11).
Also: It cannot be Mailed, error Message is: "You cannot mail Conjured Items."
But you can put it on the AH.

http://wowwiki.wikia.com/wiki/Tome_of_Conjure_Food <- This source claims it was added in 1.9
http://wowwiki.wikia.com/wiki/Patch_1.11.0 <- This source claims it was added in 1.11
Mb it was Added as an Item in 1.9 in the Gamefiles and only started dropping from the Archivist in 1.11.

Ty Navashed for you contribution, I edited this report accordingly

**Comment by Navashed** [comment]
Confirmed.

NPC 10811 - Archivist Galford is dropping Item 22897 - Tome of Conjure Food VII.

This was added in Patch 1.11 as seen in the 1.11.0 patch notes:
http://wowwiki.wikia.com/wiki/Patch_1.11.0

However, the item was mailed without any issues.
