### ISSUE TITLE
Неправильный звук спела BackStab у Rogue

### ISSUE THREAD

**Issue by Golfick** [elysium-project/bug-tracker#131]
Добрый день!

Подскажите пожалуйста, в моем клиенте почему-то звук BackStab звучит не правильно:

http://ru.wowhead.com/sound=10018/backstab-impact-chest

Вот так должен звучать, а звучит по другому, похоже на баф или другой как-йто спел, но точно не BackStab указанный выше.

Все клиенты перепробовал, брал отсюда:

https://forum.elysium-project.org/topic/57556-инструкция-по-подключению-и-часто-задаваемые-вопросы/

Проверял без аддонов, т.е.:

1. Скачал

2. Запустил

3. Проверил

Ни один клиент не проигрывает звук BackStab как положено.

Помогите пожалуйста может кто-то сталкивался.

Изменено только что пользователем Dotrad

**Comment by shenna-elysium** [comment]
Звук менялся в клиенте от патча к патчу, мы никак не можем на это повлиять :)
