### ISSUE TITLE
Interface Resetting Constantly

### ISSUE THREAD

**Issue by adamreed90** [elysium-project/bug-tracker#133]
When I logout or back in, or zone in, my action bars disappear, and I have to go back into Advanced to reenable them again.

**Comment by Terranzin** [comment]
Hello,

We do not handle addons in this bug tracker. Please contact our GMs with a ingame ticket and they might can help you.

**Comment by adamreed90** [comment]
Not addons, the basic bars, no addons installed.

**Comment by Terranzin** [comment]
Same there, it´s client side. We can´t help with that, only issues that is on the server side of things. Please contact our GM team, probably some WDB folder or such that needs to be deleted to make it work correctly.
