### ISSUE TITLE
Profession: Nighthaven fishing nightfins BUGGED again.

### ISSUE THREAD

**Issue by fatekills** [elysium-project/bug-tracker#134]
same issue that was on anathema early on- fishing nightfin fish, u get empty windows A LOT, seems like whenever you're suppose dto actually catch nightfin, instead u get empty window. u DO GET level up, so game thinks u caught something, but window is empty. this seems to happen 12am-6am, so right around the time u're supposed to catch more of them. location doesn't seem to make a difference, me and my friend went around different areas, and i remember the same thing happening on anathema. please fix, our guild need buff foooood lol, sucks being a rogue without agi buff!

**Comment by Terranzin** [comment]
Could you provide with different locations where this happened? Zone and X,Y coordinates would help.

Thanks!

**Comment by fatekills** [comment]
Tried everywhere from feralas, to moonglade, to azshara, to pretty much any place that nightfin supposd to catch up. its possible it happens with other fish that depends on the day/night cycle, maybe the squid too? not sure. location doesn't seem to make a difference, i tried moving up and downt he river/lake and it makes no difference, about 20% empty loot window which is actually the supposed drop rate for the nightfins at night, again, this was an issue back on anathema that got resolved while back when server opened up, so maybe someone would remember it from the old devs?

**Comment by fatekills** [comment]
Actually seems liek this started about week ago, -/+ I've talked with few people and seems like week or 2 ago it was fishing just fine,.

**Comment by Terranzin** [comment]
I´ve now been testing this issue, also spoke to a couple of people on the server who raid active (and grind for this certain fish). The error you´re reporting can´t be reproduced and what I´m told from certain players is that they dont find issue with this.
