### ISSUE TITLE
Feast at the Blue Recluse quest missing script

### ISSUE THREAD

**Issue by liskamic** [elysium-project/bug-tracker#135]
After completing the quest Feast at the Blue Recluse, the following things should happen:

> Upon turn in, all around the room Feast Fruit, Feast Fish, Feast Goblet and Feast Boar are spawned.
> Angus Stern says: All hail <name>, a <class> of worth!
> Angus Stern says: Behold! The Blue Recluse holds a feast in her/his honor!
> Steven Lohan says: Hooray, <name>!
> Joachim Brenlow says: Hooray, <name>!

**Comment by Terranzin** [comment]
I´ve looked into your issue and it´s ment to be a RP-event when handing in the "Feast at the blue recluse" but nothing really happens. Confirmed!

**Comment by shenna-elysium** [comment]
https://www.youtube.com/watch?v=ekIn-gl-AQE
