### ISSUE TITLE
Feralas quest The Missing Courier part 2.

### ISSUE THREAD

**Issue by swarriorh** [elysium-project/bug-tracker#136]
can't return quest The Missing Courier with quest id 4125 to the object Wrecked Row Boat with id 164909 it just says greetings <myname>
![object](https://user-images.githubusercontent.com/34297397/33648755-8f50b694-da70-11e7-8707-7b5bb997d3e4.jpg)

**Comment by Terranzin** [comment]
The quest works fine, you´re speaking to the wrong boat, the one you´re after is under water.
