### ISSUE TITLE
Quest: Chen's Empty Keg (3) not giving XP

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#137]
Quest 822 - Chen's Empty Keg (3) is supposed to give 975 XP on the first hand-in and 0 XP on subsequent hand-ins. It is currently giving 0 XP.

https://web.archive.org/web/20070213052114/http://www.thottbot.com:80/?qu=822

**Comment by Terranzin** [comment]
I´ve reviewed this issue and managed to reproduce the error. No experience was gained while handing the quest.

**Comment by shenna-elysium** [comment]
I need to know what amount of money this quest was giving at level 60 instead of XP.

**Comment by Terranzin** [comment]
Been looking futher into this matter and the last part of this quest should not give any XP to the player. There´s numerous reports back in 2007-2008 also a verification from a GM ticket back in the days.

**Comment by Terranzin** [comment]
After some conversation with QA team we found out that this quest should in matter of fact give XP. There seems to be comments from back in the days where they didnt think of repeatable quests. Confirming this!
