### ISSUE TITLE
Quest: The Nekrum's Medallion does not drop from Nekrum

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#139]
From GM:
The Nekrum's Medallion does not drop from Nekrum
http://db.vanillagaming.org/?npc=8022

**Comment by Terranzin** [comment]
I´ve now reviewed this issue. Sadly it can´t be reproduced and the item does appear on Nekrum when killed.
![image](https://user-images.githubusercontent.com/25831382/33780384-d7307a9e-dc50-11e7-96fa-0ff1ba33d01b.png)

**Comment by penialito** [comment]
Did Zulfarrak 2 times, the item didnt drop. (it dropped for a Party member tho) i guess it is character related
