### ISSUE TITLE
Viewing Glitch when Clipping onto parts of Stormwind

### ISSUE THREAD

**Issue by Razaroth43** [elysium-project/bug-tracker#140]
Was on auto-run, and got stuck on a torch along the wall, and when I got back I could see through the entirety of Stormwind. Replicated the issue 100% of the time following. No issues in restricting movement though, as I was able to escape just fine. 

Only one I saw it on was the first torch on the right, heading from Old town towards the Trade District. Didn't test any others, but will try the same thing next time I'm in town.

Sorry if the issue is minor, just trying to do my part.

**Comment by Navashed** [comment]
Thanks for the report.

This texture bug is Blizzlike and is related to the old "wallwalk under Stormwind" tricks. It's not our place to change this one.
