### ISSUE TITLE
Minor Recombobulator Blank

### ISSUE THREAD

**Issue by BoonthePaladin** [elysium-project/bug-tracker#141]
The recipe for this item has no attributes and the item itself when crafted has no attributes. 

Pictures below:

https://imgur.com/a/NHKqq
https://imgur.com/a/NHKqq

Let's get this resolved! it's a pretty fun trinket ;) thanks!

**Comment by BoonthePaladin** [comment]
https://imgur.com/a/qPfx4

thottbot archived (what the attributes are supposed to be)

**Comment by Terranzin** [comment]
I´ve reviewed your issue and it´s fine on PTR. We will merge this fix onto live during next week.
![image](https://user-images.githubusercontent.com/25831382/33783039-4fe5e7b2-dc5b-11e7-9a34-c7906db52409.png)
