### ISSUE TITLE
Troll camera position is vertically fixed too high.

### ISSUE THREAD

**Issue by sludgecity** [elysium-project/bug-tracker#143]
Minor issue I know but...

The position of the camera for troll's is higher than normal, it's set as if you are playing as a tauren or something.

You can notice this more the closer you zoom in when playing as a troll as it will focus in above their heads, but when you do the same thing with other races you will end up zooming into their faces instead.

**Comment by Terranzin** [comment]
The troll is actually taller then he looks, you can notice this while standing still and character stretches his back. The "hitbox" of the character is therefor larger vertically. Example if there would be aiming in this game, this means the troll would´ve gotten hit if you aim above his head - if the model was imported straight into a FPS-game.

If you do infact bring solid proof that the model is smaller, please report this, but with the information given It´s invalid.
