### ISSUE TITLE
Elemental invasion is wrong

### ISSUE THREAD

**Issue by Pisshead** [elysium-project/bug-tracker#144]
To get over with: no evidence can be presented. With that being said, I'd like to bring to your attention that this event is scripted wrong. There should be one elemental elite patrolling with two adds and with every portal should only spawn ONE elemental not four or five or whatever the setting is at the time. If the elite elemental has been killed the portals should disappear so that after killing the elementals, which are left they disappear after killing until the next event of elemental invasion happens and are not always there annoying and making it impossible to do any quests around there

**Comment by Terranzin** [comment]
Hello,

We need you to provide more information regarding this issue, youtube videos or anything that gives a better indication how it should´ve been.

**Comment by Pisshead** [comment]
Hmmm... Ok that's gonna be difficult, because there are no videos of that. All I can remember is that the portals are correct. There should be an elite mob, which is being escorted by two mobs patrolling the area where the elemental invasion happens. I don't think the path really matters. You can use Your creativity there. This elite mob spawns with yelling something like "I'm takeing over this world" yadah yadah. Per portal is only 1 mob spawning. As long as the elite mob is not defeated the portals remain. As soon as he gets killed the portals disappear and after killng the elementals they don't respawn. after the last elemental being eradicated it takes 24hs (not sure about that may be even a week) until the the elite mob and the portals appear again.
