### ISSUE TITLE
Long respawn time for quest chests in Grimtotem Spying Quest

### ISSUE THREAD

**Issue by Jebbadiah** [elysium-project/bug-tracker#145]
Steps to reproduce:
1. Reach one of the 3 chests in Thousand Needles in order to collect Secret Note #1,2,3 for the Grimtotem Spying Quest.
2. Open the chest and loot the Secret Note.
3. Notice that the chest despawns and respawns after ~5 minutes.

Note: While doing this quest with a 3 man group, this was very frustrating to wait 5 min x 3 chests x 3 characters.
I`m pretty sure that in Retail Vanila WOW, the chest re-spawns almost immediately after looting.

**Comment by Terranzin** [comment]
You´ll need to provide more solid proof then a speculation, usually similar quest never had a short respawn in Retail vanilla WoW.
