### ISSUE TITLE
Quest: Incorrect Level Requirements

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#146]
Quest 883 - Lakota'mani currently requires level 17.
Quest 884 - Owatanka currently requires level 17.
Quest 885 - Washte Pawne currently requires level 18.

These quests are started from items which require level 10:
Item 5099 - Hoof of Lakota'mani
Item 5102 - Owatanka's Tailspike
Item 5103 - Washte Pawne's Feather

Quests 883, 884, and 885 should require level 10.

https://web.archive.org/web/20091008142845/http://thottbot.com:80/?qu=884

**Comment by Terranzin** [comment]
QA confirmed
