### ISSUE TITLE
Water walking spell (shaman) stops working when turning into ghost wolf

### ISSUE THREAD

**Issue by viking11** [elysium-project/bug-tracker#147]
if you put water walking on yourself as a shaman and then turn into ghost wolf, you can't walk on water.

**Comment by Macsimka** [comment]
Fixed.

**Comment by Chillmok** [comment]
Still not fixed....

**Comment by sidsukana** [comment]
https://wow.gamepedia.com/index.php?title=Water_Walking&oldid=345001
It does not stack with, and is replaced by casting [Ghost Wolf] or mounting.
Wrath of the Lich King Patch 3.0.2 (2008-10-14): Water Walking no longer breaks when the target shapeshifts.

Need to revert all changes of this report.
