### ISSUE TITLE
Jammal'an the Prohpet quest bug

### ISSUE THREAD

**Issue by Alexmingud** [elysium-project/bug-tracker#148]
Hello.. i am in Sunken Temple now and i had the quest. I forgot to loot Jammal'an the Prophet but noticed and ran back pretty quickly.

When i ran back i saw mobs laying around in the room but Jammal was gone. Not much time had gone by from the kill to the despawn of Jammal. I expected that Jammal would  still be there of course since only a few minutes went by.

I dont have a screenshot of it since i contacted a Game Master before making this ticket and more time passed by from the bug happened to the GM responded.

Can i have the quest item from him please? Dont think its fair that he despawns after a that short period of time and i am pretty sure it was a bug. I dont want to lose both the experience gain and the item from the quest because of a bug.

Character name is Alexmingud level 51 shaman, was in Sunken Temple around 22:30 PM Danish time.

Edit: The God Hakkar
Same thing happened on this quest... Furthermore during the Hakkar encounter the adds either didnt spawn or randomly respawned, despite us following tacts. This happened like 4 or 5 times. So in conclusion i am positive that the dungeon is bugged

**Comment by Alexmingud** [comment]
Same thing happened with Hakkar "The God Hakkar"....

**Comment by Alexmingud** [comment]
Also Hakkar bugged several times during encounter

**Comment by Terranzin** [comment]
We´ll look into the matter with the NPC The God Hakkar, but the QA team can´t give you any items on live-server, items can only be obtained from the npcs or if a GM assists during a ongoing ticket.

**Comment by Navashed** [comment]
Jammal'an was observed despawning after the same length of time as the rest of the mobs in the room, even when he had a quest item on him.
