### ISSUE TITLE
rogue posion quest

### ISSUE THREAD

**Issue by puchal10** [elysium-project/bug-tracker#149]
I get my lvl 20 so i start de poison quests of rogue. I missclicked on questie and i mark as complete one quest. then i delete and try to accept the quest again but i cant. the quest giver dont give me the quest.
a GM tells me to delte de WDB but doesnt works. im lvl 26 and still have no venoms! i need help 

Thanks !!!

**Comment by Terranzin** [comment]
You´ll need the GMs to learn the skill for you. We can´t assist you with this thru the bug tracker.
