### ISSUE TITLE
Desaparece la mascota/ Cazador

### ISSUE THREAD

**Issue by KingRedpass** [elysium-project/bug-tracker#150]
Nighthaven PvP (parche 1.2)

Me encuentro caminando con mi cazador lvl 11 y de repente mi mascota desaparece, y me es imposible volverla a invocar. Solo me queda volver y capturar a otra, lo cual también se bugea en ocasiones ya que, en teoría, yo ya tengo una mascota.   
La mascota no debería desaparecer y si lo hiciera... por lo menos debería dejarme volverla a invocar...
No tengo videos de este comportamiento, porque ocurre aleatoriamente, todavía no se la causa de este bug. 
Espero puedan arreglarlo, ya que se vuelve muy molesta la jugabilidad con este pj. Gracias

**Comment by Terranzin** [comment]
Please make a new issue but in English. Closing this meanwhile.
