### ISSUE TITLE
NPC : Stonetalon Venture Co (Nighthaven)

### ISSUE THREAD

**Issue by Firestoat** [elysium-project/bug-tracker#151]
Venture Co. Engineer -- http://db.vanillagaming.org/?npc=3992
Venture Co. Builder -- http://db.vanillagaming.org/?npc=4070

The above mobs aren't fighting back.
I decided on later reflection that the Harvest Reaper that is summoned may or may not have the correct health even if it felt absurdly high. I couldn't find a correct dated source to give me its proper health.

Video Link of what I encountered on Nighthaven -- https://youtu.be/b014XGjB4_E
Video is HD - make sure to click on 1080 resolution if you watch it.

**Comment by Firestoat** [comment]
Freaking strange. I went to complete the same quest line with my warrior after posting this and the mobs are attacking properly.
Did someone sneak a fix in? Because I died previously on the rig and the mobs were not attacking upon being respawned for a second try with that shaman.

**Comment by Terranzin** [comment]
There´s no sneaky fix regarding the issue you found. I tried to reproduce the error but didn´t manage to do so. If this does happen again, please make a ticket to the GMs to see if they can see anything specific error.

Thanks for reporting PS: nice video! 👍
