### ISSUE TITLE
Bloodpike polearm proc

### ISSUE THREAD

**Issue by Viug4** [elysium-project/bug-tracker#152]
Hello, i play World of warcraft on Elysium project, **Nighthaven PvP** (patch 1.2), bought an polearm named **Bloodpike** [https://web.archive.org/web/20060427214120/http://www.thottbot.com:80/?i=9202](url) but its chance on hit proc does not work, never seen a proc
i would like to report this problem, hoping it will be fixed
best regards

**Comment by Navashed** [comment]
The proc works. It just has a very low proc chance. Eyeballing it, looks to be about 2%.

**Comment by Viug4** [comment]
hmm, ill test it even more, thank you.
