### ISSUE TITLE
Fleeing humanoid always runs instead of walk

### ISSUE THREAD

**Issue by DraZtiK** [elysium-project/bug-tracker#153]
Shown in Nost video https://www.youtube.com/watch?v=EIP6bVrUW4M the fleeing mob always "walks" away in fear after he reaches a lvl of health. Currently on Elysium the mob will "Run" at full speed away. This has just changed a couple days ago on the server.

**Comment by DraZtiK** [comment]
Here is another video that is on true vanilla https://youtu.be/y0f3aCoPx84?t=173 at 2:53 you can see a mob flee at what looks like slower than run speed, afterwards a player runs to loot him.

**Comment by shenna-elysium** [comment]
Indeed, could be slowed down a little.

**Comment by Navashed** [comment]
Mobs move slower at low HP, but this is not being taken into consideration when they are fleeing.

**Comment by shenna-elysium** [comment]
I am not sure about the exactly speed reducing value so now it's 50% slower.
