### ISSUE TITLE
Highlord Taelan Fordring <Highlord of the Scarlet Crusade>

### ISSUE THREAD

**Issue by Snogumz** [elysium-project/bug-tracker#154]
He seems to now get suck dead at 1% and stays that way 

![highlord](https://user-images.githubusercontent.com/34365068/33816636-b65e0836-de53-11e7-9521-8243abd56a95.PNG)

**Comment by Terranzin** [comment]
Please use the already created issue: https://github.com/elysium-project/bug-tracker/issues/142
