### ISSUE TITLE
Broken Tooth Wrong Attack Speed With Frenzy (Hunter Pet)

### ISSUE THREAD

**Issue by jackajack** [elysium-project/bug-tracker#155]
![broken tooth](https://user-images.githubusercontent.com/33477419/33817553-32cd99ca-de51-11e7-9f43-e3d53f596cd9.jpg)

Broken Tooth is a rare pet which has default 1.00 attack speed.
Beast master hunters get the talent Frenzy, which increases your pets attack speed by %30 after a critical strike. It's clear in the text.

Broken Tooth needs to have 0.70 attack speed when frenzy is procced, but as you can see in the picture it has 0.77.

Please look into this and patch it as soon as possible, me and my fellow hunters spend days to tame this beast. Also you should test if the shown attack speed is actually the true attack speed of the beast.

Waiting to hear from you, thanks!

**Comment by Navashed** [comment]
The formula for attack speed is this:

Attack_speed = "current attack speed" / (("Percent increase or decrease" / 100) + 1 )

As such, a 30% attack speed increase on a 1.0 base swing time yields a 0.77 swing time. The behavior you observed is correct. A more accurate label for "attack speed" would be "attacks per minute," as with this formula you do not attack 30% faster but you do perform 30% more attacks per minute.

If 30% attack speed took 30% off your swing timer, imagine what would happen in the unfortunate event that someone managed to get 100% attack speed. The server would crash trying to calculate infinity swings per second. With this equation, you can have 100%, 200%, 300%+ attack speed without breaking the game.
