### ISSUE TITLE
Mage arcane concentration, free cast not proc at right rate

### ISSUE THREAD

**Issue by rshi00** [elysium-project/bug-tracker#16]
Thank you admin for your quick response. I never said it does not proc, yes it does. But the rate is ridiculous compared to how it's supposed to work. Back on Elysium, when I have 10+ mobs around me as mage, within two-three arcane explosion I will surely have a proc, due to the large amount 10% chances I have around me... now, when I do the same, it takes 10-20 times to get one proc.. The rate is definitely bugged, please take a look into it.
You can msg me in game: soogood

**Comment by rshi00** [comment]
I can demonstrate what I'm talking about: with lvl 1 arcane explosion, a bunch of mobs around me, I would go from half to no mana doing it just tryin to get it proc a free spell. If this is not bugged, I dont know what is, cuz what it says in the spell clearly doesnt deliver

**Comment by Terranzin** [comment]
The proccs are correct, there is a 1/10th of a chance having arcane concentration trigger. Even though you´re hitting more enemies, this doesnt increase the %, it´s still 1/10th of chance on each mob. I attempted hitting a pack of mobs 20 times, the arcane concentration procc usually after 4-5 times and at maximum 8 times.

Also duplicate to issue #11
