### ISSUE TITLE
Dire maul - WEST: Arcane abberration to close

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#160]
Arcane abberration is to close to eachothers, should be able to pull 2-3 at times, but most of the times five gets chain pulled.

**Comment by Navashed** [comment]
Proper density can be seen here: https://www.youtube.com/watch?v=PlAfxb1Bfnw&t=23s

**Comment by Terranzin** [comment]
Should be able to pull 2 or 3 at times, but usually it´s 5.
![image](https://user-images.githubusercontent.com/25831382/33904394-b58ebb48-df7b-11e7-9b5c-7839570a99a2.png)

**Comment by twink** [comment]
Fixed.
