### ISSUE TITLE
Dire maul - WEST: Pathing bugs

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#163]
There is a need of overhauling Dire Maul West and the pathing since there seems to be some major issues.

**Comment by Navashed** [comment]
This is part of a larger pathing bug that is affecting many mobs.

**Comment by Terranzin** [comment]
All enemies can be lured into this place, and they all get stuck:
![image](https://user-images.githubusercontent.com/25831382/33904341-91d1c42a-df7b-11e7-96ff-9d8ffda1185b.png)
