### ISSUE TITLE
Dire Maul - EAST: Lethtendris's spells hit too hard

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#164]
Lethtendris's (NPC 14327) Void Bolt (spell 22709) should do ~1000 damage, currently doing ~3000 damage.

Lethtendris's Shadow Bolt Volley (spell 14887) also appears to be doing 3x too much damage.

Also, she is casting Void Bolt way too often.

After more testing:
She is supposed to be stunnable (currently immune) and silenceable (currently immune).
Evidence she should be stunnable is abundant in the comments: https://web.archive.org/web/20070614071902/http://www.thottbot.com:80/c14327

And she appears to be missing Spell 22710 - Enlarge.

**Comment by Macsimka** [comment]
Fixed damage for Void Bolt (spell 22709) and removed stun immune from Lethtendris's (NPC 14327).
For other bugs create new reports.
