### ISSUE TITLE
Dire Maul - EAST: Hydrospawn's Massive Geyser not showing up

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#165]
Hydrospawn's (NPC 13280) spell Massive Geyser (spell 22421) is supposed to summon a unit named Massive Geyser (NPC 14122) which then casts Water (spell 22422). Currently in the combat log when you get hit by Water it says "Unknown's Water hit you" when it should say "Massive Geyser's Water hit you."

Also, the spell Massive Geyser (22421) should not be interruptible.

**Comment by Giperionn** [comment]
Hello @Navashed ! Thanks for reporting.
So, it's should look like this? ;)
![image](https://image.prntscr.com/image/1zT2IDXWQoSfoDn8iuMQsw.png)
Fix will be available in next server update.
