### ISSUE TITLE
Bugged Quest: Sully Balloo's Letter

### ISSUE THREAD

**Issue by jontehack** [elysium-project/bug-tracker#17]
This is regarding Nighthaven Server(current patch progression version 1.2)

(Alliance Specific Quest)
Quest : Sully Balloo's Letter
Questid: quest=637
Which is triggered from the item : 4433 ( Waterlogged Envelope)
And is found in object=2656
(Under the bridge at thandol span)

The item (waterlogged envelope) which is a (lv 25 required) item to actually trigger the quest,
do seem to work to some degree as the quest is opened in the gui window, however when tryting to accept the quest it reads out: "You don't meet the requirements for that quest" despite being lv 25 on the character, so as said gui window triggers for quest but the accepting quest does not.

I made some research finding it was added in patch 1.11.1
However i go with the assumption this is more of a bug since even if it's a 1.2 progression server, it still operates under the 1.12.1 client, and as the quest exist it clearly should at this point exist despite the (said) server progression version. 

I wish you best of luck solving it!
/Farandana
Nighthaven

**Comment by Terranzin** [comment]
Use-case:
- Created a level 25 character
- Added item id 4433 to my inventory
- Attempted to start the quest 637 (Notice appear, that I do not meet the requirements)
- Leveled one more time to 26) did same test and it worked.

I did some additional research and found out from web.archive.org(Thottbot) that the quest requirement was actually level 26. 

> Sully Balloo's Letter
> --
> Level 30 | Ironforge
> Obtained at level 26 | Alliance
> Deliver Sully Balloo's Letter to Sara Balloo.
> Sully Balloo's Letter: 0/1

What we need to do is change the actual level requirement on itemID:4433 from saying "level 25" to "level 26"
![image](https://user-images.githubusercontent.com/25831382/32797391-e2e0331c-c971-11e7-8806-ea3d74c0a7c6.png)
