### ISSUE TITLE
Quest / Mob Bug: Hezrul Bloodmark (Nighthaven) Cosmetic

### ISSUE THREAD

**Issue by Firestoat** [elysium-project/bug-tracker#170]
Quest Link - http://db.vanillagaming.org/?quest=852
Server Image Link 1 - https://postimg.org/image/ov9o8itfx/
Server Image Link 2 - https://postimg.org/image/6fp7b4n19/

NPC Link (Hezrul) - http://db.vanillagaming.org/?npc=3396
NPC Link (Kolkar Bloodcharger - http://db.vanillagaming.org/?npc=3397

Issue - The quest works great, but Hezrul is NOT linked to his pair of Kolkar Bloodcharger bodyguards in terms of aggro when any of the 3 are attacked. You can single pull Hezrul away from them and the Bloodchargers will simply not care. Or, you can pull a Bloodcharger and the other will follow leaving Hezrul behind to simply not care.

All 3 should charge a person that aggros them.

**Comment by Navashed** [comment]
Confirmed.

Hezrul Bloodmark (NPC 3396) is not linked to the Kolkar Bloodchargers (NPC 3397). If he is pulled, they will simply stand there waiting for him to come back. If they are pulled, he keeps patting. In no situation do they come together.

The Kolkar Bloodchargers appear linked to each other (or are at least social with each other). I was not able to pull one separately from the other.
