### ISSUE TITLE
NPC: Syndicate Watchman (Nighthaven)

### ISSUE THREAD

**Issue by Firestoat** [elysium-project/bug-tracker#171]
NPC Link (Syndicate Watchman) - http://db.vanillagaming.org/?npc=2261
NPC Link (Drull) - http://db.vanillagaming.org/?npc=2239
Server Image Link - https://postimg.org/image/dix2qrv1p/

Issue - There is a single Syndicate Watchman standing near Drull for the horde quest, The Rescue, inside of a building. This single Syndicate Watchman is bugged so that they are hostile to no one, and cannot be attacked.

**Comment by Navashed** [comment]
Confirmed.

This NPC is experiencing the Line of Sight bug that has been reported elsewhere (https://github.com/elysium-project/bug-tracker/issues/168 and https://github.com/elysium-project/bug-tracker/issues/49).

![205ca0484ff2a5a1151b78c709e58b88](https://user-images.githubusercontent.com/2709545/34005138-ef91b7a8-e0c7-11e7-83c3-b46412293e69.jpg)

Note the "Target not in line of sight" text.
