### ISSUE TITLE
Quest: King of Foulweald (Nighthaven)

### ISSUE THREAD

**Issue by Firestoat** [elysium-project/bug-tracker#172]
Quest link - http://db.vanillagaming.org/?quest=6621
Item link - http://db.vanillagaming.org/?item=16976
Server image link - https://postimg.org/image/9zb50zn71/

Issue - The quest works exceptionally well, until the end when it is completed. When the King of Foulweald is slain, a basket spawns with the Totem quest item inside of it for players to obtain so they can run back to Zoram Strand to complete the quest.

The bug is that the basket remains spawned forever until the server resets. If more people complete this quest by planting the flag, then more baskets can be spawned this way as each King is slain for each group. I actually didn't have to fight the king to complete the quest. There was like 9 baskets spawned for me to just get a totem and walk off.

The spawned baskets need to have a life span of being spawned of about 3-5 minutes and then they need to despawn.

**Comment by Navashed** [comment]
I was not able to reproduce this one.

The baskets seemed to despawn in a reasonable length of time. I could not get several of them to be up at the same time.
