### ISSUE TITLE
Dire Maul - WEST: Residual Monstrosity

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#174]
NPC 11484 - Residual Monstrosity is casting Spell 22940 - Arcane Blast wayyy too often.

Currently they are casting it every few seconds.

They are only supposed to cast it about 4 or 5 times over the course of their entire mana pool. Approx 1 cast every 15-45 seconds.

ALSO: They are not spawning NPC 14397 - Mana Burst when they die. When they die they should cast Spell 22939 - Summon Mana Bursts which spawns 2 Mana Burst mobs.

**Comment by Macsimka** [comment]
Fixed.
