### ISSUE TITLE
After flying, pet's name becomes "Unknown"

### ISSUE THREAD

**Issue by wourn** [elysium-project/bug-tracker#175]
Hi.  
I noticed that after flying, Your pet name is set as Unknown.
Your pet regains its name after dieing or relog

**Comment by Terranzin** [comment]
I´ve reviewed your issue and manage to reproduce the same error. Thanks for reporting!

**Comment by Terranzin** [comment]
This issue seems to be with your client, I wiped mine clean and attempted flying between two zones and then it´s no longer a issue. (Had same issue as you).

**Comment by Svahnen** [comment]
I have the same thing every time i use a FP, i need to relog to fix it every time, a clean client will sometimes make it better for a little while, but then it comes bk.
I have read others have the same issue https://forum.elysium-project.org/topic/35149-fix-bugged-pet-names/
