### ISSUE TITLE
Dire Maul - NORTH: Doomguard Minion's Cripple

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#177]
NPC 14385 - Doomguard Minion is missing the spell Cripple.

Not sure which Cripple it is supposed to cast.

https://www.youtube.com/watch?v=NbHkXttoowE&t=09m20s

Also, the Doomguard Minions are not currently the pets of the Gordok Warlocks (NPC 11448), who seem to lack the spell Summon Doomguard (Spell 22865).

**Comment by Macsimka** [comment]
Fixed.
