### ISSUE TITLE
Quests that flag you for PvP in low level zones

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#179]
> AmelCempa - Today at 3:51 PM
npc can flag you for pvp
tiragarde keep in durator for example
horde quest there and killing the mobs t hey need flags them

Vanilla Retail:
https://www.youtube.com/watch?v=YcEqpVfrE7U&feature=youtu.be&t=181

Other instances:
> bael'dun digsite in mulgore
bael modan south barrens
northwatch hold in barrens

**Comment by Noiryx** [comment]
Just checked, it seems these should indeed not flag, despite the fact that they do - in fact the Kul Tiras marines shouldn't be marked as Alliance PvP at all, like they are now, especially the Kul Tiras Marines seem affected by this.

**Comment by Noiryx** [comment]
TODO for QA: get all the NPC ID's that do this and deliver it to the devs, makes their life a bit easier

**Comment by shenna-elysium** [comment]
Not sure about 'em tho.

bael modan south barrens
northwatch hold in barrens

Any proof?
