### ISSUE TITLE
Water walking toggled too early upon login

### ISSUE THREAD

**Issue by namreeb** [elysium-project/bug-tracker#18]
If you login and have a water-walking aura (i.e. elixir of water walking) enabled, the packet to inform the client that it can water-walk (`SMSG_MOVE_WATER_WALK`) is sent too soon.  The packet includes the GUID of the unit for which water-walking should be toggled, but it is sent before any units are introduced (via `SMSG_UPDATE_OBJECT` and `SMSG_COMPRESSED_UPDATE_OBJECT`).  This causes the client to discard the `SMSG_MOVE_WATER_WALK` packet and water walking will not function.

**Comment by cemak** [comment]
https://github.com/elysium-project/server-staging/commit/734994779bd54d22ed4b884c44c876488359db0f
