### ISSUE TITLE
Witch Hunting Quest - Drunk Permanently

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#180]
> Uhm, you guys know that Witch Hunter In Training, in Senjin Village, who can make you drunk?
 the buff expired, but my screen is still groggy. I tried relogging, and its still groggy

**Comment by tubiakou** [comment]
Confirmed through testing on PTR.  However, not a bug.

There is a scale of drunkenness in WoW - the more you drink the more drunken you can become.  E.g. there are several "levels" of drunkenness.

Check your chatlog.  When you interact with Bom'Bay and he afflicts you with "Special Brew", you immediately transition all the way to the "You feel completely smashed." drunkenness.  After the "Special Brew" effect wears off you will gradually reduce in drunkenness to the "You feel sober" stage.  However the various drunken effects (blurry screen, walking off to one side, etc.) disappear at different times as your drunkenness wears off.

In a test I did that started at 10:27pm, it was at 10:43 that I finally returned to sober.  This is the point at which all drunken effects completely disappeared.
