### ISSUE TITLE
Quest: Unrefined Ore Sample drop rate

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#181]
Item 5842 - Unrefined Ore Sample currently has a 100% drop chance off of 3 mobs:

NPC 4113 - Gravelsnout Digger
NPC 4116 - Gravelsnout Surveyor
NPC 14427 - Gibblesnik

It is supposed to have a drop chance of perhaps 20%.

https://web.archive.org/web/20070515082823/http://www.thottbot.com:80/i5842

**Comment by Macsimka** [comment]
Fixed.
