### ISSUE TITLE
Flee Speed still sprinting on some Mobs

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#183]
Makrura Shellhide and Pygmy Surf Crawler Mobs (swimming mobs only?) sprint away at full speed while fleeing.

**Comment by Navashed** [comment]
I can't find the equation that says how much mobs slow down when they are at low HP. Currently the mobs are slowing down at low HP, which is correct, but this slowing effect is for some reason ignored while they are fleeing.

**Comment by Terranzin** [comment]
In the last patch we made fixes where slowing effects (such as blizzard) did slow fleeing mobs. What other slowing effect are we speaking of? Does this appear when they flee into the water, the issue isn´t crystal clear.

**Comment by Stoley** [comment]
Fleeing mobs should be slow from the low HP, but that isn't the case for many mobs. (Not just swimming)

As Navashed said, it's ignoring the slowing effect.

**Comment by Terranzin** [comment]
We´ll look into this matter, thanks!

**Comment by Terranzin** [comment]
Confirmed
