### ISSUE TITLE
Wandering Skeleton - No Key

### ISSUE THREAD

**Issue by ryosuki** [elysium-project/bug-tracker#185]
Started to quest in WPL, and as usual I went to kill the Wandering Skeleton for the Dalson Outhouse Key. I have killed him numerous times and it did not drop the key to start the Outhouse chain.

**Comment by fulzamoth** [comment]
Did you read the diary to start the chain?

**Comment by Terranzin** [comment]
We need more information. I can´t reproduce the error, do remember: You need to read Mrs. Dalson's Diary before obtaining the key. Closing this issue.
