### ISSUE TITLE
I lost an item recevied from an mail

### ISSUE THREAD

**Issue by djluis** [elysium-project/bug-tracker#186]
A friend of mine, sent my two bags using the mail, after I open the mail with the items they simple disappear. I already restart the game multiple times, but the items didn't show up.
Is any issue with the mail system?
My nickname is: Elshankspt

**Comment by Terranzin** [comment]
There´s no known issues with the mail system since there´s a couple hundreds mails everyday that goes thru. You´ll need to contact our GM team to see if they can find your missing bags, maybe  your friend mailed it to the wrong person?
