### ISSUE TITLE
Serpents Not Tameable

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#188]
As shown here:
http://vanillawowhunter.com/vanilla-wow-hunter-pets/

These 3 pets are supposedly not tameable:
http://db.vanillagaming.org/?npc=5048
https://db.vanillagaming.org/?npc=5755
http://db.vanillagaming.org/?npc=5762

and possibly:
https://db.vanillagaming.org/?npc=5224
https://db.vanillagaming.org/?npc=7268
http://db.vanillagaming.org/?npc=5225

**Comment by Macsimka** [comment]
Fixed.
