### ISSUE TITLE
Dire Maul - NORTH: Captain Kromcrush

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#190]
NPC 14325 - Captain Kromcrush has 2 issues right now:

1) He gives Quest 7703 - Unfinished Gordok Business to anyone who speaks to him while wearing the Gordok Ogre Suit (Item 18258, Spell 22736). He is only supposed to give that quest after the tribute run is completed, aka only to someone who is King of the Gordok (Spell 22799).

2) He becomes hostile to anyone who removes their Gordok Ogre Suit (Spell 22736), **even if** they are King of the Gordok (Spell 22799). He should not become hostile to anyone with King of the Gordok active under any circumstance.

**Comment by twink** [comment]
Fixed.
