### ISSUE TITLE
Stronghold Gauntlets - "Immune to Disarm" not working

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#191]
> Hello i wanted to report a Bug with the item Stronghold Gauntlets, they clearly state: Immune to Disarm but i was just disarmed by a warrior in world pvp.

>i just tested in a duel
it worked, immune
but i was disarmed by a tauren warrior
i wonder if its different cross faction or something

**Comment by Navashed** [comment]
Unable to reproduce.

Tried in duels and cross-faction.
![ccba5276ec907c0764e8b5a5a30818e4](https://user-images.githubusercontent.com/2709545/34012556-44319908-e0e2-11e7-89d7-7cba0b94db6b.png)
