### ISSUE TITLE
Mision can`t delivered

### ISSUE THREAD

**Issue by Cristian2394** [elysium-project/bug-tracker#195]
In bloodhoof village have a mision can`t delivered the mision is the hunter`s way please i need your help in this mision

**Comment by Terranzin** [comment]
We need you to supply more information to test the issue you reported. To get help ingame with your current quest you do this by a ingame ticket and a GM can assist you.

**Comment by Terranzin** [comment]
No answer past 9 days, closing issue. Please make a new one when you have more information for us.
