### ISSUE TITLE
Mount vendor has incorrect pricing

### ISSUE THREAD

**Issue by Rred26** [elysium-project/bug-tracker#199]
My guild mates are reporting that mounts are being sold for 18g (20g) from vendors.

**Comment by Terranzin** [comment]
Confirmed, needs fix asap.

**Comment by Terranzin** [comment]
Gnomes are OK
Human - Id: 384
Dwar - ID:1261
Undead - Id: 4731
Tauren - Id: 3685
Orc - Id: 3362
Troll - Id: 7952
