### ISSUE TITLE
Level difference gives HUGE chance to miss with a spell in pvp

### ISSUE THREAD

**Issue by Crusaderz** [elysium-project/bug-tracker#20]
First of all i'm sorry for my poor english.

The problem:
Chance to miss with a spell in pvp same as in pve. It shouldn't be like this. **Completely unplayable**.

Fighting against "brown" level player is rather uncomfortable since they resists spells often. "Red" level enemy resists close to 80% of spells casted on them. "Skull" - forget it.

Physical damage dealers don't have such problem even against "skull" level enemy.

Back in 2006 casters never had this issue. Meeting someone 5 levels higher doesn't mean you are definitely going to graveyard. Casters could kill red and **EVEN** skull enemy in world pvp. They were playing battlegrounds as level x0 and fight against +9 enemy who only had better stats and spells and couldn't dodge spells like the Neo. I had a warlock back in the days. I played BGs and never had spell miss issues at all.
Sure there was chance to miss based on a level difference and level 1 would miss with most of his casts vs 60 but against someone ~20 level higher spells would land most of the time.

Proofs:

45 hunter vs 54-60 rogues.
9-15 level difference. Rogues eat imp. concussive shot (the stun proc is a spell) and freezing traps. https://www.youtube.com/watch?v=GUXvC9wKUrk

36 or 39 hunter vs 60 rogue.
Atleast 21 level difference. Rogue resisted one imp. concussive shot out of 2 procs and ate freezing trap.
https://youtu.be/NqSd1tpt06o

48 priest vs 60.
Priest killing various level 60 players.
https://www.youtube.com/watch?v=iOjJY29HA1I
Video has hundreds commentaries, the oldest from 2006 and latest published couple months ago (and only him asked about resists):

> Uh, how are skull levels not resisting like 99% of your spells

clearly that poor guy is a private server victim.
Since the video quality is 240p i reuploaded it with better quality: https://youtu.be/InXWMGxOfEo

49 mage vs 60.
Various pvp footage:
https://youtu.be/qZD4KmR7tb8

49 warlock vs 60.
Various pvp footage:
https://youtu.be/xKCT0Cjnjws

Everything above also applied to player controlled mobs. Pets  shouldn't have problems against higher level players and players shouldn't have problems against higher level enemy pets.
1) 49 felhunter used spell lock on a 60 paladin in the previous video.
2) 48 druid used hibernate against level 60 enemy pet https://youtu.be/xldmdYS5DB4?t=185

All videos were filmed on retail vanilla and downloaded (except 36 hunter and druid ones) from warcraftmovies.com using premium mirrors since the original streams gone long time ago.

Sadly i don't know what real chance to miss should be. But current system has to go ASAP. 
It's not blizzlike.
It's not even close to vanilla experience.
It's so broken.
It's absolutely **screws** casters and pvp during leveling (battlegrounds too) is a big part of the game.

**Comment by Crusaderz** [comment]
Wow. Fixed in 10 hours? Is it on server already?

**Comment by Terranzin** [comment]
Hello, it´s going  to come with next patch. Thanks for reporting issues!
