### ISSUE TITLE
Item/Offhand: Spirit of Aquementas Broken after DM patch

### ISSUE THREAD

**Issue by Gnomercey** [elysium-project/bug-tracker#200]
The offhand, Spirit of Aquementas, from the quest: It's Dangerous to Go Alone is supposed to reduce the mana cost of all spells by 25, currently it's not doing anything.

**Comment by Daumen** [comment]
http://wowwiki.wikia.com/wiki/Spirit_of_Aquementas

It was changed with this patch, its supposed to give you +Spelldmg now, did you check for that?

**Comment by Gnomercey** [comment]
Turns out the item was changed from -25 mana to all spells to +11 spelldamage and healing. Deleye your WDB folder to update item tooltips.
