### ISSUE TITLE
Pet Bugged

### ISSUE THREAD

**Issue by Bludkraze12** [elysium-project/bug-tracker#201]
So my this is for my Hunter allyiria On nighthaven. My pets refuse to learn growl or any other abilities trained by the pet trainer such as Resists, growls, armor increase nothing is ever applied to my pets after being purchased from the pet trainer but they abilities do show as learned by my trainer. To resolve this issue I tried using “unlearn abilities” by my pet trainer. This has only deleted the abilities my pet already knew when being tamed, in this case charge rank 1. I have tamed other pets since then a wolf with furious howl. I spent time with this pet till I have received a message stating that the ability has been learned. So I go to the stables switch to my higher level wolf that did not know the ability  howl but I was not able to teach the wolf the ability furious howl. Now seeing how being a hunter pets provide a major part in my experience when these pets cannot learn new abilities other than that which they are tamed with and cannot be upgraded in way’s as Growl, resists, Armor etc it is a huge inconvenience. 

Thank you in advanced.

**Comment by Terranzin** [comment]
It seems to be a db issue. There have been characters every now and then that are bugged and have to be moved to new account ID in the database. Please contact our ingame support (make a ticket) and ask them to get help from the administration.

**Comment by Bludkraze12** [comment]
I have made a ticket the told me to delete a folder and restart the game. This did not resolve the issue. So they continued to tell me to post on here. I guess I’ll try again.
