### ISSUE TITLE
Warlock Summon glitch.

### ISSUE THREAD

**Issue by zocks** [elysium-project/bug-tracker#202]
So i summoned a guild to the entrance of BRD, I believe he was mounted before he got summoned.So i believe this is a glitch that can be abused.

**Comment by Terranzin** [comment]
We´ve reviewed your issue and manage to reproduce the error, while the player accept the summon and enter a area which is not for mounts, he should instantly get his mount removed.

![image](https://user-images.githubusercontent.com/25831382/34084287-c37beedc-e37d-11e7-926d-99d904705e94.png)
