### ISSUE TITLE
Quest Sharing %t Bug

### ISSUE THREAD

**Issue by Egregious** [elysium-project/bug-tracker#203]
It looks as if the Share Quest feature is incorrectly identifying the player who accepts/denies the offered quest.

![questshare](https://user-images.githubusercontent.com/1243093/34075785-5d908a30-e29f-11e7-8cb5-8d0e9a434e37.png)

This screenshot depicts the issue. My character, Egregiouslol, is attempting to share a quest with Navak. However, the chat prompt incorrectly displays my own name as the recipient of the share.

**Comment by Macsimka** [comment]
Fixed.
