### ISSUE TITLE
Cannot interact with Timbermawhold NPC

### ISSUE THREAD

**Issue by dgasen** [elysium-project/bug-tracker#204]
Cannot interact with Timbermawhold NPC.

I could interact with them in patch 1.2. But now i cant interact with them in 1.3.
https://imgur.com/a/9ll91

what's up with that.

**Comment by dgasen** [comment]
Update. I have manage to gain my reputation to honored. 
Now i can interact with the npc.

However i can not purchase the enchanting recipes.
Acording the the database, it should be available. http://db.vanillagaming.org/?npc=11557

Will the recipes be released in another patch?

/G

**Comment by Terranzin** [comment]
It´s not a enchanting recipe, it´s from alchemy. You have the wrong profession.

**Comment by dgasen** [comment]
Is the database invalid aswell?

It clearly states that it has enchanting recipies.
http://db.vanillagaming.org/?item=22392
http://db.vanillagaming.org/?item=19445

Or does thoose recipies not exists?
