### ISSUE TITLE
Hunter Tribute Run Solo is bugged, and isn't working.

### ISSUE THREAD

**Issue by kalevale1** [elysium-project/bug-tracker#205]
I will be posting a youtube link of me trying to kite the boss, but he keeps teleporting me to him, which makes it impossible. I spoke to a GM ingame (Snogumz), he told me to report it here. 

https://www.youtube.com/watch?v=3jEze7UhqVo&feature=youtu.be

**Comment by Terranzin** [comment]
This has probably with the kiting mechanic which was fixed long time ago. Back in vanilla in the outside world of azeroth you could as hunter kite things to cities, but this was removed early by the dev team. I´ll set this one as confirmed but its up to them if this should be a thing or not.

**Comment by kalevale1** [comment]
Okay, thanks for the reply. 

The Blizzlike verision of the game, this worked, i played a hunter back in retail vanilla so i know for a fact it was a thing back then.

Thanks for the quick support :D

**Comment by cilva** [comment]
any updates on this? have the dev's come to any decision??

**Comment by nicinhd** [comment]
This is still unresolved
