### ISSUE TITLE
Blackrock mountain: LoS Issue

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#206]
There´s some error with LoS at the entrence to Molten Core. 

See picture below, the portal should´ve spawned where "Terralock" is located (marked blue) but appears on opposite side.

![image](https://user-images.githubusercontent.com/25831382/34084312-29479d1a-e37e-11e7-8ce2-c2d04ba591cc.png)

**Comment by twink** [comment]
MMAP issue, wait until we update it with full new system.
