### ISSUE TITLE
Mana Agate

### ISSUE THREAD

**Issue by Bugreported** [elysium-project/bug-tracker#208]
Patch 1.3(17.12.2017) Live Server

Mana Agate Rank 1:

Expected:   Consumes a Mana Agate to instantly restore 375-425 mana. (2 minute cooldown)

But when i consume a Mana Agate rank 1 on my mage, and conjure another one, it says 1 minute cooldown, when the 1 minute cooldown wears off, i click on Mana Agate again and it says ''That Spell isnt ready yet''--- It is supposed to show 2 minute cooldown instead of 1 minute cooldown on Mana Agate.
![screenshot_4](https://user-images.githubusercontent.com/34633169/34084449-f1b8e4a0-e380-11e7-839b-38d7872c5413.png)

**Comment by Terranzin** [comment]
The issue you´re reporting can´t be reproduced. The fault is probably on your side (client), usually clearing WDB and/or other folders fixes this issue please contact our GM Team ingame if you want futher assistance.

![image](https://user-images.githubusercontent.com/25831382/34084499-da06f0a8-e381-11e7-82b2-9638460a7b65.png)
