### ISSUE TITLE
Imp fire bolts hitting for 4x their tooltip damage every time

### ISSUE THREAD

**Issue by kevinmd88** [elysium-project/bug-tracker#209]
Warlock Rank 1 Fire Bolt at level 9. Don't even have int or SP yet. Tooltip indicates 7 to 10 damage, but it's hitting for 44-45 every time. I was able to solo Princess + entourages, and two-shot James Clark this way.

I'm not exactly complaining, but I figure this is very unfair to other players.

**Comment by Terranzin** [comment]
This fix was hotfixed on the Nighthaven server already.
