### ISSUE TITLE
Quest: Befouled by Satyr

### ISSUE THREAD

**Issue by Egregious** [elysium-project/bug-tracker#210]
Quest Befouled by Satyr #1434 is not correctly locked behind its prerequisite Alliance Relations (2) #1432. 

The quest text indicates you were having a previous conversation which is fulfilled by this small quest chain. Additionally these quests in this "chain": Alliance Relations (1) #1431, Alliance Relations (2) #1432, Alliance Relations (3) 1433, Befouled by Satyr #1434 and The Burning of Spirits #1435 are all consecutively numbered and have a related theme.

Additionally, all of these quests are labeled as Orgrimmar in your questlog.

**Comment by Egregious** [comment]
Update:

Quest Alliance Relations (3) #1436 is not properly gated. It should be unavailable until having completed both Befouled by Satyr #1434 and The Burning of Spirits #1435.

**Comment by Colemata** [comment]
https://github.com/LightsHope/server/pull/1174
