### ISSUE TITLE
Mob: Hatefury Hellcaller sometimes forgets how to autoattack

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#211]
Hatefury Hellcaller (NPC 4675) turns off his autoattack after casting Immolate (Spell 1094) for the second time. After casting for the third time, his autoattack turns back on. But upon casting Immolate for the fourth time, his autoattack is turned off again. Mysteriously, after this pattern repeats several times, eventually he corrects himself.

It seems like he may be stuck trying to cast a spell which is on cooldown (Rain of Fire?), costs too much mana (Rain of Fire?), or is invalid (Enrage?).

**Comment by twink** [comment]
Fixed.
