### ISSUE TITLE
Profession: Devilsaur Sets uses wrong LW specialization

### ISSUE THREAD

**Issue by Buffavento** [elysium-project/bug-tracker#212]
Devilsaur Sets must be crafted by Dragonscale Lw

**Comment by fulzamoth** [comment]
Devilsaur Sets were Tribal Leatherworking (Wowhead, or WoWWiki 2006 history view, as well as 2005 forum posts).

**Comment by Terranzin** [comment]
Thanks for reporting, it does use the wrong specialization as of now. Thanks!

**Comment by naohro** [comment]
My Devilsaur Legging pattern still requires Dragonscale Leatherworking to be learned. When I try to learn it says I have the wrong proficiency and starts recipe learning animation but no progress bar appears and nothing happens if I let it go. Hope this gets fixed!
