### ISSUE TITLE
Dire Maul North Keys missing during crash

### ISSUE THREAD

**Issue by ryosuki** [elysium-project/bug-tracker#213]
During a server crash, we were at the last boss for a tribute run. Both keys were taken from our bags, and the doors closed. When we logged back in half the party was at DM West. The chest box for Fengus was gone and we could not open the doors.

**Comment by Terranzin** [comment]
This isn´t a bug, just unfortunate that there was a rollback. We can´t do much about this, it´s sad it happened but you´ll just need to do the run again.
