### ISSUE TITLE
Priest mind control + sheep

### ISSUE THREAD

**Issue by jeromecaudoux** [elysium-project/bug-tracker#214]
I have mind controlled a mob and a mage sheeped him (we both started to cast ~ at the same time), then i stoped the md (right click on the icon).
The sheep was following and fighting me, i was not able to touch him.

Sry for my bad english.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and manage to reproduce the same issue. 

Use-case:
1: Start casting mind control.
2: While priest is casting make the mage sheep the mob.
3: The mob gets sheeped and mind controlled
4: Remove the Mind Control as priest
5: The mob starts attacking and throwing his spells still as the form of a sheep.

![image](https://user-images.githubusercontent.com/25831382/34577384-3e56486c-f181-11e7-8b7e-bf8a71fdf945.png)
