### ISSUE TITLE
Poisons stack

### ISSUE THREAD

**Issue by jeromecaudoux** [elysium-project/bug-tracker#215]
Idk if it is the expected behavior or not but while farming in Swamp of sorrows (See attached screenshot for coords) each mob was able to adds his poison on me even if i already got it from another one.

On the screenshot i have 3 times the same poison on me... i died :(

![wowscrnshot_121417_235838](https://user-images.githubusercontent.com/5968007/34133231-f0bf9e12-e453-11e7-92fe-4366dfb5b8f6.png)

**Comment by Terranzin** [comment]
You need to provide proof that this poison should not stack. We can´t assume that the reason is just because you died.
