### ISSUE TITLE
Quest:  Pristine Yeti Hide - Not Activating After Acquiring the Drop

### ISSUE THREAD

**Issue by Bandersnatch3** [elysium-project/bug-tracker#217]
NightHaven PVP

After acquiring the drop "Pristine Yeti Hide" from Rage Scar Yeti's in Feralas, we are supposed to be able to activate it to start the quest (Quest Name: Pristine Yeti Hide) that ends with turning in the hide to Pratt McGrubben in Feathermoon Stronghold.  This is a repeatable quest for a decent amount of Darnassus reputation which makes it ideal for farming in order to reach Exalted with the faction.

**Comment by fulzamoth** [comment]
That quest was originally added in patch 1.5.

Source: http://wowwiki.wikia.com/wiki/Quest:Pristine_Yeti_Hide

**Comment by Terranzin** [comment]
The quest needs to be removed since this quest should not even exist right now.
