### ISSUE TITLE
Wastewander Mobs Not Giving Steamweedle Cartel Rep

### ISSUE THREAD

**Issue by SterlynStevo** [elysium-project/bug-tracker#218]
Wastewander NPCs do not give Steamwheedle Cartel rep despite mobs saying "Your Steamwheedle Cartel reputation has increased by 5." after kills.

**Comment by Egregious** [comment]
I am currently getting 2 Gadgetzan rep as well as 1 Steamwheedle Cartel rep on my level 60.
