### ISSUE TITLE
Patchwork Horror's in Stratholmen doing insane amount of damage

### ISSUE THREAD

**Issue by LysanderWize** [elysium-project/bug-tracker#219]
![skarmavbild 2017-12-20 kl 14 02 20](https://user-images.githubusercontent.com/34713208/34208432-9c51a870-e58e-11e7-82db-ee4da2ba18d2.png)
![skarmavbild 2017-12-20 kl 14 01 36](https://user-images.githubusercontent.com/34713208/34208434-9c90c35c-e58e-11e7-9844-76bef7442907.png)
![skarmavbild 2017-12-20 kl 14 01 52](https://user-images.githubusercontent.com/34713208/34208433-9c6f67d4-e58e-11e7-9d10-eca7f7b9bcf0.png)

**Comment by Navashed** [comment]
Unable to reproduce.

No idea why Disease Cloud seems to be ticking so fast in your screenshots. It ticked slowly when I tested it.

**Comment by LysanderWize** [comment]
It was in combination with the server crashing, we first finished strat UD and then proceeded to do strat living, we thought it would be an easy match but we all died except a mage that managed to kite him to his death, no other patchwork was bugged in this way, it was the absolute first one that patrols at strat living when you use the backdoor via the chapel

**Comment by Terranzin** [comment]
Tried to reproduce it but can´t, it still ticks slow. Probably something that appeared during the server crash, if it happens on a new resetted instance please make another issue and we´ll need to check the differences between PTR and Nighthaven.
