### ISSUE TITLE
Ooze covered mithril veins; Shimmering Flats

### ISSUE THREAD

**Issue by kreygasm66** [elysium-project/bug-tracker#22]
They simply do not yield ores/gems when mining.
The skillup does occur.
Please try to fix this! :)

**Comment by Terranzin** [comment]
I´ve reviewed your issue and manage to get the same issue.

Use-case:
- Spawned 5 nodes (Object ID: 123310) all 5 worked just fine, got both skillup and received the gems/ores.
- Went to Thousands Needles and visited the dig site, found 1 node and attempted to mine it, worked just fine getting ores and gems.
- Found a third node at coords 65,87 inside the dig site where I managed to reproduce your error. I´m able to mine and loot the ore. The ore does not despawns and lets the user mine it serveral times, without getting any additional gems/ores.
![image](https://user-images.githubusercontent.com/25831382/32804955-32693b70-c988-11e7-815f-e3c24a9fd092.png)

**Comment by kreygasm66** [comment]
Incredibly weird. They are all gone now. I'll have to do a further examination once they have respawned. I honestly couldn't loot them. Thank you for clearing it up though!

**Comment by Terranzin** [comment]
Hello,

We did actually find a certain bug on server-side of this matter after doing a third review of this matter. It´s now been fixed and will be added next patch. Thank you for reporting!

**Comment by Levris** [comment]
ill heave 202 mining and just see how another plawers harvesting that but all cant harvest no one ( time bar ends and nothing happens (
