### ISSUE TITLE
Weapon skill issue

### ISSUE THREAD

**Issue by painthegain** [elysium-project/bug-tracker#220]
Having a weapon skilling issue, been 60 for 6+ days and am stuck at 299 for maces and 299 for swords. 

Am sure that this isn't an issue of "not playing enough" since 6 days /played (not idling of course) is plenty of enough time to level from 299-300 in both of those. 

Appreciate the help.

**Comment by Navashed** [comment]
The final point takes ages, especially if you have low intellect. Probably not a bug; try getting mages to buff you.

**Comment by painthegain** [comment]
You are actually saying that the same amount it takes from 0-60 in terms of played is the same to get from 299-30?

**Comment by Navashed** [comment]
With low intellect, I could see it taking 6+ days /played, particularly if you only raid and pvp and never farm. It took me 11 months to go from 299-300 in a weapon skill after hitting 60 in retail, and I never capped unarmed before it was removed in Cata despite playing continuously from 2004-2010 on the same two characters.
