### ISSUE TITLE
Mara Scepter

### ISSUE THREAD

**Issue by HoxEly** [elysium-project/bug-tracker#221]
Got both halves, turned them in. He ran down to his stone and did his yabbing, didn't give me the scepter. I dropped quest and restarted. He started yabbing again then bugged out in front of stone. Please fix issue and issue me my earned scepter. Thanks

**Comment by Navashed** [comment]
Thanks for the report,

QA will test this quest's functionality, but to get your individual issue addressed you will have to contact a GM.

**Comment by Terranzin** [comment]
I´ve tried to reproduce the issue you reported but can´t seem to find the error you mention. He does his ritual, I press on the book (as I suppose you did??) and then eventually it got completed.

![image](https://user-images.githubusercontent.com/25831382/34576770-55215872-f17f-11e7-93c8-968fde84e354.png)
![image](https://user-images.githubusercontent.com/25831382/34576777-5bb6c87a-f17f-11e7-9442-ac5442486d27.png)
