### ISSUE TITLE
Nothing But The Truth (Quest)

### ISSUE THREAD

**Issue by Anni9800** [elysium-project/bug-tracker#222]
Hi, 
i try to complete the quest. But the questitem Deepstrider Tumor will not drop.
I really killed over a hour the Dreaming Whelp´s to get this questitem but it will not dropped.

**Comment by fulzamoth** [comment]
This item drops from Deepstrider Searcher and Deepstrider Giants in Desolace. They're not a 100% drop rate until Patch 1.5
