### ISSUE TITLE
Combat during rend event

### ISSUE THREAD

**Issue by jbshifter** [elysium-project/bug-tracker#224]
I made a bug report of this about a year ago with youtube proof that combat drops between waves during the event.  Below is another video of combat dropping, I'll try and find the one I used last time as well and update this post.  I hope someone can address this in the script for the encounter asap.

https://www.youtube.com/watch?v=jC32eb-rQ8Q&t=3s

At the 0:05 mark you can clearly see people drinking, all mobs dead, gate is closed, no combat. Rend then comes out.  So at the very least combat dropped after all waves dead but before rend. 

https://www.youtube.com/watch?v=jXHzP_6ieHA

7:21  Shaman sits and is drinking between waves.

**Comment by Egregious** [comment]
Yeah, confirmed. Combat should drop. I recall this from my Vanilla days.

Further evidence: https://youtu.be/1tGdVHw9HME?t=9m5s
This video is obviously much, much later. However, the instance is still functioning as intended.

**Comment by Navashed** [comment]
I also remember that combat dropped in Vanilla.

**Comment by twink** [comment]
Fixed.
