### ISSUE TITLE
Underwater Walking

### ISSUE THREAD

**Issue by Bugreported** [elysium-project/bug-tracker#225]
A guy said he jumped off the booty bay boat into ocean and hit the ground, said he almost died. He could walk underwater at normal speed, its been so for 3 hours, he is still stuck with the 'gift' of walking underwater.
![screenshot_1](https://user-images.githubusercontent.com/34633169/34311609-d182df88-e75e-11e7-8151-7411f0538845.png)

![screenshot_2](https://user-images.githubusercontent.com/34633169/34311618-dd94b51c-e75e-11e7-9b51-342ec965712a.png)

**Comment by Egregious** [comment]
Can you give me a little more information as to where you were specifically? I am finding this hard to replicate.

**Comment by Terranzin** [comment]
When running back and forth in and out of the water in barrens, I manage to reproduce the issue. Eventuelly my character ran on the bottom. I´m not fully sure how I actually managed to do this, but this needs to be looked into futher with the help of our devs.

**Comment by twink** [comment]
Can't reproduce.
