### ISSUE TITLE
Minor Recombobulator

### ISSUE THREAD

**Issue by TheRealFolly** [elysium-project/bug-tracker#226]
The item isn't usable and doesn't have text describing what it does.  I essentially have it occupying a dead space in my trinket 2 slot

**Comment by fulzamoth** [comment]
If tooltips aren't displaying properly start with deleting your WDB cache. Please test and update issue.

**Comment by TheRealFolly** [comment]
After deleting the WDB cache I can still report the tool tips aren't properly displaying.  The bigger issue is that I can't even use the trinket.  It's unusable.

**Comment by Terranzin** [comment]
Could you please contact our ingame support? The items display error was fixed last patch, so the issue you´re reporting is 100% on your clients end.

**Comment by Terranzin** [comment]
https://github.com/elysium-project/bug-tracker/issues/141
