### ISSUE TITLE
Mining problem

### ISSUE THREAD

**Issue by Levris** [elysium-project/bug-tracker#227]
I heave a 203 mining start harvest a Ooze covered mithril deposit and when harvest bar ends nothing happens !

**Comment by Levris** [comment]
![giphy](https://user-images.githubusercontent.com/30007964/34319217-8e4ddf44-e7ed-11e7-82ab-4621d6a7e00c.gif)
I SEE THIS !!!

**Comment by Levris** [comment]
I think it a character problem !

**Comment by Terranzin** [comment]
This might be a character issue and your player ID. Please contact ingame support, we can´t help you thru the bug tracker.

This issue was fixed in earlier patches.
