### ISSUE TITLE
Talent bug in Sub tree, Serated blades

### ISSUE THREAD

**Issue by ryosuki** [elysium-project/bug-tracker#228]
https://imgur.com/a/xebkm

Says it has 0 to ignore armour? Is it working as intended or bugged?

**Comment by fulzamoth** [comment]
This is a common display error on private servers, but it should work as intended. Please test and update issue.

**Comment by Terranzin** [comment]
It´s working correct. Like fulza is saying this is more of a display error. Can´t be reproduced on PTR either.
