### ISSUE TITLE
Tibermaw Reputation. 

### ISSUE THREAD

**Issue by mediumjbc** [elysium-project/bug-tracker#230]
<html>
<body>
When entering the cave in Felwood up north entitled "Timbermaw Hold" and not engaging in combat with any of the Deadwood NPC's at all and then exiting the cave. I am instantly and without any reason "Hated" in Reputation with the Tibermaw NPCs. This is a bug that was known in early vanilla releases of WoW and repaired in on of the official blizzard patch's so I have seen it before. 
</body>
</html>

**Comment by Navashed** [comment]
Are you sure it set you to "Hated" after the initial interaction? It's supposed to set you to "Hostile" 2500/3000. You'd have to kill 100 Timbermaw to reach Hated.

**Comment by mediumjbc** [comment]
I'm sorry it appears you where correct it just went to hostile after I ran in the cave after someone else had already aggroed them and ran out when they where running back to there positions. 

    On Tuesday, December 26, 2017 9:57 AM, Navak <notifications@github.com> wrote:
 

 Are you sure it set you to "Hated" after the initial interaction? It's supposed to set you to "Hostile" 2500/3000. You'd have to kill 100 Timbermaw to reach Hated.—
