### ISSUE TITLE
Corruptor's Scourgestone not lootable when you're the only one in the group with Argent Dawn Commission trinket.

### ISSUE THREAD

**Issue by Midnatt** [elysium-project/bug-tracker#231]
If you are wearing the Argent Dawn commission trinket and noone else is in the party, you cannot loot the Corruptor's Scourgestones (from bosses).

You have to put FFA loot and loot it.

**Comment by Navashed** [comment]
Unable to reproduce. Zoned in alone, looted the item with no difficulty.

You can't change to FFA when you are alone. Do you mean you were in a party but no one else was online/in the instance?

**Comment by Midnatt** [comment]
No. If you are the only one in the party with the Argent Dawn Commision trinket, you are unable to loot the Scourgestones from the bosses. To be able to do that, the leader has to change loot system to FFA after every boss kill.

**Comment by Midnatt** [comment]
The error text is "This item is already beeing rolled for"

**Comment by shenna-elysium** [comment]
Unable to reproduce.

**Comment by Thenari** [comment]
Yeah ive had this happen to. But ive seen it happen when we all pass than we decide who gets it. We switch to FFA and it works
