### ISSUE TITLE
Cleave & Overpower

### ISSUE THREAD

**Issue by Daumen** [elysium-project/bug-tracker#232]
When a Warrior uses Cleave on 2 Targets & the off-target dodges, the Warrior cant use Overpower on him. Is that intended?

**Comment by fulzamoth** [comment]
Overpower works against your current target. If you have evidence of the mechanic ever being different, please add it to this report.

**Comment by Navashed** [comment]
Overpower definitely always worked against any target that dodged, not just a target that dodged while you were targeting it.

**Comment by fulzamoth** [comment]
I stand corrected - it looks like it worked a year ago. The bottom of this thread talks about it not working with Sweeping Strikes, but you should be able to switch target and Overpower on Cleave.

https://forum.elysium-project.org/topic/35605-lets-talk-warrior-bugs/

**Comment by twink** [comment]
Fixed.
