### ISSUE TITLE
Warlock Talent tree % talents

### ISSUE THREAD

**Issue by Molemaisteri** [elysium-project/bug-tracker#233]
My talents like imp drain life does not give the 10% extra drain after the 5 points also im pretty sure same is with imp curse of agony and all the other % talents, they are now just waste of my talent points. Anything you can do to fix this? Its kinda useless being an afliction wlock without the % talents. Cheers.

**Comment by fulzamoth** [comment]
You'll need to provide details beyond "this isn't working". Numbers showing what you're getting and what the expected is will help guide the devs and QA teams.

**Comment by Egregious** [comment]
I was able to get base damage of Corruption. 
Naked 60 with no talents : 43
Naked 60 with 3/3: 46

I was able to get the base damage of Drain Life.
Naked 60 with no talents: 71
Naked 60 with 5/5: 78

Seems to be working.
