### ISSUE TITLE
Ogre Warlock Banish in Dire Maul North

### ISSUE THREAD

**Issue by jbshifter** [elysium-project/bug-tracker#235]
So the banish the mobs do to players is classified as magic yet I cannot dispel it as a priest...  I don't think it's working properly.  I have seen it happen three times now where a member of my party is banished and I cannot either manually dispel the banish or use decursive as it does not even register as a debuff on the decursive addon.  Is this really "Vanilla like"?  I've never recalled not being able to dispel it, and the tooltip says that it is a magic...

**Comment by Egregious** [comment]
It could be that the banish is incorrectly classified as a Magic debuff. I'll look into it presently.

**Comment by fulzamoth** [comment]
Looks to be working correctly according to research on old Nostalrius thread: https://forum.nostalrius.org/viewtopic.php?f=6&t=11215

"Banish is technically dispellable (it's a magic effect), but you are immune to dispel magic while banished. "

September 2006 - 
"Gordok Warlock lvl 55-60 - These ogres have doomguard pets that can be annoying. They also cast Curse of Tongues, Immolation, Shadow Bolt and Banish. Banish is undispellable so it can cause big problems sometimes."

**Comment by jbshifter** [comment]
No, you don't understand.  There are others in my group who get banished and me as a priest cannot dispel them.  I know I can't dispel myself when I'm banished... The problem is I can't dispel anyone else that gets banished by the warlocks in DM.

**Comment by Egregious** [comment]
I think that was directly what he said. Of course if you are incapacitated you cannot cast on yourself or others. However, the statement was that the Banish mechanic is deceptive because, despite being labeled as Magic, a banished target is Immune to spells. Therefor they are immune to heal attempts, CC attempts, damage attempts and dispel attempts.

**Comment by Navashed** [comment]
It's like how Divine Shield is technically a Magic buff, so it would be dispellable if it didn't also make you immune to dispel.
