### ISSUE TITLE
Timbermaw Reputation Vendor

### ISSUE THREAD

**Issue by infatuationlol** [elysium-project/bug-tracker#236]
Nighthaven PvP 1.3

Expected: Timbermaw Reputation Vendor Meilosh should be selling appropriate recipes upon reaching required reputation ranks Friendly and beyond.

Outcome: Timbermaw Reputation Vendor Meilosh is not selling any of the recipes associated with Timbermaw Reputation.

**Comment by infatuationlol** [comment]
Bump.

**Comment by kreygasm66** [comment]
Well, wait until the 6th and check? :)

**Comment by Terranzin** [comment]
Hello,

I´ve reviewed your issue and I manage to reproduce the error. The NPC with ID: 11557 is certainly missing lots of patterns and plans like example ID (19204, 19202, 19215) and more.

**Comment by Colemata** [comment]
@Terranzin Can you confirm this is still an issue? I see the vendor currently has 26 items in the table, all appear to be accurate.

Marking as fixed until you can examine any further.

**Comment by tubiakou** [comment]
Confirmed still an issue on PTR as of 2018-02-09.  With exalted reputation, meilosh seems to grudgingly offer one recipe (Recipe: Transmute Earth to Water).  See screenshot for illustration:
![image](https://user-images.githubusercontent.com/35384059/36058147-9b34ad12-0de7-11e8-8db8-e15c00908047.png)

Flipping back to Confirmed.

Much appreciated....

**Comment by sidsukana** [comment]
Recipes will be added in next game patches (most in 1.6 and some in 1.10)
