### ISSUE TITLE
Fleeing humanoid always runs instead of walk

### ISSUE THREAD

**Issue by DraZtiK** [elysium-project/bug-tracker#237]
Seems as if this bug is back? Mobs are now running fast away when at low health again.
https://github.com/elysium-project/bug-tracker/issues/153

**Comment by DraZtiK** [comment]
Also, Can anyone confirm mind flays speed reduction is working properly? I tested on the dark iron dwarfs in wetlands and they were not slowed while fleeing.

**Comment by Terranzin** [comment]
Hello,

Please leave it to one issue at a time, that means please add a new issue so the log stays clear. 

Regarding the issue you´re speaking of I did test on a couple of mobs who does flee, and I can´t reproduce the error you´re speaking of. Please add more information such as exactly which mobs that does appear to do this.

**Comment by Terranzin** [comment]
I´m closing this issue, please make a new one with more detail. 

Thank you!
