### ISSUE TITLE
nighthaven toon broken

### ISSUE THREAD

**Issue by wookielovins** [elysium-project/bug-tracker#239]
I cant quest at all. none of my quests are working on this one toon, all others seem to be working fine. I have redownloaded the game and everything I can think of. does anyone know of a fix?

**Comment by Terranzin** [comment]
You´ll need to contact the ingame support team. They probably need to switch your character ID or something similar to fix this issue, sadly we can´t help with that here on QA.

**Comment by wookielovins** [comment]
they told me to contact you.
