### ISSUE TITLE
ench trade bug

### ISSUE THREAD

**Issue by shiniru** [elysium-project/bug-tracker#24]
everytime i try ench a friends bracers through trade it tells me i must have a miscellaneous item equipped, this was working 2 days ago

**Comment by twink** [comment]
Need more info . What enchant exactly?
What item did you try to enchant?
Screenshots.

**Comment by Terranzin** [comment]
Setting this issue as incomplete. Please add more information
- Enchant being used?
- Specific bracers, or all bracers? If a specific, please specify which.
- If possible make a screenshot of the issue.

**Comment by Terranzin** [comment]
27 days has gone no reply, closing issue.
