### ISSUE TITLE
Quest: Ledger from Tanaris

### ISSUE THREAD

**Issue by Zelash** [elysium-project/bug-tracker#240]
I have the same error as a previous shown bug-> https://github.com/elysium-project/bug-tracker/issues/70
I've tried banking my quest items + restarting the game but it didnt help.
By the way, the bug might be cause spider can drop multiple Leg shafts, i ended with 21 so I manually deleted one because I only needed 20. Maybe deleting one causes the bug? Only a guess.
Here's is my screenshot
![tanaris](https://user-images.githubusercontent.com/34929680/34428555-09e38ca8-ec1c-11e7-84e5-39a6cd400677.png)

**Comment by Terranzin** [comment]
Could you attempt what the player did once again, move all items to bank, delete the quest, re-take it and then pick up the items to see if that worked?

**Comment by Zelash** [comment]
Sure i'll try, give me an hour to run to searing gorge to pick it back up then run back to tanaris. Crossing fingers! Least we might know the cause of the bug, if you delete or sell an item required for a quest, this bug may occur.

**Comment by Zelash** [comment]
Reseting the quest the way i said did work, thanks
