### ISSUE TITLE
Quest: Fire Hardened Mail.

### ISSUE THREAD

**Issue by Kinkythemink** [elysium-project/bug-tracker#241]
I have gathered all the materials for the quest but cant turn it in(it says complete in the quest log and all materials are checked). I do not know where the issue lays but I kept the x50 fangs in my bank until I had all the other materials.

**Comment by Kinkythemink** [comment]
Just noticed that Issue #240 has the same problem. I did the same I got more than needed quest items from the mobs so I deleted what was not needed.

**Comment by Terranzin** [comment]
Could you move all items to the bank, abandon the quest and then re-take the quest once again and fill the items needed to your inventory?

**Comment by Kinkythemink** [comment]
Abandoning the quest worked. GM informed me that it would not destroy my quest items even though it says so when abandoning(shuffle the items via bank does not work).

**Comment by Terranzin** [comment]
Sometimes you´ll need to store them, sometimes you´ll need to abandoning the quest. This is a typical errors that happens between client and server at times, a sort of misscommunication.
