### ISSUE TITLE
Item: Spirit of Aquementas

### ISSUE THREAD

**Issue by jesterlol** [elysium-project/bug-tracker#242]
http://wowwiki.wikia.com/wiki/Spirit_of_Aquementas

Should have "Increases spell power by 20" by Patch 1.3.0, it still has "Decreases mana cost to all spells by 25."

**Comment by Terranzin** [comment]
Confirmed: 
_(07-Mar-2005): The effect of the Spirit of Aquementas has changed to a +damage and +healing of all spell schools effect._

**Comment by Terranzin** [comment]
Hello,

Reviewed your issue you need to clear your WDB folder, the item is now being displayed correctly.

**Comment by jesterlol** [comment]
Works.
Ty

:)
