### ISSUE TITLE
Item: Mind Carver

### ISSUE THREAD

**Issue by jesterlol** [elysium-project/bug-tracker#243]
http://wowwiki.wikia.com/wiki/Mind_Carver

Should have "Increases spell power by 12", it has only 7 at the moment.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and I manage to reproduce the error. 

According to old thottbot from 2005 the item did in matter of fact in 1.3 have +12 dmg/heal effect
![image](https://user-images.githubusercontent.com/25831382/34578552-b3ec6f6c-f185-11e7-86b1-619894ca3e5d.png)

But ingame it seems to have the wrong "Equip" effect
![image](https://user-images.githubusercontent.com/25831382/34578586-caf4c42a-f185-11e7-8ab8-73216312aa41.png)

ItemID: 18396
