### ISSUE TITLE
Pet skills bugged [Deathmaw]

### ISSUE THREAD

**Issue by mnemoxjr** [elysium-project/bug-tracker#246]
I tamed time ago Deathmaw but he don't learn any skills except bite... In theory he can use Furious howl, dash, cower, etc. But now is 60 and still don't have any skill more than bite...

**Comment by Terranzin** [comment]
The issue can be with your account ID there is at times issues with players Accounts on database level which makes similar things to happen. Please make a ingame ticket, tell them to create you a new account id on database and try tame him again.
