### ISSUE TITLE
Quest Prerequisite: The Real Threat

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#247]
The Real Threat (Quest 680) is supposed to require Call to Arms (Quest 678).

**Comment by Terranzin** [comment]
QA confirmed

**Comment by Colemata** [comment]
Fix in pull request:

https://github.com/LightsHope/server/pull/1174

**Comment by shenna-elysium** [comment]
If you have found the solution somewhere else, please merge the code to our own repository before you're closing the issue, thank you.

**Comment by Colemata** [comment]
Oops, I meant to leave that comment to review later, and not mark this as fixed.
