### ISSUE TITLE
Item: Savory Deviate Delight

### ISSUE THREAD

**Issue by Aneurysma** [elysium-project/bug-tracker#248]
I have had multiple issues with cooked Savory Deviate Delights having the same effects as the raw fishes. Both deleting WDB folders and disabling addons did not change anything.
Sideeffects include:
Debuff (Cowardice)
Debuff that transform you into an Ooze
Buff Fake Death
Buff Rapid Casting

**Comment by jbshifter** [comment]
I can confirm this.  I ate 4 in a row yesterday and had fake death x3 and ooze once.  Dwarf female.  I have a feeling it is related to race as a human who was in party had no issue with them.

**Comment by Aneurysma** [comment]
I am indeed a dwarf female aswell, very annoying cooking an item and its effect not changing

**Comment by Aneurysma** [comment]
I have now also experienced this bug on a gnome female, did not try to replicate it on human/nightelf yet though.

**Comment by SmokealotapotimuS** [comment]
I ate three yesterday as a male human. Same bug

**Comment by Aneurysma** [comment]
Thanks for the response, up until a few days/a week ago the only effects given by the cooked fish were: 
Yaaarrrr (turns you into a pirate)
Flip Out (turns you into a ninja)

and this changed for some reason or another without notice.
So, if the other "sideeffects" are intended it should have been noted somewhere.

**Comment by fulzamoth** [comment]
The current side-effects are Blizz-like, so they are intended. The instant-cast was a bug and was indeed hotfixed.

**Comment by jbshifter** [comment]
My brother says that the current list of effects is accurate for the patches before 1.11 or 1.12.  So indeed it is correct for this patch.  However given that lots of things have not rolled back to patch 1.3 *cough* talents, I don't understand their decision making in choosing this as one of the rollbacks.

**Comment by Terranzin** [comment]
Anyway, yes we did hotfix the instant-cast and it´s now patched ones again (see latest dev update).
