### ISSUE TITLE
Gyromast's Revenge bug !

### ISSUE THREAD

**Issue by felloz** [elysium-project/bug-tracker#249]
when we scort the npc to the goblin and we the fight starts he dissapear
you need to start spamming some damage when he become in aggresive so he wont dissapear
i think that he dont have any target so he dissapear

**Comment by Terranzin** [comment]
Hello,

I´ve reviewed your issue and manage to reproduce the error.

1: I speak to the robot
![image](https://user-images.githubusercontent.com/25831382/34578771-7a00372e-f186-11e7-8f4a-a4797701c71e.png)

2: He starts to follow the player (escort him to Gelkak Gyromast)
![image](https://user-images.githubusercontent.com/25831382/34578815-a76e92b4-f186-11e7-8b5e-dc8c7d26de64.png)

3: When arriving (marked blue) he instantly despawns when he´s actually ment to start fighting.
![image](https://user-images.githubusercontent.com/25831382/34578827-b56b9362-f186-11e7-88c6-b90de804fcf1.png)
![image](https://user-images.githubusercontent.com/25831382/34578866-deb54542-f186-11e7-8112-a6ebc9d917f6.png)
