### ISSUE TITLE
ooze covered mithril deposit bug 

### ISSUE THREAD

**Issue by vucoo** [elysium-project/bug-tracker#250]
#Nighthaven PvP 

hello, in rustmaul dig site (place in the southwest of the salt flats) there is a place with ooze covered mithril deposit i can mine it and skill up from it but i cant seem to get the loot from it (multiple respawns of it) other players around me can loot it so i was thinkijng it was an addon thing, cleared wdb and interface and nothing, installed a fresh client w/o addons, still the same problem. i can loot regular mithril,ooze silver,iron and gold in the zone/area so im kinda out of option plz help me that is my go to place for farming since i started the game... 
screenshot of the problem:
https://scontent-vie1-1.xx.fbcdn.net/v/t35.0-12/26235735_1667407753373885_693311045_o.png?oh=61d817b43364c529f347e1fa5f69d7d8&oe=5A49CDAE

**Comment by Terranzin** [comment]
There´s a similar issue that was fixed earlier. I can´t manage to reproduce it myself so I´m setting this as confirmed and I´ll let the devs decide what to do with it.

https://github.com/elysium-project/bug-tracker/issues/22

**Comment by twink** [comment]
Screenshot doesn't work. Also impossible to reproduce.

**Comment by ImperialSwag** [comment]
[![Screenshot from Gyazo](https://gyazo.com/6af475648db744cca415f90ca098afc5/raw)](https://gyazo.com/6af475648db744cca415f90ca098afc5)

I can't do it also, probably a lot of people can't do it because there is always 10 nodes here that are left unmined, it gives a level when you try to mine them as well.
