### ISSUE TITLE
Stone guardians and Devilsaurs reseting too quikly.

### ISSUE THREAD

**Issue by cilva** [elysium-project/bug-tracker#251]
Seems like elite mobs in ungoro are reseting way to fast they even reset while in CC or as in this video even while my pet is hitting it. This doesnt seem correct. heres some footage.  https://youtu.be/fNfKdXp2BpE

**Comment by Terranzin** [comment]
I think this might have with the kiting mechanic that was disabled, the script seems to make the mob eventually start evade and run back to it´s original spot. I´ll confirm this since the video is solid proof on whats happening.

**Comment by cilva** [comment]
renable the kiting mechanic its screwing up alot of elite quests and stuff its pointless if a hunter kites kazzak to sw whats the big deal srsly this is dumb...
