### ISSUE TITLE
Misplaced Quest Objects: Atal'ai Artifact

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#253]
Atal'ai Artifact - Object 30854
Atal'ai Artifact - Object 30855
Atal'ai Artifact - Object 30856

Many spawn locations of these objects are too far down, causing them to be inside other objects or under the ground. Some are impossible to see and some are so far down they can't even be reached.

**Comment by twink** [comment]
Fixed. All bugged objects will be on their new fixed positions, not under textures, in the sum 42 objects were replaced.
