### ISSUE TITLE
Durnholde Keep NPCs not attacking/aggroing

### ISSUE THREAD

**Issue by Asipdk** [elysium-project/bug-tracker#254]
In Durnholde Keep you can pretty much run right up to the npcs sometimes in the houses and strip and dance in front of them and they won't aggro, sometimes you can even attack them for some reason. Definitely some sort of bug, not something I can tell you how to reproduce just an issue I've noticed several times now.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and manage to reproduce the error. My character was level 36 while the mobs are around the same level, even when standing infront of them, they still won´t aggro.

![image](https://user-images.githubusercontent.com/25831382/34579051-b58e9c80-f187-11e7-83be-1d5bf4e35681.png)
