### ISSUE TITLE
Quest Level Requirement: Back to Booty Bay

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#255]
Back to Booty Bay (Quest 1118) currently requires level 43.

Here is an Allakhazam comment from 2005 reporting the player did it at 38:
http://web.archive.org/web/20060416014023/http://wow.allakhazam.com:80/db/quest.html?wquest=1118

Thottbot data from 2008 says the req is 35:
https://web.archive.org/web/20080526113652/http://thottbot.com:80/?qu=1118

But in TBC they did lower the req of some quests, so the correct level req is either 35, 36, 37, or 38.

Most likely it should have the same level requirement as its prerequisite, Rumors for Kravel (Quest 1117), which currently requires level 36.

**Comment by shenna-elysium** [comment]
Ok, 36 now.
