### ISSUE TITLE
Quest Level Requirement: Goblin Sponsorship (Chain)

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#256]
Quest 1183 - Goblin Sponsorship (5) currently requires level 37.
Quest 1186 - The Eighteenth Pilot currently requires level 34.
Quest 1187 - Razzeric's Tweaking currently requires level 34.
Quest 1188 - Safety First (1) currently requires level 41.
Quest 1189 - Safety First (2) currently requires level 41.

This whole quest chain should require level 29. Many old comments about twinking confirm this. This was a favorite quest chain among 29 twinks.

**Comment by fulzamoth** [comment]
This report looks to be correct. Old (2007 earliest) entries at wowwiki show it's a level 37 quest that requires level 29.

http://wowwiki.wikia.com/wiki/Quest:Goblin_Sponsorship?direction=next&oldid=579083
