### ISSUE TITLE
[Respawn Timer] Prince Nazjak Elysium = Nighthaven?

### ISSUE THREAD

**Issue by kreygasm66** [elysium-project/bug-tracker#257]
O hai,

Is the respawn timer, coding, the same as it was on Elysium?
I know how long it took on Elysium; is it just as long here?
Thanks in advance! :}

**Comment by fulzamoth** [comment]
Should be close if not the same as on the old instance. 

For future reference, this isn't a bug report. Questions should be asked on the forums.
