### ISSUE TITLE
Uncommon cloth items (chest, shoulder, and feet) are not spawning with  the "Of Fiery Wrath" Affix

### ISSUE THREAD

**Issue by Greltheruk** [elysium-project/bug-tracker#258]
Nighthaven patch 1.13

For the past three weeks I've been scouring the auction house and have not found a cloth chest, cloth shoulders, or cloth feet that are of the fiery wrath affix.

I've seen multiple wrath affixes for these items but never for fiery. At first I thought that people might be vending them or disenchanting them but finally after roughly 3 weeks and not seeing any indication of their appearance, it was time to make a ticket.

Please look into this, it would help fire mages adventuring through Azeroth

**Comment by Soyoen** [comment]
The spell damage affixes shouldn't be available in the first place at patch 1.3.

**Comment by Terranzin** [comment]
Closing since we´re in patch 1.3 on Nighthaven.

**Comment by fulzamoth** [comment]
FWIW, there are items "of Fiery Wrath" in game.

![fiery](https://user-images.githubusercontent.com/26393979/34650778-6fda32bc-f394-11e7-8b59-465f9b81ef3a.jpeg)

**Comment by Terranzin** [comment]
Yes now when we´re at Patch 1.4 - correct.
