### ISSUE TITLE
Removed from SFK Group But Was Still In Party Chat, Received XP & Loot, etc.

### ISSUE THREAD

**Issue by wirerydr** [elysium-project/bug-tracker#259]
**Server**:        Nighthaven PvP
**Patch**:         1.3
**Client**:         1.12.1
**Time/Date**:  2017-01-02, Approx 5:30am server-time

## Synopsis
Removed from party running SFK but able to remain zoned in, receive loot, XP, _etc_.

## Description
While in Org, got invited to a group currently mid-way through an SFK run.  Made my way over to SFK, and zoned in, but was immediately disconnected.  Once I logged back in I noticed that I was no longer part of the group (e.g. no party frames visible).  However I could still see other party members running around in the instance, view their party-chats, roll on loot, and I received XP / gold for every kill.

According to the party lead I had apparently been bumped out of the party to make space for a previous member who had DC'ed.  They did this without telling me.  They say they did this while I was still in Org, but a review of my chat log doesn't show any indication that I left group at all - either while in Org or at any time right up until entering the instance.

While exploring this in order to write a bug-report, I followed along, and was able to enter combat with mobs as the party engaged them.  I was also given the chance to roll on various items, including a roll (which I won) on a blue loot-drop from the 2nd-last boss.  The blue item subsequently appeared in my inventory.

The situation also apparently affected one of the party members' ability to loot Arugal's head at the end of the run.  Throughout, I received XP and gold for every kill even if I hadn't entered combat, and I could participate in Party chat.

**Comment by tubiakou** [comment]
Various attempts to reproduce this on PTR have failed dismally.  Closing as invalid until someone manages to get the issue to reoccur.
