### ISSUE TITLE
Character lost after boarding a ship

### ISSUE THREAD

**Issue by joker3896** [elysium-project/bug-tracker#26]
Hi, really need of assistance here. After getting on a ship to another continent my character caught a lag, I am stuck in the middle of the ocean, I cannot see myself, I cannot use hearthstone. All i see is sky and the sun, my characters profile pic by the health bar is gone. Please could you recover him, his name is Millioner lvl 17 Hunter on Nighthaven server.

**Comment by shenna-elysium** [comment]
Your character has been transported to a safe place. Please submit a ticket next time :) Click the ❓  in the in-game menu, click Character, and enter your report.

**Comment by joker3896** [comment]
thank you so much that was quick!
