### ISSUE TITLE
Не могу завершить квест "The rise of the machines"

### ISSUE THREAD

**Issue by Shuuum** [elysium-project/bug-tracker#260]
Условия выполнены, рядом с квестом висит (complete) Но знак вопрос над квестгивером серый, и сдать его не могу, нужные предметы в сумках. Всё есть на скриншотах.
![wowscrnshot_010218_131327](https://user-images.githubusercontent.com/35025408/34478238-b43d4c90-efc1-11e7-8176-649412a3e72a.jpg)
![wowscrnshot_010218_131334](https://user-images.githubusercontent.com/35025408/34478239-b46280be-efc1-11e7-81e9-988225ba2a2c.jpg)

**Comment by fulzamoth** [comment]
This is a frequent problem we see. Try:
- putting items in bank and taking them out again
- putting items in first bag ("Backpack")
