### ISSUE TITLE
Most escorts (if not all) bugged.

### ISSUE THREAD

**Issue by Zygga** [elysium-project/bug-tracker#262]
I first noticed the In Dreams escort beings bugged a few days ago (which has been a confirmed issue I saw listed). Now today I do the Defias Traitor escort, and noticed it had the same bug problem as In Dreams. Then later today, I saw people doing the escort in Redridge from the cave in the north, and that was ALSO bugged the same as In Dreams and Defias escort (where the escort wont hit the mobs and runs in spot). On top of that I just did the Elite escort Gyromast's Revenge in Darkshore, and soon as he was supposed to fight, he vanished. These problems weren't on Elysium before, and now have appeared out of no where. Pretty significant issue, hope it gets fixed!

**Comment by Terranzin** [comment]
Hello,

There is already issues of these escorts, not all escorts is bugged but a few is for sure and needs to be fixed (tend the "Confirmed").

In dreams:
https://github.com/elysium-project/bug-tracker/issues/244

Gyromast's Revenge:
https://github.com/elysium-project/bug-tracker/issues/249
