### ISSUE TITLE
Young Crocolisk Skins - Wetlands Quest

### ISSUE THREAD

**Issue by Goldelian** [elysium-project/bug-tracker#263]
Hello,

The NPC "James Halloran" from Wetlands does not give me access to the quest "Young Crocolisk Skins".

The NPC acts like he has no quests to give.

I have also tryed to get it from a guildie that was in my party standing just next to me and tryed to share it. It was saying "You are not eligible".

I suppose this is a bug?

Regards,
George

**Comment by Soyoen** [comment]
Prequest required.

**Comment by Terranzin** [comment]
Have you done the prequest for this issue?
