### ISSUE TITLE
Stitches getting hung up in middle of Duskwood

### ISSUE THREAD

**Issue by fulzamoth** [elysium-project/bug-tracker#264]
**Server:** Nighthaven PvP
**Patch:** 1.3
**Client:** 1.12.1 (Mac)
**Time/Date:** 2018-01-02 - many user reports since 2018-12-29 development update

# Summary

Stitches gets hung up battling an NPC patrol in middle of Duskwood.

# Expected behaviour
Stitches should patrol along the main road through Duskwood.

# Actual (unexpected) behaviour
Stitches is getting hung up in the middle of the zone battling NPCs. Neither Stitches nor the NPCs do any damage to the other, but glitch and appear to reset their paths. The entire time Stitches will yell "ROARRR" across the zone.

Running through him or otherwise engaging him in combat with a Horde character will pull him off the glitched point, but one he disengages he returns to the same point and is immediately stuck again.

---
The last server patch introduced creature AI changes related to evading unreachable targets. This may be related to that.

**Comment by Terranzin** [comment]
Already confirmed by staff.

**Comment by Terranzin** [comment]
Already fixed in earlier patch never got changed here.
