### ISSUE TITLE
Improved Power  Word : Fortitude

### ISSUE THREAD

**Issue by Platray** [elysium-project/bug-tracker#265]
Hi, 
Today i've see a problem with this buff, The rank 5 said increasing Stam by 55 for 30m ( with the talent 2/2 ), but only increase by 43
I've deleted WTB but nothing work

**Comment by totokadoba** [comment]
Check how much your health goes up after the buff. I remember this being a problem in Vanilla in that that stam increase isn't displayed as increased but the extra stam is actually applied.

**Comment by Terranzin** [comment]
This is just a normal display/procedure for Vanilla. Usually it does not display the talent specilization, the Improved Power Word:Fortitude works.
