### ISSUE TITLE
Small Jump Resulted in Instant Death

### ISSUE THREAD

**Issue by Asipdk** [elysium-project/bug-tracker#268]
So I was in thousand needles, and after coming down from a few of the giant spires. I walked over a tiny little cliff as shown in the picture and it instantly did all 1073 health from that fall.  Fall Site with Coordinates, right by the ramp up to kill the tauren. Coord 31,38 ![Fall Site with Coordinates, right by the ramp up to kill the tauren. Coord 31,38](https://i.gyazo.com/c181640676f44ed0cf10dd23273c253f.jpg)

**Comment by Terranzin** [comment]
Sadly I can´t reproduce this issue. I´ve been jumping back and forth around this ledge and nothing happens.

I would´ve needed more solid proof as a video to even make this confirmed, sadly for now we´re closing this issue.

![image](https://user-images.githubusercontent.com/25831382/34579738-96e251e8-f18a-11e7-987e-d96bec075aae.png)
