### ISSUE TITLE
Spirit of Sathrah spawns infinitely

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#27]
Spirit of Sathrah: http://db.vanillagaming.org/?npc=7411

Player's Submitted image: https://cdn.discordapp.com/attachments/377099887973761024/380230592790528001/WoWScrnShot_111517_003844.png

**Comment by Macsimka** [comment]
Can't find this creature.

**Comment by Terranzin** [comment]
I´ve reviewed your issue.

**Use-case:**
- Picked up quest in Darnassus "The Temple at the moon" (QuestId: 2519)
- Continued to next step (QuestId: 2518) and killed Lady Sathrah (NpcID:7319)
- Looted "Silvery Spinnerets" with Id: 8344
- Went back into Darnassus to the Temple at the moon, rightclicked the item and I noticed she spawned serveral times close to the wall. 
![image](https://user-images.githubusercontent.com/25831382/32854127-eaa8fb5c-ca3d-11e7-9d1d-c2dc6793aaf8.png)

Two things needs to be fixed:
- She should only spawn as one ghost.
- She should walk around the fountain, now all she does is stand still.
