### ISSUE TITLE
Dungeon: Maraudon summoned adds does not attack

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#272]
Use-case: 
1: Start the fight with Corrupted Celebras
2: Kill his adds
3: Wait for new Corrupt Force of Nature to be summoned by boss.
4: The adds does not attack the players.

Summoned NPC: 13743

![image](https://user-images.githubusercontent.com/25831382/34576702-122e09d4-f17f-11e7-9cae-014aded737a3.png)

**Comment by DriftReal** [comment]
working on it!.

**Comment by DriftReal** [comment]
it should be fixed by last PATCH!
