### ISSUE TITLE
Robe of Winter Night Pattern

### ISSUE THREAD

**Issue by babblingbrooke** [elysium-project/bug-tracker#273]
The pattern for Robe of Winter Night dropped while I was in a group with 1 other person who was dead when I looted. It did not prompt us to roll and we were on group loot. When I tried to loot the item it said that it was still being rolled for. Eventually the mob disappeared without us getting the item.
Link to screenshot: https://drive.google.com/open?id=1UXSw-4w7uZU3tbL_3rMn8dPeehNJ9zNc

I opened a ticket and the GM said that item wasn't in the game yet and couldn't help. I showed him that there is actually a robe for sale already in the AH so he told me to open a bug here since he couldn't see it in the logs. 
AH screenshot: https://drive.google.com/open?id=10fScQlVSKuCfstctswsnpYglMJK047ij

Other reports of this problem in the past: https://github.com/LightsHope/server/issues/411

**Comment by fulzamoth** [comment]
Thottbot entry from 2005-02-25 (pre-Patch 1.3):
https://web.archive.org/web/20050225005022/http://www.thottbot.com:80/?i=8129

**Comment by Terranzin** [comment]
Hello,

I´ve tried to reproduce the error and it´s hard to actually reproduce. It´s a very special case when this happens but we can´t help you restoring a lost item through the bug tracker.

I´m sorry but this issue needs to be closed, if it happens again with this item (which should´ve just been a once in a life time error) it can only be restored from ingame by GMs, and yes the item does exist in our present patch.

**Comment by babblingbrooke** [comment]
I was able to reproduce this 4 times with the same item while in a group. I was even in groups with different people each time. I dropped group and others just helped me kill things that I would tag and we got the robe no problem in 2 kills. There is just a weird bug happening when people are in groups with that specific pattern.
