### ISSUE TITLE
Quest: The Scarlet Oracle, Demetria

### ISSUE THREAD

**Issue by Arrghrow** [elysium-project/bug-tracker#274]
Having tried multiple times I'm now confident that Demetria and her adds always bug out upon engage on their patrol to Stratholme - other players and groups have reported the issue as well. 

The NPC-pack including Demtria behave normally until you engage them the first time after which they go into an evade-patrol mode where their speed increases significantly and they keep evading/resetting until they despawn at Stratholme.

**Comment by Terranzin** [comment]
Hello,

I´ve tried to reproduce the error on our test server and I kited her around, and fighting for atleast 5 minutes without any evade. I´ll need to look into this matter on Nighthaven.

![image](https://user-images.githubusercontent.com/25831382/34788458-ec72abf8-f63a-11e7-84d4-87fc895b03cf.png)

**Comment by Terranzin** [comment]
I´ve now tried to make her bug out for past 20 minutes on Nighthaven but can´t be reproduced. Been talking with GMs and they are going to contact me when the issue appears on Nighthaven, until then I´ll close this issue.
