### ISSUE TITLE
Quest: Call Of Water (part 7) problem

### ISSUE THREAD

**Issue by inlen** [elysium-project/bug-tracker#275]
So yesterday I was finishing up my call of water quest for my water totem. I got to the part 7 where you need to talk to the minor manifestation of water and the server crashed. When it came back up i was without a buff and he was not there. So I talked to Tiev Mordune in the area and he says all i need to do is bring him a Water Sapta. Problem is Islen waterseer who gives the quest doesn't give you any more Water Sapta's and if you abandon the initial quest you cant do it again to get another one. Anyone have this problem to and how did you fix it. Thanks. Nick Joxi, server Nighthaven PvP

**Comment by Terranzin** [comment]
Hello,

Regarding your issue you´ll need to contact our ingame support, when these things happens because of a server crash we can´t do much to fill/fix these gaps. They´ll need to provide you with the item once again.
