### ISSUE TITLE
Astor Hadren not going infight

### ISSUE THREAD

**Issue by Paulbsh** [elysium-project/bug-tracker#277]
As requested in the lvl 10 rogue quest, I need to talk and fight Astor Hadren in front of UC.
As soon as you talk to him, he just runs away. tried to talk to him from uc to silverpine forest and back to uc,
This was experienced on Nighthaven PVP

**Comment by Terranzin** [comment]
I´ve tried to reproduce your error but can´t manage to do so.

![image](https://user-images.githubusercontent.com/25831382/34842910-3f279674-f70d-11e7-893e-d50c1974eff8.png)
