### ISSUE TITLE
Leatherworking issue

### ISSUE THREAD

**Issue by Tuktuu** [elysium-project/bug-tracker#279]
I play on Nighthaven PvP server, version 1.12.1.

I am playing a night elf druid, with leatherworking as profession. My skill is now around 75, and I can't make "cured light hide", and none of the trainers in Darnassus can teach me it. They do teach "cured medium light hide" and "cured heavy light hide", but not "cured light hide". 

I believe that the trainers should teach me this, and now im kinda stuck in my LW progress. 

I attached a picture with a trainer that teaches this skill (taken from nostalrius, and its a tauren trainer, but still, I think it should be the same for night elf trainers).
  
![jrngj1t](https://user-images.githubusercontent.com/35168639/34639947-cc582cfc-f2e9-11e7-8d9d-3d2a4dcd571a.png)

**Comment by Tuktuu** [comment]
The layout of this post became very unclean. Don't know why.

**Comment by tubiakou** [comment]
Unable to reproduce on PTR.  Actually your screenshot does not look representational - you appear not to have learned leatherworking on that toon yet.

I took a lvl 31 night-elf druid and visited Waldor while having a leatherworking skill-level of 73.  Waldor was quite willing to teach me Cured Light Hide.

I then visited Darianna, one of the Leatherworking trainers in Darnassus.  She was also quite willing to teach me Cured Light Hide, as-shown in the attached screenshot.
![darianna](https://user-images.githubusercontent.com/35384059/34909537-f42716d0-f870-11e7-88d7-6c049e9b2ccb.jpg)

Please return to one of the Darnassus leatherworking trainers such as Darianna (on Nighthaven this time), and if you still have problems then please take a screenshot with the actual character that is having the issue.  In the screenshot please try to show both the vendor pane as well as your skills character tab.

**Comment by Tuktuu** [comment]
Well, i solved the issue after trying the LW trainer in IF, and then finally SW where it worked. My skill was indeed high enough to learn it :)

Sendt fra min iPhone

Den 20. jan. 2018 kl. 20.00 skrev Andréas <notifications@github.com<mailto:notifications@github.com>>:


Closed #279<https://github.com/elysium-project/bug-tracker/issues/279>.
