### ISSUE TITLE
Tribal Leatherworking not registering

### ISSUE THREAD

**Issue by Pikseh** [elysium-project/bug-tracker#280]
Hello

With the new update, the Devilsaur set now properly lists Tribal Leatherworking as a required skill in order to learn. However, it seems that the recipe is not registering this at all. Here is a screenshot I took this morning after failing at learning the skill. I have 290/300 Leatherworking and have completed the Tribal Leatherworking quest chain, as can be seen in my spellbook.

Imgur link: https://imgur.com/4ihtRik

![bug](https://user-images.githubusercontent.com/3406509/34647781-8f430bea-f38c-11e7-8dd9-461480d6f2ea.PNG)

**Comment by Egregious** [comment]
Thank you for the heads up. We will correctly attach these items to their specialization.

**Comment by Terranzin** [comment]
Thanks for the picture, we´ll have a look into it. Have you tried clearing your WDB folder?

**Comment by Pikseh** [comment]
Yes, I tried before clearing and after. Nothing changed, and the skill still could not be learned.

**Comment by twink** [comment]
Fixed.
