### ISSUE TITLE
Quest: The Deserters (part 1)

### ISSUE THREAD

**Issue by tishtishh** [elysium-project/bug-tracker#281]
Description:
Get information about Reethee from Balos Jacken and the deserters in Dustwallow Marsh.

This is a quest chain started from an object in the Shady Rest Inn close to the Barrens/Dustwallos marsh border. You then have to talk to some people in Theramore before you get this part.

Issue:
You are supposed to attack Balos Jacken in the tower and when at low HP he becomes friendly and you are able to turn in the quest and get the next part. This however doesn't work since he is always unfriendly. When you get him to enough low HP the HP just resets and he will still be unfriendly. It is possible to kill him if you are quick enough but he just re-spawns after some seconds, unfriendly, and the same issues are present.

**Comment by tishtishh** [comment]
Just noticed today that this issue only occurs if you fight him where he usually stands. If you pull him all the way down and fight him he actually becomes friendly and you can turn in the quest.

**Comment by Terranzin** [comment]
I´ve looked into your issue and manage to reproduce the same error. 

When he´s down at the correct health he "resets" and spams the text about him giving up (see chatlog)
![image](https://user-images.githubusercontent.com/25831382/34843339-7497edbc-f70e-11e7-900f-1acca911876f.png)

After a couple of resets his health flies up from ~10% to 50% and he continues his attacking, this appears everytime his health goes down to correct values.

![image](https://user-images.githubusercontent.com/25831382/34843381-9691517e-f70e-11e7-920e-9ffaf6bef8c3.png)

**Comment by twink** [comment]
Fixed.
