### ISSUE TITLE
Horde Patrol on Arathi Highlands is bugged

### ISSUE THREAD

**Issue by felloz** [elysium-project/bug-tracker#282]
I cannot complete Hints of a New Plague because the Forsaken Courier and their patrol is bugged, when i try to attack them they just evade my attacks.

Edit:

I could complete it only standing in fron on the patrol

**Comment by Terranzin** [comment]
I´ve tried to reproduce the error you´re speaking of but can´t manage to get the same error. I tried attacking them several times without encountering any evades.

![image](https://user-images.githubusercontent.com/25831382/34843691-7c46e878-f70f-11e7-89d7-41b684f17f98.png)
