### ISSUE TITLE
Quest: Westbrook Garrison Needs Help! prereq

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#283]
Westbrook Garrison Needs Help! (Quest 239) is supposed to require The Jasperlode Mine (Quest 76).

Proof in comments:
https://web.archive.org/web/20070311052407/http://www.thottbot.com:80/?qu=239
http://db.vanillagaming.org/?quest=76#wh-comments
http://db.vanillagaming.org/?quest=239#wh-comments

**Comment by Colemata** [comment]
https://github.com/elysium-project/server/pull/3290
