### ISSUE TITLE
20+ Gyromast's Revenge Elit quest

### ISSUE THREAD

**Issue by raventn** [elysium-project/bug-tracker#284]
Faction: Alliance
Quest in Darkshore.
NPC:  Gelkak Gyromast

Find Gelkak's First Mate, the Threshwackonator 4100, and lead it back to Gelkak.

Bring back works but then it complete dissapear! 
tryed 3 times and it dosen't work.

Gelkak talk but nothing happens.

**Comment by Terranzin** [comment]
Please search for the issues before adding new one, there is already a confirmed issue https://github.com/elysium-project/bug-tracker/issues/249
