### ISSUE TITLE
Quest: Ammo for Rumbleshot quest item

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#285]
Ammo for Rumbleshot (Quest 5541) currently provides the quest objective (Item 13850 - Rumbleshot's Ammo) to the player when picking up the quest.

It should not do this.

The player is supposed to find Rumbleshot's Ammo inside Object 176785 - Ammo Crate, which works correctly.

**Comment by Macsimka** [comment]
Fixed for all quests, that have two quest givers, item and creature.
