### ISSUE TITLE
Voidwalker Torment unavailable

### ISSUE THREAD

**Issue by gricen** [elysium-project/bug-tracker#289]
Hi
I am a level 38 warlock and today my Torment icon in my petbar is there but has a rotating light circling around saying it is unavailble andI cannot Taunt anything when attacking now

I did log out and disable all add ons but that didn't work

I also summoned all my other minions and they are all okay

Summoned the Voidwalker but still as before with this circling light around Torment Icon
It happened when I was in Desolace and now will not work!

Any ideas?

**Comment by Terranzin** [comment]
I´ve tried to reproduce the error you´re mentioning. Could you try contact our ingame support see if there´s anything with your client? Try clear WDB folder and so on.
