### ISSUE TITLE
Blasted Lands: Quests of the two blood elves #3252

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#29]
**From old tracker:**

> hi guys
> 
> These quests should appear with blue question marks after you finished them the first time, due to them being repeatable. In Feralas it's the other way around with the goblin. They are from the beginning with blue question marks inatead of being a yellow exclamation point first.

**Comment by Terranzin** [comment]
This issue has already been confirmed by QA.

**Comment by twink** [comment]
Need a list of quests.

**Comment by shenna-elysium** [comment]
http://db.vanillagaming.org/?quest=2585
http://db.vanillagaming.org/?quest=2583
http://db.vanillagaming.org/?quest=2582
http://db.vanillagaming.org/?quest=2586
http://db.vanillagaming.org/?quest=2581
http://db.vanillagaming.org/?quest=2584
http://db.vanillagaming.org/?quest=2602
http://db.vanillagaming.org/?quest=2604
http://db.vanillagaming.org/?quest=2601
http://db.vanillagaming.org/?quest=2603

**Comment by twink** [comment]
Yes, looks like all of them must be. Fixed.
