### ISSUE TITLE
Shadowmeld not like vanilla

### ISSUE THREAD

**Issue by Lupeh89** [elysium-project/bug-tracker#291]
Shadowneld does not work like vanilla.

As in vanilla hunters could shadowmeld and then cast aimed shot, and he would stay stealthed until the aimed shot would fire.

On nighthaven Pvp when u cast aimed shot while shadowmelded this will result in leaving shadowmeld as soon as u cast aimed shot.

The proof of this can be found in this vanilla wow movie : https://youtu.be/7acKg3Mziw0

Skip to 18:21 to see it happen.

Now look at his hunter bow. This means that this was after patch 1.4.
It's clearly not a late patch given the fact that all the players you see in the video are t1 geared or lower.

Also back in the day in early patch hunters rhok and lok delar where  it 2 items but u could only have 1 at the time of them. This worked simular like benediction and anathema where u could  transform to either one of the 2.

Proof of this u can also find in luptis his pvp videos.

**Comment by Navashed** [comment]
This is not a bug.

Private servers use 1.12 game mechanics. Shadowmeld + Aimed Shot was nerfed in patch 1.10.

http://wowwiki.wikia.com/wiki/Patch_1.10.0
"Stealth and Invisibility effects will now be canceled at the beginning of an action (spellcast, ability use etc...), rather than at the completion of the action."

**Comment by Lupeh89** [comment]
Yes true but nighthaven is at patch 1.4 atm

**Comment by Terranzin** [comment]
Hello,

This is true, and we´re well aware that we are at patch 1.4 though like my QA member is saying we´re using the 1.12 game mechanics which goes thru most if not all private servers.

**Comment by Lupeh89** [comment]
Allright thanks for reply
