### ISSUE TITLE
Real Guild Member Number Cap is 868

### ISSUE THREAD

**Issue by Hvethrungr** [elysium-project/bug-tracker#292]
Nighthaven
January 8th 2018.

Crogge has told me the guild cap was removed and that it should be essentially limitless, however, in practice this is not the case.

When a guild reaches 868 members you can no longer add new players to the guild.

You send an invite, the player receives the invite, accepts it, then nothing happens. 
They do not join the guild after accepting the guild invite. 
When you try to send them another guild invite it says that player has already been invited to a guild.

Was tested and proven to be an issue with Game Master Armedius. 
Armerdius escalated to development team, I received an in game letter directing me here. 

My in game username is Hvethrungr and the guild experiencing this bug is Men of the West, an Alliance side guild.

**Comment by Terranzin** [comment]
This has been fixed, there´s guilds on the server right now with 1065 members in it.

**Comment by Hvethrungr** [comment]
Tested it working, minor problem though is that as you invite more people it still says the guild count is 868.
