### ISSUE TITLE
Mac DC upon any instance entering.

### ISSUE THREAD

**Issue by Malogico** [elysium-project/bug-tracker#293]
Right after patchwork on 1/8/18 mac client stopped working, most times i hearth or teleport it crashes but still teleports me, however when i try to enter a dungeon it crashes and kicks me out over and over so i cannot do any dungeons. Tried disabling addons and deleting wbd folder to no avail, help please!

**Comment by LordZuckuss** [comment]
I am having the exact same thing. Re installed with 0 add ons and fresh copy but still have issue entering and exiting instances. This was Driving me nuts. Nightshade server.

**Comment by jonasbrother69** [comment]
Same here, playing on Mac as well.

**Comment by marshzor** [comment]
Same with me, playing on a Mac 

MacBook Pro (Retina, 13-inch, Early 2015) MacOS Sierra 10.12.5

**Comment by marshzor** [comment]
Here's an error report from after the crash on my machine https://gist.github.com/marshzor/ed17c86d2ff079b562d7a58bfa5ee93e

**Comment by LordZuckuss** [comment]
Can any of you guys on MAC successfully log out after this patch? Every time I log out it crashes and therefor loses any interface changes. (Either add ons, or with out)

**Comment by sebastianjonas** [comment]
same problem here. and it crashes on logout

**Comment by Terranzin** [comment]
We´re looking into the issue being reported by MAC users. Thanks!
