### ISSUE TITLE
Hunter: Pet keeps disappearing (permanently) 

### ISSUE THREAD

**Issue by wongjoo** [elysium-project/bug-tracker#294]
Hunter pet keeps disappearing. It has happened 3 times, once while going through a portal, once when logging back on, and once between killing mobs. I tried recalling, reviving, checking stables, and relogging. No luck. This makes me very concerned about investing time into acquiring pets. Note: All 3 times were Strigid Hunters (owls).

**Comment by Terranzin** [comment]
We´ve had similar reports and I cant manage to reproduce it, but we´ll have the devs look into it. Maybe they´ll find something.

I tried both zoning, using portals, entering dungeons etc.

**Comment by twink** [comment]
Try to use other pets, we can't fix a bug that impossible to reproduce.

**Comment by chaospotato** [comment]
Had this happen to me in Maraudon - first at the entrance with the centaur by the door, the owl disappeared and only reappeared when i Feign Deathed. Then while speaking to a GM about hunter pet icon issues, it disappeared midcharge while I was attacking a Diemetron inside Maraudon. No i did not get the "you pet has run away" message either.
