### ISSUE TITLE
Quest: The Balance of Light and Shadow (Blocked)

### ISSUE THREAD

**Issue by Jaxrs** [elysium-project/bug-tracker#297]
I successfully completed the event (twice) but the quest doesn't complete (NPC doesn't despawn so it's not failed). A GM (Theflame) completed quest in my log for me, but I'm still unable to turn it in.

Please fix!

I need my bene!

**Comment by Aneurysma** [comment]
Tried to start the quest but unable to speak with Eris Havenfire.
So not able to neither start nor complete the event.

**Comment by Jaxrs** [comment]
That might be from the bad state from when I "completed" the event. Make sure you have the Eye of Divinity equipped. I didn't have an issue accepting the quest 'The Balance of Light and Shadow' or completing the prequest 'A Warning'

**Comment by Aneurysma** [comment]
The quest-NPC has a "?" on her and is visible even without equipping "The Eye of Divinity".
Both with and without the trinket I am not able to talk to her, so I can not even start or complete the prequest.
As you see in the screenshots below she is visible with and without the trinket equipped and has a "?" above her head. But no interaction with her is possible.
![wowscrnshot_010918_222846](https://user-images.githubusercontent.com/34961992/34744164-923aa554-f58c-11e7-922b-a231aec13d2c.jpg)
![wowscrnshot_010918_222857](https://user-images.githubusercontent.com/34961992/34744174-98b041c8-f58c-11e7-8b98-f35bb4770f0a.jpg)

**Comment by Jaxrs** [comment]
RIP

**Comment by Terranzin** [comment]
Thank you for your extensive report with pictures. You´ve provided enough evidence to make this confirmed, thanks!

**Comment by twink** [comment]
I am not able to reproduce, but must be fixed.
