### ISSUE TITLE
Auto attack and spellcasting (Lightning Bolt)

### ISSUE THREAD

**Issue by Sarmatius** [elysium-project/bug-tracker#3]
Nighthaven PvP
Observed: Casting Lightning Bolt while auto attacking resets attack leading to no white hit.
Intended: Casting an offensive spell with cast time, while the time left until next white hit is shorter than cast, makes the white hit go off immediately on spell cast finish. (If the spellcast finished before the white hit was supposed to go off, the autoattack sequence would reset as it is the case everytime on live server)

While playing on Nostalrius and Elysium as a Shaman it was a standard way of doing damage -  autoattacking between Lightning Bolt casts. Casting a Healing Spell or Chain Lightning would reset autoattack sequence though, leading to no white hit. It also worked as a Mage with Fireball and Frostbolt.

**Comment by Fleisher** [comment]
Confirmed on PTR.

**Comment by cemak** [comment]
https://github.com/elysium-project/server-staging/commit/dfe4f25ee1119e7c05bd8bf20f9f63f4cd019491
