### ISSUE TITLE
10-19 Warsong Gulch is disabled #3179

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#30]
From Old Tracker:

> Players who are level 10-19 cannot queue for Warsong Gulch. The button is missing and WSG Battlemaster NPC is behaving like the AB and AV Battlemasters for all players level 10-19, when last patch it was allowing queues for WSG. I think this is a programming error due to the new patch 1.7 on the Elysium servers that came out today. In actual Vanilla these players couldn't queue till patch 1.8 I believe. So this ZG patch ended up disabling WSG for players levels 10-19. But the bracket could queue before on the previous BWL patch. So it's not fair for players like me who play solely for the WSG 10-19 bracket. It was already previously enabled.

**Comment by Terranzin** [comment]
This issue has already been QA confirmed. Thanks for reporting!

**Comment by shenna-elysium** [comment]
Additionally: Warsong Gulch was introduced in Patch 1.5 "Battlegrounds". 
Nighthaven PvP is currently running on Patch 1.2. So it's to be fixed but later.

**Comment by brotalnia** [comment]
It's not a bug @shenna-elysium 

https://github.com/elysium-project/database/blob/master/progression/Patchnotes%20%28ALPHA%20to%201.12.1%29.txt#L3683

> - World of Warcraft Client Patch 1.8.0 (2005-10-11)
> Players of levels 10 - 19 will now be able to participate in the battle for Warsong Gulch.

**Comment by shenna-elysium** [comment]
Yes, figured, thanks.
