### ISSUE TITLE
Since today: Travel Form bug in town (booty bay for example) "You can't mount here"

### ISSUE THREAD

**Issue by Pmt112** [elysium-project/bug-tracker#300]
Hey since just today got a bug on travel form, trying to shapeshift into travel form in booty bay returns "you can't mount here" which afaik is a bug? on any patches of vanilla i played before, i can use travel form in any cities so long as i am "outside". it is not a mount. one of best defense for moving away from assassin too for druid

**Comment by Terranzin** [comment]
No this isnt a bug, this was implemented because back in retail vanilla at this patch you could not use shapeshift or mounts in booty bay.
