### ISSUE TITLE
Fall dmg to death on the great lift 

### ISSUE THREAD

**Issue by roogajr** [elysium-project/bug-tracker#301]
hello. 

when you exit the lift (the great lift entrance to thousand needles) at the bottom, You take fall dmg and die. as you jumped off from the top. this should be fixed since its really annoying. even tho graveyard is right next to the lift.

Best regards
Steini

**Comment by Navashed** [comment]
I was not able to reproduce this issue. Riding the Great Lift did not incur any fall damage.
