### ISSUE TITLE
Invisible Herbs

### ISSUE THREAD

**Issue by aleekemal** [elysium-project/bug-tracker#302]
I was gathering herbs, found at silverpine forest some herbs being invisible when get close
the situation can be seem on that video
https://youtu.be/Hdbmpxshbak

**Comment by Sadumon** [comment]
I've also seen it -- there is some weird phasing going on at the entrance to Silverpine.  Herbs will show up on the minimap and you can see them, but as you approach it's like you enter a different phase and the herbs aren't there.  Mobs also appear/disappear as you cross that "phase" border (which is not the zone border, at least not according to the client, it is a little ways in Silverpine.

**Comment by Egregious** [comment]
That is due to those specific nodes being placed under the terrain. We will look into the issue further.

**Comment by Egregious** [comment]
That is due to a zoning bug. It looks as if that region of the map has not been correctly entered as Silverpine Forest.

I will test this issue further.

**Comment by Terranzin** [comment]
Been testing this issue and it´s been hard to reproduce, but we are aware there is a few zoning issues that happens, one example was when we had the christmas event on GM Island. I´ll confirm this and ask the devs take a look into the zoning issue.

**Comment by twink** [comment]
Unable to reproduce.

**Comment by Giperionn** [comment]
Please give me some coords of that's herbs.
