### ISSUE TITLE
Entering Realm Loop

### ISSUE THREAD

**Issue by HewDood** [elysium-project/bug-tracker#305]
Been trying to log in to my account all day. Every time I try I get looped back in to having a realm suggested. (Funny because there is only one realm) When I select Nighthaven, a prompt pops up that says it is logging in and then immediately jumps me right back to the select realm list. Any ideas as to what is wrong???

**Comment by assesor123** [comment]
Same, it said Nighthaven went offline but now it is back up but i still can't log into it it comes up with the loop you are refferring, reckon it is just maintenance or something?

**Comment by Egregious** [comment]
Maintenance was occurring during this time. The issue should be resolved.

**Comment by Terranzin** [comment]
Closing issue since it had with a maintenance.
