### ISSUE TITLE
Thorium Brotherhood Turn in quests

### ISSUE THREAD

**Issue by Snowie493** [elysium-project/bug-tracker#307]
The quests from Lokhtos Darkbargainer are not possible to pick up and turn in..
These were added from 1.2 and redesigned in 1.3 to give more rep for less amount of item turn in.
Somehow we cannot see any quests on him in patch 1.4 but the rep items are in the game since we can see them from links...

1 of the 4 quests from npc Lokhtos Darkbargainer:
Name: Favor Amongst the Brotherhood, Fiery Core
Quest id: 6643

Wiki source: 
http://wowwiki.wikia.com/wiki/Quest:Favor_Amongst_the_Brotherhood,_Fiery_Core

**Comment by Terranzin** [comment]
Thanks for reporting so the quest doesn´t seem to be repeatable as of now. This needs to be fixed!

**Comment by twink** [comment]
From what I can see, you must have reputation with Thourim Brotherhood (at least 1 point). If you don't have reputation, you can't see these quests.

**Comment by Snowie493** [comment]
That is false Twink. i have 1 rep with them and i cannot see the quest.

**Comment by fwieth** [comment]
@twink @Terranzin 
I must agree with @Snowie493 , there seem to be a bug that needs a fix. The quest is not optainable. Marking this bug "Invalid" seems to not solve any problem what so ever.
The GM's in-game refer to this bug-tracker to get a fix.

Please do look in to this. Thanks.

**Comment by twink** [comment]
Ok, I thought it's not a bug. Now it's fixed.
