### ISSUE TITLE
Dishonorable kills

### ISSUE THREAD

**Issue by Snowie493** [elysium-project/bug-tracker#308]
Dishonorable kills should not be in the game yet, remove it!
This was added in patch 1.5 along the battlegrounds, needs to be removed asap!
Aswell as some of us gained DHK's from your GM pvp event which we had no clue we would be punished with for just entering.. Aswell as no idea they were in the game as they are not supposed to be?!

" Patch 1.5.0 (2005-06-07):
    Dishonorable kills - gained by killing a trivial Civilian NPC - now has a negative impact on a player's honor. Enough dishonorable kills will reduce a player's rank all the way to zero. "

Wiki source:
http://wowwiki.wikia.com/wiki/Honor_system_(pre-2.0)

**Comment by Terranzin** [comment]
Thank you for that source. We´ll need to look into this and change accordingly
