### ISSUE TITLE
Priest Talent - Spirit Tap #3263

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#31]
From old bug tracker:

Catlynjenner
> Issue is when 5/5 of Spirit Tap is selected it gives 100% chance to proc Spirit Tap. While in a group however, and killing mobs that would and in this case do, because i'm still leveling. It doesn't proc the 100% chance of Spirit Tap. Usually seems to be an issue with mobs that are elites that I group for and non- elites seem to proc Spirit Tap in a group.TL:DR - Spirit Tap isn't proc'ing 5/5 when in a group killing elites
> --

**Comment by twink** [comment]
Spirit Tap procs only if you had killing blow. So if your party member kill an npc, your spirit tap shouldn't proc. Declined.
