### ISSUE TITLE
Quest: Bitter Rivals 

### ISSUE THREAD

**Issue by Octanius** [elysium-project/bug-tracker#310]
Reporting a bug on the quest "Bitter Rivals". Discovered on Nighthaven - patch 1.4.

On the quest Bitter Rivals I am supposed to replace a barrel of Thunder Ale by first buying a Thunder Ale from the innkeeper in Kharanos and then going downstairs to give it to Jarven Thunderbrew who is guarding the ale. Jarven should then walk upstairs and an unguarded thunder ale barrel should spawn for you to loot. 
This is where my issue occured. I missed looting the barrel as Jarven went upstairs and when he came back down the barrel wasn't there anymore. I thought I could bribe him once again with a Thunder Ale from the innkeeper but I couldn't interact with him at all. 
I tried reloading, relogging, deleting my WDB folder and abandoning the quest and picking it up again to start over without success.

This all happend to me when I failed to loot the barrel that spawns when you give Jarven Thunderbrew the Thunder Ale to lure him upstairs.

**Comment by Navashed** [comment]
Confirmed. I was about to open an issue about this exact quest.

Quest 403 - Guarded Thunderbrew Barrel (and its follow-up, Quest 308 - Distracting Jarven) should still be available to the player until they have picked up Quest 311 - Return to Marleth. If the player abandons Return to Marleth, 403 (and thus 308) should become available again.

Alternatively, 403 (and thus 308) could remain available to the player at all times between picking up Quest 310 - Bitter Rivals and handing in Quest 311 - Return to Marleth. Either functionality should prevent the quest chain from breaking.

**Comment by twink** [comment]
Fixed. Now Quest 403 - Guarded Thunderbrew Barrel will be repeatable.
