### ISSUE TITLE
NPC: Innkeeper Belm

### ISSUE THREAD

**Issue by Egregious** [elysium-project/bug-tracker#311]
Innkeeper Belm has 4 items that should not be on his inventory sales table. 

1) Hearthstone. Should never be viewable.
2) Love Token. Should only be viewable during Valentines event.
3) Perfume Bottle. Should only be viewable during Valentines event.
4) Cologne Bottle. Should only be viewable during Valentines event.

![](https://i.gyazo.com/6f041a63eb7880fe5e3ac422f1c5f978.jpg)

**Comment by twink** [comment]
Fixed.
