### ISSUE TITLE
Heathy Dragon Scale

### ISSUE THREAD

**Issue by Articsnow** [elysium-project/bug-tracker#314]
Quest Item from Scholomance

Healthy Dragon Scale,

whenever I click to start the quest, it gives me an error.  Even when I have lots of bag space.

Healthy Dragon Scale failed: Inventory failed.

**Comment by Kukarek** [comment]
Confirm this bug. I have more then 6 dragon scales and still can't accept the quest. It says: Inventory is full. I haven't this quest accepted in my quest log for sure. Also i deleted WDB folder twice, it did not help.

![3](https://user-images.githubusercontent.com/35478313/34971887-d864dee4-fa8e-11e7-9d93-82786b6cc8b2.jpg)
![2](https://user-images.githubusercontent.com/35478313/34971885-d5ba1664-fa8e-11e7-992d-e7bbb25d4580.jpg)
![1](https://user-images.githubusercontent.com/35478313/34971882-d1eaf134-fa8e-11e7-8904-0d77d04e2c63.jpg)

**Comment by Terranzin** [comment]
I´ve looked into the issue and I can´t reproduce the error you´re encountering. 

I added the Item (Healthy dragon scale) to my inventory and then started the quest and this worked just fine without any errors.
![image](https://user-images.githubusercontent.com/25831382/35009331-84dc2a2c-faff-11e7-9f46-b4d0b6134980.png)

Have you completed the quest "Plagued Hatchlings"? This is a requirement to actually start the quest.

**Comment by Kukarek** [comment]
Solved it by deleteing all others Healthy Dragons Scales from bank/inventory (got at least 6+). This is sad, i was sure i could gather as many as i want, since it's repetable quest.
