### ISSUE TITLE
Quest: Can´t start quest A Grave Situation

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#316]
Use-case:

1: Start quest Meet at the grave (3912)
2: You´re now provided with 	Linken's Tempered Sword
3: Use the elixir and kill yourself
4: Run north and hand in the quest
5: Attempt to take next quest in Chain (where Linken's Temptered Sword should first get removed from inventory then add it again).
6: Instead of removing it from bags it tries to just add same item again and giving the duplicate error (see picture)

![image](https://user-images.githubusercontent.com/25831382/34909319-47781d74-f89f-11e7-8328-f78143419737.png)

**Comment by Terranzin** [comment]
QA Confirmed

**Comment by twink** [comment]
Fixed.
