### ISSUE TITLE
Quest: The Balance of Light and Shadow

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#319]
Quest 7622 - The Balance of Light and Shadow has a combat bug. After the event is successfully completed, NPC 14494 - Eris Havenfire gets stuck in combat.

Due to the recent development update (https://forum.elysium-project.org/topic/62783-development-update-08012018/), NPCs stuck in combat will not speak to players.
> Creatures can no longer interact with the player while in combat. 

This prevents the player from handing in the quest once it's complete.

I think the cause is that the Scourge Archers (NPC 14489) despawn after the event and Eris Havenfire is still in combat with them. She heals the player, who heals the peasants, who are damaged by the archers, so she is in combat with the archers and combat does not clear when they despawn.

**Comment by twink** [comment]
Fixed.
