### ISSUE TITLE
Quest bugged

### ISSUE THREAD

**Issue by Candlejackk** [elysium-project/bug-tracker#320]
The Completed Orb of Dar'Orahil won't complete. I've done all the prequests and even deleted my WDB folder.

**Comment by Terranzin** [comment]
You´ve done following quest, http://db.vanillagaming.org/?quest=4961 ?

**Comment by Candlejackk** [comment]
I figured it out. It won't take the orb you get cleaned out of your bag when you turn it in, so the quest gets failed due to duplicate items, because it trys to give you that orb back.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Terranzin** [comment]
Similar issue to following: https://github.com/elysium-project/bug-tracker/issues/316

**Comment by twink** [comment]
Fixed.

**Comment by Lockylukee** [comment]
I'm stuck on the same quest as i have done all the steps in the quest chain, but not able to get the option to choose the item after completion. I'm lvl 35 aswell, so im eligible.
