### ISSUE TITLE
Heavy Junkboxes wrong loottable

### ISSUE THREAD

**Issue by Roarboar** [elysium-project/bug-tracker#323]
on [Nighthaven 1.4] the loottable for heavy junkboxes is currently wrong.  It is lacking many items, most of the time you will get a shabby knot or Coarse snuff, whereas other items are completely absent.

Here is a reference: http://web.archive.org/web/20070509165318/http://www.thottbot.com:80/i16885

Also it is known that the heavy junkboxes can contain certain epics. For exampe http://wowwiki.wikia.com/wiki/Teebu%27s_Blazing_Longsword

According to wowhead, this sword has dropped from junkboxes 6 times out of 54190 attempts, making it a 0,011% drop. It is still obtainable, but it is an incredibly rare drop.

**Comment by fulzamoth** [comment]
Patch 1.12 brings the updated junk box loot tables. The loot table you linked is from after TBC was out.

- _All manner of rogue reagents can be found in locked junkboxes (obtained from pickpocketing)._
