### ISSUE TITLE
Can't learn Devilsaur set

### ISSUE THREAD

**Issue by fankumo** [elysium-project/bug-tracker#324]
![wowscrnshot_011518_185410](https://user-images.githubusercontent.com/35455562/34944188-db954ab0-fa28-11e7-96f5-8e75da714b3f.jpg)

**Comment by Terranzin** [comment]
Comes next patch (tuesday or wednesday)

**Comment by fankumo** [comment]
ty

**Comment by fankumo** [comment]
not comes
