### ISSUE TITLE
Item/Weapon: Venomstrike 

### ISSUE THREAD

**Issue by theragentino** [elysium-project/bug-tracker#325]
Hello, im writting you to report a most likely bugged item in the game, the bow Venomstrike ( right here: http://www.wowhead.com/item=6469/venomstrike) As the effect states, it has a proc chance of hitting the target with nature damage, but it simply doesn't proc in Nighthaven, im not saying it happens even less than it should, im stating "It just doesn't happen"

I had this bow previously in elysium, and it did indeed work prefectly with the animation of the proc striking and even sometimes dealing critical hits with said nature damage. So I believe it to be a bug of the new server. 

Im Theargentino, and my character is Hidani - troll hunter

**Comment by Navashed** [comment]
Confirmed.

Tried many different weapons which should have elemental damage bonuses, both ranged and melee, and none were working.

Tested:
1482 - Shadowfang
1959 - Cold Iron Pick
6469 - Venomstrike
7730 - Cobalt Crusher
9412 - Galgann's Fireblaster
9718 - Reforged Blade of Heroes
10567 - Quillshooter
13146 - Shell Launcher Shotgun
13982 - Warblade of Caer Darrow
13952 - Iceblade Hacker
16004 - Dark Iron Rifle
17753 - Verdant Keeper's Aim

**Comment by twink** [comment]
http://www.wowhead.com/item=6469 doesn't have proc spell right now, maybe in other patch it will have.
1482 - Shadowfang , 7730 - Cobalt Crusher - work fine. 
Others don't have proc spell too.
