### ISSUE TITLE
Unable to Tame pets

### ISSUE THREAD

**Issue by HewDood** [elysium-project/bug-tracker#326]
Have a level 10 Hunter and I am unable to tame a pet. Whenever I use the spell, it takes the 20 seconds and then tells me I have an active summon, which I do not. Unable to dismiss any pet because I do not have one in the first place. Think there must be some kind of bug with this. Help! Being a Hunter without a pet is getting difficult.

**Comment by HewDood** [comment]
![image](https://user-images.githubusercontent.com/35316142/35121186-93b630fa-fc68-11e7-81b8-e7acd74068f5.png)

**Comment by Terranzin** [comment]
This is a issue that usually gets solved when GMs reset players account ID. I´ll confirm this to see if our devs can do anything about it but for now try get assistance from our GM team ingame.

**Comment by twink** [comment]
Can't reproduce. Need a way to reproduce.

Next time in such cases you can ask GM team for help, but if you want us to fix this bug, we need to be able to reproduce it.
