### ISSUE TITLE
Hinterlands phasing into WPL instant death due to fall dmg

### ISSUE THREAD

**Issue by Eevee123** [elysium-project/bug-tracker#327]
https://streamable.com/tnr1f'
what do i need to say more?

**Comment by Navashed** [comment]
I have been unable to reproduce this issue on PTR.

However, I can confirm it also happened to me when walking down this slope back on Elysium.

**Comment by twink** [comment]
We've updated mmap system, seems fixed.

**Comment by shenna-elysium** [comment]
I don't get why it's showing such coords as 65:89 on the minimap, it isn't the correct ones for this area.

**Comment by shenna-elysium** [comment]
Coords are changing from the correct range 21:23 to the 65:89 at the exactly the same moment when he dies.
