### ISSUE TITLE
Un'Goro Crator Pylons 

### ISSUE THREAD

**Issue by mediumjbc** [elysium-project/bug-tracker#328]
Unable to retrieve Crystal Restore from the North Pylon in On'Goro Crater with 10 green Crystals and 10 yellow Crystals as stated on db.vanillagaming.org for the quest Fragments of the Past after doing all the quest received from the NPC under the name of "J.D. Collie".

**Comment by Terranzin** [comment]
I´ve looked into your issue and it seems like you can´t continue the quest even though you have gathered enough materials.

![image](https://user-images.githubusercontent.com/25831382/35528838-6e440ba6-052f-11e8-83a0-56ba243af3d6.png)

QuestID:4381
Gems:  11188 and 11185
Objectid: 164955

**Comment by mediumjbc** [comment]
Interesting that you where able to even get that dialog box open, I went there with the same crystals and hit right click on the golden troogle as you would with all of those types of quest in the game and nothing even poped up but if that's coming up for you then yes that would seem to be another problem , of course mine could be OS(Windows Vista) related to.

**Comment by sidsukana** [comment]
Quest works. If you have problem, please upload screenshot from inventory with 10/10 pylons. Quest log may display incorrect info from  cache.
