### ISSUE TITLE
[Gnomeragan] Dark iron Agent

### ISSUE THREAD

**Issue by shadowoffice** [elysium-project/bug-tracker#329]
## Gnomeragan

- NPC ID : i dont know (dont found on DB vanillia)
- NPC Name : Dark iron guard
- Cast : Mine whit 10 seconde for destroy or its armed

Mine of iron guard on gnomeragan can move its bug and not normal ....

i have play today on dungeon and see thats and my groupe its death by this bugs ....

Cast iron Mine and Follow player or small bug can shoot mine good time and kill all players ...

in this dungeon normaly 2 possibility juste move see mine or destroy mine.

**Comment by Terranzin** [comment]
I´ve looked into your issue and manage to reproduce the error. They don´t always move, but usually they move once, when getting into a position they stop there until they get destroyed. The easiest way to see them all moving is gather a bunch of Dark iron agents to set off a couple of mines, run away from it or put GM On again and they´ll move in position (the mines). 

Picture below shows a blue square where he initially got spawned, and then where he stopped.

![image](https://user-images.githubusercontent.com/25831382/35528421-0dea1c2e-052e-11e8-9367-bc2e7ad57e59.png)

**Comment by Giperionn** [comment]
Hello @shadowoffice . Thanks for reporting.
I cut off legs from Mine.
Fix will be available on next server update.
