### ISSUE TITLE
Copper Vein and etc. 

### ISSUE THREAD

**Issue by olegqb** [elysium-project/bug-tracker#330]
Hey. I pumped up to 16 lvl (orc) and saw ONLY ONE Copper Vein. ONLY ONE. After that, I went to the undead territory and what do you think? I did not find NOT ONE VEIN. This is a big problem for the profiling of the profession. ITS A BIG PROBLEM.

**Comment by Terranzin** [comment]
The node spawns are correct as it is. What you need to know is that vanilla had a max population of around 2500 players/server. We´re up at around 5k at times, this means that there´s more races for nodes or other material professions.
