### ISSUE TITLE
Can't start Cuergo's Gold

### ISSUE THREAD

**Issue by Fifix** [elysium-project/bug-tracker#332]
Server/Patch : Nighthaven PvP (1.4)

Steps : 
- In Tanaris, farm Lost Rigger Cove till you get Pirate Footlockers, containing map fragments.
- Combine the lower, middle and upper fragments. This gives Cuergo's Treasure Map.
- Click on the item, a quest appears.
- Accept.

Expected behaviour : The quest starts, let's go treasure hunting !

Current behaviour : A system message appears : "Cuergo's Gold failed: Duplicate item found."

![image](https://user-images.githubusercontent.com/12305794/35004981-3d4eb6dc-faf2-11e7-9108-43f110e2ba9c.png)

**Comment by Terranzin** [comment]
The issue appears because the item is recieved once again and unable to remove itself from the bag (should happen while accepting the new quest). Thanks for reporting this issue!

**Comment by twink** [comment]
Fixed in general for all such problems.
