### ISSUE TITLE
Crossroads Conscription Dialogue Bug

### ISSUE THREAD

**Issue by 1102085a** [elysium-project/bug-tracker#333]
- I handed in this quest to Sergra Darkthorn at the Crossroads in The Barrens
 ( http://db.vanillagaming.org/?quest=842 ).
- Near the end of her-hand in dialogue, she claimed she was glad another female like me is out there fighting for the horde (I didn't think to screencap this, my bad).
- I am a male Troll, so clearly she is mistaken.

**Comment by Navashed** [comment]
Confirmed.

![5f445a248957115fc9531400930de944](https://user-images.githubusercontent.com/2709545/35021833-c2594b22-fb00-11e7-8bef-1b36964e4b35.jpg)

Props for actually reading quest completion text.

**Comment by twink** [comment]
Don't see proofs.
