### ISSUE TITLE
Can't start quest - "Arena Master failed: Inventory is full."

### ISSUE THREAD

**Issue by marshzor** [elysium-project/bug-tracker#335]
**Server/Patch:**

Nighthaven PvP (1.4)

**Steps:**

 - loot gurubashi arena chest 12 times, looting Arena Master each time
 - attempt to start quest given by Arena Master trinket
 - EXPECTED: Arena Master quest is accepted
 - ACTUAL: Arena Master failed: inventory is full. (My inventory has over 20 open spaces)

**More info:**

I have looted the Gurubashi Arena chest 12 times, and I have 12x Arena Master in my bags

When I right click on Arena Master, the quest dialog pops up and I click Accept

Then, instead of starting the quest, I get an error message in yellow text in my General chat window:
`Arena Master failed: Inventory is full`

I talked with a GM about the issue, and they couldn't get it to work from their side either, so they asked me to open an Issue here.

Is there anything that can be done? I really want to start the quest so I can turn my 12 Arena Master trinkets into Arena Grand Master.

Any information would be greatly appreciated, thanks.

**Comment by tonygaetani** [comment]
Item that starts the quest: http://db.vanillagaming.org/?item=18706 (I have 12 of these in my bags)
The first quest: http://db.vanillagaming.org/?quest=7810 (I get an error while trying to start this quest)
The quest I really really am hoping to do: http://db.vanillagaming.org/?quest=7838

**Comment by marshzor** [comment]
Item that starts the quest: http://db.vanillagaming.org/?item=18706 (I have 12 of these in my bags)
The first quest: http://db.vanillagaming.org/?quest=7810 (I get an error while trying to start this quest)
The quest I really really am hoping to do: http://db.vanillagaming.org/?quest=7838

**Comment by Terranzin** [comment]
Hello this is similar issue we´ve had for a couple of other quests. Thanks for reporting it!

**Comment by marshzor** [comment]
update, there is a workaround and a fix! more info here https://forum.elysium-project.org/topic/62952-how-to-complete-the-arena-grand-master-quest/
