### ISSUE TITLE
Tribute Run Cho'Rush bugged aggro after king died

### ISSUE THREAD

**Issue by komugifb** [elysium-project/bug-tracker#336]
https://cdn.discordapp.com/attachments/377099887973761024/403333853151756288/unknown.png

He kept aggro on me while friendly, just stood there. 

This results in no chest until everyone who's in combat suicides.

**Comment by Terranzin** [comment]
Can you please say how you manage to produce the error? Looks more like you intentionally tried to bug him since the position you´re in isn´t even remotely close to where you usually aggro him.

**Comment by Terranzin** [comment]
No reply for 19 days closing the issue for now.
