### ISSUE TITLE
Incorrect behavior of NPCs and violation of pvc mechanics

### ISSUE THREAD

**Issue by Ehkiller** [elysium-project/bug-tracker#337]
Dear developers.
I would like to clarify why at the moment in the game NPCs that serve as security guards of the settlement do not do this? In particular, today two players of level 60 (Nabble and Wangwang) kill all the characters who were in the camp of the Mahahi (Feralas) camp. NPCs that served as guards and other nps at the time, did nothing.
I also want to clarify why the abolition of the system of dishonest murders. Because now a player of a higher level, killing a low-level character, does not receive a penalty for honor points, and this murder is not considered dishonest. The fact that the server is pvp does not override the rules of more or less honest murders.

**Comment by Terranzin** [comment]
Regarding the guards, we´ll look into this. But about "dishonest murders" we´re not going to do much about that from a github bug report, instead add it as a suggestion on our forum.

**Comment by shenna-elysium** [comment]
Can't reproduce.
