### ISSUE TITLE
Hunter PET leveling BUGGED!

### ISSUE THREAD

**Issue by vretz** [elysium-project/bug-tracker#339]
So today I was leveling my pet in Dustwallow Marsch killing Searing Whelp's and I noticed (after a long time and it has happened before) that while I was in a party my pet didn't recieve any EXP. The party member was not close to me. It has also happened when I've done dungeons with the pet and in a party group.
So it seems that while in a party group the pet can't recieve any EXP, it wasn't untill I left the group that my pet started to get EXP again.

**Comment by Terranzin** [comment]
There has been similar issues reported before, I can´t manage to reproduce it. Though I´ll confirm this and maybe the devs have a idea how the issue keeps appearing for a few players.

**Comment by twink** [comment]
Can't reproduce, can't fix without way to reproduce.
