### ISSUE TITLE
Quest( Devourer of Souls ) Horde

### ISSUE THREAD

**Issue by Drackers** [elysium-project/bug-tracker#341]
Hello, i abandon the mission Devourer of Souls, is quest for a succubo,and now I can't take her back becose the npc dong give me the quest. I talk with assistant in game and i do all. Sorry for my bad english and thx for ur time.

My pj is Drackers(Horde)

**Comment by Terranzin** [comment]
Please make a ingame ticket and they´ll help you get the quest started. Thanks!
