### ISSUE TITLE
Quest: Race-specific Intro Quests

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#342]
The quests which introduce the player to flight paths are supposed to be race specific:

**Alliance**
_Human_: A Swift Message (Quest 6181)
_Dwarf/Gnome_: Honor Students (Quest 6387)
_Night Elf_: Nessa Shadowsong (Quest 6344)

**Horde**
_Undead_: Supplying the Sepulcher (6321)
_Orc/Troll_: Meats to Orgrimmar (Quest 6365)
_Tauren_: A Bundle of Hides (Quest 6361)

I was able to pick up Honor Students as a human. I am not sure which others are lacking this requirement so I have listed them all. I think some or all of the Horde quests might already be correct.

Proof in comments:
https://web.archive.org/web/20070515024642/http://www.thottbot.com:80/q6181
https://web.archive.org/web/20070701063528/http://www.thottbot.com:80/q6387
https://web.archive.org/web/20070318042126/http://thottbot.com:80/q6344

**Comment by twink** [comment]
Fixed.
