### ISSUE TITLE
Purchase a Guild Charter

### ISSUE THREAD

**Issue by Articsnow** [elysium-project/bug-tracker#343]
I'm trying to purchase a guild charter

the guild name is Tempest

and it keep telling me

"That name contains invalid characters, Enter new name"

**Comment by Terranzin** [comment]
It worked fine registering a guild named "Tempest". I´ll see if the devs can see the reason why this isnt possible on Nighthaven.

![image](https://user-images.githubusercontent.com/25831382/35194221-42138956-feb0-11e7-867d-56c2cb9f75b4.png)

**Comment by Terranzin** [comment]
So apparently the word "Temp" is banned on Nighthaven. I´ll confirm this and see if the word can be revoked.

**Comment by shenna-elysium** [comment]
There're no blacklisted entries such as "Temp*" neither on anti-spam neither somewhere else. I had no problems with creating a guild on Nighthaven; so I suggest you to contact me on Discord (Shenna
#8368) or any GM in-game to help you to claim the requested guild name.
