### ISSUE TITLE
Stronghold not working

### ISSUE THREAD

**Issue by Maggrokh** [elysium-project/bug-tracker#344]
I just got disarmed while having stronghold gauntlet on .

**Comment by Maggrokh** [comment]
Ok so apparently only 1h get disarmed when you wear them 2h seems fine

**Comment by Terranzin** [comment]
Can´t be reproduced on PTR sadly. Seems to be working just fine both with 1h weapon and 2h weapon.

![image](https://user-images.githubusercontent.com/25831382/35187765-6d39729e-fe29-11e7-87ed-c12071ffae3d.png)
