### ISSUE TITLE
Coded Mail never making it back 

### ISSUE THREAD

**Issue by Wallywee** [elysium-project/bug-tracker#345]
Hi, 

I was sent here by a GM to explain what happened to my C.O.D to another player.
I sent a recipe (flask of Wisdom) by C.O.D for 600g, the remaining gold on my char was about 200 so i know for a fact i coded it, when in wrote in 600g and sent it (or else the game would complain).

They never bought it (HTBANK, bank of the guild hightide, and they confirmed this) and sent it back, but i never received the recipe.
I know that my mailbox was full at the moment ( i came to realize this later when i panic took over).
Plz help me cuz i have alot invested here, it was not a missmail i am 100% sure i coded.
I tried removing WDB folders and remove addons.
I even tried using the same method to one of my own charrs, but without the same result.

Br Wally

**Comment by Terranzin** [comment]
We´ll look into the matter if there´s a bug with COD, but we cant assist you with the lost gold on QA, this is what GM might be able to assist you with.

**Comment by Snowie493** [comment]
I was told by gm ingame cod mail have 2day time to take out, else they get returned on a 30 day delay..

**Comment by Terranzin** [comment]
Hello,

Not sure if this is the same error but when I´m trying to send mail as COD I get "Internal server error". I´ll have the devs look into it.

![image](https://user-images.githubusercontent.com/25831382/35527031-ac6316da-0529-11e8-92b9-491fe48b8bd6.png)

![image](https://user-images.githubusercontent.com/25831382/35527126-020fd9c4-052a-11e8-9742-0f976799beab.png)

**Comment by Terranzin** [comment]
On PTR this error can´t be reproduced. 
![image](https://user-images.githubusercontent.com/25831382/35527526-4644d4e0-052b-11e8-8e50-ebc5967edd60.png)

Do you have any use-case on how it all happened? Did the server crash just after the transfer happened?
