### ISSUE TITLE
I can't see Q Pirate Hats Ahoy! & Southsea Shakedown. 

### ISSUE THREAD

**Issue by Axlimage** [elysium-project/bug-tracker#348]
Hi , i went to Tanaris today to Steamwheedle Port .. and i should take there Qs Pirate Hats Ahoy! and Southea Shakedown but i cannot even see ! above the npc should give it to me. please help

**Comment by Navashed** [comment]
These quests were added in patch 1.8.

http://wowwiki.wikia.com/wiki/Patch_1.8.0
"A few new quests have been added in Tanaris. Head over to Steamwheedle Port to see if you can help out."
