### ISSUE TITLE
Did not recive item

### ISSUE THREAD

**Issue by Taelon90** [elysium-project/bug-tracker#349]
Good evening, wrote a ticket that directed me here!

Was in stratholme whit some friends when https://db.vanillagaming.org/?item=18722 dropped and i won roll on them, only plate user in group yay! but i think i was clumsy and i did not check if inventory was full or not so i did not bring them along whit me after boss atleast, is there a possibillity to backtrack and resend? 
Nighthaven Heimdal 60 Tauren war

Best regards 
Peter.S

**Comment by Terranzin** [comment]
QA team does not restore items ingame. We test for bugs only
