### ISSUE TITLE
Ghost Saber pet missing Claw, Rank 3

### ISSUE THREAD

**Issue by RainElysium** [elysium-project/bug-tracker#35]
http://db.vanillagaming.org/?npc=3619 (Ghost Saber) 
is missing spell
http://db.vanillagaming.org/?spell=16829 (Claw, Rank 3)

Player unable to see spell in spellbook or bars. Removed all addons + WDB Clear. Respawned a new Ghost Saber for player to tame, however spell is still missing from second attempt.

**Comment by twink** [comment]
Fixed, you will need to tame pet one more time after fixes will be applied.
