### ISSUE TITLE
RE : Stronghold not working with 1h

### ISSUE THREAD

**Issue by Maggrokh** [elysium-project/bug-tracker#350]
https://gyazo.com/38b2d20d2de511a1fe93ddada638a21a , really disappointed you close my previous one without really trying .

**Comment by Terranzin** [comment]
We used a 1h weapon and the disarm says "Immune" see picture

![image](https://user-images.githubusercontent.com/25831382/35194195-c5fbfc7c-feaf-11e7-86a5-328d5fe1838b.png)

**Comment by Maggrokh** [comment]
come to me now and disarm me if you re a gm

**Comment by Terranzin** [comment]
Duplicate of: https://github.com/elysium-project/bug-tracker/issues/344 & https://github.com/elysium-project/bug-tracker/issues/191

**Comment by Terranzin** [comment]
There´s probably a difference between PTR and Nighthaven, devs will need to look into this.

**Comment by Maggrokh** [comment]
New issue :( got disarmed when using weapon chain https://gyazo.com/68da83b969b42342d9c13edc13b206e7
