### ISSUE TITLE
Can't join Guild

### ISSUE THREAD

**Issue by schexo** [elysium-project/bug-tracker#351]
Hi, 
after a guild Invite I had get an disconnect sinc this I cant join any Guild and the person who try to invite me in a Guild get the massage "the player is alreadey in a Guild" but I am not.

serername : nighthaven /Hord
char name : Schexo

thanks

**Comment by twink** [comment]
Try one more time.

**Comment by Terranzin** [comment]
You´ll need ingame support so they can remove you in the DB. But I think this already been made by twink. Ask for a new invite now.
