### ISSUE TITLE
Problems with chat

### ISSUE THREAD

**Issue by thedanger89** [elysium-project/bug-tracker#352]
Hi there, i started playing this server 2 days ago.

I have a problem with ingame chat. People only read me when they are in my party. When i whisper or use other chats like /s /1 /2 or /y, no one reads me. I dont know why or what happen. Because of it, i cant trade stuff, ask for groups, ask for missions... nothing. They just read me only if they are in my group.

Can anyone help me? Its a big problem for me. Im a role player and i need to interact with other people to enjoy this game.

(Apologies about my english level, im spanish)

Thank you.

**Comment by thedanger89** [comment]
The server name is Nighthaven PVP
The character name is Petaisimo

**Comment by Terranzin** [comment]
Could you contact ingame support, see if you might have been muted earlier. There has been some issues with people getting muted couple days back.
