### ISSUE TITLE
Armorsmith recipes

### ISSUE THREAD

**Issue by Wolve1** [elysium-project/bug-tracker#354]
I am a blacksmith at lvl 283 and I just did all the quests for becoming an armorsmith. But instead of now being able to craft all the blue vanilla BoP-items, I just got two recipes for "Truesilver Gauntlets" and "Truesilver Breastplate", and no further recipes are available at the vendors.

**Comment by Navashed** [comment]
Please provide more information. What exactly is supposed to happen?

**Comment by Terranzin** [comment]
No reply for 17 days, closing issue for now.
