### ISSUE TITLE
Quest: The God Hakkar

### ISSUE THREAD

**Issue by MiticoPalla** [elysium-project/bug-tracker#355]
Yesterday evening the event wasn't working.
We got the first blood of hakkar and used it on the flame, then all of a sudden the floor turned off and the everything went back to the start. 
My wild guess is that if someone takes aggro while on the border ledge the event bugs. 
Can you look into this? 
Thanks

**Comment by MiticoPalla** [comment]
After the reset, we tried to restart the event but only one add spawned and we where forced to recall cause the room was closed

**Comment by Terranzin** [comment]
I´ve tried to reproduce the error but can´t seem to do so on PTR. We havent had many reports except yours regarding this issue, therefor I´m guessing this was just one time issue.
