### ISSUE TITLE
Problem with Elixir of Wisdom

### ISSUE THREAD

**Issue by Darkguys1** [elysium-project/bug-tracker#357]
Hello everyone who read this!

I am a Troll Mage lvl 24 and got Arcane intellect +7. Whenever i use it, my int stat and mana pool increase correctly. The problem is that i chose to be Herbalism/Alchemy and i can create Elixir of Wisdom now.
This potion gives +6 int for 1 hour. So when i use it, nothing happens. I see the icon on the top of my screen but my int stat and mana points doesnt change. I tried to disconnected and connect while its active. Nothing. It doesnt work.

Someone told me that it might be a stack problem thing (and im probably not the first player to see it).

**Comment by Navashed** [comment]
The consensus is that basic stat buffs from elixirs do not stack with class buffs.

If you find evidence that this stacking behavior did occur in Vanilla please post it here.
