### ISSUE TITLE
Turning in Guild Charter makes it vanish.

### ISSUE THREAD

**Issue by Sircharlez** [elysium-project/bug-tracker#359]
Waited all day for the 10 people I wanted to sign the charter to get on to sign it turned it in while the charter was in the main bag (no they didn't sign  any other charters or join any guilds)  and poof gone. Thinking this was a one time thing we tried again, with my friend doing it instead (new guild name) and poof gone again. 5 Times Later, and with different people. And still Nothing, Lost about 3 gold in the process and I'm a tad frustrated because people had to leave their current guilds to do this, all that said this has to be a bug on your end if you could fix it that would be great thanks!

**Comment by Terranzin** [comment]
We´ll need some more evidence, a video of the issue would be perfect. I can´t manage to reproduce the error. What guild name are you trying to use? Some words are banned.

**Comment by Terranzin** [comment]
No replies, closing this issue for now.
