### ISSUE TITLE
Mage Class Quest Reward - Celestial Stave

### ISSUE THREAD

**Issue by Cybrok** [elysium-project/bug-tracker#36]
Never done this quest before, but other database sites show Celestial Stave to be a rare quality item with +8 Intellect and +22 dmg to spells

In game on this server however, it shows +2 Intellect and +7 dmg to arcane, fire and frost spells.

Not sure which its supposed to be, but the first one is definitely better :P 

https://gyazo.com/46773bc8467b041d75111f55ed9e9283
(left is server, right is database)

**Comment by twink** [comment]
Thanks for your report, but Nighthaven right now has 1.2 patch, this item was changed in patch 1.8. When server will go to 1.8 it will have +8 Intellect and +22 spd.
