### ISSUE TITLE
The Grand Betrayal

### ISSUE THREAD

**Issue by Letsgochampwow** [elysium-project/bug-tracker#360]
I did the quest (The Grand Betralyal) with my low-be friends. 
When we killed the boss we did not get any loot, nor did our quest update.
The boss afterwards just despawned and we were left with nothing.[https://i.imgur.com/46BJQHj.jpg](url)

**Comment by Terranzin** [comment]
This was probably some temporary error. Can´t manage to reproduce the error you´ve reported, manage to complete both quest and get loot from his body.

![image](https://user-images.githubusercontent.com/25831382/35528166-4d765e9e-052d-11e8-9f16-e594497c8d64.png)
