### ISSUE TITLE
Power in Uldaman

### ISSUE THREAD

**Issue by Laaashi** [elysium-project/bug-tracker#362]
The Obsidian Sentinel does not drop the Obsidian Power source needed for Power in Uldaman.

**Comment by Terranzin** [comment]
Hello,

I´ve tried to reproduce the error but unable to do so. When fighting Obsidian sentinel and he finally fell after a hard fight he dropped the item.

![image](https://user-images.githubusercontent.com/25831382/35529646-eba6d2ca-0531-11e8-8737-c86a095fe6db.png)
