### ISSUE TITLE
Dead on fly

### ISSUE THREAD

**Issue by jeromecaudoux** [elysium-project/bug-tracker#364]
Hi,

Someone killed me at the same time i clicked on my destination. The result is on the screenshot.
I was able to release the spirit in ogrimmar and to find my corpse.

![deadonfly](https://user-images.githubusercontent.com/5968007/35306641-1f89378c-009f-11e8-8039-ba25df4d9ccf.png)

**Comment by shenna-elysium** [comment]
This is amazing.

**Comment by shenna-elysium** [comment]
![05onfire1_xp-facebookjumbo](https://user-images.githubusercontent.com/24865383/35366354-576ade32-0179-11e8-9c42-8afd22d87353.jpg)

**Comment by Terranzin** [comment]
I´m guessing the picture is proof enough! :-)

**Comment by twink** [comment]
Fixed.
