### ISSUE TITLE
Quest: Crime and Punishment

### ISSUE THREAD

**Issue by Brunelleschino** [elysium-project/bug-tracker#365]
Dextren Ward in the Stockades doesn't drop his hand for the quest above (noone in my group could loot him).

**Comment by Terranzin** [comment]
Probably a temporary hickup. Can´t be reproduced on our PTR-server. Got the quest and killed him, quest item appeared.

![image](https://user-images.githubusercontent.com/25831382/35530220-bc4dbab4-0533-11e8-88b9-dc7e21cf4de4.png)
