### ISSUE TITLE
Pet doesn't gain experience when in party

### ISSUE THREAD

**Issue by JinzJinz** [elysium-project/bug-tracker#366]
Leveling a low level pet to 60 is a pain... but its even more so when you'r pet doesn't gain xp when you're in a party. Please fix

thanks 
jinz

**Comment by bigboobanalfest** [comment]
New pet i just tamed is gaining neither loyalty or experience!

BUMP!!

**Comment by YaboyJimmyrustle** [comment]
Can you provide your level and the level of the pet you are trying to gain experience and loyalty with, please.
