### ISSUE TITLE
Shade of Hakkar bug'd 

### ISSUE THREAD

**Issue by Dinosauras** [elysium-project/bug-tracker#367]
I wrote a ticket in regards to Shade of Hakkar fight (ST) bugging out and the GM told me to post it here so I am. During the first fight the server crashed while we were fighting pre-boss adds, then we managed to wipe on our second attempt. On our third attempt the fight simply refused to start, as using the egg did absolutely nothing. Something similar happened the day before where we completed the adds part but boss wouldn't spawn until a GM spawned it for us. Not much else to say, 2 out of my 3 fights with him so far have bugged out so we couldn't complete it without GM assistance.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and manage to get similar issue.

Use-case: 
- Accepted quest ID: 3528
- Provided myself the item: 10465
- Started the event (fine)
- Door closed and adds spawned
- Started fighting, kill my first Hakari Bloodkeeper
- Looted Hakkari blood and used it to shut off 1/4 flame
- Noticed a new wave spawned.

After this everything resetted, the mobs despawned, the boss (shade) dissapeared and the doors opened.

![image](https://user-images.githubusercontent.com/25831382/35938005-324e4af6-0c48-11e8-8bb7-f019e832162b.png)

**Comment by sidsukana** [comment]
Can't confirm. You must have min 2 players for fight him. He cast "Cause Insanity" (charm spell) if you will solo, then Hakkar leave from combat because he will not have enemies for a few seconds

**Comment by shenna-elysium** [comment]
Can't reproduce even with 2 game clients, tried 6 times.

**Comment by shenna-elysium** [comment]
Still can't reproduce.
