### ISSUE TITLE
Honorless Target - Mind Control Issue

### ISSUE THREAD

**Issue by Momodiekuh** [elysium-project/bug-tracker#368]
I wanted to report, that the "honorless target"-buff (you get after landing from flightpath or running out of a dungeon) will be removed when the player is mind controlled and attacks a enemy player WHILE being mind controlled.
Dont think this is intended.

Greetings

**Comment by Terranzin** [comment]
We´ll need some more solid proof on how the expected behavior is like blue post from Blizzard or other then just speculations.

**Comment by shenna-elysium** [comment]
No information provided, closed.
