### ISSUE TITLE
Friends list

### ISSUE THREAD

**Issue by Bugreported** [elysium-project/bug-tracker#370]
![screenshot_1](https://user-images.githubusercontent.com/34633169/35471276-2a155c38-0358-11e8-8ed0-ff0446c26679.png)

My online friends dont appear on top of the list, they are mixed up with offline players, its been like this for days.

**Comment by Bugreported** [comment]
its really annoying

**Comment by Terranzin** [comment]
Try clearing your WDB folder, should solve the issue.

**Comment by Terranzin** [comment]
Wasn´t ment to close, please reply if clearing the WDB folder worked out for you.

**Comment by shenna-elysium** [comment]
I can confirm it's the same for all my GM/Players characters currently.

**Comment by Bugreported** [comment]
I have deleted my WDB folder 3 times now, it does not work.

**Comment by Bugreported** [comment]
same problem today
