### ISSUE TITLE
Minor Recombobulator bug 

### ISSUE THREAD

**Issue by rippijuhla** [elysium-project/bug-tracker#373]
This trinket just wont work. It only shows me white tooltip text. Nothing about dispelling polymorph or healing. 

-I have 150engineering
-I have learned that schematic
-YES it is on my trinket spot

![ss 2018-01-27 at 10 41 02](https://user-images.githubusercontent.com/35876717/35475556-409b06fa-03a9-11e8-92d0-e90939745f53.jpg)

**Comment by Terranzin** [comment]
Have you cleared your WDB folder? This was fixed in earlier patches and this is probably just a display error.

**Comment by rippijuhla** [comment]
Ahh! YES It worked! Thanks a lot !
