### ISSUE TITLE
My account got deleted ?

### ISSUE THREAD

**Issue by vankata4211** [elysium-project/bug-tracker#374]
Well to be honest it happened a few months ago (I know i should have acted faster), but one day I was playing wow vanilla and everything was ok.The next day I try to log-in but i can't, it says that there is no such account. I tried to reset my password,but it said that my email is invalid  - but I used that same email to register and in it I still have the email you sent me at the beggining to confirm it . 
![wowv](https://user-images.githubusercontent.com/24272348/35480194-b9711106-0411-11e8-8c52-94bb3854db98.png)
![wowv2](https://user-images.githubusercontent.com/24272348/35480197-bf792566-0411-11e8-8968-f4f8372a6bd3.png)

I don't know if this is enough information for you to work with, but  I hope that you guys can help me.

**Comment by Terranzin** [comment]
You´ll need to contact our support/admins on Discord here: https://discord.gg/w6bfD7E or go to our forum here: https://forum.elysium-project.org/ 

We can´t help you here on github.
