### ISSUE TITLE
Blacksmithing keys bug

### ISSUE THREAD

**Issue by isolud** [elysium-project/bug-tracker#376]
When you create BS Keys, they are not appearing in the keyring anymore, the ressources are consumed though.

**Comment by isolud** [comment]
In fact , the problem seems to be more with the keyring : 

I was under level 40, had 4 keys ( from quests ) in the keyring , created a set of key , did not appear in the keyring.

I destroyed two quests keys , tried creating keys , the keyring remained the same with the two quests keys and two empty slots.

After, I reached level 40, the keys created before appeared on the keyring, so the problem is that the keyring does not expand ( maybe you are not allowed to have more than 4 keys before 40 but in this case destroying keys should still update the keyring. )

**Comment by Terranzin** [comment]
You need to try clear your WDB folder and/or remove addons that might have something with the bags. When switching between levels my keyring does update correctly. Can´t reproduce the error you´re mentioning.

![image](https://user-images.githubusercontent.com/25831382/35936629-1511be7c-0c44-11e8-9f35-6272f3b4702b.png)
