### ISSUE TITLE
Improved Arcane Shot

### ISSUE THREAD

**Issue by Dioxane** [elysium-project/bug-tracker#382]
Putting points into Improved Arcane shot does not decrease the cooldown of the ability as the talent suggests.

**Comment by Terranzin** [comment]
Putting points in the talent tree does not change the display text, but does decrease the cooldown. You need to send proof of the arcane shot not having decreased cooldown.

**Comment by Dioxane** [comment]
The display text does change with my tooltips, however it is still 6 seconds before I can use it again. The same as with Aimed shot. https://www.youtube.com/watch?v=UKS0FPp1iYQ

**Comment by Terranzin** [comment]
Hello,

I´ve looked into your video and did some timing between all your shots. If you do the counting yourself you´ll notice you´re around 5,6 seconds. You have to remember the CD timer does not show 5,6 instead it rounds upwards (6) but you´ll also notice real quick there isn´t one second from that you shoot, until the timer goes to 5.
