### ISSUE TITLE
Opposing faction reputation

### ISSUE THREAD

**Issue by SterlynStevo** [elysium-project/bug-tracker#384]
I discovered opposing faction reputation for AB, which I'm not sure how/why, since I can never gain or lose reputation with them. Screenshot: [https://imgur.com/a/4ASti](url)

**Comment by SterlynStevo** [comment]
![bug](https://user-images.githubusercontent.com/34696762/35718116-940f9456-07a8-11e8-9c69-4e844223c934.png)

**Comment by Terranzin** [comment]
The defilers shouldn´t even be in the game right now. The defilers as a faction came in patch 1.7.0

@Devs: While removing The Defilers, look up if League of Arathor is a thing in current patch.

**Comment by SterlynStevo** [comment]
If a dev could also remove the defilers reputation from my reputation tab, that would be very much appreciated. Snogumz said GMs are not able to do that. IGN: Stevo
