### ISSUE TITLE
why i am banned from wow

### ISSUE THREAD

**Issue by HeadShot552** [elysium-project/bug-tracker#385]
I have no unauthorized software on my computer that would give me an unfair advantage in the game. Nor have I ever used anything to do with botting, increased speed, teleportation etc. I play level 25 twinks in World of Warcraft, and the only conclusion I can come to is that I have been reported by players unaware of what twinking is and have reported me thinking i'm hacking or cheating or whatever because i'm doing much better than they are in PvP. I don't know what else I can say in this matter, other than that I doubt that this suspension has come in under any serious consideration, and would like to see some evidence of these claims. 

Thank you.

**Comment by Terranzin** [comment]
Dont know, if you want to ban appeal use the forum, in here we look for bugs on PTR-server we have no access to Nighthaven.
