### ISSUE TITLE
AH hacked/bugged?

### ISSUE THREAD

**Issue by LinerOne** [elysium-project/bug-tracker#386]
Hello there,so i put an item on AH in Orgrimmar called(The Black Night) at bid:5g and buyout:6,50g yesterday around 12am server time.After 10 mins a message popped up saying that my item was sold and when i got back to get my money from a mailbox it said that my item sold to a guy named Arash with a total value of almost 50s.Unfortunately for me i deleted the AH message after a while so i dont have any prove,i would be very gratefull if you can help me with this.
Best regards,Liner.

**Comment by Terranzin** [comment]
Since QA team doesn´t have any access to Nighthaven we´ve sent this to our dear GM staff to investigate. Closing this issue and if we find something you´ll be contacted ingame, if you don´t get contacted its probably that you made a mistake on your bid minimum.
