### ISSUE TITLE
Soul stone not working on self

### ISSUE THREAD

**Issue by xDeepankarx** [elysium-project/bug-tracker#388]
I've casted the soulstone numerous times on myself and whenever I die, I do not get the option of ressurecting on my spot. However, when I cast it on other people, it works for them.

It's not dispelled because I've died to different mobs and players and it still doesn't work.

This is for nighthaven pvp 1.4

**Comment by Terranzin** [comment]
I´ve tried to reproduce the issue you´ve reported. I can´t manage to see or reproduce the error, I can soulstone without a issue. I think this is on your end, try clear your WDB folder and remove any addons you might have and try again. If this would be a issue I´m pretty sure almost every warlock on server would say so.

![image](https://user-images.githubusercontent.com/25831382/35936553-d53bfbaa-0c43-11e8-8dc1-3184428c6dd9.png)
