### ISSUE TITLE
Damage on warlock spells not increasing

### ISSUE THREAD

**Issue by xDeepankarx** [elysium-project/bug-tracker#389]
From when I learned rank 7 shadowbolt and the second highest rank of drain life, every level my damage in those spells has kept increasing.  However, the last 3 levels(I'm level 51 right now) I see the same damage.  I've had the same gear since then so my spell power and intellect couldn't have accounted for this.  

For example, at level 48 my drain life(second highest rank) did 90 damage per tick. At level 51 it still does 90 damage per tick.

**Comment by Terranzin** [comment]
This is because drain life rank highest rank is 6, it does not increase damage because of you being on a higher level, the tick continues the same way all up to 60.
