### ISSUE TITLE
Mind Vision does not properly persist on targets that enter stealth

### ISSUE THREAD

**Issue by Inomares** [elysium-project/bug-tracker#392]
Bug repro'd on Nighthaven PVP Patch 1.4

Currently, mind visioning a target who then enters stealth, resets your vision back to the priest and you can no longer see the stealthed person.

Vanilla behaviour was that mind vision persisted on the target, you could keep seeing them as long as you kept mind vision on them. You could even cast instant spells on them.

Sources: 
[Wiki from 2006 (patch 1.12.1)](http://wowwiki.wikia.com/wiki/Mind_Vision?oldid=317381) ("A mind-visioned rogue or druid who stealthes can still be seen, and even hit with an instant cast spell.")
[Random video from 2007](https://www.youtube.com/watch?v=hW46h_q68lE)

**Comment by Inomares** [comment]
It should be noted, a patch note entry from 1.11 claims to remove this behaviour:
"Mind Vision now cancels when the target is not visible."

However, all sources I can find seem to imply the exact opposite happened. The stealth entry addition to the wiki was made a month after this patch, revised again a few months later, the video is from early TBC, and there are no patch notes mentioning this ever again. 

As far as I can tell, Blizzard said one thing but did the exact opposite. Considering the fact this apparently was never changed again (according to current wiki, this is still the case on retail), this was most likely a patch notes mistake.

**Comment by Navashed** [comment]
This definitely worked in TBC. Many sources mention it (ex: https://www.mmo-champion.com/threads/608676-Whats-the-deal-with-Mind-Vision).

The patch 1.11 notes are a bit mysterious however. But all evidence suggests this is the correct functionality.

**Comment by Inomares** [comment]
After some further scouring, I found this from 1.12 patch notes:

> Vanish now removes effects that allow the caster to always remain aware of their target (currently Hunter's Mark and Mind Vision)
[(Source)](https://web.archive.org/web/20061115210443/http://www.worldofwarcraft.com/patchnotes/patch1p12.html)

Should make sure this is the case once this gets fixed. This also confirms the earlier 1.11 notes were a mistake or referring to something else.
