### ISSUE TITLE
Cannot re-cast Mind Vision while channeling it

### ISSUE THREAD

**Issue by Inomares** [elysium-project/bug-tracker#393]
Bug repro'd on Nighthaven PVP Patch 1.4

If you cast Mind Vision, you are unable to cast it again on another target until it is cancelled. This makes it impossible to "chain" Mind Vision by casting or refreshing it on targets that are far away.

In vanilla, you could cast Mind Vision while it was already active, as can be seen in these two videos from 2006:

https://youtu.be/u4NY4EXchvA?t=120 (2 mins in)
https://youtu.be/KxITOD-fQ5g?t=120 (Many times throughout this video, for instance 2 minutes in)

**Comment by Navashed** [comment]
Confirmed.

![ef003e2087d38d6750d75d29e3d6a9d1](https://user-images.githubusercontent.com/2709545/35894873-d744c678-0b82-11e8-906a-633612d3b887.jpg)

**Comment by Thenari** [comment]
Tried this yesterday, still doesnt work.

**Comment by Inomares** [comment]
Regarding the tag, I provided sources showing clearly that this is a bug @Thenari - the videos are from retail vanilla :)
