### ISSUE TITLE
Seal Fate gives a combo point on a critical Eviscerate

### ISSUE THREAD

**Issue by Fifix** [elysium-project/bug-tracker#395]
Server/Patch : Nighthaven PvP (1.4)

Steps : 
- As a rogue, get Seal Fate, without taking Ruthlesseness (to avoid false positives)
- Build combo points on stuff, hit Eviscerate (Cold Blood it to ensure a crit if you're lazy enough)

Expected behaviour : Combo points are reset to 0, since Seal Fate only adds combo points on critical combo point generating abilities, and no point is put in Ruthlessness (which gives a 20% chance per talent point to reset your counter at 1 when you spend your combo points)

Current behaviour : Combo points are reset to 1, indicating that Seal Fate procs from a combo point spender.

**Comment by Navashed** [comment]
Confirmed, crits with Eviscerate (Spell 31016) trigger Seal Fate (Spell 14195). Seal Fate should not affect Eviscerate.

**Comment by sidsukana** [comment]
Will be fixed in next updates
