### ISSUE TITLE
My pet won't gain exp while in a party.

### ISSUE THREAD

**Issue by pilavcacik** [elysium-project/bug-tracker#397]
No matter where the other party members are, my pet isn't gaining experience while I am in a party. But, I noticed something that if my target is green to me that's when my pet gains experience. So, I can't level my pet through low level dungeons. 
I tried with other hunters, and their pet gained experience from low level mobs while I am in a party with them.

I tried to delete WDB folder, didn't work.
Character: Tsira
Pet: Lupos

**Comment by YaboyJimmyrustle** [comment]
Can you provide your level and the level of the pet you're trying to level up, please.
