### ISSUE TITLE
Problem with quest

### ISSUE THREAD

**Issue by fareladyz** [elysium-project/bug-tracker#398]
When smokey sings, I get Violent. When I plant the charges on the zuggarat to blow it up. I take damage and the charge is used but I do not get credit for the quest. Please fix this! Thank you!

-Fairladyz

**Comment by Terranzin** [comment]
Hello,

I´ve tried to reproduce the error but cant seem to do so. Is it on any specific Ziggurats this appears on?

![image](https://user-images.githubusercontent.com/25831382/35938803-98beb486-0c4a-11e8-823f-c74243eccb49.png)

**Comment by fareladyz** [comment]
Any of them, I walked in with an invis potion. Killed the non elite and planted my charges. It would not count it when I waiting 5-10 minutes to plant the charge again once the symbol showed up again

**Comment by Terranzin** [comment]
Try remove quest and take it again, also clean your WDB folder (remove) and disable any addons, then try again. Your error can´t be reproduced if the issue is the same on all of them.
