### ISSUE TITLE
Character stuck on boat/barrens

### ISSUE THREAD

**Issue by hoolabandoola** [elysium-project/bug-tracker#399]
Gnome mage Lewenhaupt - stuck in the ocean after priest MC during loading screen, cant use HS nor die, pls help!

**Comment by tubiakou** [comment]
Did you try the "Unstuck" feature?  Access it as follows:

1. Click the little **?** (Question Mark) on your UI.
2. Click _**Issues that GMs can assist with**_
3. Click "_**- Stuck**_"
4. Click "_**Auto-Unstuck**_".
