### ISSUE TITLE
Quest in BRD Bugged

### ISSUE THREAD

**Issue by fareladyz** [elysium-project/bug-tracker#401]
Quest in BRD Bugged, "whats going on" cannot talk to Gor'shak to kill dwarf for next part of quest.

-Fairladyz

**Comment by Terranzin** [comment]
I´ve looked into the issue and manage to reproduce the error.

Use-case:
- Added prison cell key to my inventory (11140)
- Killed the guards outside
- Took first quest (3981)
- Spoke to Commander Gor'shak and accepted next part
- Cleared first wave of twilight enemies
- Cleared the second wave of twilight enemies
- Quest got completed
- Tried to turn in the quest but you can´t seem to get the quest dialogue with him.

![image](https://user-images.githubusercontent.com/25831382/35939282-f93e70a2-0c4b-11e8-9661-b7b537a4def7.png)

**Comment by Giperionn** [comment]
Hello @fareladyz ! Thanks you for report.
Poor Gor'shak can't rest after battle. He's restlessly seek for new enemies, and don't want to talk, even if no enemies around. Now, after several conversations with the ~~psychologist~~ programmer, he started to live with full npc life! And talking to people after fights.
Have a good day!
![Desc](https://image.prntscr.com/image/acHBSWB9SvuZYoRS1-3eqA.png)
