### ISSUE TITLE
Cannot stop auto attack during Mind Control

### ISSUE THREAD

**Issue by Inomares** [elysium-project/bug-tracker#403]
Repro steps:
1) Mind control a humanoid using a priest's Mind Control ability
2) Melee attack another enemy using your mind controlled NPC
3) Untarget the enemy or target yourself, which would normally cancel the melee attack as a normal player
4) Note that your controlled character will keep attacking anyway

This behaviour was fixed on retail with patch 1.7:
> Possessed units (e.g. Mind Control, Eyes of the Beast etc...) can now cancel combat mode by clearing your current target. In addition, the UI will have a gold border when the possessed unit is actively in combat mode with the target. 

> You can cancel melee combat while mind controlling by clearing the target, like you can normally. 

[Source](http://wowwiki.wikia.com/wiki/Patch_1.7.0)

**Comment by Terranzin** [comment]
Hello,

If this was fixed during patch 1.7 that´s also when we´re getting it. Nighthaven is today on patch 1.4 (soon 1.5). If the issue is there during patch 1.7 please make another report.
