### ISSUE TITLE
Neutral guards do not see through Vanish & Feign Death

### ISSUE THREAD

**Issue by Inomares** [elysium-project/bug-tracker#404]
Neutral guards in cities such as the bruisers in Booty Bay, Ratchet, and Everlook or the Argent Dawn Sentries in Light's Hope Chapel do not currently see through Vanish (Rogues) and Feign Death (Hunters). This was originally fixed in patch 1.12.

Sources for vanish:
[Official Patch Notes 1.12.0:](http://wowwiki.wikia.com/wiki/Patch_1.12.0)
> Neutral guards are now able to see through the rogue Vanish ability.

Neutral guards seeing through Feign Death was an undocumented change. The sources I can find seem to indicate this was fixed by the time 1.12 came out, but it is unclear if it arrived in that same patch, or sometime earlier.
In a random forum thread from 2006, I found these posts in response to people speculating whether this also affected Feign Death:
>[I can personally attest to being \[killed\] by the neutral guards in Everlook when I thought I'd clicked the mailbox but instead took a poke a shaman. FD \[Feign Death\] does not work!](https://arstechnica.com/civis/viewtopic.php?p=6150661#p6150661)

>[Cenarion Hold guards in Silithus don't care about your playing possum.](https://arstechnica.com/civis/viewtopic.php?p=6161361#p6161361)

>[Same with the Tanaris gobs. Shoot someone, and they're going to come kill you, FD or no.](https://arstechnica.com/civis/viewtopic.php?p=6164755#p6164755)

Different forum:

>[Yay! 
\* Neutral guards are now able to see through the rogue Vanish ability.
Got so sick of my FD not working, whilest rogues could waltz about ](https://worldofwarcraft.livejournal.com/3977565.html?thread=62252381#t62252381)

**Comment by Terranzin** [comment]
We´re on patch 1.5 as we speak, if this was fixed in 1.12 that´s when this will be added too.

Thanks for great sources though.
