### ISSUE TITLE
lunar fest quest bugged

### ISSUE THREAD

**Issue by femmefatel** [elysium-project/bug-tracker#407]
unable to complete the firework launching quest.

**Comment by femmefatel** [comment]
Buying fireworks and launching them from a nearby vendor does not count towards Lunar Festival Quest line.

**Comment by Terranzin** [comment]
Lunar festival shouldn´t even exist. Nighthaven is soon on patch 1.5 which was released around 2005-06-07. 

The first ever Lunar Festival was dated 2006
![image](https://user-images.githubusercontent.com/25831382/36018819-6db26312-0d7d-11e8-8570-1472698aedf4.png)

I´m not confirming your issue, I´m confirming that this even should be removed until later content patch.
