### ISSUE TITLE
Pamela's doll quest bugged

### ISSUE THREAD

**Issue by nileppezdel34** [elysium-project/bug-tracker#411]
When doing Pamela's doll I was able to loot the head and left side however the right side will not appear to loot. I had a friend with me showing exactly where he looked it, I checked back several times over an hour and tried abandoning and retaking still unable to collect the last piece

**Comment by Terranzin** [comment]
I´ve tried to reproduce the error you reported but unable to do so. I was able to loot all 3 items and complete it.

![image](https://user-images.githubusercontent.com/25831382/36171171-e8a266bc-1101-11e8-9e01-65313d632b12.png)

**Comment by nclsmitchell** [comment]
Hi, I have the same issue with the head that is not lootable on my side. The right and left sides were lootable though.
