### ISSUE TITLE
The Vile Reef - Encrusted Tail Fins

### ISSUE THREAD

**Issue by Warsonx** [elysium-project/bug-tracker#412]
The Vile Reef area seems to be lacking some spawns points, if I'm not mistaken there used to be some murlocs standing all around near some rocks and they're spawning exclusively inside the ruins. Also there seems to be reports of this (http://www.wowhead.com/quest=1107/encrusted-tail-fins) and for those using Questie it shows drop locations outside the ruins, only there's no murlocs there.

This affects gameplay, as it is a Group quest and it requires a high amount of kills to get everyone set and the murlocs that spawn are the ones standing at a higher depth, wich makes it even harder for those with limited breath. (not Undead or using Unending Breath)

**Comment by Terranzin** [comment]
You´ll need to provide much more information/sources for us to add more spawn points then there already is. I did take a look at it though, and from my old experience from vanilla it does look about accurate what I remember. 

![image](https://user-images.githubusercontent.com/25831382/36171391-d0783318-1102-11e8-9cd7-dbd376845a32.png)
