### ISSUE TITLE
Warrior T1 Helm

### ISSUE THREAD

**Issue by Eevee123** [elysium-project/bug-tracker#414]
Warrior T1 Helm was supposed to be nerfed in patch 1.5 but seems like it got buffed? 
![image](https://user-images.githubusercontent.com/35239707/36063066-1f288914-0e46-11e8-9498-e1aa616a6c27.png)

![image](https://user-images.githubusercontent.com/35239707/36063051-f6ec3612-0e45-11e8-9622-8adc402268d8.png)

**Comment by Qualthalas** [comment]
The second one is T2

**Comment by Terranzin** [comment]
You´re linking two different sets. One is T1 the other one is T2
