### ISSUE TITLE
Quest In Dreams is bugged and not completable

### ISSUE THREAD

**Issue by comus777** [elysium-project/bug-tracker#415]
The quest In Dreams is bugged, specifically the event during which Taelan defends himself at the tower from the inquisitor and his lackeys. After Taelan is killed as per scripted, the mobs instantly aggro towards the player, whether or not they have vanished for feigned death or lost aggro using any other method beforehand. If the player manages to lose aggro again, the mobs despawn. If the player is killed during the event, the mobs also despawn. If the mobs are kited around for long enough, they eventually also despawn. No matter what happens, the mobs will always despawn and Tirion never shows up to challenge the Inquisitor, and thus complete the quest. This makes this quest effectively impossible to do.

**Comment by bobojoga** [comment]
> No matter what happens, the mobs will always despawn and Tirion never shows up to challenge the Inquisitor, and thus complete the quest. 

I just wrote to the issue what I did to complete the quest. So your point that the quest is not completable is false.
Check it out:
https://github.com/elysium-project/bug-tracker/issues/420

**Comment by Giperionn** [comment]
Already fixed, patch not uploaded to live server.
Thank you for report.
