### ISSUE TITLE
Cannibalistic Cousins quest in hinterlands

### ISSUE THREAD

**Issue by fareladyz** [elysium-project/bug-tracker#416]
I was killing mobs for canabalistic cousins quest in hinterlands, one of the new one just released and I am no longer getting a mob count to be able to complete the quest for turn in, is there a way to get this fixed please?
-Fairladyz

**Comment by Terranzin** [comment]
"one of the new one just released", you speaking of new patch? What you could attempt is clear your WDB folder fully (as we ask players to do) and then try again.
