### ISSUE TITLE
NPC's Curse of Weakness completely blocks range dmg on hunters.

### ISSUE THREAD

**Issue by bk187** [elysium-project/bug-tracker#417]
Jadefire Trickster's Curse of Weakness blocks hunter's range damage done by 100%.. many other npcs that do this ability does the same effect.. I didnt investigate for Warlock's Curse of Weakness yet.

**Comment by YaboyJimmyrustle** [comment]
Hunter ranged attacks against Jadefire Trickster, Felwood and Deadwind Warlock, Deadwind Pass both fell within the normal range of block chance while Curse of Weakness was active.

**Conditions:**
- Level 50 hunter
- 250 Bow skills
- Rough Arrow with a Worn Shortbow
- No added hit gear (+0%)
- Curse of Weakness (spellid 11980)
![curse of weakness tooltip](https://user-images.githubusercontent.com/36592168/36472028-4eb391c6-16a5-11e8-80b2-5bc893c41f77.png)

Block chance fell within the range of 2.9% (without CoW) to 3.4% (with CoW) after ~600 auto shot ranged auto-shot attacks.

It seems ranged blocks against hunter attacks is functioning as intended while Curse of Weakness is active. Are there any other circumstances that may have also had an effect on ranged attack block chance for these npcs?

**Comment by bk187** [comment]
Then we must have been playing on different servers. Because when I leveled up hunter all NPCs that casted Curse of Wakness did completely lower my range damage to 0, then I went into melee and realised it's only lowering range damage by ridiculous amount of 100%, while for malee damage it was lower normally I guess.
