### ISSUE TITLE
Seal Of Wrynn - Does not give proper stats!

### ISSUE THREAD

**Issue by Mortdecay** [elysium-project/bug-tracker#418]
I just got this ring as a quest reward, I always loved this ring, but as i replaced my old ring which gave me +3 int, i got less mana. I was canfused as first, because this ring should give +4 int, but later as I checked my stats change as I unequipped the ring, it became clear for me: it only gives +2 stamina and +6 spirit, which is pretty useless (for me) now...(On it's text it says: +4 stamina +4 int +3  spirit +3 agility +3 strength). 
Shouldn't it be fixed? 

- Mortdecay

**Comment by SterlynStevo** [comment]
It wasn't changed until a later patch.

**Comment by Terranzin** [comment]
Clear your WDB folder fully and you´ll see the correct stats, there´s no issue with it.
