### ISSUE TITLE
Issues completing quests in Tarren Mill

### ISSUE THREAD

**Issue by NsirhC** [elysium-project/bug-tracker#419]
Apothecary Lydon has the following quests:

Elixir of Suffering
Elixir of Pain
Blood of Innocents

Both Elixir quests I have finished and get to the "complete quest" button, but when I hit it nothing happens. This is the case for both quests. 

Also a minor bug with Blood of Innocents, the text cuts off:

"Did you find the Syndicate Shadow Mages, and collect from them the bl" 

I'm not sure if this NPC is bugged due to the new server-side patch for BGs or what.

**Comment by NsirhC** [comment]
Character name is: Blazedfrosty

**Comment by Terranzin** [comment]
**Quest: Blood of innocents (id: 1066)**
![image](https://user-images.githubusercontent.com/25831382/36171772-2b502d6c-1104-11e8-841f-e09fa6b03d55.png)

I confirm this, it should say: 
Did you find the Syndicate Shadow Mages, and collect from them the blood?


________________________________________

**Quest: Elixir of suffering**

I can´t reproduce the error, I was able to complete the quest and got the next part of it:
![image](https://user-images.githubusercontent.com/25831382/36172062-0a21a3c2-1105-11e8-9277-f7c14c2aa394.png)

**Quest: Elixir of pain**

Cant be reproduced, I was able to complete the quest
![image](https://user-images.githubusercontent.com/25831382/36172145-3e4d2798-1105-11e8-98ca-5cd789e71641.png)

**Quest: Elixir of suffering**

There wasn´t a follow-up on this quest but it was working fine to hand in the quest. Have you tried clearing your WDB folder?


PS: I´m only confirming that the progress text is wrong on Blood of innocents, the rest unfortunately I can´t manage to reproduce.

**Comment by NsirhC** [comment]
It apparently had to do with compatibility issues between addons "Aero" and "Questie" with the base client. I'm not sure why exactly, but it stopped me from turning in quests. I'm unsure if this is because of the new patch 1.5 on the server or something inherently wrong with the addons for Vanilla.
 
The solution has been found, so the only thing of note is the text error in the quest.

 Thank you for your response and help!

**Comment by Giperionn** [comment]
Hello @NsirhC ! Thank you for report.
I can't reproduce all issues (as reported by Terranzin). I was able to complete all quests.
Howewer, I fix progress text in quest 'Blood of Innocents'. Fix will be active in next server update.
Have a good day!
