### ISSUE TITLE
Darrowshire paladin deal of crusader #3265

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#42]
From Old bug-tracker:

> Seal of crusader tool tip states 40% weapon sod increase but is only doing 30%
> 
> Using blue glittering axe wpn spd 1.8 should be 1.08 but is showing 1.26 which is a 30% increase not 40%

**Comment by twink** [comment]
Not a bug.
http://wowwiki.wikia.com/wiki/Attack_speed

> Attack_speed = "current attack speed" / (("Percent increase or decrease" / 100) + 1 )
