### ISSUE TITLE
In Dreams.

### ISSUE THREAD

**Issue by egojohn** [elysium-project/bug-tracker#420]
Tirion won't come help after his son dies, so groups die and mobs despawn.
I talked with a gm that was willing to let me complete the quest, but told me to wait till someone did the quest and tirion actually appeared. Been camping the tower for 3 hours. and 4 groups have tried everyone failed due to no tirion, aka no tirion to complete my quest at.
How exactly am i supposed to complete it and claim my preraid bis ring? Do i just give up?
Over and out Egojohn
Thanks for an amazing server! :)

**Comment by bobojoga** [comment]
Hello. I completed In Dreams. And it was quite easy. My tactic was: wait as ghost in front of tower and wait for someone to complete it.
The way they completed the quest was quite intuitive: Just have friend with 100% mount who will keep aggro of mobs and run around the tower until Fordring comes. When he comes, he will nuke every enemy and the quest can be completed. 

And harder way to handle the quest is to have 5+ players to keep up with fight untill Fordring comes.

**Comment by Giperionn** [comment]
Already fixed, patch not uploaded to live server.
Thank you for report, anyway ^_^
