### ISSUE TITLE
Quest turn in bugged "The Legend of Korrak" Alterac Valley quest!

### ISSUE THREAD

**Issue by Dcamslam** [elysium-project/bug-tracker#421]
In AV pvp battleground Korrak was tagged red for my side and killed. Once outside the AV the quest turn in at Warmaster Laggrond is able to be turned in but once I select a reward and click complete quest it gives an error message stating please select a reward. Tried deleting some file and restarting wow from help with a GM but no luck so logging problem here.

**Comment by Wrath669** [comment]
For some reason a majority of the AV quests are bugged and have a Red clickable "Complete Quest" button, even when prerequisites are not complete and then just give an error when turning in. 
When you go to hand into the quest giver, it may appear that "The Legend or Korrak" is complete and give the symptoms as you describe above. 
Double check your quest log and make sure it definitely marked as "Complete" and not "Raid" to make sure it definitely completed and credited you. 
If you have ranked up your faction rep, but do not have the insignia in your inventory, the quest giver will show a Yellow Question Mark which is actually for the insignia upgrade quest which makes it look like you can turn in other quests, giving the illusion you can turn in "The Legend of Korrak". 
It's possible after Korrak died when tagged to your faction, you died and were too far away to be credited a kill?

**Comment by Giperionn** [comment]
Internal testing shows that quest work.
But respawn time was incorrect (2 hours). In next patch, it will be 30 min
