### ISSUE TITLE
Quest Taming the beast BUG 10lvl elf

### ISSUE THREAD

**Issue by Bagheerahunter** [elysium-project/bug-tracker#422]
![wow bug](https://user-images.githubusercontent.com/36374588/36075420-81e90c9c-0f57-11e8-95a7-891e63e38cc1.png)

I first caught the spider without a problem. Now I can not capture Nightsaber Stalker. I tried to get questa and get it again but nothing happened. I do not know what to do Help me. hunter without beast does not get :( 

I remember removing the spider before it disappears alone. Maybe this is the problem. What to do?

**Comment by YaboyJimmyrustle** [comment]
It sounds like you tamed the Spider, turned that particular quest in. Then you accepted the quest for taming the NIghtsaber Stalker, dismissed the Spider you had previously tamed, and attempted to tame the Nightsaber.

This looks like the Nightsaber Stalker behind the inn in Dolanaar, did you try to tame a different one? My suggestion would be to look for and try taming different Stalkers to see if that resolves your issue. Ensure you have no other pets currently under your control and have the quest item to tame the animal. If it doesn't we can take a look at why this might be happening.
