### ISSUE TITLE
Quest "Material Assistance" not yet implemented.

### ISSUE THREAD

**Issue by Wrath669** [elysium-project/bug-tracker#423]
Not entirely sure on the reliability of the information on WoWWiki, but according to the following page, the quest "Material Assistance" should be implemented at patch 1.4.0
http://wowwiki.wikia.com/wiki/Quest:Material_Assistance
The NPC "Sagorne Creststrider" doesn't offer me this quest as a level 60 Shaman when the only prerequisite is to be at least a level 58 Shaman. There are no quests required before it is offered, as far as various databases advise. https://classicdb.ch/?quest=7667

**Comment by Terranzin** [comment]
Hello regarding sources, the wowwiki is a OK source, but classicdb.ch is not. I´ll confirm this.

**Comment by Wrath669** [comment]
Has the fix been implemented yet? I still do not see the quest available for my level 60 Orc Shaman, Wrathius.
Or are we due a development update that implements bug fixes separate to last Saturday's content update?
Thanks.
