### ISSUE TITLE
Channeling of Gnomish Death Ray deals damage while the player is Immune. Before Patch 1.9.0

### ISSUE THREAD

**Issue by Gelori** [elysium-project/bug-tracker#425]
Hello.

According to patch notes of 1.9.0 ( checked on different sources)

**http://wowwiki.wikia.com/wiki/Patch_1.9.0**

**The Gnomish Death Ray's backfire will now affect players even if they have an immunity effect, such as Divine Shield.**

So basically before **1.9.0**, Blessing of Protection and Divine Shield, should prevent the player from getting damage while channeling the Death Ray , since it is a Physical damage school. 

Dont break it again please! You fixed it before:

https://forum.elysium-project.org/topic/30143-gnomish-death-ray-and-bubble/

**Comment by Navashed** [comment]
The server uses 1.12 game mechanics. Game mechanics (talents, spells, etc) are not progressively patched as content is released. The 1.12 functionality of the Death Ray is the correct functionality.
