### ISSUE TITLE
"Tanaris Field Sampling" not working

### ISSUE THREAD

**Issue by Dnamix** [elysium-project/bug-tracker#428]
Hi.

I've finished the "Tanaris Field Sampling" quest but I cannot turn in the quest at Chief Engineer Bilgewhizzle. The quest has a 2 hour timer on in, don't know if it affects the ability to hand it in.

/Cheers

**Comment by Wrath669** [comment]
I completed the quest without any problems this week. I imagine the 2H time does affect the ability to hand in currently, not sure if that is intended though if it's already marked as "Complete" in your log.

**Comment by YaboyJimmyrustle** [comment]
For the quest "Tanaris Field Sampling," you have two hours to complete it and turn it in to Chief Engineer Bilgewhizzle. This is referenced to by his warning that if the power goes out, everything inside will be ruined and you will need to start all over. Even though you gathered the data and it says you completed the quest, the time limit ran out and the data expired. This is the intended quest mechanic.
