### ISSUE TITLE
Chain quest "Nothing But The Truth"

### ISSUE THREAD

**Issue by Sarisean** [elysium-project/bug-tracker#429]
There is a problem with the quest chain Nothing But The Truth, horde side in Duskwood.
The right order for this chain should be: 
[Deathstalker Zraedus](https://classicdb.ch/?npc=5418) starts the chain with the [first quest](https://classicdb.ch/?quest=1372) where you have to talk to [Apothecary Faustin](https://classicdb.ch/?npc=5414)
Then, [Apothecary Faustin](https://classicdb.ch/?npc=5414) give you the [next quest](https://classicdb.ch/?quest=1383), which is an elite quest.
When you end this quest, [Apothecary Faustin](https://classicdb.ch/?npc=5414) should start the [next one](https://classicdb.ch/?quest=1388). 
You now have to talk to [Deathstalker Zraedus](https://classicdb.ch/?npc=5418) and he gives you the [last quest of this chain](https://classicdb.ch/?quest=1391)

Here the problem is [Apothecary Faustin](https://classicdb.ch/?npc=5414) gives you [the third quest ](https://classicdb.ch/?quest=1388) without any conditions, therefore without having to do the first two quests.

Also, during [the last quest](https://classicdb.ch/?quest=1391), you have to give a poisonous drink to[ Infiltrator Marksen](https://classicdb.ch/?npc=5416) and he should say "I believe the Forsaken are misleading the allies of the Horde.... wait... I feel so... dizzy..." and then turns undead and then dies. Here nothing happens.

**Comment by Giperionn** [comment]
Hello @Sarisean ! Thank you for report.
Fix for corrected quest order and additional scripting will be available in the next server update.
If you want know, what truly happens to Infiltrator Marksen, here's a video for you:
https://youtu.be/1zaLjHemEIg
Have a great day!
