### ISSUE TITLE
Felheart Belt "Use" Effect

### ISSUE THREAD

**Issue by Macaiden** [elysium-project/bug-tracker#430]
instead of the increased spell damage being a static ability its showing that i need to click it as a use ability to activate the spell damage. it says this to be precise.

Equip: Restores 6 health per 5 sec.
Use: Increases damage done by Shadow spells and effect by up to 11.

**Comment by Macaiden** [comment]
i would also like to note that i tried deleting the WDB folder already to no avail

**Comment by Terranzin** [comment]
Hello,

I´ve looked into your issue and it´s indeed incorrect as of now.

![image](https://user-images.githubusercontent.com/25831382/36168972-2905e5fa-10fb-11e8-98be-5e221cf93d7f.png)

**Comment by Giperionn** [comment]
Thank you for report, Macaiden.
This issue will be fixed in the next server update.
https://image.prntscr.com/image/I9Y5TKshRDO1Vshj7mRmuQ.png
Have a great day ^_^

**Comment by Hatmud** [comment]
Delete my WDB folder and still follow the bug

**Comment by Hatmud** [comment]
This belt has bad characteristicshttps://www.photobox.co.uk/my/photo?album_id=5271405355&photo_id=500630475411

I should give these other

https://classicdb.ch/?item=16806

That's why it does not work
