### ISSUE TITLE
Engineer Transporter is borken!

### ISSUE THREAD

**Issue by Eevee123** [elysium-project/bug-tracker#431]
I'm 100% sure that Goblin transporter is taught in Everlook and Gnomish transporter is taught in Gadgetzan but all my guildie and me have a problem with that, they both are taught in Gadgetzan by the engineer trainer outside the inn and you can learn both??? wtf im pretty sure u can't learn both...
![image](https://user-images.githubusercontent.com/35239707/36148817-4d6b44e6-108b-11e8-8bd9-94cc3a9819ee.png)

**Comment by Terranzin** [comment]
We´ll need some valid sources on how you expect it to be on current patch.

**Comment by tubiakou** [comment]
There are 3 engineering NPCs involved in this issue:
1. Jhordy Lapforge (Gnome Engineer, standing by the Gnome transporter in Gadgetzan)
2. Zap Farflinger (Goblin Engineer, standing by the Goblin transporter in Everlook).
3. Buzzek Bracketswing (Expert Engineering trainer, standing outside Gadgetzan Inn)

According to the [patch notes for Client 1.5](http://wowwiki.wikia.com/wiki/Patch_1.5.0), the gnome and goblin transporters were added in 1.5.0, and engineers could obtain the recipes from Everlook and Gadgetzan respectively.

Testing on PTR with a character specialized in Goblin Engineering, Zap Farflinger does appear to teach the **Dimensional Ripper - Everlook** recipe.  He does not teach the gnome equivalent.  **This seems correct.**

Testing on PTR with a character specialized in Gnome Engineering, Jhordy Lapforge does appear to teach the "Ultrasafe Transporter - Gadgetzan" recipe.  He does not teach the goblin equivalent.  **This seems correct**.

What the OP is pointing out seems totally wrong:  Buzzek Bracketswing is a goblin Engineering Trainer (up to Expert level).  So while it is conceivable that he could train the goblin transporter, it shouldn't be possible for him to teach the gnome equivalent.  **This definitely seems incorrect**.

However I question whether Buzzek should be able to teach even the goblin recipe.  Nothing in my research suggests that he can teach this recipe, and the 1.5.0 patch notes don't suggest this either.  Actually there is very little period literature (a.k.a. written between 2003 - 2006) that I could find on Buzzek in the first place.  He seems to be a slightly mysterious figure, aside from being acknowledged as an Expert trainer.

Based on this I believe that the resolution of this issue would be to remove both recipes from Buzzek's available list, and leave them available only from their respective Transporter Engineers in Gadgetzan and Everlook.

Replacing "Report Incomplete" with "Confirmed", pending further investigation.

**Comment by Giperionn** [comment]
Hello @Eevee123 ! Thank you for report.
Ultrasafe Transporter: Gadgetzan recipe will be removed from this npc trainer in next server update.

![Desc](https://image.prntscr.com/image/47E3D8dQSLG_F3mZfGYTKg.png)

**Comment by Lightsockie** [comment]
As a (master race) Gnomish Engineer I was able to learn the Everlook teleporter from Buzzek. Doing so seems to have locked me out from my Gnomish Gadgetzan teleporter. Before I bought the Everlook one, Buzzek taught both. Now that I know the Everlook one, neither Buzzek nor Jhordy will offer me the Gnomish teleporter. I don't believe I should've been able to learn the Goblin version to begin with. It's locked behind Goblin Engineering, and I just don't remember it being that way.

Also while I'm here I don't think the Truesilver Transformer was added to Buzzek  until TBC. However, even after digging through the patch notes, the best proof I can find is someone commenting on the recipe in classicdb (from patch 2.0) saying he now teaches it

**Comment by Lightsockie** [comment]
Was just talking with a guildie (and fellow gnomish engi) about the teleporters. Seems they have the same problem too: Learning the (unusable) goblin teleporter and being locked out of the gnomish.

Can this ticket please be reopened? Buzzek should not teach the Everlook teleporter. But if the decision is to keep him teaching it, then can you also add the corresponding check to make sure that the target is a goblin engineer?

Also I've talked with a GM in-game and he pointed me to opening this ticket and getting it resolved this way. (I did this before my last comment.) Seems they aren't allowed (or able?) to change skills like that. So even after this is fixed, there's going to be some of us left hanging. I _suspect_ it's because there's a check to make sure someone doesn't know both teleporter recipes at the same time

**Comment by ely-perseus** [comment]
The spell will be removed from Buzzek, as he should definitely not be teaching it :).

**Comment by Lightsockie** [comment]
Thanks @ely-perseus!
What should we do that know the wrong teleporter do? We can't learn our correct, Gnomish, one (just checked again). GM said to open this ticket to get it fixed. Said he couldn't fix it, seemed to imply it was because he didn't have the perms to. Should I try a GM again?

**Comment by RainElysium** [comment]
I fixed his char in game.
