### ISSUE TITLE
Thorium Brotherhood on a progressive server

### ISSUE THREAD

**Issue by painthegain** [elysium-project/bug-tracker#432]
Hello,

Regarding reputation on a progressive server I feel that there isn't enough time to even get one person to exalted with Thorium Brotherhood before BWL hits (march 10th). 

In current patch the following quests reward the follow reputation:
**Favor Amongst the Brotherhood, Fiery Core - 200 reputation**
https://classicdb.ch/?quest=6643
**Favor Amongst the Brotherhood, Blood of the Mountain - 200 reputation**
https://classicdb.ch/?quest=6646
**Favor Amongst the Brotherhood, Core Leather - 150 reputation**
https://classicdb.ch/?quest=6645
**Favor Amongst the Brotherhood, Dark Iron Ore - 50 reputation**
https://classicdb.ch/?quest=6642
**Favor Amongst the Brotherhood, Lava Core - 200 reputation**
https://classicdb.ch/?quest=6644

This means that let's say only turning in Lava or Fiery Cores would require the following amount.

Assuming you are at a honored reputation:

0/12000 - 12000/12000 = 60 Cores. Now assuming you haven't missed a single week of MC (Molten Core) since launch pretty much (same week server first was done) you barely have enough to get to revered. 

Now for the second part:

0/21000 - 21000/21000 = 105 cores. 

This would mean we would have to do more than double the amount of MC we have already completed in order to reach exalted with Thorium Brotherhood and there's less than or 4 resets left until BWL hits. 

Suggestion: seeing as we are an progressive server make the rewards progressive where to as they reward the following amount of experience
**Favor Amongst the Brotherhood, Lava Core - 500 reputation**
http://www.wowhead.com/quest=6644/favor-amongst-the-brotherhood-lava-core
**Favor Amongst the Brotherhood, Fiery Core - 500 reputation**
http://www.wowhead.com/quest=6643/favor-amongst-the-brotherhood-fiery-core
**Favor Amongst the Brotherhood, Blood of the Mountain - 500 reputation**
http://www.wowhead.com/quest=6646/favor-amongst-the-brotherhood-blood-of-the-mountain
**Favor Amongst the Brotherhood, Core Leather - 350 reputation**
http://www.wowhead.com/quest=6645/favor-amongst-the-brotherhood-core-leather
**Favor Amongst the Brotherhood, Dark Iron Ore - 75 reputation**
http://www.wowhead.com/quest=6642/favor-amongst-the-brotherhood-dark-iron-ore

Thanks!

**Comment by Terranzin** [comment]
Greetings! Although your post is a good one, this needs to be in the correct place. The QA team does not look into these issues, what you posted is a suggestion which needs to be addressed on our forum. 

Therefor I´ll close it here since we have no power in these kind of questions. Like I said, please post it on our forum instead!
