### ISSUE TITLE
Frostwolf Battle Standard

### ISSUE THREAD

**Issue by Mumfo** [elysium-project/bug-tracker#434]
The Frostwolf Battle Standard disappeared after one use in AV.

**Comment by Terranzin** [comment]
I´ve reproduced your issue. It should stay in the inventory with 15 min cooldown, but right now it´s a one time use.
![image](https://user-images.githubusercontent.com/25831382/36322430-81d49510-134d-11e8-9d82-e39ef5338d4f.png)

**Comment by Mumfo** [comment]
Worst 4+ gold I’ve ever spent, hopefully the fix is easy.
