### ISSUE TITLE
Red Whelp Scales don't drop

### ISSUE THREAD

**Issue by Stankface** [elysium-project/bug-tracker#437]
Nighthaven PVP
Class: Rogue
Alignment: Horde

I managed to get my hands on the Red Whelp Scale Gloves, and after killing over 75 whelps, I've determined they are not implemented.

The droprate from skinning these is supposed to be as follows:

Flamesnorting Whelp = 20%
Crimson Whelp = 10%
Lost Whelp = 10%
Red Whelp = 10%

**Comment by Stankface** [comment]
After killing about 100 I finally had 1 drop. Change the droprate it's not at what it's supposed to be.

**Comment by Terranzin** [comment]
Regarding the drop rate, could you please give us valid source from that era of patch 1.5, Battlegrounds?

**Comment by Thenari** [comment]
does like skinning skin change things?

ill test it now i guess

**Comment by Stankface** [comment]
I haven't played in a long time, but I managed to get them to drop

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40286209-0f75ae68-5c73-11e8-84b8-9c52eeff8c69.png)

red whelps

2 red whelp scales
5 medium leather
3 (2*Light leather)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40286564-c54ca55a-5c75-11e8-87fd-29950bb073a9.png)

lost whelps  1/17 probs just unlucky
1 red whelp scale
10 medium
3 (2*light leather)
1 (1*light leather)
2 light hides

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40286661-7141e60e-5c76-11e8-9dd3-a092ff8f4d54.png)

crimson whelps 2/11
2 red whelp scales
3 medium leather
4 (2*light leather)
2 light leather

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40286962-58b3bc64-5c78-11e8-9af0-c5fc12f9c064.png)

Flamesnorting Whelps 2/21
2 red whelp scales
16 medium leather
3 heavy leather

(3 small flame sacs too which is nice)
