### ISSUE TITLE
Brutal Armor Quest #3221

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#44]
From old bug-tracker:

> So after reviewing articles online I have yet to find anything seeing a bug related to the Brutal Armor Quests for level 20 warriors. I am currently a level 21 undead warrior and have found all required items to turn in the quest. In my quest log it says complete, but when I go to turn it in to Firegaze he has a greyed out question mark and it does not allow me to turn it in. I've tried reloading, turning addons off, even banking and unbanking nothing is working.
> 
> any help would be appreciated.

**Comment by Terranzin** [comment]
I´ve reviewed your issue by doing the last part of the quest works fine.

**Comment by Gvozdy** [comment]
I Have the same problem! My name is Gvozdy, I have all items, the quest "Brutal Armor" is complete in my quest list, but the Thun'grim Fireglaze's question mark is GREY! Please, fix this problem, Ispend many hours to do this quest, that doesn't work (to my surprise).
