### ISSUE TITLE
Sentinel Farsong

### ISSUE THREAD

**Issue by Maladas** [elysium-project/bug-tracker#441]
This NPC right outside of the Warsong Gultch instance has a yellow exclamation point above her head but when I click on her there are no quests displayed. My character is level 29.

**Comment by Terranzin** [comment]
The quest shouldn´t even be there. The quest Vanquish the Invaders! was added in patch 1.11. I´m not confirming your issue (the quest does require level 60 though) I´m confirming that the quest shouldn´t even be there.

**Comment by sidsukana** [comment]
This quest has level bracket analogs.
Bug exist and fixed. Wait new updates.
