### ISSUE TITLE
Job opening: Guard Captain of Revantusk Village

### ISSUE THREAD

**Issue by Cramitclowny** [elysium-project/bug-tracker#442]
There should not be a level requirement on this quest in this patch. When released, it was possible to get this item for the twink battle grounds at level 19. It was the most popular twink item, being as how it was one of the few available trinkets, and if you went all out you got arena grand master as well.  Moving to patches closer towards BC, it was implemented with a level requirement, in the push to end twinks. Walked all the way there on a level 14 warrior to check this and was disappointed i couldn't pick up the quest.

**Comment by fulzamoth** [comment]
You'll need to provide some sources for this information.

**Comment by drozdez** [comment]
The database says it have level requirements. https://classicdb.ch/?quest=7862

So there, i think that it works as intended
