### ISSUE TITLE
Mind control breaks too early when going out of range

### ISSUE THREAD

**Issue by Inomares** [elysium-project/bug-tracker#443]
Unlike other channeled spells, Mind Control breaks _instantly_ when the mind controlled target is brought out of range. This is not Blizzlike. This video for instance shows multiple instances of the target being brought outside of mind control range, and it persisting for up to five seconds (exact leeway time seems to vary, and probably resets when going back in range, though this is hard to tell from the video).

Warning: For your own sake, you may want to mute this video.
https://www.youtube.com/watch?v=PnnWDPgk_3Y

You can see him going well out of the 20 yard range (he is holy, so he does not have increased shadow range) in many of the clips. Most notably is the one at 3 minutes, where he runs _very_ far off with the mob before the mind control breaks. Measuring this distance in-game shows he was able to run the mob almost _50 yards_ away from the priest's location before the spell broke. In this example, his NPC is out of range for a full five seconds.

**New source - original upload [June 2005](https://web.archive.org/web/20051025114522/www.warcraftmovies.com/movieview.php?id=2740):**
https://www.youtube.com/watch?v=cQ3gkWbnNnM (see 2:46 for the best example of this behaviour)

~~Best as I can tell from this video and others (I can provide a few more sources if you want them), is that the intended behaviour is for there to be a random leeway between 2-5 seconds that starts once you step out of range.~~

**EDIT:** After reviewing [this 3rd video](https://www.youtube.com/watch?v=WN-xySlgzQI) at 2:25, I believe the above to be slightly incorrect. The mind control appears to last the full duration here, even though the target is clearly out of range as you can tell from the Mind Control button on his action bar once the spell breaks. It appears that Mind Control should simply have a much higher chance to break once you step out of range (though it appears to always last _at least_ 2 seconds after going out of range), scaling with how far out of range you go. Not only that, but it appears "out of range" doesn't mean outside of the normal 20 yards. All spells have some leeway, in which you can still finish casting the spell even if the target goes out of range, by at most approximately 20% of the original max range. I believe this "bonus" range is what's considered out of range for the extra chance to break to start counting down.

Repro (Nighthaven 1.5):
1) Mind Control any NPC or player at the edge of your Mind Control range.
2) Step slightly outside your Mind Control range. Note that the channel is cancelled instantly.

**Comment by Terranzin** [comment]
The problem I have with the video is that it was released Februari 2006, the patch we´re on came out July 2005. If you have more sources please send them our way and we´ll investigate futher - but please use sources that is around the same patch.

**Comment by Inomares** [comment]
@Terranzin In July 2005, youtube was half a year old, and according to my search query there existed exactly six videos with the keywords "world of warcraft" on youtube at that time. My source is only a few months after our patch, and there is no mention of any relevant changes to mind control or channeling in patch notes throughout all of vanilla.

**Comment by Inomares** [comment]
https://www.youtube.com/watch?v=WN-xySlgzQI Here's one a bit closer, dec 2005, where you can see the mind control persist for a few seconds after jumping off.

**Comment by Inomares** [comment]
Hey, good news. Found a source from June 2005:
https://www.youtube.com/watch?v=cQ3gkWbnNnM (see 2:46 for the best example of this behaviour)
This video was originally uploaded to Warcraftmovies at 2005-06-17 [(proof)](https://web.archive.org/web/20051025114522/www.warcraftmovies.com/movieview.php?id=2740)

Will add it and some more info I found to the OP.
