### ISSUE TITLE
Incorrect kill criteria for quest "Job Opening: Guard Captain of Revantusk Village"

### ISSUE THREAD

**Issue by Inomares** [elysium-project/bug-tracker#450]
The quest "Job Opening: Guard Captain of Revantusk Village" (id 7862) should require you to kill 20 of each mob, not 5-10. The quest requirements were not lowered until patch 2.3

Sources:

- https://web.archive.org/web/20060614155851/http://thottbot.com:80/?qu=7862 Thottbot ca 2006
- https://web.archive.org/web/20060525194738/http://wow.allakhazam.com:80/db/quest.html?wquest=7862 Allakhazam ca 2006. **The key in this one is the comment from June 2005:** "80 elite trolls is a hell of a lot" showing that this was the case even back in mid 2005.
- http://www.wowhead.com/quest=7862/job-opening-guard-captain-of-revantusk-village#comments:id=4026:reply=330912 Note the comments, some mentioning the requirements were not lowered until 2.3

Repro (Nighthaven 1.5):
1) Have a level 46+Horde character
2) Go to Revantusk Village in The Hinterlands
3) Interact with the "Call to Arms!" billboard and accept the quest. Note that it only asks that you kill 10/5/5/5 trolls instead of 20 of each.

**Comment by YaboyJimmyrustle** [comment]
This issue was marked as duplicate, which was incorrect as it focuses on a different potential problem with the quest criteria. I am removing the "Duplicate" label and marking it as "Confirmed" based on the sources you have provided. Thank you!
