### ISSUE TITLE
Rare NPC - No Loot

### ISSUE THREAD

**Issue by bk187** [elysium-project/bug-tracker#452]
Huricanian in Silithus drops no loot, should have guaranteed drop at least 1 green item.

**Comment by bk187** [comment]
What do you mean Report Incomplete? Go and check it out yourself, rather than ignoring bugs like this.. it doesn't help the server.

**Comment by Navashed** [comment]
Confirmed.

Huricanian (NPC 14478) is missing the standard green/blue/epic gear drops that rares normally have:
![6a78a7a1399270c37127d56be5499386](https://user-images.githubusercontent.com/2709545/36634308-91c0e81a-1970-11e8-9524-47d19cf42f09.png)

Correct loot table: https://web.archive.org/web/20070813021328/http://www.thottbot.com:80/c14478

**Comment by Egregious** [comment]
Also Barnabus in Badlands seems to have an issue with his loot table.
