### ISSUE TITLE
Bugged lashers in DM:E

### ISSUE THREAD

**Issue by regalz** [elysium-project/bug-tracker#455]
So, i was doing my regular farm in DM:E, but whats happening lately is that when you pull the packs (i always start in the southeast entrance), sometimes on or two of the mobs stays behind, and it can end up aggroing the patrols, thus making the farm way slower or even killing you if you are not paying attention. that happens more with the 2 packs on the top floor, but ive seen also happening with one of the 4 packs below.

**Comment by Navashed** [comment]
I was not able to replicate this issue on the Whip Lasher packs near the southeast entrance of Dire Maul: East. The Lashers are linked to each other; they all respond instantly to one of them being pulled no matter how far apart they are.

Are some of the Lashers snagging on terrain and getting stuck? Is someone in your group standing on something and causing them to evade?

**Comment by regalz** [comment]
I got a screenshot of it but dont know how to post it here. And I was doing it solo as mage. Anyway, what happened was exactly what you said, one of them get stuck in the terrain for some time and evades (wanding for example). They dont aggro the patrols when stuck, but sometimes they auto unstuck without needing me to get close to it, so they can aggro when that happens.

**Comment by YaboyJimmyrustle** [comment]
A video of this happening would be ideal, but you can post pictures by just dragging and dropping them into the post.
