### ISSUE TITLE
Herod spawning Scarlet Myrmidons

### ISSUE THREAD

**Issue by Tonno1234** [elysium-project/bug-tracker#458]
Herod in Scarlet Monastery spawned 4  Scarlet Myrmidons after entering Combat with him around 22:40 Server Time 20/02/18
Group Involved;
Tonno
Lasskicker

**Comment by Navashed** [comment]
Herod spawns 4 elite mobs in the hallway behind him when he's pulled. This is to force everyone into his room and to prevent players from kiting Herod throughout the Monastery.
