### ISSUE TITLE
Quest: Another Message to the Wildhammer - NPC not offering quest

### ISSUE THREAD

**Issue by fulzamoth** [elysium-project/bug-tracker#459]
**Summary**
The quest _Another Message to the Wildhammer_ should be offered by Otho Moji'ko in Revantusk Village, but the NPC does not offer the quest. 

**Details**
* _Another Message to the Wildhammer_ was added in Patch 1.5 is in Vanilla (Ref: http://wowwiki.wikia.com/wiki/Quest:Another_Message_to_the_Wildhammer).
* Otho has a yellow exclamation point above him, indicating a quest is available, but the quest is not offered (see screen shot) when talking to the NPC.
* Clearing WDB cache does not fix the issue.
* Logging in and out does not fix the issue.
* Screenshot: ![2018-02-20 at 6 01 pm](https://user-images.githubusercontent.com/26393979/36454208-f832ae54-1668-11e8-80dd-2298902acf7c.jpeg)

**Comment by YaboyJimmyrustle** [comment]
I was able to talk to the NPC, click the quest gossip link, and accept the quest. It should be functioning correctly.

![screen shot 2018-02-24 at 1 39 58 am](https://user-images.githubusercontent.com/36592168/36628910-dc5b7ac4-1903-11e8-94f2-107549da67e2.png)

![screen shot 2018-02-24 at 1 40 24 am](https://user-images.githubusercontent.com/36592168/36628911-dc76849a-1903-11e8-9976-93e610a23228.png)

**Comment by fulzamoth** [comment]
Wrong quest. It's **_Another_ Message to the Wildhammer** I'm referring to.

**Comment by YaboyJimmyrustle** [comment]
My mistake. I went back, completed "Message to the Wildhammer" and was able to see, accept, abandon, and re-accept "Another Message to the Wildhammer" just fine. Seems to be Functioning properly.

![another message to the wildhammer](https://user-images.githubusercontent.com/36592168/36637165-9e369094-198a-11e8-807f-a2c784a32bf0.png)

**Comment by Sarisean** [comment]
I have exactly the same problem. I abandoned "Another Message to the Wildhammer" and now I can't re-accept it even if Otho has a yellow exclamation point above him.

**Comment by Terranzin** [comment]
Can´t be reproduced on PTR. Might be difference between Nighthaven and PTR? @shenna-elysium needs to look into this.

**Comment by shenna-elysium** [comment]
Can't reproduce, really. Same on NH.
