### ISSUE TITLE
Quest: The Legend of Korrak (not completing) 

### ISSUE THREAD

**Issue by LordZuckuss** [elysium-project/bug-tracker#462]
I have killed Korrak twice now. The first time I just thought I might not of gotten credit, so I joined another AV and I'm confident we killed him and I was right next to him. Screenshot attached. 

When I try to turn the quest in, it states it is complete, but when I select the reward (bow) it doesn't actually complete. (it does make the sound like a completed quest though)

Hoping someone can help me fix the quest so I can actually turn it in and snag them treats. 

Thanks 

![screen shot 2018-02-21 at 8 34 52 pm](https://user-images.githubusercontent.com/35251432/36515430-5801831c-1747-11e8-8962-bc1cff6d4deb.png)

**Comment by sidsukana** [comment]
Can't confirm. I complete quest with Warmaster Laggrond without problems.
