### ISSUE TITLE
The Test of Skulls, Chronalis Quest is bugged

### ISSUE THREAD

**Issue by Zeduce** [elysium-project/bug-tracker#464]
Need GMs help. The Test of Skulls, Chronalis Quest is bugged for me. Says it have it in my quest log but I dont. I have abandon all Qs in my log and still it says I got it. Did the other 2 quests without a problem but this one has totaly bugged out. Please help!

**Comment by YaboyJimmyrustle** [comment]
I attempted to replicate the circumstances, but I was able to accept and abandon the quest as many times as I needed. Is there any other information you can provide that may have also contributed to this issue?

Alternatively, if you haven't already, you should try exiting game and deleting your WDB folder.
