### ISSUE TITLE
Disgusting Oozling Vanity Pet Cosmetic Issues

### ISSUE THREAD

**Issue by Aaron182** [elysium-project/bug-tracker#466]
It seems that when you have your ooze summoned and your player is turned green, that you cant mount up without it taking away the green effect. In theory it should keep you green and make your mount green as well, but this isn't the case. Can we fix this :) I love that pet so much and I would love to see it working 100%. :)

**Comment by Navashed** [comment]
The green aura did not apply to mounts in Vanilla. Proof in comments: https://web.archive.org/web/20070510133009/http://www.thottbot.com:80/i20769

"Mounting / snowmaning / illusioning etc w the pet out will cancle the green effect but still leave the debuff as well as the pet."

"Tip:  Turn your pet on, then mount and dissmount.  This makes the green color on you go away!  You are still effected by the pets debuffs but at least your not green.  :P  Screenshot here. "

I actually remember the latter bug.
