### ISSUE TITLE
Hunter's pet  does not gain experience

### ISSUE THREAD

**Issue by gimly666** [elysium-project/bug-tracker#467]
at the moment when the pet reached my level he stopped getting experience, and the scale of the experiment stands still (its value is 0)

**Comment by gimly666** [comment]
what should i do? support team help me please

**Comment by YaboyJimmyrustle** [comment]
In order for your pet to gain experience, you must be at least one level above it. When you and your pet reach the same level your pet will stop gaining experience until you reach the level above it, in which event your pet will resume accumulating experience again. This is functioning as intended.

**Comment by gimly666** [comment]
oh, thanks... now i understand.
