### ISSUE TITLE
T1 stats of mage are wrong

### ISSUE THREAD

**Issue by Effi28** [elysium-project/bug-tracker#468]
Arcanist Crown should have 20 Spelldmg and 1% hit (https://classicdb.ch/?item=16795) 
Arcanist Mantle should have 14 Spelldmg instead of 11 frost dmg (https://classicdb.ch/?item=16797)
Arcanist Robes should have 23 Spelldmg instead of 16 (https://classicdb.ch/?item=16798)
Arcanist Bindings should have 12 Spelldmg instead of 6 and also more mp5 (https://classicdb.ch/?item=16799)
Arcanist Gloves should have 14 Spelldmg instead of 0. (https://classicdb.ch/?item=16801)
Arcanist Belt should have 14 Spelldmg instead of 9. (https://classicdb.ch/?item=16802)
Arcanist Leggings should have 20 SP instead of 14 Frost dmg. (https://classicdb.ch/?item=16802)
All of the parts also have also different int/stamina/spirit  values according to classicdb.

On wowiki.com is says that mage t1 is only update once (in patch 1.5) 
http://wowwiki.wikia.com/wiki/Arcanist_Regalia

**Comment by sidsukana** [comment]
https://wow.gamepedia.com/index.php?title=Arcanist_Regalia&diff=next&oldid=92007

Diff on Patch 1.9.
