### ISSUE TITLE
Incorrect stats on ring

### ISSUE THREAD

**Issue by furyen** [elysium-project/bug-tracker#47]
Hi,
I got this quest reward ring https://i.imgur.com/hEOsObh.png

When I equip it though I don't get the stats it says I should but I get 2 stamina and 5 spirit only. GMs directed me here. Can you help?
Character name - Prychka
Thanks

**Comment by Yetigamer** [comment]
Hi,
I got this quest reward ring https://i.imgur.com/hEOsObh.png

When I equip it though I don't get the stats it says I should but I get 2 stamina and 5 spirit only. GMs directed me here. Can you help?
Character name - Hirim
Thanks

**Comment by anaydenovGH** [comment]
Hi,
I got this quest reward ring https://i.imgur.com/hEOsObh.png

When I equip it though I don't get the stats it says I should but I get 2 stamina and 5 spirit only. GMs directed me here. Can you help?
Character name - Hirim
Thanks

**Comment by twink** [comment]
It's not a bug , clean your WDB folder. In 1.2 this ring gives 2 stamina and 6 spirit.
