### ISSUE TITLE
Grounding totem has too much delay when i put it down

### ISSUE THREAD

**Issue by rawane007** [elysium-project/bug-tracker#470]
when i drop grounding totem it shold work instantly but its like 1 too 1 and a half sec coldown on it kinda fuks up alot for a shaman

**Comment by Navashed** [comment]
Confirmed.

There is about a 3/4 of a second delay before the Grounding Totem Effect buff (Spell 8178) applies to the player after casting Grounding Totem (Spell 8177). This delay has unfortunate implications for PvP.

Other totems tested did not have this problem.

**Comment by shenna-elysium** [comment]
Fixed for now, but I really need some sort of video from 2004; just to make sure there's no delay.

**Comment by shenna-elysium** [comment]
Nevermind.

**Comment by rawane007** [comment]
LOL

**Comment by rawane007** [comment]
https://www.youtube.com/watch?v=ja1j7xWpB3w&feature=youtu.be&t=463
