### ISSUE TITLE
Alterac Valley mount should cost 10g

### ISSUE THREAD

**Issue by Mumfo** [elysium-project/bug-tracker#473]
https://classicdb.ch/?item=19030#comments
The database has it as 10g. It was never 100g back in Vanilla.

**Comment by Navashed** [comment]
Confirmed.

Evidence in comments:
https://web.archive.org/web/20070322120248/http://www.thottbot.com:80/i19030

**Comment by Rubmywrinklz** [comment]
any plans to change it?

**Comment by Oshskiymarader** [comment]
So you fixed it, But where is my 71g ? :)

**Comment by Wrath669** [comment]
Has this been implemented yet? I see comments on #510 saying it is showing the lower price for them, but the Horde version is still appearing as 90g for me. 
![av mount](https://user-images.githubusercontent.com/36385529/37289483-aa0ef720-2601-11e8-8ac8-01fffef514eb.JPG)

**Comment by Wrath669** [comment]
Frostwolf Howler was ignored in Development Update 11.04.2018  and only the Altrac Battle Charger was fixed.
