### ISSUE TITLE
Truesilver key is glitched

### ISSUE THREAD

**Issue by Kamebos** [elysium-project/bug-tracker#474]
I had four keys in my  keyring, the scarlet monastery key, gold blacksmithing keys, a silver blacksmithing key and the gnomergan key. When I make a truesilver key it does not appear in my inventory or in my keyring. The item appears to go into my main backpack when I create it, but I cannot find it in there.

**Comment by Kamebos** [comment]
Looking at it further, it looks like the keyring is fine and the creation of truesilver keys is the problem. I make them and they do not show up in my inventory.

**Comment by Navashed** [comment]
Truesilver Skeleton Key (Item 19668) behaves correctly for me. It was crafted correctly and went into my keyring without any issues.
