### ISSUE TITLE
Critchance displayed as 0.00%

### ISSUE THREAD

**Issue by Neciss** [elysium-project/bug-tracker#475]
I've noticed that my critchance in the spellbook is displayed as 0.00% for melee. Also the addon "Theorycraft" is showing 0.00% for melee and 5% for ranged which comes from the talents (playing Hunter).

I've tried multiple relogs and deleted the WDB and WTF folder.  I also tried to put my items in the inventory and dress up back. All the stats are showed correctly except for the critchance which keeps staying at 0.00%.

I'm not sure yet if it is has repercussions on my "real" critchance. Although it is probably a display bug, I can't compare stuff properly anymore, since I've no idea what is my critchance.

I've noticed it today. Few days ago it worked properly for sure. No new addons were installed. Theorycraft worked also fine. I've also tried to delete it, no results. On my second Char it is showed correctly using same addons.

**Comment by Navashed** [comment]
Is your weapon skill low? I see this behavior on some of my characters and I think it reflects their weapon skill.

**Comment by Neciss** [comment]
You are fully right. My fault. Feeling kind of dumb. Sorry for the inconvenience.
