### ISSUE TITLE
Searing Totem (nighthaven: spell)

### ISSUE THREAD

**Issue by Firestoat** [elysium-project/bug-tracker#48]
Spell link - http://db.vanillagaming.org/?spell=3599

Issue - When dropped, it immediately begins attacking the nearest hostile (red) or neutral (yellow) mob to the totem. This behavior is incorrect - the totem should only attack the nearest hostile (red) mob to the totem until the target is killed, and then it attacks the next nearest hostile (red) mob until its duration runs out.

Apologies for the vanilla gaming link. Information for the spell is available in-game from its tooltip to display that it attacks Enemies only. This bug WAS fixed on Valkyrie back in 2012.

**Comment by Terranzin** [comment]
I´ve reviewed your issue. The Searing totem does in matter of fact attack neutral mobs when it should just attack those who are a enemy of you (hostile). 

Thanks for reporting!

**Comment by twink** [comment]
Fixed all damaging totems behavior, now their first priority is owner target and if owner doesn't have a target, then totem will try to select a victim by itself, but now it will be only hostile targets, not neutral.
