### ISSUE TITLE
Verify for Patch 1.6: Nefarian LOS

### ISSUE THREAD

**Issue by fulzamoth** [elysium-project/bug-tracker#480]
Players should not be able to LOS Nefarian's Shadow Flame by standing in the caves / behind the throne.

**Comment by shenna-elysium** [comment]
@Terranzin Beep!

**Comment by Rubmywrinklz** [comment]
this was a strategy that worked on LIVE servers since forever.

**Comment by fulzamoth** [comment]
Correct - this "bug" has existed since Vanilla, and should probably remain in place.
