### ISSUE TITLE
Cromatic sword is not glowing like it should

### ISSUE THREAD

**Issue by Soldrax** [elysium-project/bug-tracker#487]
Hello so I got the chromatic sword yesterday and I noticed it's not working as it should the problem is that the sword is not glowing 
Here is a picture what it should look like https://gyazo.com/dfd06c20c17a1104eee2f569416bef93
and on the elysium server its not glowing at all

**Comment by Navashed** [comment]
Chromatic Sword (Item 1604) did not glow in Vanilla.

Sorry about that.

https://classicdb.ch/?item=1604#comments

**Comment by Terranzin** [comment]
Soldrax, We already replied to you in earlier issue that it´s in later versions.
https://github.com/elysium-project/bug-tracker/issues/483
