### ISSUE TITLE
Items not appearing in Chat

### ISSUE THREAD

**Issue by Espinouge** [elysium-project/bug-tracker#488]
Hi,

Started playing a few days ago (Nighthaven 1.12.1), loving the server but today an issue started popping up where certain 
things are not appearing in the General Chat log that should be.

New members joining the guild, friends coming online, party invites being declined, these things are not showing up in the chat however the corresponding sounds are. I've tried everything I can think of from looking at filters on the chat to resetting all settings to default.

Just wondering if you can help

**Comment by Terranzin** [comment]
I havent noticed this error on our PTR-server. Do you use any kind of addons, fonts that has with your chat to do? Try disable all addons and clear your WDB folder, does the problem still occur?

**Comment by Espinouge** [comment]
Hi,

I don't use any addons no, and what are the ramifications of clearing the
cache? I created another character and the issue is not with this new Char.

Thank you for the quick response as well

Liam

**Comment by Terranzin** [comment]
Have you tried clearing your WDB folder?

**Comment by Espinouge** [comment]
Hi, yeah but still not working

**Comment by shenna-elysium** [comment]
Please try to delete "World of Warcraft \WTF\Account\**YOURCCOUNTNAM**E\Nighthaven\**YOUCHARACTERNAME**\chat-cache.txt" file. This will resolve your problem.
