### ISSUE TITLE
Quests: Plagued Lands bugged, bear not being trapped

### ISSUE THREAD

**Issue by AlexHurd** [elysium-project/bug-tracker#489]
I tried multiple times to get this damn bear trapped. I approached one of the rabid thistle bears, laid down the trap, aggro'd him, and made him walk right over the trap, but the trap didn't work. The bear did not turn friendly like it's supposed to--it just kept attacking me. This has happened every time I tried it.

**Comment by zinbalu** [comment]
Why is this closed without resolution? How is the quest completed or it is bugged?

**Comment by AlexHurd** [comment]
So it wasn't working at first like I said, but when I abandoned the quest and accepted it again, it finally worked. That's why I closed this.

**Comment by Alkimor** [comment]
First need pull Bear, after need use quest item
