### ISSUE TITLE
Korrak does still spawn after 2h

### ISSUE THREAD

**Issue by karni186** [elysium-project/bug-tracker#491]
Korrak is still spawning after 2h and not after 30 Minutes

**Comment by Terranzin** [comment]
We´re sorry for wrong confirm from the QA staff. Our admins has looked into the issue and reverted the issue back to 2 hours after checking up more indepth what his actual timer was set back in retail vanilla (with the help of wayback machine site). He´ll stay with a 2 hour spawn timer.
