### ISSUE TITLE
NEED ROLLING on AV rare drops from bosses should be bannable offense. 

### ISSUE THREAD

**Issue by Rubmywrinklz** [elysium-project/bug-tracker#494]
I would like to suggest that need rolling on loot you cannot possibly benefit from, from one of the AV summonable bosses should be a bannable offense. It is akin to griefing and should be treated as such. 2nd time a rogue has need rolled on the spell damage and intellect ring and won it. This kind of behavior should never be tolerated.

**Comment by shenna-elysium** [comment]
Please move the suggestion to our forums. Here we can't really discuss such things. Thank you.
