### ISSUE TITLE
Cut scene quest "Set Them Ablaze!"

### ISSUE THREAD

**Issue by Sarisean** [elysium-project/bug-tracker#496]
Hello,
The cutscene at the end of the quest "[Set Them Ablaze!](https://classicdb.ch/?quest=3463)" is missing on this server. I did not find a video showing this but [the transcript on WowWiki](http://wowwiki.wikia.com/wiki/Quest:Set_Them_Ablaze!) is pretty good I think. 
For the moment, you finish the quest and nothing happen.
More than just adding some lore and some immersion to the game, this cutscene is also important to notice that a chest had spawned and what to do to find the next quest in the Burning Steppes.
Moreover, the chest giving the quest [Trinkets...](http://wowwiki.wikia.com/wiki/Quest:Trinkets...) should spawn during this cutscene. On the server i believe that it is always spawn near the npc.

**Comment by Thenari** [comment]
yeah i never knew that chest became lootable, on my main I still never opened that chest.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40107208-9fbe3d0c-58c5-11e8-937b-a2d5d4597cf4.png)

quickly did the whole quest chain on ptr

tried looting the chest pre quests and only after set them ablaze was i able to loot it
