### ISSUE TITLE
LUPOS

### ISSUE THREAD

**Issue by SuperHeroesAlwaysdie** [elysium-project/bug-tracker#498]
Hi there

The current patch is 1.12 adapted in 1.5 currently ,right? (or 1.4 , that doesnt matter here)

So here is my question:

Why lupos still deal shadow dmg ?
(while it was a bug fixed in AQ patch... it s like u let another broken hability to some other class like rogue)

I hope hunters aren't gonna flood here :)

**Comment by Inomares** [comment]
They are not fixing bugs with abilities until their corresponding patch. (I don't personally agree with it, I'm just letting you know.)

**Comment by bk187** [comment]
Whoever levels Lupos from 23 to 60 deserves to have it imho lol

**Comment by shenna-elysium** [comment]
Lupos won't deal any shadow damage once NH is running on 1.9 patch.
Could be reconsidered but doubtfully. Please make a suggestions on our forums instead.
