### ISSUE TITLE
No pet abilities or spellbook

### ISSUE THREAD

**Issue by fytro** [elysium-project/bug-tracker#5]
Hello. I need some help with my pet problem. When i hitted lvl 10 i tamed a boar, the pet had spellbook and abilities. I then went and got a place in the stable and turned the boar in, i tamed a new pet a cat and the problem started there! The cat did not have any abilities or spellbook. So i went back to the stable master and traded the cat for the boar, the boar had spellbook. so i abonded the boar took out the cat and is still the same problem. I then abonded all the pets, went out to the WDB folder deleted it and logged in again. I tamed a raptor but it was still the same problem. Can u guys help me ? i am the only one with this bug!!!

**Comment by fytro** [comment]
The GM told me to write this issue here

**Comment by fytro** [comment]
really fixed ? i dont think so

**Comment by fytro** [comment]
I have only 1 abilties on my pet and that is cower, and i should have growl cower claw but i dont. and as soon as i tame another one the spellbook disappeares!

**Comment by Terranzin** [comment]
Could you please supply me with the following information:
- Level when you tamed the cat
- The zone your tamed it in, also exact name of the "cat" - before you renamed it.
- Your race

**Comment by Terranzin** [comment]
Use-case:
- Started a new character (troll)
- Leveled up to 12
- Did the quest chain of 6082 (Taming the beast) for hunter.
- Went to Crossroads to tame "Savannah Huntress" (Id:3415)
- No skills required for the cat.

Do notice: Savannah huntress should not start with prowl.

**Comment by cemak** [comment]
Fix npc id 3415

**Comment by shenna-elysium** [comment]
https://github.com/elysium-project/server-staging/commit/17e4902cf87f280cda7b919ff18366f35f836585

**Comment by Hubreeze** [comment]
Leveled up to 10 on orc hunter on Nethergarde no feed pet or other pet abilities, only have tame and call pet
