### ISSUE TITLE
Mark of Flames in LBRS text error.

### ISSUE THREAD

**Issue by Midnatt** [elysium-project/bug-tracker#50]
Mark of Flames should be fire damage taken, not given. 

![mark of flames](https://user-images.githubusercontent.com/18221811/32915106-18784e2c-cb18-11e7-9763-2506e6a85459.png)

**Comment by Terranzin** [comment]
I´ve reviewed your issue, the text on spell ID: 15128 is correct, but the tooltip that appears as a debuff on the player is incorrect.

**Comment by twink** [comment]
It's not a bug. Such things from tooltip - clientside.
