### ISSUE TITLE
Чернокнижник - Талант "Improved Drain Life"

### ISSUE THREAD

**Issue by epicbaron** [elysium-project/bug-tracker#503]
Доброго времени суток!
Огромная просьба перепроверить на работоспособность данный таланты у Чернокнижников "Improved Drain Life". 
Даже при вложении 5 очков, совершенно не ощущается прибавка в 10% к умению скила.
Такие аддоны как SCT (scroll combat text), не фиксируют прибавку от таланта, только отображаемые базовые значения от самого скила "Drain Life"
Делаю вывод, что талант не работает.
_______________
Спасибо!

**Comment by sidsukana** [comment]
Наконец-то репорты на русском)

**Comment by sidsukana** [comment]
Могу сказать что у этого таланта самый стандартная аффект система и это значит что он 100% работает. Пусть тестеры проверят.

**Comment by Egregious** [comment]
In the future, please post in English.

**Comment by Navashed** [comment]
The talent works.
