### ISSUE TITLE
Graveyard master doesnt Revive me 

### ISSUE THREAD

**Issue by Dimitrakoc13** [elysium-project/bug-tracker#504]
Ok so ive been playing for a couple of days and while my friend can revive anytime he wants, the only way for me to revive is to run back to my corpse. When i press the revive button, the gravekeeper just makes an animation, but then nothing happens. 

Character name: Relegand

**Comment by Terranzin** [comment]
Where does this happen? All gravekeepers or just a certain?

**Comment by Dimitrakoc13** [comment]
All of them, still have the issue

**Comment by shenna-elysium** [comment]
Please make an in-game ticket.
