### ISSUE TITLE
Alterac Valley battle charger issue!

### ISSUE THREAD

**Issue by Oshskiymarader** [elysium-project/bug-tracker#510]
Hello. So i bought that mount (Stormpike battle charger) about 4-5 days ago FOR 81g, and now its price only 8g10s. Tell me please, what the heck is that :)

**Comment by Navashed** [comment]
#473

**Comment by Oshskiymarader** [comment]
???

**Comment by Oshskiymarader** [comment]
Why you closed this thread ?
