### ISSUE TITLE
Job opening: Guard Captain of Revantusk Village Bug

### ISSUE THREAD

**Issue by Sagounet** [elysium-project/bug-tracker#512]
While doing this quest my quest log showed a higher number of mobs killed compared to the needed amount. (11/5 for ex). Then the npc didn't validate the quest, wich was completed in my quest log.

**Comment by Sagounet** [comment]
Ok thx for the info



Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Inomares <notifications@github.com>
Date : 03/03/2018 15:21 (GMT+01:00)
À : elysium-project/bug-tracker <bug-tracker@noreply.github.com>
Cc : Sagounet <Sagounet@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [elysium-project/bug-tracker] Job opening: Guard Captain of Revantusk Village Bug (#512)


The needed # of mobs was recently changed and you probably need to delete WDB & cache folders for it to display correctly.

**Comment by Terranzin** [comment]
Already got it answered by another. Closing the issue
