### ISSUE TITLE
Characters missing

### ISSUE THREAD

**Issue by siath** [elysium-project/bug-tracker#513]
recently returned to the server. Log in and see nighthaven with 1 character. join the server no character to be found i had a lv 42-44 warlock undead named siath also guildmaster Afterquest..

**Comment by siath** [comment]
any help getting my character back would be awesome takes a long time for me to get that lv again. but i have been gone it said fresh start server on the main page. did we get reset again while i was away.

**Comment by Terranzin** [comment]
The server "Nighthaven" is a new progress-server, if this Character was before the server existed and your character is from one of the older servers they are not available any longer since about 6 months now.
