### ISSUE TITLE
Druid talent "Omen of clarity" not working for my character

### ISSUE THREAD

**Issue by Pherona** [elysium-project/bug-tracker#514]
Hello.

I recently specced my druid (Pherona) into Feral with the balance talent "Omen of clarity".

Started noticing something was wrong as I could not recall getting a single proc on omen of clarity. 
I started grinding mobs for a while to verify. I have been keeping close track of my buffs and energy consumption and  and after killing now hundreds of mobs it has not procced one single time. 

Other druids say that it's working fine for them but for me it's somehow not working.

**Comment by YaboyJimmyrustle** [comment]
Keep an eye on your combat log to see if you gain clearcasting. As of right now I'm able to verify it is proccing in all form correctly on PTR.
