### ISSUE TITLE
Druid Quest: Lessons Anew - wrong quest text

### ISSUE THREAD

**Issue by frozenice-xx** [elysium-project/bug-tracker#516]
There is a wrong quest text. Going as a Night Elf Druid to Dendrite Starblaze first you see a text about the Barrens (wich is obviously for Horde). On the next page he asks you to collect water in Darkshore...

**Comment by Navashed** [comment]
Confirmed.

The Alliance version of Lessons Anew (Quest 6121) is displaying the Horde completion text.

The correct completion text:
>Greetings young <class>, I'm glad to see you ready and eager to learn about the curing of poisons.

>While most <class>s in the past were put through pre-planned trials, your work will involve no such thing. There has been a rash of animal poisonings in Auberdine, and the village there has been unable to cure it. To that end, a representative there has asked Moonglade for aid and we are sending you there to aid them. This is no exercise - the work you'll do is quite real. Bear this in mind.

https://web.archive.org/web/20090321024803/http://thottbot.com:80/q6121
