### ISSUE TITLE
Keeping Pace quest bug

### ISSUE THREAD

**Issue by taistotatti** [elysium-project/bug-tracker#517]
Keeping Pace quest in 1k needles, shimmering flats requires "a quest in quest" to create a distraction. This quest in quest is called Zamek's Distraction. When accepting the quest the quest giver is supposed to create distraction so the played charecter can go and loot a quest item. The Zamek's Distraction says complete but Zamek doesn't do anything so the mob guarding the quest item doesn't move and quest item is unlootable thus Keeping Pace can't be completed.

**Comment by Lightsockie** [comment]
Seconding bug'd quest.

Keeping Pace: https://classicdb.ch/?quest=1190
Zamek's Distraction: https://classicdb.ch/?quest=1191

**Comment by Supersagee** [comment]
Just tried this today. Still bugged

**Comment by Navashed** [comment]
Confirmed.

Zamek's Distraction (Quest 1191) is no longer working. See previous ticket for more information (#115).
