### ISSUE TITLE
Character missing 

### ISSUE THREAD

**Issue by Embiid90** [elysium-project/bug-tracker#518]
The weirdest thing happened. I was playing today with no issues. Then a few hours later I logged in and my character was missing. When my guildies look in the guild list it is still there, so it is not deleted. It just somehow moved from my account. I wrote a ticket as well but got no response.

**Comment by shenna-elysium** [comment]
Please check if you aren't connected to Player Test Realm.

Please write an in-game ticket for a faster response from the GM team.
