### ISSUE TITLE
Дух Гепарда

### ISSUE THREAD

**Issue by Arkyenon** [elysium-project/bug-tracker#52]
Добрый Вечер. Не корректно работает талант Дух гепарда. Прокачал талант на увеличение скорости бега в духе на 3%. А отображает все равно 30%.

**Comment by Terranzin** [comment]
I´ve reviewed your reported issue. I´ve ran a couple of marathons now with Aspect of the cheetah (id: 5118) and Aspect of the pack (id:13159) without the talents. I´ve attempted to do the exact same run pattern both with 1/2 (3%) and 2/2 (6%) and the speed does not increase, the time it takes to go from one place to another is exact same with both aspects with or without the increased speed talent. 

PS: Try report issues in English if possible, had to use a translator, thanks!

**Comment by Arkyenon** [comment]
https://vk.com/elysiumwow
"Уважаемые игроки! Рады сообщить, что наша команда растёт, и в связи с активной разработкой сервера, нам нужна ваша помощь — сообщайте нам о любых проблемах связанных с игрой на наших игровых мирах: для этого воспользуйтесь нашим баг-трекером https://github.com/elysium-project/bug-tracker (нужна регистрация аккаунта, если его у вас нет). Репорты можно писать на русском языке, снова! Приятной игры и увидимся в Азероте"

my english is realy bad )))

**Comment by shenna-elysium** [comment]
Со следующим апдейтом (сегодня вечером) будет поправлено :) Спасибо за репорт.

**Comment by Arkyenon** [comment]
К сожалению ни чего не изменилось.... Не могли бы Вы еще раз проверить ?!

**Comment by twink** [comment]
Отображать так и будет 30%, но теперь талант работает корректно, увеличивает скорость.
Отображение - часть клиента, пакет отправляется корректно.
