### ISSUE TITLE
Quest: Fragments of the Past

### ISSUE THREAD

**Issue by MiticoPalla** [elysium-project/bug-tracker#522]
Hi,

in this quest you have to find a world object called "Dire Pool" and use the empty bottle near it. The "Dire Pool" is located at the left end of the T corridor in the entrance of Dire Maul.

This pool exists, but it's invisible. I was able to fill the bottle but it should be visible, you can see the screenshot in the provided link here for reference:
http://www.wowhead.com/quest=5247/fragments-of-the-past

**Comment by YaboyJimmyrustle** [comment]
Found the quest and found the spot. Here is a picture to confirm collecting water from an invisible pool. Thanks for the report.

![gathering water from invisible pool](https://user-images.githubusercontent.com/36592168/37203445-83fbbfb2-2342-11e8-85d8-424b66ade985.png)

**Comment by sidsukana** [comment]
Visible now, closed
