### ISSUE TITLE
BUG [Felheart Belt] 

### ISSUE THREAD

**Issue by Hatmud** [elysium-project/bug-tracker#523]
This belt has bad characteristicshttps://www.photobox.co.uk/my/photo?album_id=5271405355&photo_id=500630475411

I should give these other

https://classicdb.ch/?item=16806 

No patch appears. Also if it was a skill to use, it would work. In fact it does not work when you press to increase the damage

**Comment by Terranzin** [comment]
It´s already been fixed, clear your WDB folder.

See following issue: https://github.com/elysium-project/bug-tracker/issues/430
