### ISSUE TITLE
Master of Elements, firemage

### ISSUE THREAD

**Issue by mendenie** [elysium-project/bug-tracker#524]
Hello,

The Talent Master of Elements in fire tree tree isn;t working 100% correctly.
For example, im 45 mage ATM, Level 1 2 and 3 scorch do return the mana correctly, but now rank 4 does not.

I also notice that i dont get returns on Flamestrike for sure, blast wave i haven't tested fully yet.

Thanks

**Comment by Navashed** [comment]
Unable to reproduce.

Scorch Rank 4 was observed returning mana:
![scorch4](https://user-images.githubusercontent.com/2709545/37223005-195fe420-239d-11e8-88e6-a49ad7a36407.png)
