### ISSUE TITLE
Winterspring Frostsaber wrongly priced

### ISSUE THREAD

**Issue by Xestarius** [elysium-project/bug-tracker#525]
The Mount Price of the Winterspring Frostsaber is wrong. It is still set on 1k gold instead of being set on 100g gold. The mount price and mount skill prices have been swapped earlier in a patch, so the price should be 100g for the Winterspring Frostsaber now instead of 1k gold

Screenshot attached to this thread.

![ss 2018-03-05 at 07 45 53](https://user-images.githubusercontent.com/37089434/37005414-3fa1ca16-20d4-11e8-81da-a15e91c18d3a.jpg)

**Comment by Navashed** [comment]
Confirmed.

Item 13086 - Reins of the Winterspring Frostsaber should cost 100g after mount-riding price swap. Currently 1000g.

![winterspring](https://user-images.githubusercontent.com/2709545/37224340-2426bd80-23a1-11e8-98a6-fa6f788f8740.jpg)

https://web.archive.org/web/20070312050430/http://www.thottbot.com:80/i13086
