### ISSUE TITLE
Clearcasting not procing properly

### ISSUE THREAD

**Issue by Bugreported** [elysium-project/bug-tracker#527]
In retail if you cast blizzard on 20 mobs there was a near 100% chance of clearcasting as it checked per monster hit.

On Nighthaven it seems to be a flat 10% no matter how many targets you hit, which heavily devalues the talent in aoe grinding, separating this server from retail quit a bit for mages.

Take this video for example where clearcasting is procing as it should be(per mob hit) on a 57 level mage with 4.7k mana who is farming BRD elite mobs:  https://www.youtube.com/watch?v=jxU7-iXyoAE

**Comment by Navashed** [comment]
That was a private server bug, not the correct Blizzlike behavior. It has been corrected on this server. For more information see the previous report. (#448)
