### ISSUE TITLE
Razorfen Kraul Bat - As a hunter pet

### ISSUE THREAD

**Issue by Catlynjenner** [elysium-project/bug-tracker#530]
Pretty sure it's been addressed before but here it is again.  Should act like a normal bat pet

How it acts now in-game:  Immune to all CC - stuns, sleep, roots, etc. So you can play marksman and have a pet that acts like a BM enraged pet 24/7, well just with the immunity to crowd control that is not with the enraged portion bonus that BM gives.

**Comment by Navashed** [comment]
Unable to reproduce.

Neither the Kraul Bat (Creature 4538) nor the Greater Kraul Bat (4539) are immune to slows, roots, or stuns whether tamed or not.

![nova](https://user-images.githubusercontent.com/2709545/37230248-c03e7ed4-23b4-11e8-869b-1795ba596f38.png)
![nova2](https://user-images.githubusercontent.com/2709545/37230270-d5bdb3e2-23b4-11e8-9d76-ba164f480303.jpg)
