### ISSUE TITLE
Cant learn riding skill in Darnassus as a NE 

### ISSUE THREAD

**Issue by gsannas** [elysium-project/bug-tracker#531]
I reached level 40 with the NE Druid Character and upon getting to Darnassus to learn the riding skill the trainer jartsam doesn't teach me anything and asks me for exalted reputation as if I was from another race!

 The name of the Char is Palemoon in Nighthaven PvP
![darn](https://user-images.githubusercontent.com/37144257/37091538-341a94aa-2211-11e8-902a-06d6e80ff5fe.png)

**Comment by YaboyJimmyrustle** [comment]
When talking to the NPC and looking at the filter in the upper right corner of the chat box, are any filter options deselected? You may not be able to see anything if the "Available" filter option is not checked. All filter options may be disabled in your particular case as it appears you're not seeing any skills available to you at all.

If what I have described is not the case, please comment again and I will look further  into what can be done.

**Comment by YaboyJimmyrustle** [comment]
After further investigation, I was able to train just fine as a night elf in Darnassus. Be sure to double check the filter to ensure you are seeing the correct training available to you.
