### ISSUE TITLE
Feign Death Not Working Properly

### ISSUE THREAD

**Issue by cajo3** [elysium-project/bug-tracker#532]
Server: Nighthaven PvP (patch 1.5)

Sometimes when casting Feign Death my character does not stay in the "dead position" and gets back up/stays up without moving or making any other action.  I discussed with other hunters and they are also having the same issue.

**Comment by YaboyJimmyrustle** [comment]
Can you give any more specific details on what you might have been doing at the time you attempted to feign death?

One of the tricky things about feign death a lot of players have noticed is the ability may function properly, **however**, if you hold the mouse button that changes the direction your character is facing, the character will move to look in that direction which will cancel out feign death. Your character will stand up to look in the direction you're indicating with the mouse, which is something to be aware of when feigning death.

If this is not the case, I would like to gather more information from you about the circumstances the ability is not functioning as intended.

**Comment by YaboyJimmyrustle** [comment]
After further review, I haven't noticed anything unusual about the feign death ability. It is functioning as intended.
