### ISSUE TITLE
Баг с отмычками.

### ISSUE THREAD

**Issue by Aziroth** [elysium-project/bug-tracker#535]
Здравствуйте, подскажите, такая проблема. Ключница была забита ключами, я сделал отмычки они скрафтились и неизвестно куда делись, в сумках нет, в ключнице нет. Освободил ключницу, скрафтил опять отмычки, и они опять хз куда делись. Как исправить баг?

**Comment by Aziroth** [comment]
Hello, tell me, such a problem. The clavier was crammed with keys, I made the master keys, they were scratched and it's not known where they went, there are not any in the bags, the housekeeper does not. I freed the housekeeper, I again made the master keys, and again they left. How do I fix a bug?

**Comment by Thenari** [comment]
umm, idk anything.

**Comment by drozdez** [comment]
I think, that was visual client side bug, cause there's no any movements from reporter for 3 months. So I can close this issue.
