### ISSUE TITLE
Dusty old tome despawning in DM:E

### ISSUE THREAD

**Issue by Tyjjoo** [elysium-project/bug-tracker#537]
There's a bugged, or despawning book in DM:E near the big tree in the south west corner. I can hover over the book, at times, but i cannot see it or interact with it.

**Comment by YaboyJimmyrustle** [comment]
Can you take a screen capture of where it is near this tree?

**Comment by Navashed** [comment]
A Dusty Tome (Object 179548) spawns in that area. I was not able to observe anything unusual.
