### ISSUE TITLE
Frostmane Trolls in Dun Morogh are tagged as speaking Gnomish instead of Troll

### ISSUE THREAD

**Issue by Lenivietz** [elysium-project/bug-tracker#538]
As the title indicates.

**Comment by YaboyJimmyrustle** [comment]
Thanks for the input! I guess we found some bilingual trolls.

![trolls language labelled as gnomish](https://user-images.githubusercontent.com/36592168/37201225-eb062032-233b-11e8-9a87-36657bd25be5.png)
