### ISSUE TITLE
Strigid hunter is not a beast and it is not tameable.

### ISSUE THREAD

**Issue by Hanzemon** [elysium-project/bug-tracker#539]
The beast "Strigid Hunter" in Teldrassil is not tameable and it doesn't appear in the minimap if you use [Track Beasts] spell. When you try to tame it, it says "invalid target"; the addon "mobinfo2" does not show its stats either.
![invalid target owl](https://user-images.githubusercontent.com/32701428/37198324-514ffa9e-2354-11e8-9a33-6134bf89b7c8.jpg)
![not a beast owl](https://user-images.githubusercontent.com/32701428/37198325-516e5b06-2354-11e8-99e5-290c605f0873.jpg)

**Comment by Navashed** [comment]
Unable to reproduce.

A cache clear will probably correct this issue for you. The server has the correct information.

![strigid hunter](https://user-images.githubusercontent.com/2709545/37233328-c14ff9fe-23c0-11e8-848c-f4bf0316f224.jpg)
