### ISSUE TITLE
Savage Gladiator set - Wrong stats

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#54]
The stats on Savage Gladiator seems to be a little off.

# **Savage Gladiator Chain (Id: 11726)**
_PTR:_
![image](https://user-images.githubusercontent.com/25831382/32965716-bdb66a1c-cbd7-11e7-82f8-5e722b496274.png)

_Actual:_
![image](https://user-images.githubusercontent.com/25831382/32965704-ade293f4-cbd7-11e7-942b-da3743973375.png)

# **Savage Gladiator Greaves (Id: 11731)**
_PTR:_
![image](https://user-images.githubusercontent.com/25831382/32965778-f8094ea0-cbd7-11e7-8e69-926c1eba8d92.png)

_Actual:_
![image](https://user-images.githubusercontent.com/25831382/32965761-e9655baa-cbd7-11e7-8dc0-17a1f7519ed3.png)

# **Savage Gladiator Grips (Id:11730)**
_PTR:_
![image](https://user-images.githubusercontent.com/25831382/32965833-248e5e5c-cbd8-11e7-9ab2-fbba09cd0554.png)

_Actual:_
![image](https://user-images.githubusercontent.com/25831382/32965826-1a315720-cbd8-11e7-8893-b9ffe503aadc.png)

# **Savage Gladiator Helm (Id: 11729)**
_PTR:_
![image](https://user-images.githubusercontent.com/25831382/32965895-5bfc71a8-cbd8-11e7-9bb3-e8a90ef96397.png)

_Actual:_
![image](https://user-images.githubusercontent.com/25831382/32965873-4bea535c-cbd8-11e7-9af5-79d07f3a7a96.png)

# **Savage Gladiator leggings (Id: 11728)**
_PTR:_
![image](https://user-images.githubusercontent.com/25831382/32965955-8ef445ea-cbd8-11e7-944f-bcebb199e7af.png)

_Actual:_
![image](https://user-images.githubusercontent.com/25831382/32965937-8486d974-cbd8-11e7-9d58-6e5343dea8d4.png)

**Comment by Navashed** [comment]
1.2 / 1.3 stats:
http://web.archive.org/web/20050420175118/http://wow.allakhazam.com:80/db/item.html?witem=11726

Stats from later in Vanilla:
http://web.archive.org/web/20060508233655/http://wow.allakhazam.com:80/db/item.html?witem=11726

**Comment by shenna-elysium** [comment]
Working as intended, Nigthaven's patch 1.3 has correct stats. Clear WDB folder.
