### ISSUE TITLE
Timbermaw Hold reputation bugged

### ISSUE THREAD

**Issue by Wowplayer** [elysium-project/bug-tracker#540]
Hello , my reputation with Timbermaw Hold is stuck at 0 (zero) hated and it doesn't drop from that point. When I turn in the repetable quests the hate is increasing, if I kill enemies of Timbermaw , hate is increasing also instead of decreasing. Please help, I have two characters Piciu and Elfy , same problem on both.
Thank you.

**Comment by Navashed** [comment]
Unable to reproduce.

Which repeatable quest are you doing?

**Comment by Wowplayer** [comment]
Winterfall Activity from Salfa NPC.

![1](https://user-images.githubusercontent.com/37214853/37243447-1f83770a-2482-11e8-99d7-fca13d229b58.jpg)
![2](https://user-images.githubusercontent.com/37214853/37243450-23a766a2-2482-11e8-8cab-8f1480c06341.jpg)
![3](https://user-images.githubusercontent.com/37214853/37243451-26a019f8-2482-11e8-810a-c803958f19b3.jpg)
![4](https://user-images.githubusercontent.com/37214853/37243455-2cc92fc2-2482-11e8-890c-6cab64a781ae.jpg)
![5](https://user-images.githubusercontent.com/37214853/37243456-325c42ee-2482-11e8-90f7-1e53041eafc5.jpg)
![6](https://user-images.githubusercontent.com/37214853/37243459-365a134e-2482-11e8-9979-ffa013cdc25f.jpg)
![7](https://user-images.githubusercontent.com/37214853/37243462-39b3f794-2482-11e8-8df8-7da701a50360.jpg)

**Comment by fulzamoth** [comment]
The bar moves opposite to what you think - it's counts _up_ through hated, then moves to neutral, counts up through it, and then moves to friendly.
