### ISSUE TITLE
Arikara can't be tamed

### ISSUE THREAD

**Issue by Nerelya** [elysium-project/bug-tracker#541]
The boss Arikara that's summoned in thousand needles is not tamable or it should be.

**Comment by Navashed** [comment]
Confirmed.

Creature 10882 - Arikara is not tameable, and it should be.
After casting Tame Beast, red error text appears: "Creature not tameable"
![a0f0625e2977e3eed90ca0717e01e721](https://user-images.githubusercontent.com/2709545/37228543-fa52dba2-23ae-11e8-95aa-548b2efa33e9.jpg)

This beast was always tameable as can be seen in old comments:
https://web.archive.org/web/20070704050739/http://www.thottbot.com:80/c10882

**Comment by Nerelya** [comment]
Plus this pet has some unique features: Entrance effect (little smoke like the summoning quest), sounds effects.

**Comment by Nerelya** [comment]
Still not working.

**Comment by shenna-elysium** [comment]
Will be fixed with the next server update. If you see something labeled as Fixed here it doesn't mean that all changes instantly go on the live server.
