### ISSUE TITLE
STILL NOT WORKING | Arikara can't be tamed

### ISSUE THREAD

**Issue by Nerelya** [elysium-project/bug-tracker#547]
The boss Arikara that's summoned in thousand needles is not tamable or it should be. Plus this pet has some unique features: Entrance effect (little smoke like the summoning quest), sounds effects.

**Comment by shenna-elysium** [comment]
Will be fixed with the next server update. If you see something labeled as Fixed here it doesn't mean that all changed instantly go on the live server.

**Comment by Nerelya** [comment]
oh ok ok, my bad, I thought so ;)
