### ISSUE TITLE
2 Blue quests not working

### ISSUE THREAD

**Issue by Dajelhorde** [elysium-project/bug-tracker#549]
1st blue quest that doesn't work for me is in alterec valley the "Dwarf spine" I can't turn it in to the npc

Looked the quest up online, went to the NPC, no blue ?

2nd bug is in diremaul Lorekeeper lyros, he wont give me the quest for the arcanum

Thats all

**Comment by Thenari** [comment]
I'm sorry but im gonna need to mark this as incomplete until you at least name the quests, also please tell me your characters class and level.

**Comment by Thenari** [comment]
ok i think by blue quest you probably mean repeatable quests

**Comment by Thenari** [comment]
for the second part of your report you are having trouble with the arcanum quests, you need the book first to get the quest i believe I've done the focus one a few times personally so there must be a unique nature to whatever you are doing that is preventing you from getting the quest.
