### ISSUE TITLE
Drain Life and Siphon Life generates healing aggro

### ISSUE THREAD

**Issue by Crusaderz** [elysium-project/bug-tracker#550]
Those are health drain spells, not healing one. Thats the reason why they not affected by healing reduction effects.

How to test: pull two mobs with a pet, cast DL or SL on one of them, second one immediately attacks you.

Death Coil, lifestealing enchant and skullflame shield proc probably affected too.

**Comment by Navashed** [comment]
Confirmed.

Drain Life, Siphon Life, and the Skullforge Reaver proc generate healing aggro. They should not.
Death Coil and the Skullflame Shield proc do not generate healing aggro; this is the correct behavior.

Affected spells:
Drain Life (all ranks) - Spell 11700 (Rank 6)
Siphon Life (all ranks) - Spell 18881 (Rank 4)
Skullforge Brand - Spell 17484

**Comment by Crusaderz** [comment]
Still not fixed, eh? First drain life cast always pull mobs off the voidwalker, leveling is a pain since you forced to self-tank everything on your way to 60.

**Comment by shenna-elysium** [comment]
Please provide more sources. Spells with any healing effects should generate healing aggro, no?
Same reason why SP don't use Shadow Word: Pain in raid.

**Comment by Crusaderz** [comment]
@shenna-elysium 
Приветик.

>Spells with any healing effects should generate healing aggro, no?

As i said earlier, healing reduction effects like mortal strike or wound poison does not affect drain life and shiphon life just because it's not **healing** spells, they does not benefit from +healing gear (unlike hunter mend pet), only from +spell damage gear, it's completely different mechanic (leech) and toolip of both spells specifically says "transfers X health from the target to the caster". We can also look into db for details:

Death coil (does not generate healing aggro on elysium, correct behavior) - Effect #1 | (9) **Health Leech**
Drain Life and Siphon Life - Effect #1 | (6) Apply Aura #53: **Periodic Leech**
Renew - Apply Aura #8: **Periodic Heal** 
Mend pet - Effect #1 | (6) Apply Aura #8: **Periodic Heal**

P.S.
I leveled lock back in 2006 up to levels 50+ (and then TBC came out) just by grinding mobs and i knew that something is wrong when my voidwalker is loosing aggro by single drain life (and nothing besides that) and adds switch their target to me after first tick of those spells.

Please reopen this bug report. Thanks!

**Comment by Thenari** [comment]
Yo @shenna-elysium not to undergo your authority but i have only ever played warlocks and over a decade ago leech did not generate aggro.

**Comment by Thenari** [comment]
@drozdez can you clairfy what kind of fixed this is?

Has then been fixed for a while now but never updates?
Did you work on code and feel like your changes can go to PTR?
Did you get testing done on PTR and this is ready for live?

**Comment by drozdez** [comment]
@Thenari i fixed it only today and tested on my local server. Everything goes ok. I commited it to develop branch on github. It think it will be uploaded with one of updates. So i think it can be closed for now.

**Comment by drozdez** [comment]
@Thenari it's never late to reopen issue if it will be neede, but i don't think it's needable to leave it as open issue

**Comment by Thenari** [comment]
Alright well its good to label things. So you added code to the upcoming ptr or to live?

**Comment by drozdez** [comment]
I added code to develop branch. That is all that I can say. All another actions are making Shenna, so it will be better for you to talk with her

**Comment by Thenari** [comment]
@shenna-elysium let someone know when it goes to ptr ill do threat tests
