### ISSUE TITLE
Enchant 2 hander: agility (+25agi)

### ISSUE THREAD

**Issue by Cramitclowny** [elysium-project/bug-tracker#552]
Have required rep, (i have honored), and it should be available at friendly. I bought the +15 agi to one hander from Timbermaw quartermaster, and the tailoring recipes that required friendly and honored. I think its a bug that the recipe isn't there, however i could be wrong and it could come out in a later patch. Looking for resolution/clarification if you all dont mine.

**Comment by Navashed** [comment]
http://wowwiki.wikia.com/wiki/Patch_1.10.0
>A new enchanting recipe that adds +25 Agility to two-handed weapons has been added to the Timbermaw Furbolgs that requires Friendly reputation.
