### ISSUE TITLE
Druid Revive Spell - Can't be learned in any trainer.

### ISSUE THREAD

**Issue by Maye94** [elysium-project/bug-tracker#553]
Trainers has no revive spell to learn for druids.

Revive is druid ability learned at level 12. It allows druids to revive fallen allies. In contrast to the [Rebirth] ability, Revive has no cooldown and is only usable out of combat. It is the druid's equivalent to the shaman spell Ancestral Spirit, the priest spell Resurrection, and the paladin spell Redemption.

**Comment by Wrath669** [comment]
Revive wasn't implemented until WotLK.
