### ISSUE TITLE
Mailbox problem

### ISSUE THREAD

**Issue by Chie6** [elysium-project/bug-tracker#556]
I can not recieve mail from players, I have tried sending main from all of my characters to my main character and it is not working at all, it just says "You have reached the ingame cap of mail recipients" yet I have an empty mailbox on both the character recieving and the character sending. GMs have tried to fix the issue by asking me to delete WDB. asking me to disable addons and unsilencing my account but nothing makes a difference, I've had this issue for three days now and have not been able to recieve a single mail except Returns and auction house.

Character name: Chie

**Comment by shenna-elysium** [comment]
Please make an in-game ticket.
