### ISSUE TITLE
CLUCK BUGGED

### ISSUE THREAD

**Issue by Jhamez** [elysium-project/bug-tracker#557]
My friend and i were questing in Westfall and we finished the CLUCK quest and did not reward (EGG), we are very sad about this, please help.

**Comment by YaboyJimmyrustle** [comment]
Confirmed. I was able to interact with the chicken and give Special Chicken Feed in an attempt to get the egg as a quest reward. However, I did not receive an egg as quest a reward. We will look into this.

**Comment by Lightsockie** [comment]
The egg is spawned on the ground (and must be right-click'd), and is very _very_ easy to miss. Especially if you're not looking for it. Are you guys sure you didn't just forget to grab it? I totally did when I did the quest.
