### ISSUE TITLE
Issues with quest completion

### ISSUE THREAD

**Issue by Oobytron** [elysium-project/bug-tracker#559]
Dear Elysium-Team,

unfortunately I can not complete the quest Ledger from Tanaris 
( http://www.wowhead.com/quest=4450/ledger-from-tanaris ) despite having all the required items. 
I'm playing on the Nighthaven PvP-realm currently on patch 1.6.

Please look into the matter as soon as you can.

Many thanks in advance and kindest regards

Tankyham/ Oobytron

**Comment by YaboyJimmyrustle** [comment]
I was able to get this quest and complete it just fine without any trouble. Be sure you have all required quest items including the ledger you get when you first start the quest.
