### ISSUE TITLE
Quest "A Noble Brew" has no payoff

### ISSUE THREAD

**Issue by Suobig** [elysium-project/bug-tracker#56]
It's not a major bug, just some small inconvenience.

In the end of the quest "A Noble Brew" NPC should die shortly after you turn the quest (you give him some "brew" made by some evil guy and he should die after drinking it). Right now the quest just ends and nothing happens.

**Comment by liskamic** [comment]
Same behaviour for me:
The script of the quest NPC drinking the brew and dying thereafter didn't play out after I turned in the quest.
