### ISSUE TITLE
Improved Eviscerate bug

### ISSUE THREAD

**Issue by Quirrrel** [elysium-project/bug-tracker#560]
The talent doesn't increase the damage from eviscerate. Neither the tooltip gets updated with new numbers, nor it actually starts to hit harder. Tested with undead rogue and rank 3 eviscerate. Tried resetting talents and clearing cache/addons, so it's not likely the problem on my end.

Now I know the discussed talent is straightforward and works probably everywhere. However, it being bugged is the only way I can explain why it doesn't work for me. And since it's rather easy to test, could you please look into it? Thanks.

**Comment by Navashed** [comment]
The talent works. Tooltip doesn't get updated. Tested with rank 3.
