### ISSUE TITLE
Quest "Rin'ji is Trapped" Buged

### ISSUE THREAD

**Issue by Hadring** [elysium-project/bug-tracker#561]
I completed this task alone without killing any mobs, because I escorting NPC in stealth and no one mobs attacked this NPC or me.

**Comment by Navashed** [comment]
Confirmed.

NPC 7780 - Rin'ji is not hostile with the Highvale elves he is escorted through. He should be.
![70b3b71692746e263db99c083586c486](https://user-images.githubusercontent.com/2709545/37486287-7185fc9a-2864-11e8-960f-2ab5414446dc.jpg)

Rin'ji's faction is 126. The Highvale elves' faction is 1576. These factions appear to be hostile to one another, so I don't know why Rin'ji is not hostile with the elves.

**Comment by sidsukana** [comment]
Will be fixed on next update
