### ISSUE TITLE
Gray quests gives way less rep

### ISSUE THREAD

**Issue by regalz** [elysium-project/bug-tracker#563]
So, i went back to ashenvale (as a 60) to do some quests and try to get darn rep for tiger mount. but i was getting like 5~20 rep per quest or something like that.

Got to vanilla db (https://classicdb.ch/?quest=7800) and you can se comments from 2007 saying that you should get the normal rep per quest (150/250/350)

Is this correct on the server? Thanks

**Comment by YaboyJimmyrustle** [comment]
Specifically, normal world quests will scale with your level when rewarding experience and reputation. 

The ClassicDB post you linked to is specifically for cloth donations which sole purpose is to build rep with associated city factions.
