### ISSUE TITLE
The Stones that Bind Us 

### ISSUE THREAD

**Issue by briggsmo** [elysium-project/bug-tracker#565]
Class quest "The Stones that bind us" provided by fallen hero of the horde does not seem to be working as intended. Since they dont get the stun effect needed to give time to break the stone, its virtually impossible to do this quest as a melee class without help.

**Comment by Navashed** [comment]
Confirmed.

Creature 7668 - Servant of Razelikh
Creature 7669 - Servant of Grol
Creature 7670 - Servant of Allistarj
Creature 7671 - Servant of Sevine

When these mobs reach 5% health, they should become afflicted by Spirit Shock (Spell 10794). This is supposed to disable them long enough for the player to destroy their crystal and kill them.

http://www.wowhead.com/spell=10794/spirit-shock#comments
https://www.youtube.com/watch?v=f0M8_cFB4v0
