### ISSUE TITLE
A Troubled Spirit missing

### ISSUE THREAD

**Issue by briggsmo** [elysium-project/bug-tracker#566]
Quest A Troubled Spirit http://www.wowhead.com/quest=8417 is missing - it should be given by Warrior Trainers (check the Quick Facts field in the link) to Warriors at level 50.

Missing in Ironforge and Stormwind, Darnassus not checked

**Comment by shenna-elysium** [comment]
Hello! This quest is supposed to go live in Patch 1.8.
Feel free to prove me wrong and reopen the issue if you find the better source than WoWWiki. 

http://wowwiki.wikia.com/wiki/Quest:A_Troubled_Spirit
