### ISSUE TITLE
Character skills

### ISSUE THREAD

**Issue by Taelon90** [elysium-project/bug-tracker#567]
Heimdal lvl 60 warrior Nighthaven PVP

Wrote ticket about my weapon skill never go above 298 specificly 2h axe, defence is 300 tho dont know if its only vissual!

Mvh Peter

**Comment by Navashed** [comment]
Weapon skill is working correctly. The final couple of levels take a very, very long time, especially with a 2-handed weapon and low Intellect. It takes most players months to cap 300.

Try using Intellect buffs.
