### ISSUE TITLE
Lockboxes in Angor Fortress, Badlands and Desolace missing

### ISSUE THREAD

**Issue by Midnatt** [elysium-project/bug-tracker#57]
Used to skill lockpicking. Are they not in this patch? Or are they simply missing?

**Comment by Terranzin** [comment]
Hello,

Could you please give more specific information, such as location (x:y). Thank you!

**Comment by Midnatt** [comment]
Badlands 42.29, Angor Fortress.
Desolace 37.21, In the water and at the beach

**Comment by Terranzin** [comment]
I´ve reviewed your issue again.

For the one in Angor Fortress its there, maybe you´re unlucky with the spawn?
![image](https://user-images.githubusercontent.com/25831382/32993898-56a10524-cd5f-11e7-9f03-6f7c80a0d2d9.png)

For the chest in Desolace I found two close to eachother.

![image](https://user-images.githubusercontent.com/25831382/32993911-9b744b20-cd5f-11e7-8eb2-77c524bb4df3.png)

So in respons, the chests do exist, if you think there might be a respawn issue on Nighthaven, please make a GM ticket instead and they can locate its respawn time.
