### ISSUE TITLE
Quest: A Crew Under Fire not working

### ISSUE THREAD

**Issue by fulzamoth** [elysium-project/bug-tracker#570]
## Summary
Captain Vanessa Beltis offers the quest **A Crew Under Fire**, but the mobs to fight never appear.

## Details
Speak to Captain Vanessa Beltis. She will offer **A Crew Under Fire**, with an objective of _defend Neutral 15 Captain Vanessa Beltis, her crew and the Horizon Scout's passengers against the naga attack. Captain Vanessa Beltis must survive._ 

Six waves of nagas, mixed Raiders (warriors) and Witches (casters) should come from around the far corner towards the barricade.

There are two problems with the quest:
1. The Naga never appear, making the quest impossible to complete.
2. If you speak to Vanessa again, the progress text for the quest reads: "Have you met with Andron yet? He rarely leaves Undercity, so I don't think it'd be too hard to find him." This progress text is incorrect, and belongs to the quest **Quest:Andron's Payment to Jediga**.

**Comment by MiticoPalla** [comment]
I also confirm this

**Comment by Thenari** [comment]
yeah lots of sites say this quest is just a broken incomplete quest, no reward no exp no rep should just be removed from game.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39779872-6ef1a1d4-52d8-11e8-8299-38b00854da7c.png)
it did start on the ptr for me though

**Comment by Thenari** [comment]
but theres no point to this quest so just remove it

**Comment by drozdez** [comment]
It don't give no exp nor money, so now I can close it
