### ISSUE TITLE
Spirit of Aquementas quest reward has wrong stats

### ISSUE THREAD

**Issue by Gloomtrap** [elysium-project/bug-tracker#573]
Характеристики предмета  Spirit of Aquementas  , полученные на Nighthaven 1.6 , неправильные, как у предмета до патча.
 Предмет Spirit of Aquementas должен иметь характеристики : Equip : Increase damage and healing by magical spells and effects by up to 20, вместо этого у предмета характеристики : Equip : Decrease mana cost all spells by 25.
Этот предмет был изменен в патче 1.3 Ruins of Dire Maul

**Comment by Inomares** [comment]
I believe this item has changed properly. You should clear your cache & WDB folders and see if you still see the old stats on the item.

**Comment by Gloomtrap** [comment]
After clearing  WDB  folder item stats is correct. Thanks a lot.
