### ISSUE TITLE
Incorrect demon voidwalker and Incorrect Summon Inferno

### ISSUE THREAD

**Issue by Merezin** [elysium-project/bug-tracker#574]
Играя за чернокнижника , столкнулся с проблемой ! касательно демона (синяка) 
когда я нахожусь далеко на расстоянии от своего демона и юзаю sacrifice , то демон падает за мертво вешая на меня щит вроде всё так и должно быть но .... 
1. он не пропадает в течении 20 - 30 секунд и весит во фрейме как мёртвый демон 
2. если он на расстоянии умер то он ползёт к тебе собирая паки мобов стоящими перед ним , а по истечению 20 - 30 сек эти все мобы переагриваются на меня ....
3 . команда /script PetDismiss(); не убирает труп демона из фрейма 
4 . если я захочу заюзать щит от демона (sacrifice) а потом вызвать Инфернала то у меня это не получится даже с макросом 
/script PetDismiss();
/cast Inferno(Summon)
5 .при использовании вызова инфернала пишется что у вас уже есть вызванный демон ... 
хотя при вызове других демонов то есть ( у меня вызван бес я юзаю призыв синяка = на бесе кружится стан и синяк вызывается ) по идее при вызове инфернала должна быть такая же механика ?
![u12uujoaecw](https://user-images.githubusercontent.com/28783519/37598889-89c79632-2b94-11e8-9271-0c4f0d5c4202.jpg)

**Comment by Thenari** [comment]
I am trying to recreate this, do you have any more info you would like to share?

**Comment by Thenari** [comment]
I know for a fact that after using Sacrifice on Voidwalker it takes the VW 15 seconds to despawn for another demon to be summoned or enslaved.

**Comment by Thenari** [comment]
I used to see the sac'd VW crawl towards me after being sac'd but I haven't seen that in a long time.

**Comment by Thenari** [comment]
![](https://cdn.discordapp.com/attachments/411408805453234181/443155106788147201/unknown.png)


I sac'd my VW waited 15seconds then summoned an Infernal, had the shield on me still with an infernal out for a dozen seconds.

**Comment by Thenari** [comment]
![](https://cdn.discordapp.com/attachments/411408805453234181/443155149142097920/unknown.png)

side note, infernal cannot come into instances (at least DM E backdoor) but he still says he is bound to me

**Comment by Thenari** [comment]
![](https://cdn.discordapp.com/attachments/411408805453234181/443156222196056074/unknown.png)

when i went into the instance the infernal went back to his original summoning spot, he waited there for a bit. I wanted to see how long until despawn but a lvl 48 or something came too close and infernal attacked him, I killed the infernal.

**Comment by Thenari** [comment]
![](https://cdn.discordapp.com/attachments/411408805453234181/443156951736516609/unknown.png)

after killing the infernal i was stuck in combat, I went into and out of an instance to clear the combat, but the whole time i flew to org it said i had a pet infernal, I made a party and asked someone if they could see the pet window, they could not, summoning an imp cleared the infernal pet window from the frame.

was just a client side visual error, not a big deal.
