### ISSUE TITLE
Can't Turn in "In Dreams"

### ISSUE THREAD

**Issue by Nosisrogue** [elysium-project/bug-tracker#575]
I completed the quest "In Dreams" today with a group of 5 people.  After we completed the quest and the first person turned in the quest with Tirion de-spawned and nobody else could turn in.  The quest still shows complete in my quest log.  We also attempted to turn in at Tirion's house in EPL, but it did not work.  I would like the Mark of Fordring if the quest can be completed for me.

R,
Nosisrogue

**Comment by tulahbear** [comment]
I turned  in quest "Scarlet Subterfuge" yesterday (03/21/2018) and nothing happened - the quest just completed with no result/escort (no Redemption quest). I can't even "drop" it to pick up later at NPC Myranda.  I'd really like my healing item - Fordring's Seal. ~Tulahbones
