### ISSUE TITLE
Combo Points Bug

### ISSUE THREAD

**Issue by bk187** [elysium-project/bug-tracker#577]
Combo Points disappearing from target after change target (but not attacking) and then re-target my previous target. How it should work = Combo Points should stay on target unless a new Combo Point generating move has been performed on a NEW TARGET or unless enemy is RESET.

*Note: this is only for Rogue combo points, don't have Feral Druid so I wouldn't know for that one,

**Comment by sidsukana** [comment]
Not a bug.
Do you look the WoW pathc-notes on wowpedia/wowwiki before you write a report?

https://wow.gamepedia.com/Combo_point

Patch 2.0.3 (2007-01-09): Combo points added to a target should not be reset until you add a combo point to a different target.
