### ISSUE TITLE
[Warlock] Improved Drain Soul not 100%

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#58]
Nate in Discord:
> "Hey, im not sure but i think there is an issue with my warlock ability? I have improved drain soul 2/2 and when i kill a mob with it on, that gave experience, it doesn't activate the ability. even though its 100% chance."

**Comment by liskamic** [comment]
It is working as intended. I use it in my warlock's main grinding rotation. The tooltip says:
> if the target is killed by you
Which means your character has to deal the killing blow. NOT your pet or party member. Probably shouldn't work on gray mobs too but I never tested that.
I recommend recalling your pet just as the mob is about to die. There are also macro suggestions for doing this automatically on various internet forums but none of them works for me on Elysium.

**Comment by liskamic** [comment]
While I'm here: anyone having any idea why my Improved Drain Soul macro doesn't work?
`/run local n=GetContainerItemLink(1,9) if n and strfind(n,"Soul Shard") then PickupContainerItem(1,9) DeleteCursorItem() end end/run local n=GetContainerItemLink(1,9) if n and strfind(n,"Soul Shard") then PickupContainerItem(1,9) DeleteCursorItem() end`
`/run CastSpellByName("Drain Soul (Rank 1)") if UnitIsUnit("playertarget","pettarget") then PetPassiveMode() end`
None of the /run commands works for me, even separately.
