### ISSUE TITLE
Improved curse of exhaustion isn't working

### ISSUE THREAD

**Issue by UninstallWizard** [elysium-project/bug-tracker#584]
Hello!

Recently T spent 3 talent points to improve my curse of exhaustion (in affliction tree for warlocks) and i seen that it wasn't upgrade the slow on the spell. Can it be fixed? If no, can i get a free respec pls? 

Respectfully,

Wagadougou

**Comment by Navashed** [comment]
The talent works. The tooltip doesn't update, which is a known issue with talents. Don't worry, your talent points are making the spell more powerful even if it's hard to tell.
