### ISSUE TITLE
Quest Bug ~ Counterattack! ~ Barrens

### ISSUE THREAD

**Issue by JitlanBG** [elysium-project/bug-tracker#593]
Quest Name: Counterattack!
 
Zone: Barrens ~ West of Crossroads

Quest Giver: Regthar Deathgate

Quest Turn-in NPC: Regthar Deathgate

Objective: Bring a Piece of Krom'zar's Banner to Regthar Deathgate, west of the Crossroads.
 
Issue: To Get the Banner Piece you need to talk with Regthar Deathgate, and Select the Option: "Where is Warlord Krom'zar?" in which Regthar does his Response of "Beware, (Name)! Look to the west!" Following that, a Small mini Event Should start where Kolkar Spawn (Which they don't) and after killing a few or a lot depending on your Luck, Krom'zar himself will spawn with a small Pack of a few Body-guards will assist him to Kill you. your Objective is to Bring him down and once he dies a Banner will spawn a top of his Corpse in which you may Pick a Piece of it and return.

**Comment by sidsukana** [comment]
Will be fixed in next update.
