### ISSUE TITLE
(Axe)[Ravager] Too weak

### ISSUE THREAD

**Issue by Hanzemon** [elysium-project/bug-tracker#595]
This axe takes too long to proc from Wing Clip (which procs weapon effects such as Nightfall's proc) and 
it doesn't seem to proc off itself no matter how many enemies it is hitting at the same time (which is against all probabilities whatsoever) or it seems like it procs off itself but the second proc gets cancelled after a brief period of time.

I have proof that back in the day it procced off itself and had a solid ppm ratio which seemed increased by abilities such as "Cleave", "Wing clip" or its own proc "Bladestorm" which does weapon damage to all enemies around, which means it also counts towards the ppm.

If we assume it has a 1 ppm i means it procs 1 time per 15 hits, it just makes no sense that if one spams wing clip indifinitely the axe doesn't proc anywhere near that, it just makes not sense, either Wing Clip is bugged or this Axe is 
https://www.youtube.com/watch?v=NPMpjuu9XF8
https://www.youtube.com/watch?v=HColEQLk3Bg

**Comment by Navashed** [comment]
Ravager procs off of yellow attacks. I have confirmed that it procs on Whirlwind.
