### ISSUE TITLE
Black Dragonscale Mail  set error

### ISSUE THREAD

**Issue by egyfecske** [elysium-project/bug-tracker#596]
Dear Elysium,

I crafted Black Dragonscale Breastplate and Black Dragonscale Leggings.

https://classicdb.ch/?item=15050
https://classicdb.ch/?item=15052

Black Dragon Mail set:

Black Dragon Mail (0/4)
Black Dragonscale Boots
Black Dragonscale Breastplate
Black Dragonscale Leggings
Black Dragonscale Shoulders

(2) Set: Improves your chance to hit by 1%.
(3) Set: Improves your chance to get a critical strike by 2%.
(4) Set: +10 Fire Resistance.
-------------------------------------------------------------------------------------------------
there's NO setbonuses in the items right now ingame. 
What happened to the set, and the setbonuses?!

Pls fix it as soon as possible.

**Comment by Inomares** [comment]
The set bonus isn't added until patch 1.8, released July 8th. Sorry :/
