### ISSUE TITLE
Ledger from Tanaris - Bugged

### ISSUE THREAD

**Issue by Manuvaa** [elysium-project/bug-tracker#609]
Okay, so i've got all the stuff that's needed for the quest and it even says completed in my QuestLog. 
But when i arrive at The NPC in Tanaris ''Krinkle Goodsteel'' he only shows a grey ''?'' so i cant turn it in. 

Anyway this is a bug? or did i just mess something up. 

Cheers Manuva

**Comment by sombyton** [comment]
same for me

**Comment by Navashed** [comment]
#380 #240 #70 

I have completed this quest without any problems 3 times now, I have never been able to replicate this issue. Since it is reported so often I believe there may be a bug, but since the quest has always worked fine for me I don't know what the problem could be.
