### ISSUE TITLE
Wild Leather Vest - cant complete quest

### ISSUE THREAD

**Issue by rosserr** [elysium-project/bug-tracker#610]
![inked 2018-04-01 15 47 39_li](https://user-images.githubusercontent.com/37978234/38173313-e2b4625e-35c4-11e8-8a1d-a9f645acd95d.jpg)
Cant turn in quest, but I have everything needed.

**Comment by YaboyJimmyrustle** [comment]
Alliance and Horde versions of this quest are both working as intended. When on collection quests for recipes it is possible to abandon the quest and pick it up again to circumnavigate problems like this.
