### ISSUE TITLE
Dire Maul: North tribute chest despawns after any server crash or client-side disconnect

### ISSUE THREAD

**Issue by Ooooom** [elysium-project/bug-tracker#615]
Problem is as said in the title and I do not remember this being the case in vanilla and it seems very harsh to punish players who have completed the Dire Maul run only to have the loot vanish before their eyes because they didn't decide upon distribution quick enough. There is already a spawn timer on chest which is reasonable, but punishing those for often which is server crashes seems a little harsh.
Is this something that can be easily resolved and fixed. I know many friend who are avoiding doing any Dire Maul: North runs now purely because they say its not worth the time, as you risk not getting any loot because of server crashes or client-side disconnects.

Let me know.

**Comment by Inomares** [comment]
@Giperionn On a related note, the door in DM North (you need the key from the middle of the courtyard to open) also closes when the server crashes, but the key in the chest does not respawn. Want a new bug report on this or can that just be thrown in with this fix as well?

**Comment by nexiros** [comment]
Thanks for confirming this bug. Does this mean we can expect a fix within the next patch or so? Because I've seen bugs just left as confirmed in the past with nothing done to them :(

**Comment by Giperionn** [comment]
Hello @Ooooom . Thanks for reporting, I agree, that it's very frustrating to loose all loot after server crash happend. I maded several changes in code.
1. Boss kill counter now saved immediately after killing, so even if crash happend second after, server will remember that anyway
2. Checkpoint "Tribute Spawned" deleted, instead I add checkpoint "King Dead", so you can spawn Tribute again after crash, or instance reloaded.
Fix will be available on next server update. Have a nice day ^_^ .
P.S. Yes, I aware of "key dissapearing" bug, will do that later.
