### ISSUE TITLE
Hunter quest bugged - Stave of the Ancients

### ISSUE THREAD

**Issue by Chubbychop** [elysium-project/bug-tracker#619]
Silithus Demon seems to not be working as intended.

He never stands till to cast stuff, he just continues chasing you, even when more than 2yds away from him.

Please have a look into this

Thanks

- Chubby

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39849045-6ff51222-53d8-11e8-88db-aad34e317544.png)


spawned a petrified leaf in my bag cause i cant enter MC solo :/ handed it in looks like the first part works

**Comment by Thenari** [comment]
yeah i went to "nelson" the nice gnome in silithus

big demon is just chasing me

but i do know the strat is to use like improved wing clip so im testing that now

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39849343-d900df02-53d9-11e8-9e38-d35092f8a560.png)

I wing clipped him which immoblized him for a long time

**Comment by Thenari** [comment]
I know its a really hard fight.

I play a warlock and people often get me to duel them during the fight and put curse of recklessness on the hunter which makes them immune to fears

other than that I cant repeat whatever problem you were having, you just need to rank 3 wingclip him for that secret bonus effect
