### ISSUE TITLE
Quests: Incorrect Prerequisites

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#622]
Quest 4642 - Melding of Influences is supposed to require both Quest 4293 and Quest 4294 as prereqs.
Quest 5514 - Mold Rhymes With... should have the same level requirement as its prequests, lvl 55.

https://web.archive.org/web/20070511214957/http://thottbot.com:80/q4642
https://web.archive.org/web/20070716030401/http://www.thottbot.com:80/q5514

**Comment by sidsukana** [comment]
Done. Will apply with next update.
Quest 4642, i not found detail information about prequests. Not change for now

**Comment by Navashed** [comment]
https://web.archive.org/web/20070511214957/http://thottbot.com:80/q4642

It's in the comments:
>yes there is quests before this btw, from the same place, you have to get samples of ooze from Un'Goro, then some from Felwood and test them @ UC then u get this part.. worked fine for me just now.. 

Also both prequests are listed here:
https://classicdb.ch/?quest=4642
