### ISSUE TITLE
Pattern:Robe of Winter Night

### ISSUE THREAD

**Issue by irokez13rus** [elysium-project/bug-tracker#623]
Chance 61% (https://classicdb.ch), i kill ~180 Cobalt Mageweaver, i got Mature Blue Dragon Sinew, all recipe, but dont got thats pattern. How much chance drop?

**Comment by shenna-elysium** [comment]
That's the data from Nighthaven realm: 
![image](https://user-images.githubusercontent.com/24865383/38459649-106847fc-3ab5-11e8-9af7-58f6404229d2.png)

However, in practice barely possible to obtain.

**Comment by Inomares** [comment]
classicdb has wildly incorrect drop rates on almost all items. Correct drop rate is roughly 1-2% depending on the mob, as can be seen here: https://web.archive.org/web/20051222104458/http://www.thottbot.com:80/?i=21483

**Comment by shenna-elysium** [comment]
Thank you. @Inomares

**Comment by irokez13rus** [comment]
I figured out the current problem. The fact that the addon showed me that the recipe falls, but in the loot it was not. It turns out that only characters with the tailoring skill can see it. And yes the drop chance is ~ 61%, but if there is no tailoring then you just do not see the recipe

**Comment by irokez13rus** [comment]
Like me, too. For this is a good Russian proverb. Live and learn. Verbatim -  live 100 years - learn 100 years
