### ISSUE TITLE
Data Rescue Quest in Gnomeregan

### ISSUE THREAD

**Issue by Radchy** [elysium-project/bug-tracker#624]
I've picked up the Data Rescue quest for Gnomeregan, which requires me to pick up a White Punch Card and upgrade it through Matrix Punchographs into a Prismatic Punch Card. Unfortunately, when I attempt to use 'Matrix Punchograph 3000-A', a red error message pops up saying "Already Open", as if it were a chest. How do I go about completing this quest?

**Comment by Thenari** [comment]
hmm i just did this for the very first time ever cause ive never played ally before, it worked for me so im guessing they fixed it after your comment...
