### ISSUE TITLE
Gorosh the Dervish bugged

### ISSUE THREAD

**Issue by baaaaaaaaasowenyaaaaaaamamabeatsebaaah** [elysium-project/bug-tracker#626]
"Gorosh the Dervish" in BRD Arena is bugged. After u killed him he will only drop some Silver. After looting him he instant despawn.
I have killed him 20 times, every time only some Silvers. 

found some source: 
http://web.archive.org/web/20050413234315/http://wow.allakhazam.com:80/db/mob.html?wmob=9027

**Comment by SebastianScherieble** [comment]
I did the Arena Run nearly 200 times. Finally i got the Savage Chest. Every single other try he only dropped some Silver. I also noticed that the event sometimes is bugged and npc's just run in the middle and stay there. This also happens to the bosses.

**Comment by baaaaaaaaasowenyaaaaaaamamabeatsebaaah** [comment]
I did the Arena Run nearly 200 times. "Gorosh the Dervish" can only drop the Epic: Savage Chest. Every single other try he dropped just some Silver. I also noticed that sometimes the Npc's are bugged and just run straight to the middle of the arena. This also happens to the bosses.

**Comment by shenna-elysium** [comment]
Can't reproduce, working as intended.
