### ISSUE TITLE
Feero Ironhand spawn timer

### ISSUE THREAD

**Issue by WuMingi** [elysium-project/bug-tracker#629]
Either this NPC is not respawning or spawn timer is way too long for a quest that is very hard to complete at the appropriate level.

**Comment by shenna-elysium** [comment]
Alright. His spawn timer is 5 minutes but you have to wait while another group is finishing the escort itself.

![image](https://user-images.githubusercontent.com/24865383/38460910-8cdb9d86-3acc-11e8-8f4d-c829f5cef892.png)
