### ISSUE TITLE
NPC Bug: Molten Elemental (ragefire chasm) (nighthaven)

### ISSUE THREAD

**Issue by Firestoat** [elysium-project/bug-tracker#63]
NPC Link - http://db.vanillagaming.org/?npc=11321
game server screenshot link - https://postimg.org/image/4brazoxzh/

Issue - The mob in question located inside of Ragefire Chasm has a flame shield damage buff that it will start a fight with. This flame shield buff can be dispelled as a magic effect, from a shaman's Purge, etc. This is correct, but the issue is that the mob will instantly cast a new shield over and over when it's dispelled again and again by a player.

This is incorrect. The mob requires a timer to be set so that it has a span of time needing to be passed before it will buff itself again if it's left alive to do so.

**Comment by twink** [comment]
No proofs.
