### ISSUE TITLE
Unable to learn mace proficiency

### ISSUE THREAD

**Issue by Woddie** [elysium-project/bug-tracker#631]
There is no option to learn how to use maces from Ansekhwa in Thunderbluff, not sure if this issue is just for me however.

**Comment by shenna-elysium** [comment]
![image](https://user-images.githubusercontent.com/24865383/38460901-358bb9a8-3acc-11e8-998a-68fd9ff1dc05.png)

I thinks it's just you. Please make an in-game ticket.
