### ISSUE TITLE
Sunken Tempel missing greens in "Oozzeling" loottable

### ISSUE THREAD

**Issue by baaaaaaaaasowenyaaaaaaamamabeatsebaaah** [elysium-project/bug-tracker#635]
The lvl 40 "Oozzeling" which are summoned from the "Saturated Ooze" are not dropping any greens.
They should drop "Haakari Breastplate", "Haakari Shroud" and "Mark of Haakar" drop chance should be around 10%. 

Found some source:
http://web.archive.org/web/20060520164811/http://wow.allakhazam.com:80/db/mob.html?wmob=8257

**Comment by Navashed** [comment]
Confirmed

These green items should be on the loot table of Oozeling (Creature 8257):
Mark of Hakkar (Item 10780)
Hakkari Breastplate (Item 10781)
Hakkari Shroud (Item 10782)

The drops on Allakhazam appear reliable, supported by the comments which can be seen by viewing from a later date: http://web.archive.org/web/20071110131048/http://wow.allakhazam.com:80/db/mob.html?wmob=8257

I recommend assigning an independent 10% drop chance to each of the 3 green items listed above. A commenter reported looting more than one green from the same mob, so they must have independent drop chances.
As for the Thorium Ore (Item 10620) drop chance, I recommend lowering it to 40-45% to be more aligned with the data we have in the links above. The drop chance is currently much higher.

**Comment by Thenari** [comment]
Oozelings are also reused in the weeping cave in WPL. In that cave they have no connection to hakkar items. It might be a mix up.
