### ISSUE TITLE
Bug when trying to complete Blood of the Black Dragon Champion

### ISSUE THREAD

**Issue by Petisisback** [elysium-project/bug-tracker#638]
I have run UBRS twice in the past two days to obtain the Blood from General Drakk and the Blood has not been dropped both times. I am currently wondering if there is anything to do to obtain the Blood so I may get my Onyxia Attunement.

**Comment by Navashed** [comment]
Unable to reproduce

![](https://i.gyazo.com/103fb259d30ab822d3df9a2440741c37.png)
