### ISSUE TITLE
Bug: NPC "Mist Howler" - dealing too much damage

### ISSUE THREAD

**Issue by Nimryl** [elysium-project/bug-tracker#639]
Found a bug I think..

Zone: Ashenvale
NPC Name: Mist Howler
Level: 22
Type: Wolf/Beast
Rarity: a Rare/Silver Dragon NPC

Problem:
[http://oi65.tinypic.com/2nl8pie.jpg](http://oi65.tinypic.com/2nl8pie.jpg)

Pretty sure a level 22 shouldn't be hitting for 423pts of damage vs a level 20 orc shaman.
I did manage to kill him by Frost shock kiting.

**Comment by Navashed** [comment]
Confirmed

Creature 10644 - Mist Howler's damage is not appropriate to his level and there are no comments from Vanilla suggesting he hit unusually hard.

https://i.gyazo.com/648c042a0be0d8f80503b9665e734b87.png
