### ISSUE TITLE
Sometimes Polymorph doesn't work.

### ISSUE THREAD

**Issue by Midnatt** [elysium-project/bug-tracker#64]
Sometimes when a mob gets polymorphed, it becomes a sheep, but it can still attack and use abilities just as normal.

**Comment by Terranzin** [comment]
I´ve reviewed your issue. I would need more information, logs and such, been attempting the same thing with different mobs for over 50+ times and couldn´t get it to work a single time.

**Comment by Midnatt** [comment]
I will try to record and publish logs.

**Comment by Midnatt** [comment]
PROOF:
https://clips.twitch.tv/MoistGoldenPuffinChefFrank
https://gyazo.com/04bf8cf6792e5259045250aaeac9282d

**Comment by Terranzin** [comment]
I can´t reproduce it myself, but the video is clear proof of what can happen. I´ll ask the devs look into the issue.
