### ISSUE TITLE
Hero of the Stormpike

### ISSUE THREAD

**Issue by L0nik** [elysium-project/bug-tracker#640]
Can't get quest "Hero of the Stormpike" after completing "Battle of Alterac"

**Comment by Thradia** [comment]
https://classicdb.ch/?quest=8271
Hero of the Stormpike comes with Patch 1.8, so it is not ingame yet.

**Comment by Navashed** [comment]
This quest was added in Patch 1.8.
http://wowwiki.wikia.com/wiki/Quest:Hero_of_the_Stormpike
