### ISSUE TITLE
Diremaul East: Whip Lasher loot table

### ISSUE THREAD

**Issue by Stonetroll** [elysium-project/bug-tracker#641]
It seems that in Diremaul: East, the non-elite Whip Lashers no longer drop any herbs, mithril lockboxes etc. After 5 mage "farm runs" I only looted their grey items and some random greens.

**Comment by Mikekike** [comment]
Aggree with that. Same shit. No more herbs and lockboxes from this mobs. Think problem come in april 11/2018 development update.

**Comment by Navashed** [comment]
Confirmed.

The lockbox and herbs are still on the loot table but they have had their drop chances reduced as if they were world drop greens:

![](https://i.gyazo.com/ef73461c9e180caac46ff73154d140dc.png)
