### ISSUE TITLE
Tome of Divinity 

### ISSUE THREAD

**Issue by Oobytron** [elysium-project/bug-tracker#642]
Although I have reached level 12, I can not accept the quest that the Tome of Divinity is supposed to start.

**Comment by Kyrro** [comment]
I came across this problem too. I could accept a quest named "The Tome of Divinity" from Duthorian Rall which would give me the item Tome of Divinity but the quest description and requirements are blank!

I abandoned the quest and tried right clicking the Tome of Divinity and it showed this quest: https://vanilla-twinhead.twinstar.cz/?quest=1643

I attempted accepting it but it said I do not meet the requirements of this quest (I've tried this at level 12 and 13). So I then made a ticket and a GM forcibly added the quest to my log, but it was displaying blank again!

I checked on Stephanie Turner and she cannot be interacted with which makes the quest unusable. I hope this helps!

I wonder how other people have been getting their Resurrection spells. Maybe they've been filing GM tickets saying the quest is bugged to get it magically given to them.

**Comment by Kyrro** [comment]
Human Paladin

**Comment by drozdez** [comment]
I think that your problem in GM's error. There are two types of quest chains for this quest. And both of them are starting with different items. All requirements in tables are right. Also both of this questlines are surely working. Howbeit, ask GM to add you the quest from another questline.

https://classicdb.ch/?item=6847 - this start first questline
https://classicdb.ch/?item=6846 - this start second.

https://classicdb.ch/?quest=1784 - the first questline
https://classicdb.ch/?quest=1787 - the second.

This must help you to end your problems!

**Comment by Kyrro** [comment]
I'll attempt killing enemies of the right type in hopes that the quest object drops. Then hopefully it turns in even though everything for the quest is blank.
![capture](https://user-images.githubusercontent.com/37011019/40873049-0c6f49a0-660e-11e8-84f1-7933950aade0.PNG)

**Comment by drozdez** [comment]
The problem could be only on the sql side. But there everything is ok. So it seems to be a problem with visual client side. Maybe some addons. Try to download the client again.

**Comment by Kyrro** [comment]
Deleting my WTF folder and disabling all addons enabled me to continue the quest.

**Comment by Thenari** [comment]
Well thats good. You wanna give a list of your addons? The servers on WTF folder i feel is less likely the culprit here. We find the addon, if its a modern vanilla addom we might be able to tell the maker. If its old relic not much we can do eh
