### ISSUE TITLE
Incorrect Level Requirement: Enchanted Thorium Platemail

### ISSUE THREAD

**Issue by Thradia** [elysium-project/bug-tracker#647]
Item: https://classicdb.ch/?quest=7649
The ingame tooltip shows "requires level 50"
![nighthaven_ingame](https://user-images.githubusercontent.com/38205670/38751731-3c9e6902-3f59-11e8-84a2-061d82bb62df.png)

As you can clearly see, it says "Level 60" on ClassicDB. And this was confirmed by a player some minutes ago. He met all the requirements, but was level 59 --> couldn't start the Quest. As soon as he hit 60, he was able to start it.

**Comment by Navashed** [comment]
Item 18769 - Enchanted Thorium Platemail certainly required level 50 in vanilla as seen in the old databases:
https://web.archive.org/web/20070608143054/http://www.thottbot.com:80/i18769
http://web.archive.org/web/20071124090127/http://wow.allakhazam.com:80/db/item.html?witem=18769

ClassicDB is notoriously wrong about level requirements, particularly concerning quests which begin from items. The old databases both state the quest's requirement was level 58:
http://web.archive.org/web/20060415064811/http://wow.allakhazam.com:80/db/quest.html?wquest=7649
https://web.archive.org/web/20070515021508/http://thottbot.com:80/q7649

However, all this means is the lowest-level player Allakhazam and Thottbot ever observed completing the quest was level 58. It's entirely possible the quest was available to level 50 players and simply no level 50 player ever completed the quest and had their data recorded in the old databases. If the item states the quest is available to level 50 players, we should assume this to be the case.

Therefore, the level requirements for these quests should be lowered to 50:
Quest 7649 - Enchanted Thorium Platemail: Volume I
Quest 7650 - Enchanted Thorium Platemail: Volume II
Quest 7651 - Enchanted Thorium Platemail: Volume III
