### ISSUE TITLE
Gnarlpine Necklace

### ISSUE THREAD

**Issue by RainElysium** [elysium-project/bug-tracker#65]
Gnarlpine Necklace:
http://db.vanillagaming.org/?item=8049

Necklace is supposed to open and give access to loot this item:

Tallonkai's Jewel: 
http://db.vanillagaming.org/?item=8050

It does not. It bugs.

**Comment by twink** [comment]
It's not a bug, it's quest item, to receive Tallonkai's Jewel you must have this quest: http://db.vanillagaming.org/?quest=2459

**Comment by RainElysium** [comment]
This is when the player has the quest, loots the quest item 8049, opens it to obtain the quest completion item 2459. 2459 does not show up.
