### ISSUE TITLE
[BUG] Quest: Counterattack!

### ISSUE THREAD

**Issue by Retrovidya** [elysium-project/bug-tracker#651]
The Kolkar and Krom'zar do not spawn in properly. They pop in for a second then disappear. You can see a  .gif of this happening here. https://gyazo.com/14a79c487440b9570a6618ce02535097

**Comment by Retrovidya** [comment]
Server restart seems to have fixed it.

**Comment by AliziaKaline** [comment]
Nethergarde (1.6) : The bug still here.
