### ISSUE TITLE
Thorium Brotherhood Rep

### ISSUE THREAD

**Issue by Tasselhoff1337** [elysium-project/bug-tracker#659]
The quests from searing gorge are supposed to provide 250 rep each. After completing all of them i have only received 140 rep... this seems like an issue

**Comment by Thenari** [comment]
Where did you read they were suppose to give 250 rep each?

**Comment by Thenari** [comment]
also yeah they only give 20 rep per quest this patch lol its not even worth doing them :P just grind up the 200-300 incendsaur scales +lots of kingsblood/iron bars/heavy leather to friendly
then its like 960 dark iron residue to honoured.
then its like 53 fiery cores to revered. (maybe 21 i cant remember)
followed by double that so 105 fiery cores (or maybe 53 i cant remember) to exalted.


$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

gl hf!

**Comment by Thenari** [comment]
I went and did it on my main so yeah ill confirm that your claim is true, but its intended....

there enough quests in the game for a non-druid to get like 1.8k rep with Cenarion Circle

I'm at 7k/21k to revered (not even exalted)

1 rep per kill until 8k then its literally one mob in the current game who gives rep honoured-revered (Flamereavers in a cave NE silthus)

WoW Vanilla is a fucking GRIND!

**Comment by shenna-elysium** [comment]
If you say `I went and did it on my main so yeah ill confirm that your claim is true, but its intended....` I don't get why it's confirmed.
