### ISSUE TITLE
Second part of "The Missing Courier" in Felaras isn't scripted

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#66]
> AfterShave - Today at 8:55 PM
> Second part of "The Missing Courier" in Felaras isn't scripted
> clicking on the broken row boat does not lead to the third part of the quest

**Comment by twink** [comment]
It works fine. You need to find a boat in the water, no on the beach. It's close to the one that on the beach, try to find it.

**Comment by Stoley** [comment]
> AfterShave - Today at 9:17 PM
> Oh I see
> thank you
