### ISSUE TITLE
Test Server - Boats and Blimps not showing up

### ISSUE THREAD

**Issue by Akamai-Okole** [elysium-project/bug-tracker#660]
Hi, for the past several days boats and blimps haven't been coming in so there's no way to travel between continents. 

For a couple days, flight paths would stick you in an endless loop where you couldn't get off and when you logged out and in, it would start a two direction flight over from the start and you'd be stuck at the end. This seems to have cleared up day before yesterday but may be worth looking into if you haven't changed anything. Note that I deleted all database folders and disabled all add ons and this did not help.

**Comment by shenna-elysium** [comment]
Resolved.
