### ISSUE TITLE
balance of holy quest Epl

### ISSUE THREAD

**Issue by alltime01** [elysium-project/bug-tracker#665]
ive been here for couple hours now and its bugged bad. I completed the quest on saving the people of strat but not the scourge just keep coming. everything else is done except it wont complete even though she said I was finished. now theres hundreds of scourge just hanging out by the tunnel and I'm hanging back so they don't keep charging me. ive spent tons of gold to finish but this is the 2nd time something has bugged on this quest. please let me know what I can do. I'm just hanging here waiting as for now

**Comment by Thenari** [comment]
i think this was addressed cause that quest is very script heavy and script stuff gets messed up bad lol :P 
sorry for late reply 25 days jeez hope you got help!

**Comment by shenna-elysium** [comment]
Fixed.
