### ISSUE TITLE
[Foror's Compendium of Dragon Slaying]

### ISSUE THREAD

**Issue by Emigrantt** [elysium-project/bug-tracker#668]
[Foror's Compendium of Dragon Slaying]

item=18401

 WRONG DROP CHANCE!? 

https://classicdb.ch/?item=18401
Guard Slip'kik 10% https://classicdb.ch/?npc=14323

**Comment by Thenari** [comment]
Im on my phone once i get home ill go ahead and invalid this post

**Comment by Emigrantt** [comment]
https://youtu.be/9HNi47ameLI

**Comment by Emigrantt** [comment]
чё?
