### ISSUE TITLE
Reanimated Corpse bug in Scholo

### ISSUE THREAD

**Issue by Midnatt** [elysium-project/bug-tracker#67]
Scholomance. We died. When we got back the mobs looked like this, we have killed them.. 

They can be targeted, however not making you go into combat and they dont do anything against you.

![poisonbug](https://user-images.githubusercontent.com/18221811/32987111-b14468d2-cce1-11e7-9c4d-444ba0078f10.jpg)

**Comment by Terranzin** [comment]
I´ve reviewed your issue. It´s hard to reproduce, if you do kill them normal it does not appear. But I´ll have the devs take a look since you have a solid screenshot of the issue, probably some kind of desync between client and server.

**Comment by Midnatt** [comment]
The corpses didnt act like this when we first killed them. It was after we died. More ore less when we left the room and came back.

**Comment by twink** [comment]
It means taht they are in ressurecting phase.
