### ISSUE TITLE
Cannot get Water Totem Shaman Call of Water

### ISSUE THREAD

**Issue by ghost** [elysium-project/bug-tracker#681]
If you abandon Part 8 of the Shaman [Call of Water] quest you can not finish the quest.  This is a pretty rare thing to happen, but it did happen to me and now I might have to remake my Shaman...  I cannot get water totem.  I tried talking to both the quest giver and all NPCs during the quest again and none of them give it.

I think the issue is you need the special item to see the elemental and you need the elemental to get the last part.

IGN: theSpacebaker

**Comment by Thenari** [comment]
I did every part of the chain just to check and im at part 8

![image](https://user-images.githubusercontent.com/38762769/39851119-341cb61e-53e3-11e8-8ac8-a79296ec1f0b.png)


I have the shard and am going to drop the quest

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39851141-5225ef90-53e3-11e8-9839-770251d01e7f.png)

I dropped the quest and right away the shard disappeared, and i took it again and dropped like 5 times in a row

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39851340-49a10624-53e4-11e8-8e81-bec4d54447ae.png)

it seems theres a failsafe quest giver you can bring the water sapta to and hell reveal the spirit

the troll on the right

**Comment by Thenari** [comment]
your report is incomplete at least i was unable to repeat what you did it worked for me? if you can give more info ill test further

**Comment by Thenari** [comment]
ok im guessing you dropped the quest far from the spirit and he despawned... yeah maybe if the waterseer lady southeast of ratchet could give you a backup water sapta you can give that to the troll near the water shrine.

this quest bug is so unlikely to reproduce its almost always easier to just talk to a gm and .additem or .quest add to just get it again, changing or adding a new quest in case you drop the quest would be a lot harder than just talking to a gm

so im gonna say confirmed but intended

**Comment by MartYtheSpaceBaker** [comment]
Okay, sounds good.  I agree it is very rare.  Yes your most recent reply
was how it happened.

I was able to get a GM to give me quest again and got my totem, thanks for
looking into this!
