### ISSUE TITLE
Miner's Fortune quest bug

### ISSUE THREAD

**Issue by netherspite** [elysium-project/bug-tracker#682]
Server: Nighthaven PvP

I couldn't complete the Miner's Fortune quest (ID 896) normally. 

Was killing the quest mobs (Venture Co. Enforcer ID 3283 and Venture Co. Overseer ID 3286) for a total of 2 hours but never seen a quest drop (Cats Eye Emerald ID 5097).
I tried killing them grouped (both FFA and Group Loot) and ungrouped, inside the cave and outside of it.
I tried killing them at the different stages of the Samophlange chain. I was getting the Samophlange Manual Pages ID 11148 drops despite not having the quest for them (ID 3924) yet so I guess there could be some connection between those quests.

In the end I had to ask the GM to complete the quest for me.

**Comment by Gzuzz** [comment]
Just tried myself, and I didn't have an issue. You are probably unlucky my friend 😄
