### ISSUE TITLE
Bug on the quest Counterattack! in The Barrens

### ISSUE THREAD

**Issue by Hak97** [elysium-project/bug-tracker#684]
Kromzar doesn't appear, or more specifically, it appears and disappears like a loop, i hit him once and he disappears, i tried multiple times, in different hours of the day, i tried also to reset the quest but always happens the same. Hope in a fix soon

**Comment by Thenari** [comment]
testing this now, If i cant figure it out by myself plz give more info like your level and class maybe some screen shots to help

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787576-0ccbdf26-52f4-11e8-8f19-ad174a0cb9ba.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787588-1642fe22-52f4-11e8-887d-ea8c836754e5.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787640-6be7fd96-52f4-11e8-91a8-b9ebdd0b361a.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787671-86dc2afa-52f4-11e8-90e5-df91bbdf9bd7.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787690-a276dd00-52f4-11e8-845d-8482852fe189.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787709-b7ee14b4-52f4-11e8-9943-823a5208c2eb.png)
