### ISSUE TITLE
Bugged Ogre Brute in Feralas @ Ruins of Isiliden

### ISSUE THREAD

**Issue by OMAOMC** [elysium-project/bug-tracker#685]
61.2, 55.4 cords
Bugs frequently underground and causes combat bugs etc

**Comment by Thenari** [comment]
pretty lack of info but i think i found the guy

![image](https://user-images.githubusercontent.com/38762769/39787295-ac2c695c-52f2-11e8-843f-e5c765f0a876.png)


yeah he can start swimming, then after swimming he can just swim through the ground

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787316-c11b8da2-52f2-11e8-9e1c-0efe3f1dc94e.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787322-c8ba69f2-52f2-11e8-831c-78915605e614.png)
