### ISSUE TITLE
Zul'Farrak Zombie spawns bugged, do not spawn properly or de-spawn

### ISSUE THREAD

**Issue by OMAOMC** [elysium-project/bug-tracker#686]
Zombie spawns do not spawn, or de-spawn properly upon boss aggro - or if group wipes on boss.

This is a hugely annoying issue, that ought to be at least put on ice with a proper de-spawn tweak.

The zombies behave incredibly bugged, run through walls, 24/7 root, keep spawning more and more sometimes even after full group wipe.

This is an issue that GMs seriously should look into, and find some kind of compromise for.

**Comment by Thenari** [comment]
Please expand. The boss fight is designed to be punishing if you run up to the chest before dealing with the graves.

**Comment by Thenari** [comment]
Like i was running ZF a bunch to collect the Tarnished Silver Necklaces from the shallow graves (you can wear a full stack of 20 on your neck but dont tell any GM or bug testers that or they'll take away my bling bling)

even a 60 can get overrun very easily if you dont clear the graves before running up to the chest

**Comment by Thenari** [comment]
Im closing this
