### ISSUE TITLE
Gerenzo Wrenchwhistle (Stonetalon Mountains) bugged

### ISSUE THREAD

**Issue by OMAOMC** [elysium-project/bug-tracker#687]
64.5, 40.3 cords
Also the mobs around him doesn't behave properly

They just stand still, and don't even attack.
In fact it seems the entire area on those boards, and planks up has some immensely broken pathing.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787174-0873e8ee-52f2-11e8-8789-898490c4aa48.png)

these guys? your report is pretty incomplete but i ran around on all the boards trying to bug them out but the only time they stood still was to throw dynamite

im marking this as incomplete and invalid

if you have a specific pathing problem here i missed let me know
