### ISSUE TITLE
AI pathing, Quel'Danil Lodge (the Hinterlands)  insufficient

### ISSUE THREAD

**Issue by OMAOMC** [elysium-project/bug-tracker#688]
The AI pathing around the edges of the Quel'Danil Lodge is broken.
cords: 30.4, 47.9 

When going into and out from the building through the side way ledges, the AI pathing doesn't follow the player properly.

(In particular, the AI pathing around the two lamp posts at the front entrance of the building.
But as stated above, also very bad pathing around the ledges on both sides of the building.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39786953-e3cb715c-52f0-11e8-8613-a2dc193a3957.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39786960-fbddf6ac-52f0-11e8-826c-ba178aa39de9.png)

**Comment by Thenari** [comment]
yeah thats actually pretty standard for vanilla. mobs dont like to jump off cliffs this is pretty much 100% blizz-like

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39787047-5d46994e-52f1-11e8-8ef1-fcbdc24efb3c.png)

they found a way onto the roof too
