### ISSUE TITLE
Deathknell quest bug

### ISSUE THREAD

**Issue by genghazoid** [elysium-project/bug-tracker#689]
Hi! Nothing major. 'Fields of Grief' directed me to Deathknell for turn-in on my minimap, but Brill's the turn-in.

![bug](https://user-images.githubusercontent.com/38856365/39425082-89a62172-4c2e-11e8-81c8-25d16c2dda82.png)

**Comment by Gzuzz** [comment]
It directs you to the closest town. No system like this was implemented in Vanilla.
