### ISSUE TITLE
Gnarlpine Necklace 

### ISSUE THREAD

**Issue by RainElysium** [elysium-project/bug-tracker#69]
Gnarlpine Necklace:
http://db.vanillagaming.org/?item=8049

Quest item necklace looted from Ferocitas mob (2459) is supposed to open and give access to loot this item:

Tallonkai's Jewel:
http://db.vanillagaming.org/?item=8050

It does not. It bugs.

Video evidence:
https://youtu.be/tIvDJyC-szg

**Comment by Terranzin** [comment]
I´ve reviewed your issue. I manage to reproduce the same error as you. I killed the mob he dropped the Gnarlpine Necklace (Id: 8049), opened the "container" and tried picking up the quest, nothing happened.

![image](https://user-images.githubusercontent.com/25831382/32995227-ba7a977e-cd71-11e7-85da-68afe80a4295.png)

Additionally, the item went grey and text appeared.

![image](https://user-images.githubusercontent.com/25831382/32995194-6d0c6c38-cd71-11e7-9ccd-397ddc9839bc.png)
![image](https://user-images.githubusercontent.com/25831382/32995197-7aa3a596-cd71-11e7-91db-4b29d7062be1.png)
