### ISSUE TITLE
"A Crew Under Fire" quest in Azshara bugged 

### ISSUE THREAD

**Issue by OMAOMC** [elysium-project/bug-tracker#694]
Does not award proper experience reward upon completion.
Only got 600xp at level 53 from completing the quest.

Will try to find out how much would be the appropriate xp reward and return if I find it.

**Comment by Thenari** [comment]
thats weird that you got any exp at all, the quest is an incomplete quest that was removed, it never gave exp rep or gold its a unfinished quest. this is also a duplicate so i recommend the quest be removed from game and never spoken of again.

**Comment by shenna-elysium** [comment]
The quest was added to the game so the issues is to be checked.

**Comment by Thenari** [comment]
like if you want it to work you have to create content, it was never completed in vanilla wow, you can step away from blizz-like and make a reward for the quest but the effort to create content for a zone that was never completed seems like a waste of manpower.
