### ISSUE TITLE
Broken Herb Nodes + Cords and zone info

### ISSUE THREAD

**Issue by OMAOMC** [elysium-project/bug-tracker#695]
I will post in this thread, every single broken herb node spot I find within the game.

Felwood, Dreamfoil 42.7, 63.2
Felwood, Plaguebloom 41.3, 68.1

**Comment by Thenari** [comment]
can you clarify what is broken about them too, no loot/bugged into ground/whatever.

**Comment by Thenari** [comment]
i feel like this is just clutter, you could do this in the forums
