### ISSUE TITLE
Issue with "The Attack!" quest.

### ISSUE THREAD

**Issue by Peachpizza** [elysium-project/bug-tracker#7]
Ill do everything what GM advice me, but it's not work. Player can turn quest also can kill both objects but can talk with gnome Tyrion after this. Quest seems to be broken.

**Comment by WardenElysium** [comment]
Issue confirmed.

**Comment by twink** [comment]
Tested , works fine.
You need to finish talking to http://www.wowhead.com/npc=482 , not to Tyrion.
