### ISSUE TITLE
Quest: Ledger from Tanaris

### ISSUE THREAD

**Issue by Djdave89** [elysium-project/bug-tracker#70]
Have all the items, The quest will not turn in.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and I cant manage to reproduce your issue. 

If you can see here I completed the quest after gaining all items
![image](https://user-images.githubusercontent.com/25831382/32995446-b0aea5fc-cd74-11e7-9fa1-53b9e491cd4d.png)

Are you at the correct place? The quest needs to be handed in at Tanaris.

**Comment by Djdave89** [comment]
Yea, I have it all but the goblin wont let me turn it in.

**Comment by Djdave89** [comment]
![wowscrnshot_111917_160750](https://user-images.githubusercontent.com/33679873/32995545-f6e67292-cd43-11e7-8203-aa49023e2443.jpg) So yea not sure what is happening.

**Comment by Djdave89** [comment]
Fixed, Thank you TheFlame. Had to re-pickup to complete.
