### ISSUE TITLE
Int giving 1 mana

### ISSUE THREAD

**Issue by Gyronell** [elysium-project/bug-tracker#701]
just leveled a troll shaman from 1-5 and turns out int from leveling is only giving me 1 mana.
lvl 1 70 starting mana
lvl 2 gave +8 mana and +1 int resulting in 79 mana
lvl 3 gave +7 mana and +1 int resulting in 87 mana
lvl 4 gave +23 mana resulting in 110 mana
lvl 5 gave +9 mana and +1 int resulting in 120 mana

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39784645-244f2534-52e7-11e8-8eb2-c80b7e80fab9.png)
 lvl 1

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39784662-3b31a97a-52e7-11e8-94e1-cdfc2d8b8cf8.png)

lvl 2

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39784678-45d448c4-52e7-11e8-912a-5f65b0b7574d.png)

level 3

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39784689-4f05c062-52e7-11e8-978d-083dec20d677.png)

level 4

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39784697-57a696ba-52e7-11e8-87f2-183c1980f888.png)

level 5

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39784710-60383126-52e7-11e8-8355-7cd57dbe9afc.png)

level 6

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39784724-69106246-52e7-11e8-9e44-c2726a8ae6bd.png)

level 7

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39784737-70b63d2c-52e7-11e8-8836-8eadb01dd5c6.png)

level 8

**Comment by Tinkertee** [comment]
How do we test on the test server like this?

**Comment by Thenari** [comment]
you need the blessing of daddy Rain to have magic powers

**Comment by shenna-elysium** [comment]
Tested everything, working as intended.

http://vanilla-wow.wikia.com/wiki/Base_mana
http://vanilla-wow.wikia.com/wiki/Attributes

Not gonna quote anything, please take a look yourself.
