### ISSUE TITLE
Primal Hakkari Idol

### ISSUE THREAD

**Issue by mnisss** [elysium-project/bug-tracker#706]
Primal Hakkari Idol, do not drop from Mandokir & Jin'do.

Raid id 1458 Cleared last night.

**Comment by Alastor89** [comment]
It is my understanding that the idol isn't in the game yet and was added in a later patch. That's the whole reason you need miscellaneous materials to get your class enchants, rather than getting and using 2 items from the instance itself.

**Comment by Thenari** [comment]
that ideal isnt in the game yet

https://wow.gamepedia.com/Primal_Hakkari_Idol

added 1.11
