### ISSUE TITLE
 Change of Goblin specialization to Gnomish

### ISSUE THREAD

**Issue by gygorya** [elysium-project/bug-tracker#707]
The book in the tent at Narain Soothfancy in Tanaris is not read. 
My Rogue 59lvl engineering 293

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39781684-ec603068-52dd-11e8-81ae-8682b67b08e6.png)
 the gnome talks about it but it just not be in the game yet i cant click it either with literally every profession in the game learned maybe if i delete some

**Comment by Thenari** [comment]
https://wow.gamepedia.com/Narain_Soothfancy

his wow wiki page claims he was added 1.9 so he probs shouldnt even be in the game, maybe delete him?

**Comment by gygorya** [comment]
patch 1.9 added  Change of Goblin specialization to Gnomish?

**Comment by Pirupuku** [comment]
In Patch 1.10 they implemented for engineers to respecc and choose a new specialization but you have to learn from 1-200 again and then read the book! Is that confirmed to work on Elysium?
