### ISSUE TITLE
Viper Sting breaks Freezing Trap

### ISSUE THREAD

**Issue by WobLight** [elysium-project/bug-tracker#709]
When Viper Sting removes mana it breaks Freezing Trap.
EDIT: Actually breaks polymorph too, and probably anything else that breaks on damage.

**Comment by Thenari** [comment]
That sounds like it should be intended, same happens with Warlock Drain mana on Sheep'd targets. It would be a real killer combo to sheep a mage or priest and just drain all their mana. I am going to ask some other people if that is intended.

**Comment by Thenari** [comment]
![](https://cdn.discordapp.com/attachments/411408805453234181/443171120733093918/unknown.png)

drain mana on a sheep


![](https://cdn.discordapp.com/attachments/411408805453234181/443171207232225280/unknown.png)


also breaks it but does no damage

**Comment by Thenari** [comment]
![](https://cdn.discordapp.com/attachments/411408805453234181/443176205479313408/unknown.png)
you can get hit but the mana steal happens in i think 2 or 3 seconds after you get affected, once anything ticks damage mana or dmg it breaks


![](https://cdn.discordapp.com/attachments/411408805453234181/443176080593911810/unknown.png)


so this is confirmed. thank you for bringing this to attention.

**Comment by WobLight** [comment]
I've found that wowwiki from 2006 mention that viper string breaks Freezing Trap
http://wowwiki.wikia.com/wiki/Freezing_Trap?oldid=186784
> Any damage caused will break the ice (this includes DoTs such as Serpent Sting and Viper Sting).

**Comment by drozdez** [comment]
So, with this information all is working as intended as I think.

**Comment by WobLight** [comment]
It is, my bad for having missed that in first place.
