### ISSUE TITLE
Ultrasafe Transporter: Gadgetzan

### ISSUE THREAD

**Issue by bobby8212** [elysium-project/bug-tracker#71]
The guy who should give you recipe is broken.

**Comment by yimido** [comment]
Yeah! Same for me  ive got 280 engi and gnomish engi but when i click on the guy there is animation of learning spell but spell doesnt appear in engi recipes

**Comment by Terranzin** [comment]
I´ve reviewed your issue and something doesnt seem to be fully correct here. Sadly the use-case seems to be a little bit different between the PTR and live server too. I would like to ask some additional help from our devs regarding this issue. Thanks for reporting!

**Comment by twink** [comment]
It will be added in 1.5, right now Nighthaven on 1.2 patch.
