### ISSUE TITLE
The melee brute mobs in Dire Maul North have ranged attacks lol

### ISSUE THREAD

**Issue by europoor** [elysium-project/bug-tracker#711]
Its pretty fucking annoying getting hit with melee attacks from 20 yards...the knockback is annoying enough

**Comment by Thenari** [comment]
Can you give the name of the mobs you are talking about?

I assume you mean the Gordok Brute elite mob

they are supposed to have 2 ranged abilites

within 10 yards of them they can do an uppercut

within 15 yards of them they can do a cleave.

Are you sure you were 20 yards away?

I will go into the instance and attempt to snare them and stand various distances from them.

**Comment by Thenari** [comment]
I know sometimes when mobs are evading because they can't find a path to you they will just hit from far away was it something like that?

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39780715-2bdf4f92-52db-11e8-997b-6261c972e1f4.png)

i gathered a bunch of brutes and i ran around and away from them and they always followed me to melee

maybe theres more conditions to your situation you didnt mention a particular combo of enviroment that causes it but with no further info this is invalid
