### ISSUE TITLE
When logging in I cant get past the 'Connected' message

### ISSUE THREAD

**Issue by MN7213** [elysium-project/bug-tracker#713]
When logging in, I cant seem to bypass the connected message. I have had a look at this issue through the forums and they all say the same thing just delete your WTF and WBD folder and itll be fine I have done this several times and still no joy. Please help.

**Comment by Thenari** [comment]
this isn't really the forum for that, connecting to the server is more the support channel on discord or the forums. I hope you've been able to connect by now
