### ISSUE TITLE
Pets use autocast abilities even when not supposed to

### ISSUE THREAD

**Issue by WobLight** [elysium-project/bug-tracker#714]
The only I'm sure of is Dash, the pet uses it even while stunned or feared and so on. Also sometimes looks like it is able to stealth when its target dies even while still in combat. Iirc I've also seen a pet charging while CCed in PvP once. That only happens when abilities are autocasted, when used directly by the player they give error as expected.
EDIT: sometimes also happens that the pet resets and runs to you while feared or polymorphed (w/ the effect still on).

**Comment by WobLight** [comment]
About CC you see the pet with fear or polymorph on coming towards you (and then follow while still in CC). It's like pet movements overrides the wandering random movement generator.

**Comment by WobLight** [comment]
My pet still sprints while polymorphed with autocast, is this not live yet?

**Comment by Thenari** [comment]
I dont super know whats supposed to be blizz-like i see lots of sheeps i fear once the fear breaks they are stuck as sheep but they run at me lol

**Comment by WobLight** [comment]
A succubus just casted charm while frozen....
