### ISSUE TITLE
Shimmering Gloves of the Tiger, Lvl 17 green giving +14 stats

### ISSUE THREAD

**Issue by Tinkertee** [elysium-project/bug-tracker#719]
![image](https://user-images.githubusercontent.com/39176184/39901307-aa8cfe82-5495-11e8-9d9f-2727954c61e1.png)
 Cleared WBD and Cache folders. Bug still exists. Not dropping 23g to see if it raises stats by that much.

**Comment by Thenari** [comment]
This is like an old joke. Its not real dont worry about it.

**Comment by Inomares** [comment]
They are on the auction house (horde side), looks real enough.

**Comment by Thenari** [comment]
Its an old bug from vanilla days. Dont worry about it.

**Comment by Thenari** [comment]
haha i was wrong as fuck

![image](https://user-images.githubusercontent.com/38762769/39964785-56f589a8-565a-11e8-9b10-1f973473abba.png)

found the vendor that sells the bugged item
it totally does increase your stats way too much for a lvl 17 item

**Comment by Thenari** [comment]
of the tiger is not in the random bonus pool for shimmering gloves i spawned 100 of them, but this vendor first pair he sold me were the broken of the tiger version

**Comment by Thenari** [comment]
https://github.com/elysium-project/bug-tracker/issues/616

#616 is the source of this new bug lol

**Comment by shenna-elysium** [comment]
Clear WDB now.
