### ISSUE TITLE
Timbermaw Rep Bug

### ISSUE THREAD

**Issue by motivol** [elysium-project/bug-tracker#720]
Well,its the second time i lvl rep 0 to 3000 ( Neutral ) and when i get the 3000 rep necesary for upgrade return to 0 in neutral,2 time this happend to me :)

**Comment by Thenari** [comment]
that's really weird, I can't see your character stats but maybe an ingame ticket is more apporiate for this

I have grinded furblogs to the point that killing them no longer gives rep (Revered)

it should be i think 2500/3000 in the unfriendly section

0/3000 to neutral

**Comment by Thenari** [comment]
I'd need more info on what you were doing
until than this is a incomplete report.

**Comment by motivol** [comment]
I grind furbolgs and do the quest for rep,when its time to upgrade to friendly ( 3k ) i return again to 0 rep in neutral,i try it doing whit quest,and whit grind and nothing,always return to neutral whit 0 rep

**Comment by motivol** [comment]
I post ticket in game,but they say to me try post here

**Comment by Thenari** [comment]
Hmm thats really weird. Can you give me more details. Its probs not important but race and class. And if you could what was the mob or quest you did that pushed you over 3k that caused the rep reset.

**Comment by motivol** [comment]
Human warlock,and i try whit only grind,or whit quest,but always return to neutral whit 0rep

**Comment by Thenari** [comment]
Hmm ok ill go make a human warlock and repeat what you did

**Comment by Thenari** [comment]
Do you have any addons? Im thinking it might be a client side visual. Can you try buying something that requires friendly rep for me.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40284472-a833b98a-5c5d-11e8-9607-95601c2a3f33.png)

human warlock, set rep at 2999/3k to friendly confirmed i cant buy stuff

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40284484-cf417e18-5c5d-11e8-8d59-5802890db114.png)

killing one furball gave me 5 rep and took me over the limit and now im friendly.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40284494-f6e1a8d0-5c5d-11e8-8ad3-f7b423516e9b.png)

was able to buy a friendly require recipe

**Comment by Thenari** [comment]
If you have any more data about your issue can you share, until then I cannot repeat.

I highly suspect it is just a client side visual error. likely from an Addon

**Comment by Thenari** [comment]
Just to be safe, i logged out then back in, and it remembers that im friendly.

**Comment by motivol** [comment]
I got some addons on,but muy rep is 146 neutral,cant buy.
Well then i try again to grind rep whit mob again and check what
happend.This take time,this next week so much work.

**Comment by Thenari** [comment]
I could not confirm your isue. Both methods of rep increases probably worked when tested. I recommend you contact a GM in game and link to this thread for personal assistance.
