### ISSUE TITLE
In Dreams

### ISSUE THREAD

**Issue by hatov** [elysium-project/bug-tracker#721]
Hi

In Dreams quest seems to be bug.

Highlord Taelan Fordring is waiting with 50% life (turned back from his original spot) with dead corpse of Scarlet Cavalier layed down to his foot. 
Nothing happening for several minutes and I can't take quest while i'm Disguise.

EDIT : Not moving or interactif for 20mn now, bug confirmed

Thanks in advance

**Comment by hatov** [comment]
![Uploading f2bce959fcfd9684813515b4b04969a0.jpg…]()

Screenshot : https://gyazo.com/f2bce959fcfd9684813515b4b04969a0

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39965049-b77076c6-565f-11e8-8950-350d5715819a.png)

I completed the 3 murder animals quests

then he wants me to listen but he never speaks

**Comment by Thenari** [comment]
just gonna give myself the next quest

**Comment by Thenari** [comment]
.quest complete 5742

**Comment by Thenari** [comment]
killed some grave robbers and completed next quest

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39965189-93f6b72a-5662-11e8-99b9-06ed637365b0.png)
found it!

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39965264-a3ecbd2c-5663-11e8-86d8-daafaf619ed2.png)

painting worked

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39965296-4ae1bdbc-5664-11e8-9fa8-e43330f241ec.png)

hmmm gnome hag illusion isn't working on ptr right now

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39965501-06a06316-5668-11e8-8e3c-49187534caea.png)

I killed things too fast the first time so i went slow and let the pally do all the work

**Comment by Thenari** [comment]
once you get to the escort part you dont need to be disguised he'll stay friendly with you

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39965514-6a509958-5668-11e8-9b98-35cc393ab8b2.png)

oops old man died too

**Comment by hatov** [comment]
quest done this morning
thanks
