### ISSUE TITLE
[BUG] Quest: Counterattack!

### ISSUE THREAD

**Issue by Jayrief** [elysium-project/bug-tracker#724]
The Kolkar and Krom'zar do not spawn in properly. They pop in for a second then disappear. You can see a .gif of this happening here. https://gyazo.com/14a79c487440b9570a6618ce02535097

**Comment by Thenari** [comment]
looks like the scripts are going by too fast

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39965818-520af2c0-566e-11e8-9ce4-98e29a69ed3d.png)

it looks like its starting ok for me

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/39965860-1f4ca422-566f-11e8-9712-a0015bf7d207.png)

i didnt leave the bunker, just let the troops fight as much as they could, that got boring so i sent an infernal in there and the scripts ran like they were supposed to.

**Comment by Thenari** [comment]
Script Quests are always weird but im gonna close this issue cause its easy to just message a GM to get it going correctly, or just drop and take the quest again
