### ISSUE TITLE
WSG queue bug

### ISSUE THREAD

**Issue by Sklyff** [elysium-project/bug-tracker#725]
I can't join WSG by talking to the battlemaster Brakgul Deathbringer in Orgimmar, even though my character is level 18.
Loging out and back in won't fix the bug.

**Comment by Thenari** [comment]
yeah funny thing, in 1.6 the 19 WSG was a thing, then in 1.7 it was taken out, but then returned in 1.8

its technically blizz-like for there to be no WSG for 19s this patch but it'll probably be changed
