### ISSUE TITLE
AV Glitch at mountain use by horde to rush Aid Station.

### ISSUE THREAD

**Issue by Caretable** [elysium-project/bug-tracker#726]
There is a glitch at Alterac Valley Battleground that alows Horde players to rush Aid Station in Dun Baldar and win. this is a cheat that allows the hord winning unfair.

**Comment by Thenari** [comment]
I know nothing about PvP and dont have access to the battlegrounds on ptr yet, until i get it can you try and explain as if i was 5 years old, how is the glitch done?

**Comment by Inomares** [comment]
He's referring to the age-old tactic of backdooring. Both factions can (kinda) do this, horde's version just involves a sort of semi-walljump.

It fails almost every time anyway, since it's so well known and easy to counter.

**Comment by Thenari** [comment]
The ToU was updated, if you see it happening you can record it and tell a GM in-game.
