### ISSUE TITLE
Penalty to stats without a source

### ISSUE THREAD

**Issue by dnamein** [elysium-project/bug-tracker#728]
![wow](https://user-images.githubusercontent.com/20075010/39995794-b3654d4e-577d-11e8-8adc-0cd9b2c22bc4.png)

Without anything equipped and without any buffs my character have mysterious -4 strength modificator.  Alliance 47lvl druid. 

It is not even right with calculation (see the screnshot)  "Strength 49 (60-4)"

**Comment by Thenari** [comment]
Weird. Double check for me your talent page. I know theres some talents that minus one stat to buff another.

**Comment by dnamein** [comment]
I relogged my character and it dissapeared. I guess it was propably some kind of visual bug leftover from  debuff I recived from mobs or players.

The only talents that could affect this behaviour is "Heart of the Wild" that increases strength by 20% in cat form (so it's decreasing it after leaving cat form, but it's 23 strength at the moment not 4)
