### ISSUE TITLE
Can't Que for WSG as a level 19. 

### ISSUE THREAD

**Issue by Aaron182** [elysium-project/bug-tracker#729]
I tried to clear my WDB and disable my addons multiple times but it still will not let me que my lower levels :/

**Comment by Aaron182** [comment]
I was recently informed that during 1.7, level 10-19s were unable to que, they patched it once again in 1.8, allowing them to que again.

**Comment by shenna-elysium** [comment]
You can queue now, Although it's not Blizzlike but I don't see any reasons to support this.

**Comment by Aaron182** [comment]
It seems I am still unable to que on my low levels :/ Would really like to
see this happen, this would help fix the pool size problem caused by the
recent que changes...
