### ISSUE TITLE
[Spell] Priest's Mind Flay - Ticking 2x instead of 3x

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#73]
> VincentVolaju - Yesterday at 11:46 PM
> Hey, is it possible to ever have Mind Flay working correctly? I've found posts from the old Ely boards, Nost from 2016, Emerald Dream from like 5 years ago. No server ever has Mind Flay working as its supposed to, as in each mind flay ticks 3 times. It's a 3 second channel spell that is supposed to do 3 ticks of damage. However, on every private server I've ever played on, 50% of the time it only ticks 2x. Here is a link to the post on Ely forums where multiple people confirm that have the same issues.
> 
> https://forum.elysium-project.org/topic/37103-mind-flay-only-ticking-2x-instead-of-3x/
> 
> Please dude, help a shadow priest bro out, I hate only doing 66% of my potential damage. If you were able to fix it, you'd be the first server I've even seen with working channeling spells.

**Comment by Terranzin** [comment]
I´ve reviewed your issue. I´ve managed to reproduce the error you´re speaking of. It does not appear to often but a small guess is that 20-30% of the times the spell actually only ticks twice. 

Below is a example, first it ticks 3 times, then I put another mindflay and this one ticks only 2 times.

![image](https://user-images.githubusercontent.com/25831382/33039123-41b9f14c-ce37-11e7-911a-3b01abbc62cf.png)

What I´ve noticed is that it's never the first or second tick of mindflay that gets ignored, but always the last one. I´ll put this one as confirmed

**Comment by polyamor61** [comment]
so what excactly was the probem? And how did u fix it if you dont mind me asking
