### ISSUE TITLE
Satyr Slaying! (alliance)

### ISSUE THREAD

**Issue by Brunelleschino** [elysium-project/bug-tracker#731]
The quest with the name above only yields 199 xp which is far too low considering you have to collect 16 satyr horns and it is no run and talk only quest.

**Comment by Thenari** [comment]
let me check

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40037415-307aa16e-57db-11e8-8ecf-0ffc74ed6b83.png)

at level 28 i received 199 exp that is a weird number lets look up what it should be

**Comment by Thenari** [comment]
I'm going to put the confirm tag on this because it is true it gives 199exp

but idk if thats a problem.

**Comment by Inomares** [comment]
Should be 2550 xp at the appropriate level. It can scale down by at most 90% so 199 is definitely not correct under any circumstance. 

https://web.archive.org/web/20060507090018/http://www.thottbot.com:80/?qu=1032 
and
http://web.archive.org/web/20060525003949/http://wow.allakhazam.com:80/db/quest.html?wquest=1032 (see comment by "Sarnath")
