### ISSUE TITLE
Defeat Nek'rosh (alliance quest)

### ISSUE THREAD

**Issue by Brunelleschino** [elysium-project/bug-tracker#732]
Wrong xp-value. The experience reward is way to low (only around 850 if I remember correctly from doing it today) for killing a lvl 32 elite.

**Comment by Thenari** [comment]
i got 1900exp from setting the catapult on fire, then 900 exp from turning in the head, the 32 elite gave a lvl 28 444exp too

**Comment by Thenari** [comment]
i think its a group quest so its expected youll do it in a group probs why its lower.
