### ISSUE TITLE
Night Watch Pantaloons wrong stats

### ISSUE THREAD

**Issue by daxaru** [elysium-project/bug-tracker#735]
https://classicdb.ch/?quest=55
https://classicdb.ch/?item=2954

On Nighthaven they come with 8 strenght and 8 spirit. Maybe they got confused with the stats from the helmet?

**Comment by Inomares** [comment]
[8 strength and 8 spirit is correct](http://web.archive.org/web/20051127044553/http://wow.allakhazam.com:80/item.html?witem=2954). ClassicDB is for some reason based off of a ~2.3 (tbc) database, and thus is not a reliable source.

**Comment by daxaru** [comment]
Thank you

**Comment by Thenari** [comment]
yeah ive farmed for items that arent even in the game yet before lol

my advice, go to classicdb, look at the item you want, there should be a "Links" button near the top, click that, copy, paste in wow and youll see the item as in game. generally if you cant click it that means its not in game yet/no one on server has it.
