### ISSUE TITLE
Hellfire not triggering Pyroclasm

### ISSUE THREAD

**Issue by Thenari** [elysium-project/bug-tracker#738]
yeah like the title says, RoF and Soulfire do it 26% of the time (about 1 ever 4 tries) but hellfire does not do it at that rate, i use hellfire all day everyday and it stuns about 2.6% of the time.

this bug was known to happen between 1.8-1.10 when pyroclasm was first changed to stun % , and the bug happened again in 2.03

the stun is also not supposed to be classed as a controlled stun and should not diminish in PvP settings.

http://wowwiki.wikia.com/wiki/Pyroclasm talks about the patch history.

**Comment by Thenari** [comment]
rank 1 and rank 2 hellfire proc more than rank 3.

**Comment by Thenari** [comment]
still not working on ptr

aftermath a 10% chance is happening much more often than pyroclasm with a 26% chance

**Comment by shenna-elysium** [comment]
@Thenari Just updated the PTR please check again.

**Comment by Thenari** [comment]
Will do!

**Comment by Thenari** [comment]
Havent had ptr powers in so long T_T can't test it

its not live for sure I've been using it all day my 4% daze happens way more often than the 26% stun

**Comment by drozdez** [comment]
Found another problem with calculation. Fixed it. Now it going to work correctly)
