### ISSUE TITLE
Spells not triggering Blade of Eternal Darkness

### ISSUE THREAD

**Issue by Thenari** [elysium-project/bug-tracker#739]
testing varius AoEs that it does work

can someone explain why Hellfire (rank 3 only)/Rain of Fire/Blizzard/Volley do not work?

whenever it does proc, either the first target it hits is the only one who can be affected, or the combat log always shows it at the top... strange. there is no internal cd for this item based on the forums and patch notes, either ive never seen it proc twice from one explosion (which people on the forums claimed can happen, reliably too, using rank 1 explosions to generate mana via procs)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40276897-33e3a704-5be3-11e8-8077-f33fff088144.png)

holy nova works

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40276905-5fff7444-5be3-11e8-8c79-a38f2c8490b9.png)

Touch of weakness works

**Comment by Thenari** [comment]
RoF does not trigger

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40277031-fb9e5aee-5be5-11e8-98bf-f2a79fd3f06b.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40277098-81d7ac2c-5be7-11e8-9121-217394ebdd65.png)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40277146-65f98dda-5be8-11e8-96ad-ca10d7d76313.png)
blastwave works

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40277165-c367df12-5be8-11e8-8b9e-aee820f6dcee.png)
flamestrike works

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40277202-1ef273e2-5be9-11e8-859c-30bc3d36e5e5.png)
Cone of Cold works

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40277208-34441cc8-5be9-11e8-9d55-7b799a3e9712.png)
Frost Nova works

**Comment by Thenari** [comment]
Blizzard like Rain of Fire either doesnt work or is very unlikely

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40277423-d6b8cd7a-5bec-11e8-98e7-2e9223bdb559.png)
chain lightning works, but its either really unlikely or the chain parts don't proc

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40277525-2dafc5b0-5bee-11e8-8141-67c931fe1a38.png)

all 3 shocks proc'd very often (or im lucky)

**Comment by Thenari** [comment]
it don't expect any of the totems to work, they are kinda like pets, not really me casting the spell to proc it. i did test every damaging totem though and none worked

**Comment by Thenari** [comment]
Can't figure out how to test if Windfury/Flametongue work cause i dont know how to put the buff on myself, i cant be buff'd or debuff'd by others on ptr, and enchantments on weapons/armour do not work

**Comment by Thenari** [comment]
would be cool as heck if a windfury proc could proc +100shadow/100mana

**Comment by Thenari** [comment]
Lightning bolt and lightning shield both work

**Comment by shagu** [comment]
Out of 100 Arcane Shots, it triggered zero times. Not sure if this is working as intended. I'll just leave it here.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283495-facc97cc-5c4c-11e8-80af-3fc66f1d41fa.png)
killed a royal guard using only rank 1 arcane missiles, so i fear channel spells might not be able to proc it.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283511-33028322-5c4d-11e8-8a65-f9494d95f1b0.png)

fire blast and fire ball both work

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283520-6627f62e-5c4d-11e8-8ebb-7542434e7db6.png)

scorch and pyroblast both work

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283525-8135cc5c-5c4d-11e8-9cd1-373b3029ff9b.png)

frostbolt worked

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283629-5ccd7552-5c4f-11e8-8b96-1c412240cf5b.png)
Immolation trap effect spell (which i think should behave just like an immolation trap) does proc it, but i can't get explosive trap to do it.

**Comment by Thenari** [comment]
volley doesnt work (or is very unlikely)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283723-cac089cc-5c50-11e8-9e8e-ae77aa77463d.png)

Surprisingly, the act of putting corruption on targets can proc it! but the tick dmg never will.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283731-ea9e64b2-5c50-11e8-9bde-d1f0e1a14aab.png)

curse of agony, putting on can proc, never tick.

**Comment by Thenari** [comment]
Shadow Bolt, Death Coil, Immolate work

**Comment by Thenari** [comment]
none of the non-damaging curses do it just agony (or im very lucky)

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283775-c45ea914-5c51-11e8-9901-6d928d871dcc.png)
hellfire rank 1 actually worked lol! either its crazy rare or its like the previous bug reports and its rank 3/4 that are bugged

**Comment by Thenari** [comment]
I have seen Pyroclasm proc before usually by Soul Fire (1/4 chance feels right) Rain of Fire I've seen it too, but i feel like hellfire never does it.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283873-9054b83c-5c53-11e8-8494-c9353ef45fb8.png)
hellfire rank 2 proc'd Pyroclasm! it must be a 26% => 2.6% mistake those are pretty common

**Comment by Thenari** [comment]
Ok i think its working as intended now.
