### ISSUE TITLE
Mobs in BRD hitting x2 the usual amount.

### ISSUE THREAD

**Issue by MmorpgFanatic** [elysium-project/bug-tracker#74]
Just like the title says, I tested by pulling 1 mob (sheeped the first, attacked the second) and I noticed I was receiving twice the normal damage every time he attacked.

For example:

Mob swings once
Damage taken 273
Damage taken 259
Mob repeats.

I tested by pulling 3 mobs and low and behold the moment they got to me I was instantly shot down.

**Comment by yimido** [comment]
Yeah happend to me as well, sometimes sudden oneshots happen when try to kite them

**Comment by Terranzin** [comment]
Could you please provide more information.
- All mobs?
- Certain mobs?
- What damage is he supposed to do? (Need you to give solid links/urls for site that tells their correct output damage)

**Comment by Terranzin** [comment]
No respons for 22 days, I´ll close this. If you want to make issues, please provide more information, proof and solid text.
