### ISSUE TITLE
Rare mob Prince Nazjak

### ISSUE THREAD

**Issue by Merezin** [elysium-project/bug-tracker#741]
обьясните мне кто нить его кривое время спавна , я так понят что промежуток между его появлением составляет 50 часов ( 14 мая в 21 :15 - 21 : 20 он появлялся +- 35 минут ) я уже очень много времени потратил на его поиски , следовательно изходя из того что время его спавна составляет 50 часов то он должен был появиться 21 мая в 03:15 - 03:20 +-35 минут по МСК но он появился аш на 4 часа раньше в 23 : 15 из за чего может быть подобная фигня ?! и из за чего меня почти постоянно дисконектит ?! прям перед его появлением .... !!!!

**Comment by drozdez** [comment]
На сайте с классической базой указано, что время его спауна составляет 32 часа. Так что скорее всего все в порядке) Для бпущей уверенности прилагая ссылку: https://classicdb.ch/?npc=2779
