### ISSUE TITLE
Arcane missles stop channeling immediately.

### ISSUE THREAD

**Issue by Duhripper** [elysium-project/bug-tracker#742]
Everytime I cast arcane missles they never work properly. If im lucky when I cast the spell 1 set of missles cast then the channel stops but most of the time it uses my mana and the channel will start for a brief second then instantly stop without shooting any missles. Any suggestions?

**Comment by Thenari** [comment]
thats weird i was testing arcane missiles yesterday when i was doing blade of eternal darkness testing (arcane missiles do not proc it) each rank of a spell is different sometimes a rank can be messed up, plz tell me what rank you are using, just for giggles tell me race too, maybe talents if you have something that might work with Arcane missiles


plz check you dont have some sort of addon that is causing the channel to break, any movement or esc key presses would do that, some programs like lazy pig can do actions automatically

**Comment by Duhripper** [comment]
I don't use lazy pig I use big wigs, decurse, X-perl, ktm and dpsmate. but this problem has been an issue since i was leveling b4 i used any addon. and I have tried every rank of arcane missiles and they all fail and I'm a troll mage.
sorry for failing to respond faster.

**Comment by Duhripper** [comment]
I have also deactivated all addon's and tried every rank of arcane missiles and its all the same.

**Comment by Duhripper** [comment]
seems like it requires a ton of hit to maintain the missiles.

**Comment by Thenari** [comment]
:/ i was using a brand new mage and i was testing all the ranks last week. I didnt do a lot of testing but i never missed once :/

Its 6am here im gonna leave this till i wake up tomorrow.

..... you say this has been happening for a long time... maybe its your logs thats broken.... probs not gear cause long time issue...same with talents... can you give me a print screen of the miss messages... you can just screen shot then ctrl v in a comment github is smart itll work. And do each rank. Find like a friend to duel or something to get some easy to repeat numbers

**Comment by Thenari** [comment]
Lol reread your problem. Missiles arent missing its the channel breaking.... hmmm....i dont know shit like this... i dont have special vision that could let me see your inputs... let me ask a smarter person if theres a GM power to see a players inputs cause there has to be something breaking the channel

**Comment by Thenari** [comment]
How about blizzard? When you cast that it works normally? Mages got a few channel spells i think. Its just arcane missile you claim?

**Comment by Thenari** [comment]
Whats your connection to the server like? Any trouble there?

**Comment by Duhripper** [comment]
My ping or whatever sits at about 130. And blizzard works completely fine. Last night i actually went out and tried it again and when say I use max rank against a lower level npc it works just fine but if I cast it on a lvl 60+ the channel immedietly cancels itself.

**Comment by Thenari** [comment]
Does magic missiles go on a long cooldown? Or just the standard global cooldown? I dont super know how mage spells work. It could be it resists but it should resist the individual shots not cancel the channel. Some enemies can interupt spells but i assume you know that.

**Comment by Thenari** [comment]
Hmmm i swear it was working when i was testing blade of eternal darkness but its not working for me either now :/ i think there was an update between last i tested it and now, someone probs messed up some code. im bring this to attention now. sorry for the delay

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40283495-facc97cc-5c4c-11e8-80af-3fc66f1d41fa.png)
killed a royal guard using only rank 1 arcane missiles, so i fear channel spells might not be able to proc it.


thats from 10 days ago and it was working for sure
