### ISSUE TITLE
A Bijou for Zanza Bug-

### ISSUE THREAD

**Issue by casterb** [elysium-project/bug-tracker#745]
All ZG quests bugged out of my questlog today. 

Originally I thought it was only the A collection of Heads quest. So I **PREVIOUSLY** submitted this to a GM which describes the issue that is persisting with my A Bijou for Zanza quest.

"My questlog is bugged.

A collection of heads quest from the Zandalar Tribe is bugged in at least two ways.

 #1 It is not showing up in my questlog, along with all other ZG quests If I'm not mistaken.

#2 I currently have 3/5 heads, and when we killed the bosses in ZG today that should drop the other two heads I need, nothing dropped.

I had thought It was my fault, I'd convinced myself I'd accidentlally abandoned the A Collection of Heads quest. But, ? is Grey over Exzhal's head still, the quest giver. I cannot abandon and restart."

**ps. Bat boss respawned in our ZG**, maybe this bug contributed to the other bug?

--

Now I've realized the same has happened with A Bijou for Zanza - I didn't care about the quest as much so It took longer to realize but it is also not abandon able or complete able.

**Comment by Thenari** [comment]
Hmm quests bugging out? Plz double check it with all addons disabled. I think if you put in an im game ticket you can show the GM your 3 channler heads you still have and ask the GM to drop the quest and regive it to you. Idk a lot about ZG bugs. You claim the bat boss respawned? Thats pretty weird ill ask around about that one.

**Comment by Thenari** [comment]
did you follow through with the ingame ticket? I hope you notified a GM if a raid boss respawned. if so if you know which GM you talked to i can follow up with them.

**Comment by Thenari** [comment]
Yo this is too specific you can get a fix for this with an in-game ticket.

**Comment by casterb** [comment]
Thanks Then,

Someone fixed everything for me and it’s all good now, sry for late reply
