### ISSUE TITLE
Hidden Enemies (RUS)

### ISSUE THREAD

**Issue by germeoo** [elysium-project/bug-tracker#748]
Я не знаю, что за баг, но есть такой квест за Орду. Цепочка с самим Траллом, называется по-русски "Тайные Враги". И вот на 3 из 4х этапов квеста, Тралл дал мне квест (http://wowroad.info/?quest=5729), но он у меня не появился к квест-буке. Я не могу его выполнить. А цепочка очень важна и интересна по лору. К тому же, у меня на руках висит квестовый символ лейтенанта, который я выбивал еще на 1м этапе квеста и выбросить я его не могу. Имя персонажа "Hardger" (Тролль - Шаман 12 уровня). Пофиксите, пожалуйста, или сделайте какой-то ретейк, чтобы этот квест перезагрузился.

**Comment by drozdez** [comment]
Добрый день! Протестировал данный квест, все работает. Попробуйте отменить его, поговорив с Траллом или Ниру. Если это не поможет - проверьте, возможно у вас стоит какой-либо из модов, привносящий этот баг. К сожалению данный баг не на стороне сервера.

**Comment by germeoo** [comment]
Дело в том, что модов у меня никаких не стоит. У Тралла горит "восклицательный знак" серым цветом, будто квест я взял, но в книге у меня его нет. Да и отметить я его не могу(разговаривал и с Ниру и с Траллом). Видимо не доделаю эту цепочку. Может быть квест вернётся в книгу после перезагрузки сервера?
