### ISSUE TITLE
Seaforium charges

### ISSUE THREAD

**Issue by yimido** [elysium-project/bug-tracker#75]
Guys, cant use seaforium charges in lockboxes and chests. Please fix this. 

![image](https://user-images.githubusercontent.com/33834147/33020113-08be146e-ce0e-11e7-9bb6-ac889f4270ae.png)

**Comment by yimido** [comment]
![image](https://user-images.githubusercontent.com/33834147/33020342-04ce3a90-ce0f-11e7-865d-a9aa1d77f339.png)

one more from VANILLA wiki

**Comment by Terranzin** [comment]
Thanks for reporting this issue, on current patch you can't use items like Seaforium Charge to unlock lockboxes / chests.
https://github.com/elysium-project/bug-tracker/issues/59
