### ISSUE TITLE
Thekal's/Arlokk's Grasp buff

### ISSUE THREAD

**Issue by Thenari** [elysium-project/bug-tracker#750]
i dont know a super lot about this but...

i unarmed a guard until it buffed me

but i never got a message in my combat log of having a buff on me (idk why that happened but doing it more it always shows the buff being put on me now), but i did get one when it fell off in 12 seconds doing a lil damage comparisons of when buffed and when not but it was all over the place for damage

**Comment by Thenari** [comment]
Well i still dont know shit about how +300 attack power should work but it does do slightly more dmg (on a warlock who i forced to learn fist weapons and duel-wielding and also made her have an unarmed skill of 300) I don't even remember what the original person was having troubles with

**Comment by Thenari** [comment]
I suppose i could check every single class who does melee or ranged damage but that sounds like a lot of work so im not gonna do that unless someone tells me what class is having problems cause im a lazy bum

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40755877-5d6a436c-644e-11e8-978e-e99a40efd6db.png)

i can put it on other people

but it is rare as heck or theres weird stuff with it for putting it on myself naturally

i unarmed to death 2 guards

guard A i got 4 tiger procs

guard B i got 0 tiger procs

also when i turned a guard to a tiger it did like a ton more dmg so the +attack power is probs working

**Comment by Thenari** [comment]
also guard A when i was fighting them i got 2 procs back to back, so im pretty sure the item doesnt have an internal cooldown (maybe at most 12 seconds to wait till the buff falls off)

**Comment by Thenari** [comment]
I'm reading its cool on hunters. fun on warriors and rogues

its mostly a silly weapon set that gets removed when ZG gets a remake

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/40756362-371e0e52-6451-11e8-89c9-ead82027a875.png)


feels weak on aimed shot for hunters

**Comment by Thenari** [comment]
You grow slightly when you use it. The growth may be increased later patches?

**Comment by Volant84** [comment]
No model should be like a tiger boss in full growth !!!

**Comment by Thenari** [comment]
That video you showed as proof is TBC and i wouldnt put it past the person to use other growth items

**Comment by Volant84** [comment]
https://www.youtube.com/watch?v=PyW-ysfaepw&t=1s

time line 3 - 25

**Comment by Thenari** [comment]
Yeah it does that in game you get 300 attack power and turn into a tiger and grow

**Comment by Thenari** [comment]
Like i was using it on an undead female and got like a 25% growth. Tauren get bigger than that
