### ISSUE TITLE
Primal Blessing Buff and set problem

### ISSUE THREAD

**Issue by Volant84** [elysium-project/bug-tracker#751]
Good afternoon . Help with the buffs from set Primal Blessing from Arlokk's Grasp fist weapon from ZG. With triggers and transformations in the Tiger, growth does not change !!

There must be a model in size like the Tiger boss.

What can be wrong ??

https://classicdb.ch/?spell=24256
https://classicdb.ch/?spell=24255

https://www.youtube.com/watch?v=QCmbU1Cg1L8

**Comment by Thenari** [comment]
Yo i just posted this 10 hours before your post #750  its a rather rare proc but it was working for me
