### ISSUE TITLE
Problem with Dagger. Acting like weapon skill isnt leveled (Finkle's Skinner) 

### ISSUE THREAD

**Issue by Gralky** [elysium-project/bug-tracker#756]
Hello. at about 3:00 PM PST on 6/1/18 I recently equipped my new dagger (Finkles skinner) and am unable to hit ANYTHING with it. seems to be acting like the weapon skill is not levled but daggers are at 300. Not sure if problem with the item or my character? Thank you 

Link to the item but im sure this does nothing shitty wowhead lol. 
http://www.wowhead.com/item=12709/finkles-skinner

**Comment by Thenari** [comment]
Those +10 skinning knives are so weird. You have to have a basic skinning knife in your inventory to skin things lol.

Its probs not important but can you tell me race and class of the toon in question?

**Comment by Thenari** [comment]
Also can you tell me what enemy you were unable to hit pref iď like you to open your combat log and expand it take a screenshot of what the combat log says when you attack

**Comment by Thenari** [comment]
Maybe do a duel with a tanky friend and just fiddle around with it. See what works/doesnt

**Comment by Gralky** [comment]
Yeah its Warrior and Orc. The weird thing is when its equipped sometimes the dagger skill just doesnt stay anything at all instead of 300/300 . and sometimes it just uses my defense stat skill (310+61) . not sure if that has anything to do with it. 

you think it has anything to do with me not being a skinner?

**Comment by Gralky** [comment]
https://gyazo.com/a44f5d645bca7a54c3150ea2aece92ef 

https://gyazo.com/da2e96b4a99f42da82a0f194ecc1baec

**Comment by Thenari** [comment]
haha you got the skinner dagger and you're not even a skinner lol :p 

yeah thats weird is it main hand or off hand... maybe the game thinks its a shield?

im real sorry its 1am here but ill fiddle around with it tomorrow, I was notified about your comments cause a Dev messaged me asking questions so its on our radar!

**Comment by Gralky** [comment]
ahhahaha Insane dagger for Threat lmao. And i think its one of those "One Hand" kind of daggers haha. ill learn skinning and see if that does anything LMAO... 

Appreciate the help man

**Comment by Thenari** [comment]
Ì hope you dont drop a profession for skinning i can do that kinda thing on a test character... it shouldnt be connected to profession though

**Comment by Thenari** [comment]
I feel like the skinner is acting like a main hand shield... so you have 2 shields no way to hit. But your defense bonus is huge

**Comment by drozdez** [comment]
That's strange, but all game libs think, that it's a dagger. So there i really don't know what can we do with it...

**Comment by Thenari** [comment]
Hello its been about a week, do you have an update? If you feel comfortable giving out info I can try and put you in contact with a GM who can inspect your issue better than i can. Im Theenari#7860 on discord and i made an email address GMThenari@gmail.com if you prefer

**Comment by drozdez** [comment]
I tested it on my local server, and everything's going ok
So there i can say it's working as intended.
