### ISSUE TITLE
Mail issues, not visible in /1 /s /y chat aswel

### ISSUE THREAD

**Issue by Burensteinas** [elysium-project/bug-tracker#758]
Hello, here's my problem and thanks for the support : 

1. players can"t see me in /1 /s /y chat, i can /w player and they can see me in /p

2. I receive mail but I can't send mail : players do not receive any mail but it still cost me money. When i put an item in the mail it will still remain in my bag.
I reinstal the game with no addon and the problem remain.
My friend (who have 0 issues on his account/computer) logged on my character on his own computer (different from mine) and have the same problem with my account. The problem is with all my character not only one.

I've done everything i could, thanks for help !

**Comment by Thenari** [comment]
You might of accidentally triggered a secret anti spam measure. I cant and dont know the details but I'll forward this to someone. Youre account probably has a secret mark on it

**Comment by Thenari** [comment]
Ok can you put in an in game ticket the red ? To the left of your bag slots. Feel free to link this page in the ticket

**Comment by Thenari** [comment]
This is probably a GM issue they can fix in game

**Comment by Thenari** [comment]
Hey theres no link to what your WoW account name is, so we cant really do anything without that, plz put in an in-game ticket, you can link this github page if you dont wanna explain yourself.

until than i am closing this issue, reply here if you have more info.

**Comment by Burensteinas** [comment]
Ok thx i'll do it
