### ISSUE TITLE
Arcane Concentration - Broken

### ISSUE THREAD

**Issue by MmorpgFanatic** [elysium-project/bug-tracker#76]
This one is pretty confusing, it seems like Arcane Concentration will proc more over casting non damaging spells as opposed to actually hitting targets with damaging spells.

Hear me out,

I'll cast ice barrier, it will proc...what? ice barrier isn't a damaging spell nor did it hit any targets.
Pull 20 mobs in level 30 areas and spam arcane blast? 0% chance of proc'ing.

Below is me sitting in Ironforge casting ice barrier and having an arcane concentration proc.

![wowscrnshot_112017_111536](https://user-images.githubusercontent.com/33832714/33028864-084c7abc-cde5-11e7-8875-cddbe5df2311.jpg)

**Comment by Terranzin** [comment]
Hello!

I´ve looked into your report and I managed to reproduce the error you´re speaking of. I managed to gain Arcane Concentration while casting Ice barrier which needs to be addressed.

![image](https://user-images.githubusercontent.com/25831382/33039588-b83dde68-ce38-11e7-8286-66364aa63f50.png)

**Comment by Terranzin** [comment]
Regarding hitting multiple enemies, we´ve done test of this matter already and that works fine.

https://github.com/elysium-project/bug-tracker/issues/16

**Comment by MmorpgFanatic** [comment]
Thanks for trying it out for yourself and replicating that bug!

Can you tell me how the test was done on the multiple enemies? Being an AoE frost mage I can tell there's something extremely fishy about it not proc'ing when I have arcane blasted 10 times...with 10 mobs aggroed...

It just generally seems broken all around.

**Comment by Terranzin** [comment]
simply mathematical, if each cast on a mob has a separate chance of 10% to procc, that's just it, 10% which is 1/10 of a chance, on each mob. When we tested the issue, we manage to get a arcane concentration procc every 5-6th time which is about accurate.
