### ISSUE TITLE
Quest arcane runes not giving flare gun if abandoned then re picked up

### ISSUE THREAD

**Issue by ElysiumHaggis** [elysium-project/bug-tracker#762]
As title suggests I got the quest Arcane runes in IF but was too low, so abandoned it to make space. Then when I got a few levels picked the quest up again but was unable to get the flare gun from Pilot Xiggs Fuselighter so I am unable to finish the quest. I've spoken to a GM they have tried what they can by regiving me the quest but still to no avail.

**Comment by Thenari** [comment]
i did an issue like this before with a shammy quest

if you dropped it + deleted the item and got it later you couldnt finish it
its such a specific issue, the already strained GM-Dev team would have to do a lot more work to create brand new quest just to get the previous quest item reward, as opposed to just give the player the quest item by command.


im labeling it ingame GM + probably intended (it is very blizz-like to have a lack of failsafes)

its when you get the quest item from a previous quest thats used for the next part normally

A GM could delete the players quest completion of the previous quest that might also work.


Either way, Dear player, plz put in a GM ticket and link this page, the GM can fight me about it.

**Comment by Thenari** [comment]
Hello im checking in. Im actually gonna close this as its a super specific issue thats probably blizz like.

I recommend you put in an ingame ticket and link this webpage.
