### ISSUE TITLE
Nelson the Nice not transforming

### ISSUE THREAD

**Issue by Drkorv** [elysium-project/bug-tracker#766]
Hello. Im on the Q Stave of the Ancients and I cant get Nelson the Nice to transform into Solenor as Nelson isnt giving me the option to click on anything when talking to him.

Thanks in advance

**Comment by Thenari** [comment]
As a warlock ive helped 3 seperate hunters with that fight. Around 10hours ago from this post it was working.

**Comment by Thenari** [comment]
So i would like my info from you. Plz confirm you do have the quest. It might be a visual error so if you can contact an ingame GM to look at your quest log

**Comment by Thenari** [comment]
hey don't take alarm to this, but im closing this issue. If you end up answering back with more info ill reopen it until than its a incomplete report.
