### ISSUE TITLE
[Glowing Cat Figurine] AutoPvP/Attack

### ISSUE THREAD

**Issue by Kruxis** [elysium-project/bug-tracker#767]
Greetings, 

just found out at PTR that the Ghostcat from the above item randomely attacks. I summoned him. passed some flaged players and suddenly my pet run and attacked em + PvP flaging me without my command

**Comment by Thenari** [comment]
This sounds like normal, summoned mobs without the pet bar, are not completely under your control, like summoned felhunter from spiked collar, or the dog whistle from SM houndmaster boss

they are probs closer to a shitty escort quest.
