### ISSUE TITLE
Absence Blacksmith quest 

### ISSUE THREAD

**Issue by blackbull32** [elysium-project/bug-tracker#77]
Hello, 
I would like to point out the absence of the quest that allows the specialized blacksmith armor to obtain the imperial plate set via the following quests.

this one should start with Krathok Moltenfist in Orgrimmar and this unfold in Tanaris with Derotain Mudsipper out this is not currently the case,

for simple information I am specialized blacksmith armor, lvl 266/300.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and it seems like the quest is gone, as example the quest "Imperial plate bracers" with ID: 7655 doesn't exist. Also attempted to speak with Derotain Mudsipper but no chance of obtaining the quest.

**Comment by blackbull32** [comment]
indeed neither of them offers anything.

**Comment by twink** [comment]
Not in 1.2.
Terranzin , about your quest, it will be added in 1.4.
