### ISSUE TITLE
Quest: Astral Knot Garment

### ISSUE THREAD

**Issue by Aceius** [elysium-project/bug-tracker#770]
The quest Astral Knot Garment gives 2 a sellection of 2 items Astral Knot Robe and Astral Knot Blouse
These 2 items are supposed to have different stats, 

Robe:
+6 stam
+6 int
+6 spirit

Blouse:
+6 stam
+9 int

yet they both have +2stam and + 8 spirit.

**Comment by Thenari** [comment]
I havent super checked, but some items get changed by patches... this is such a minor item though, so im not super sure blizz would of gone back to change it.

it is possible it is blizz-like until 1.x

or its an error

either way, thank you for bringing this to our attention, I'll ask around and learn more.

I am going to check the Horde version of this quest https://classicdb.ch/?quest=1946

Nether-Lace versions, if those are the buffed ones than for sure the ally will be fixed, if they are both the old stats than we'll have to do more research. I am not at my computer right now I am out of the house.

**Comment by Thenari** [comment]
![image](https://user-images.githubusercontent.com/38762769/41129588-cae9f45e-6a80-11e8-8cda-f5662af03df9.png)

yeah horde versions are the same

im afraid it is probs a future updated item

this is probably blizz-like for them to suck right now.
