### ISSUE TITLE
Quest: [A Sample of Slime...] and [... and a Batch of Ooze]

### ISSUE THREAD

**Issue by Jayrief** [elysium-project/bug-tracker#777]
Hi, some problems with two quests in UD, [A Sample of Slime...] and [... and a Batch of Ooze] (given by Alchemist Fuely, Undercity > Apoticarium). Its seems the two [Testing Equipment] (near, on the table)  are bugged. They can't be use and the message "already open" appears. No way to transform the slim sample into pure sample because of that (i have 15 and 13 of each). The red one is for the first quest and the green for un'goro's sample.

**Comment by Thenari** [comment]
Did you do this in a party? I remember having to waiting 5min+ to be able to use quest nodes im ulda if other party members used them first. Let me know and i can see what I need to test

**Comment by Jayrief** [comment]
No, i did them solo. I'm in front of the table since 2h ago, and there is the same thing. can't open the two Testing Equipment because they are already in use.

**Comment by Thenari** [comment]
Oh hmm. Did you do an in game ticket with a GM? Sometimes you have to drop the quest amd get it again. That sometimes deletes quest items so do it with a GM present.

In your ticket to the GM include a link to this github issue page so if they have any questions they can write them here or message me on the GM discord.

**Comment by Jayrief** [comment]
That was the first thing i did, and he said "Unfortunately, you'll have to report this bug on our githhub" ^^

**Comment by Thenari** [comment]
Name drop ill hound the GM :p
I actually dont have any authority here.
it sucks but you might have to hearth/portal/travel to UC drop the quest and get it again. I was hoping the GM could look at your quest log and drop/accept the quest again for you so you dont have to leave Ulda

**Comment by Thenari** [comment]
Interacting with a node shouldnt involve any addons but maybe a auto looter or a quest helper add on might interfere. Before leaving ulda do a addon disable exit and reopen game. Theres also some folders you can delete i think its either WDB or WTF. One clears your "cookies" the othet deletes your macros and settings so check the support discord page and start a talk about it a CM might be able to walk you through steps.

**Comment by Thenari** [comment]
Just out waiting on a park bench, any update? @Jayrief

**Comment by Thenari** [comment]
@Jayrief. Thanks for letting us know about this. Im marking this as report incomplete as id like more info about the event.
