### ISSUE TITLE
[Warrior] Rage lost on execute dodge\parry

### ISSUE THREAD

**Issue by Crusaderz** [elysium-project/bug-tracker#778]
15 rage lost when execute dodged or parried. Should be 5.

Alonzo 4 ([release](http://www.warcraftmovies.com/movieview.php?id=29219) date: 2006-10-09) https://youtu.be/FkTaOBJplK8?t=406 (timestamp in the link)
6.48: 32 rage
6.48: execute dodged -> 28 rage
6.5: whirwind (cost 25 rage) -> 3 rage

Alonzo 3 https://youtu.be/LSLZJQFoTKs?t=694
11.34: 40 rage
11.34: execute dodged -> 35 rage

**Comment by Thenari** [comment]
Hello I do appreciate you making all these topics about warriors. Im not home right now but i think it might be best to make one super issue about Warriors, I believe i might have the power to edit your issue. Id probs just copy all your previous issues and paste them in one issue. I does feel a lil awkward editing someone elses post but i feel like these are all connected and could be fixed all together.
