### ISSUE TITLE
Fel Cannon MKI not attacking properly

### ISSUE THREAD

**Issue by nastyxx** [elysium-project/bug-tracker#783]
These Mobs should cast fire blasts. but its just Autoattacking.
http://db.hellfire-tbc.com/?npc=22461#abilities
https://gyazo.com/217073e60c8c7606f860abf3733510dd

**Comment by drozdez** [comment]
Sorry, but it seems, like you have made a mistake with bug tracker, cause this mob is from TBC. And that's a vanilla bug tracker. I'm closing issue. Please, be more attentive next time ;)
