### ISSUE TITLE
quest The Stones That Bind US (vanilla)

### ISSUE THREAD

**Issue by timoha21** [elysium-project/bug-tracker#784]
Hi, dear GM!
I think quest "The Stones That Bind Us" in Blasted Lands doesn't work correctly. 
I kite servant to the stone and after he is going to astral i broke the stone, but after that i can't kill him.
I try many combination but it doesn't work(((

PS sorry for my bad English

**Comment by Thenari** [comment]
This is actually in progress of being fixed it seems to have broken a lil more than 5 days ago

#771
