### ISSUE TITLE
Quest: Salt Flat Venom

### ISSUE THREAD

**Issue by pepyachka** [elysium-project/bug-tracker#785]
Thousand Needlas quest - Salt Flat Venom 
extrimly low drop rate 20+:1

**Comment by Thenari** [comment]
Yes its actually blizz-like. Most quest items are around 80% but this one and buzzard gizzards in badlands are two i know are around 8%

This being blizz-like it hasnt been touched. It is an extremely low priority to fix but it is confirmed. Changing data from 8% to 80% is a lil harder than it sounds but maybe one day a dev will do it.
