### ISSUE TITLE
[Warrior] 100% rage lost on miss instead of 20%

### ISSUE THREAD

**Issue by Crusaderz** [elysium-project/bug-tracker#786]
This is gamebreaking.
Warrior already considered as most hardest classes to level and this bug just adds unnecessary pain and this pain is HUGE. In my opinion this bug should be highest priority.

How it works right now:
30 rage -> mortal stike (costs 30 rage) -> miss -> 0 rage
How it should work:
30 rage -> mortal stike -> miss -> 24 rage

Proof:
Alonzo 4 ([release](http://www.warcraftmovies.com/movieview.php?id=29219) date: 2006-10-09)  https://youtu.be/FkTaOBJplK8?t=976 (timestamp in the link)
16.16: 29 rage 
16.17: hamstring miss (costs 10 rage) -> 27 rage -> 2 rage lost, 20%

Alonzo 3
https://youtu.be/LSLZJQFoTKs?t=428 
7.07: 42 rage 
7.09: overpower miss (costs 5 rage) -> 41 rage -> 1 rage lost, 20%

**Comment by Thenari** [comment]
Also lol if i was a warrior missing would make me angry and make me gain rage, the whole losing 100% rage on a miss could because you feel embarressed haha

I did post this to a bugtracker gm channel and i dropped a @ development.

**Comment by Crusaderz** [comment]
Fix is not live yet?

**Comment by Thenari** [comment]
Yo @drozdez im making 2 labels.

Fixed, needs to be tested before release.

Fixed, and has been released.

Plz use those instead.
