### ISSUE TITLE
Catseye Goggles

### ISSUE THREAD

**Issue by Zizzal** [elysium-project/bug-tracker#787]
Catseye Goggles seem to be giving way too high invisibility detection compared to what it should, it currently sees through invisibility potions and everything from a long range.

**Comment by Thenari** [comment]
Hmm I thought catseye goggles were only stealth detection. Invisibilty detect is ita own thing.

Do you have any sources?

**Comment by drozdez** [comment]
@Thenari is right, it's increasing only stealth detection, not invisibility.

**Comment by Zizzal** [comment]
Yes that is how it's supposed to work :O But it's not working like that atm, can try to get some proof if I remember later.
