### ISSUE TITLE
Quests in Cenarian Hold

### ISSUE THREAD

**Issue by happyman126** [elysium-project/bug-tracker#788]
I have not been able to quest in Silithus at all and was wondering if there are quests to do there? If so what am I missing to get them started? But not one quest will show up to do at Cenarian Hold..

**Comment by Thenari** [comment]
Ha i wish. Ive been grinding CC rep for the 24 slot herb bag. Its 1 rep for 1 kill. Up to honoured for most twilight hammer mobs than after honoured only 1 mob type in the game gives 1 rep per kill and there are 13 of them in the game. Im at about 1k/12k to revered now. And theres about 1.5k rep in quests in the game if youre not a druid. So ive killed 1.5k to friendly 6k to honoured and 1k to revered so far. 8.5k killed 11k to go!
