### ISSUE TITLE
Hunters/Warlocks pet's spellbook or pet actions bar can not be seemed

### ISSUE THREAD

**Issue by Buffavento** [elysium-project/bug-tracker#79]
My 31 Level hunter's pet doesnt have Growl, dash ,bite or something like that on it's pet bar also there is no tab called pet on spellbook. The spells are already learnt by trainer but something is bugged on character which is explained here https://forum.elysium-project.org/topic/57787-pet-spells-cant-be-seem/?tab=comments#comment-453022
  i have found many topics on blizz forum, they fixed it before.

**Comment by Terranzin** [comment]
When trying to reproduce the error, my pet tab does appear on both alliance and horde side, attempted on 3-4 pets. You need to be more specific regarding YOUR problem and give more information such as what pet you´re using, pictures and more proof of the problem you´re having.

**Comment by Buffavento** [comment]
Problem is i m a bm hunter but i cant use my pet as a tank, its like paper because of nothing works on him what i trained from pet trainer. When i go pet trainer there is nothing to learn (all trained) but on pet there are many points to spend so that means pet doesnt get any spesific from pet trainer. Also you can see on the picture there is nothing special on pet's bar .. there should be some dash,bite,claw etc. something special for a pet. My pet is a lion but nothing changes when i tame a boar or turtle 
[url=https://hizliresim.com/nJ6DB0][img]https://i.hizliresim.com/nJ6DB0.jpg[/img][/url]

**Comment by Buffavento** [comment]
https://hizliresim.com/nJ6DB0

**Comment by Terranzin** [comment]
Not sure if the issue is only on his client, but there is lots of evidence. I´ll take this to our devs to look into the code.

**Comment by shenna-elysium** [comment]
Can't reproduce at any way.
