### ISSUE TITLE
Cannot train First Aid at Trauma Surgeon

### ISSUE THREAD

**Issue by johnsonmann** [elysium-project/bug-tracker#791]
I cannot train FA skill at trauma surgeon in Theramore after completing Traige quest, he only says greetings to me. Ive tried deleting WDB folder and restart game. My FA skill is 232

**Comment by drozdez** [comment]
Sorry, but for train skills that trauma surgeon can offer you, you need 240 for first, 260 for second and 290 for third. So, i think you just have to raise your FA skill)
