### ISSUE TITLE
Quest "Stranglethorn Fever" does'nt work

### ISSUE THREAD

**Issue by Equinoxx1995** [elysium-project/bug-tracker#794]
I farmed all 10 "Gorilla Fangs", but I can't talk to the NPC "Witch Doctor Unbagwa". 

![wowscrnshot_061818_130818](https://user-images.githubusercontent.com/40356729/41532854-e9ce093e-72f8-11e8-9cee-218a6f84cbca.jpg)

**Comment by Thenari** [comment]
Hey @drozdez so you wanna explain what you did?

@Equinoxx1995  i could be an addom thing. Or dropping and getting the quest again can sometimes fix issues like that. Those would be my first two tests
