### ISSUE TITLE
Onyxia Skin Issue

### ISSUE THREAD

**Issue by bandini9** [elysium-project/bug-tracker#795]
Hello,

Nighthaven PvP (patch 1.7), in game character name Bandini

I have a issue about Onyxia ID: 3945

Me and my guild killed her and i skinned it but i didnt get any loot, her corpse is still here and there's no ''Skinnable''
Created a ticket and talked with GM Theflame, he/she said me to post it on GitHub it's about coding and im here.

edit: Her body despawned after 30 minute or so, still didnt provide scale of onyxia

**Comment by Thenari** [comment]
Just double checking, is skinning like disenchanting, after doing it to a corpse, does it auto loot? If not looted does the corpse despawn and the loot is lost if your inventory is full?

**Comment by Thenari** [comment]
Also its really shitty but for GM to take action they almost always need verified video proof of an issue for loot errors. So this is a bit of a more personal issue there are several ways to contact a GM. Discord is pretty easy. Im gonna suggest you talk to theflame and send them a verified video recording of the event.

Closing this issue as its not a specific issue its a very general loot error probably

Giving it the ingame GM label
