### ISSUE TITLE
Shadowsworn Warlock - Curse of Weakness

### ISSUE THREAD

**Issue by yanju** [elysium-project/bug-tracker#796]
Trying to fight the Shadowsworn Warlock mobs at Altar of Storms, when they use Curse of Weakness my damage goes to zero.
Recorded video evidence: https://www.youtube.com/watch?v=BtkiMjmP1Ec

**Comment by Crusaderz** [comment]
https://github.com/elysium-project/bug-tracker/issues/658

**Comment by Thenari** [comment]
I made a master post about this. Its on the radar just i dont have the ptr powers to test anything loke getting debuffs from enemies, also theres at least two dozen spells labelled Curse of Weakness all with different effects so its a slow test figuring out what ones are the problem
