### ISSUE TITLE
southfury river quest, Dorutar

### ISSUE THREAD

**Issue by Ahilez** [elysium-project/bug-tracker#8]
the quest for a emblem that drops from crocodiles in Southfury river in Durotar is bugged. Everytime i tried to tag a mog and drag it to land it dissapears.

**Comment by WardenElysium** [comment]
Hello,
Please name the quest properly and also give us details about your class and race.

regards

**Comment by Terranzin** [comment]
Did the following:
- Took up quest 816 (Lost But not forgotten)
- Went over to southfury river
- Killed Dreadmaw Crocolisk (id: 3110)
- Obtained the item Kron's amulet (id: 4891)
- Worked just fine.

I also attempted to drag the crocodile from water to land and from land to water about 5 times, didnt notice any despawns on the crocodile.
