### ISSUE TITLE
Quest:Melding of Influences

### ISSUE THREAD

**Issue by Djdave89** [elysium-project/bug-tracker#80]
When using Encased Corrupt Ooze on/near a Primal Ooze, the Ooze is not merging to make the Gargantuan Ooze.

**Comment by Terranzin** [comment]
I´ve reviewed your issue regarding quest ID: 4642. So the whole idea is that the corrupted ooze spawned from itemId: 12288 are ment to merge together with the Primal Ooze (ID:6557) to make a "Gargantuan Ooze (Id:9621)", then you´re supposed to kill the Gargantuan Ooze and obtain the quest item. This does however not happen and the Corrupted Ooze starts attacking the player.
