### ISSUE TITLE
Post doesn't arrive after changing race

### ISSUE THREAD

**Issue by Zaubertrick** [elysium-project/bug-tracker#800]
Hi,

I am playing on the server  Nighthaven PvP Patch 1.12.1 Horde

I sent 4 bags and more than 500g from my character "Zaubertrick" to my new character "Vivi". The post didn't arrive.

After that i sent two more bags from my character "Ceizu". The post didn't arrive as well.

A GM told me to delete the folder WDB and see if the post arrives. But it didn't.
After that the GM said I have to report my problem right here at Elysium GitHub.

I hope you can help me and bring me back my bags and gold.

Thanks a lot.

Best regards

**Comment by Thenari** [comment]
Ive seen this before, when you change race/gender your tech a new character and the mail system should take 1 hour for mail between your account and that new toon.

**Comment by Thenari** [comment]
The concept of changing race/gender is not a vanilla feature, it was manually made for this server, by mostly volunteers... plz excuse the inconvience

**Comment by Zaubertrick** [comment]
So it just takes one hour and then it arrives?

**Comment by Thenari** [comment]
Its as if you mailed a person of a different account. Remember the instant mail between alts is not blizz-like that was manually added
