### ISSUE TITLE
Quest: Chasing A-Me 01

### ISSUE THREAD

**Issue by Liverstones** [elysium-project/bug-tracker#82]
The escort npc slid on the ground straight across un'goro and didn't return to where the escort would start.

**Comment by Liverstones** [comment]
Slides all the way to Coordinate 48, 15

**Comment by Terranzin** [comment]
Thanks for your report, we´ll look into this matter.

**Comment by Terranzin** [comment]
I´ve reviewed your issue.
 
Use-case:
- I picked up the quest.
- Looted Mithril casing ID: 10561.
- Completed the quest.
- Started escort.
- Escorted A-Me 01 all the way to Karna Remtravel 

![image](https://user-images.githubusercontent.com/25831382/33223141-59ea3d16-d15d-11e7-9a8d-5d3e5355fa85.png)

I cant reproduce the error you´ve reported.
