### ISSUE TITLE
HUNTER PET CAN'T LEARN CERTAIN SKILLS AT CERTAIN LVL

### ISSUE THREAD

**Issue by Madafakero** [elysium-project/bug-tracker#83]
Pet is lvl 9. I want to teach him skill that requires lvl 1. I receive error message target is too low lvl. Relog and WDB doesnt help.

https://imgur.com/a/m3dFF

**Comment by Madafakero** [comment]
After some testing i found it can learn that skill at level 10, however ingame it says that required level is 1.

**Comment by Terranzin** [comment]
That´s correct, pet needs to be level 10 but the text needs to be changed from level 1 to 10.

Thank you!

**Comment by Terranzin** [comment]
I´ve reviewed your issue once again. Please empty your WDB folder, after I did it the issue got solved and it does show "Level 10".
