### ISSUE TITLE
Sinster strike bugged

### ISSUE THREAD

**Issue by Snappen** [elysium-project/bug-tracker#84]
Everytime I try and attack with Sinister strike, it tells me that it is an invalid target

**Comment by Snappen** [comment]
Apparently it works now, just by idling for a few seconds ?

**Comment by Terranzin** [comment]
Are you certain it wasnt just lag? Can you reproduce it now or was it just temporary?

**Comment by Snappen** [comment]
It wasnt lag, i was still able to pull ceres, and I had a stable ms.. It just fixed it self just by idling for a bit

**Comment by Snappen** [comment]
Creeps *
