### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by dehrios** [elysium-project/bug-tracker#86]
In the barrens, there are a bunch of mobs (Kolkar Stormer) that cast lightning storm. After 30 minutes of the mob casting the storm it is still shown. This happens around Wailing Caverns, Stagnate oasis, and the forgotten pools.  There are usually about 50 of these in each area.

**Comment by twink** [comment]
I can't reproduce, according to DBC it will last for 15 seconds.
