### ISSUE TITLE
[Quest] Ammo for Rumbleshot = Auto-completes

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#88]
> Sonic? - Today at 7:01 PM
> I'd like to report a very minor bug, The quest "Ammo for Rumbleshot" auto completed it self for me and a partner in game lol.

**Comment by Terranzin** [comment]
I´ve reviewed your issue on our PTR-server. Sadly I can´t reproduce the error you´re mentioning.

![image](https://user-images.githubusercontent.com/25831382/33234566-68a59ad6-d229-11e7-9609-7e58bc06547f.png)

**Comment by liskamic** [comment]
I think what they mean is they got the ammo from the Start NPC instead of having to loot it from the [box](http://db.vanillagaming.org/?object=176785).
Also, when I finished this quest 2 weeks ago, the scripted scene of mortar team shooting didn't occur.
