### ISSUE TITLE
Antonio Perelli pathing in Elwynn

### ISSUE THREAD

**Issue by vek35** [elysium-project/bug-tracker#92]
Antonio Perelli NPC Vendor is running through the woods clipping through trees
he should be walking on the road from Goldshire to Redridge zone change.

Once he arrives in Goldshire he will immediately take off running through the wood clipping through everything in his path until he reaches his destination and once he reaches it his pathing picks up and he walks normally on the road to Goldshire.

**Comment by Terranzin** [comment]
Thanks for reporting the issue. His pathing seems to be fixed on PTR (1.3), sure he doesnt tend to walk straight on the road all the time, maybe the road hurts his knees? Anyway I couldn´t see much of a issue that he walked close to the road at times and on the road on other times. (And yes, I did follow him the whole way back/forth).

![image](https://user-images.githubusercontent.com/25831382/33234667-59fbdd54-d22b-11e7-83a9-f49c9330ed0e.png)

**Comment by vek35** [comment]
GM Rain contacted me said they fixed the issue had  me place a ticket
