### ISSUE TITLE
Pet stable bug

### ISSUE THREAD

**Issue by Madafakero** [elysium-project/bug-tracker#96]
When pet is put to the stable, it still counts as active and when you try to tame another one, nothing happens. After relogging issue is solved but still doing relog everytime after using stable master is a drag.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and I can´t seem to reproduce the error you´re speaking of.

First I stable my pet:
![image](https://user-images.githubusercontent.com/25831382/33282879-5359d6c4-d3aa-11e7-8d27-31110482054e.png)

I went away to tame a new pet, and managed to do so.
![image](https://user-images.githubusercontent.com/25831382/33282944-8935bd9e-d3aa-11e7-8b31-f60e22d82ce5.png)

Went back to the stable and as you can see, both pets (old and new) is being correct without logging in and out. If there´s a issue on your character, please make a GM ticket.
![image](https://user-images.githubusercontent.com/25831382/33282958-95aa15de-d3aa-11e7-87f7-91716f53fcfd.png)
