### ISSUE TITLE
Pets follow you in stealth

### ISSUE THREAD

**Issue by eriks112** [elysium-project/bug-tracker#97]
If you are targeted by a lock/hunter and they send pet to attack you, and then enter stealth. Your stealth is doomed. You run run on forever in stealth but the pet will just follow you wherever and hit you and break stealth. Pets should loose target and reset after target is stealthed.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and managed to reproduce the error you´ve reported.

- Asked a nice citizen on PTR server to assist me (rogue)
- Turned GM off first to see that I can´t see the player while he goes stealth
- Once duel started and he saw my pet run towards him, the player went into stealth.
- The pet did in matter of fact continue to chase the rogue even while being stealthed and we manage to reproduce this everytime.

Screenshot was made just before he goes into stealth, but the pet does not disrupt his attack. Note: The pet was at level 14 while the player was level 22.

![image](https://user-images.githubusercontent.com/25831382/33282621-797e8fc6-d3a9-11e7-91c4-39c41f6f5527.png)

**Comment by Soyoen** [comment]
With the exception that this in fact is the actual correct behaviour for 1.12. Read from the following:
https://github.com/ccshiro/cc-buglist/issues/1155

**Comment by Niceguyone** [comment]
Here is also a video about the correct behaviour:
https://youtu.be/Q0O4RKeD4g4
