### ISSUE TITLE
Druid Stealthing out of Cat Form

### ISSUE THREAD

**Issue by logandar** [elysium-project/bug-tracker#98]
I made a macro to cast stealth and then cat form, as follows:

/cast Prowl(Rank 1)
/cast Cat Form(Shapeshift)

On the first click it puts me in Cat Form. On the second click it puts me stealth and takes me out of cat form. I then can proceed to walk around as a stealthed tauren.

**Comment by Navashed** [comment]
Reproduced.

Spell 5215 - Prowl(Rank 1)
Spell 768 - Cat Form

Macro:
/cast Prowl
/cast Cat Form

Pressing the macro 2 times reproduces the issue. Works with any rank of Prowl.
